### ISSUE TITLE
d-pad of F310 doesn't work as intended in VBA-M-WX-2.0.0-beta2

### ISSUE THREAD

**Issue by pokandu** [visualboyadvance-m/visualboyadvance-m#100]
I use the F310 Logitech controller, and the emulator version VBA-M-WX-2.0.0-beta2. The issue has been tested on these games, but it probably do in more games:
Final Fantasy Legend III (U) [!].gb
Knight Quest (U).gb

When i move my character using the d-pad, if i go Up or Down, i can't slide my thumb to the Right or Left direction. If i try to slide my thumb to turn Right or Left, it will continue to walk in the Y axis i was using, even if Up/Down is no longer pressed.

As i can't slide my thumb, i actually have to release the d-pad completely before changing direction. However, it seem to have no problem to change direction from X-Axis to Y-Axis. The issue only occur when sliding the thumb from Y axis to X axis.

Using the same controller, i doesn't have the issue with other version of the emulator (for example 1.8.0 beta 3 or 1.8.0-SVN work fine). However, i couldn't try with a different controller as i only have F310 Logitech. The joystick works fine, and my laptop keyboard works fine too, so the problem is only to the d-pad, and specific to VBA-M-WX-2.0.0-beta2. For the driver of the controller, it's just a plug-and-play so i don't really know. I'm using winXP-SP3, but since the problem only occur to one specific version of the emulator, i don't think it's related to WinXP.

**Comment by ZachBacon** [comment]
We fixed input issues since beta 2

https://github.com/visualboyadvance-m/visualboyadvance-m/releases/tag/throttle

Try this and report. Also keep in mind, windows XP will be dropped it is a dead operating system.

**Comment by pokandu** [comment]
It seem to work perfectly with that version. Thanks!
Then, i will keep this new version.

ps: For WinXP, i should get a Win10 as soon as i will buy a new laptop (current laptop is too old to take a more recent windows). I should be able to buy it this year.
