### ISSUE TITLE
Sonic Advance Native save wont work VBAM 2.0

### ISSUE THREAD

**Issue by RinMaru** [visualboyadvance-m/visualboyadvance-m#101]
Ive followed VBA-M for awhile but now it wont load native saves instead it makes new ones and importing saves dont work either.

Update: Only happens to sonic Advance

**Comment by rkitover** [comment]
note: probably related to the flash size auto-detection

**Comment by rkitover** [comment]
@Zetchzie can you please tell me how I can make this different type of save file you refer to to test loading it? DId you use a different emu and if so which one?

**Comment by Zetchzie** [comment]
Apparently other saves work but  Sonic advance resets I had the game beat. its a save from an earlier version of VBAM before 2.0

**Comment by rkitover** [comment]
@Zetchzie ok thanks, will try to look into it at some point.

**Comment by Squall-Leonhart** [comment]
this occurs with many titles since the attempt at auto detection, we're discussing reverting and going back to a built in database.

**Comment by Squall-Leonhart** [comment]
This can be closed, it no longer occurs on master.
