### ISSUE TITLE
[Bug]: error creating file 

### ISSUE THREAD

**Issue by MadShura** [visualboyadvance-m/visualboyadvance-m#1013]
### Expected behavior?

not any error report.

### Actual behavior?

open the game and show me this message .
my os is :
  System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 7.73 GB / 15.92 GB

### Steps to reproduce the problem

open the game and show me this message .

### Error messages?

error creating file 

### What game were you playing

pockmon red

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M 2.1.4 
 

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
Can you provide a screenshot of the error, because to me it sounds like you're trying to write to a read only folder or system.

**Comment by MadShura** [comment]
yeah , but i found all the folder  is read only folder .and im try to play other gba game.its ok .only when i play the gb or gbc game will show it . 
![QQ截图20221006193239](https://user-images.githubusercontent.com/45080320/194302305-425fe411-c5df-4ea4-8f2d-988abe722e6c.png)

**Comment by Squall-Leonhart** [comment]
Read only doesn't apply to windows folders, only files inside, the only way to change write acces on a folder is to remove those ACL permissions.

**Comment by rkitover** [comment]
If the rom folder is read-only, we should fall-back to writing saves and states to the config directory, IMO.
