### ISSUE TITLE
[Bug]: Parts of audio not playing at matching volume

### ISSUE THREAD

**Issue by Maple-LAN** [visualboyadvance-m/visualboyadvance-m#1014]
### Expected behavior?

when selecting options in the game menu and cycling text, there should be an obvious loud tick noise

### Actual behavior?

Parts of music are quieter than others, menu tick sounds are barely audible

### Steps to reproduce the problem

1. Boot up Fire Red
2. Adjusted volume down
3. Audio no longer works as intended
4. Readjusting volume slider did not help

### What game were you playing

Title: Pokemon - Fire Red Version (USA, Europe)
GB, GBC or GBA: GBA
ROM CODE: BPRE
BIOS Used?: Don't know
SAVE TYPE: Automatic
Clean, Intro'd or Hacked?: Clean

### What settings are you using?

Video driver: OpenGL
Sound driver: OpenAL
Scale Filter Used: Unsure

### Specifications and Build details

VBA-M: VBA-M 2.0.1 64-bit
OS: Windows 10 64-bit
CPU: AMD Ryzen 5 3600 6-Core Processor
GPU: RTX 3060
RAM: 16 GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Duplicate https://github.com/visualboyadvance-m/visualboyadvance-m/issues/823
