### ISSUE TITLE
[Feature request]: Additional strings to wxvbam.pot

### ISSUE THREAD

**Issue by StanleyKid-22** [visualboyadvance-m/visualboyadvance-m#1029]
### Request box

Once when I've launched Visual Boy Advance-M for testing translation (I translate into Ukrainian), I noticed that 7 strings remained untranslated. And although they are not announced in the **wxvbam.pot**, I've decided to add them in PO-file by my own hand - in the end, the translation was shown in the application. And that's despite the fact that, e. g., the strings "License", "Developers" and "Artists" don't seem to be declared at all in the source, or I didn't find them.
I've collected (maybe not fully) the references to the probable location of these strings in the source. Is it possible to include them to the POT?

### Reason box

This is for localization completeness.

### Examples

```
# --- Not approved ---
#: cmdevents.cpp:2929
msgid "License"
msgstr "Ліцензія"

#: cmdevents.cpp:2944
msgid "Developers"
msgstr "Виробники"

#: cmdevents.cpp:2952
msgid "Artists"
msgstr "Художники"

#: xrc/AccelConfig.xrc:117 xrc/CheatAdd.xrc:102 xrc/CheatCreate.xrc:208 xrc/CheatEdit.xrc:82
#: xrc/CheatList.xrc:54 xrc/CodeSelect.xrc:17 xrc/DirectoriesConfig.xrc:127 xrc/DisplayConfig.xrc:294
#: xrc/ExportSPS.xrc:58 xrc/GameBoyAdvanceConfig.xrc:270 xrc/GameBoyConfig.xrc:207
#: xrc/GBAROMInfo.xrc:162 xrc/GBPrinter.xrc:57 xrc/GBROMInfo.xrc:171 xrc/GeneralConfig.xrc:149
#: xrc/JoypadConfig.xrc:40 xrc/LinkConfig.xrc:33 xrc/Logging.xrc:127 xrc/MemSelRegion.xrc:39
#: xrc/NetLink.xrc:98 xrc/SoundConfig.xrc:344 xrc/SpeedupConfig.xrc:60 xrc/UIConfig.xrc:19
msgid "OK"
msgstr ""

#: xrc/AccelConfig.xrc:120 xrc/CheatAdd.xrc:107 xrc/CheatEdit.xrc:87 xrc/CodeSelect.xrc:20
#: xrc/DirectoriesConfig.xrc:124 xrc/DisplayConfig.xrc:297 xrc/ExportSPS.xrc:61
#: xrc/GameBoyAdvanceConfig.xrc:273 xrc/GameBoyConfig.xrc:210 xrc/GBPrinter.xrc:64
#: xrc/GeneralConfig.xrc:152 xrc/JoypadConfig.xrc:43 xrc/LinkConfig.xrc:36 xrc/MemSelRegion.xrc:42
#: xrc/NetLink.xrc:103 xrc/SoundConfig.xrc:347 xrc/SpeedupConfig.xrc:63 xrc/UIConfig.xrc:22
msgid "Cancel"
msgstr "Скасувати"

#: xrc/Disassemble.xrc:473 xrc/GBDisassemble.xrc:242 xrc/GBMapViewer.xrc:162 xrc/GBOAMViewer.xrc:155
#: xrc/GBPaletteViewer.xrc:123 xrc/GBTileViewer.xrc:158 xrc/IOViewer.xrc:341 xrc/MainMenu.xrc:212
#: xrc/MapViewer.xrc:224 xrc/MemViewer.xrc:121 xrc/OAMViewer.xrc:168 xrc/PaletteViewer.xrc:116
#: xrc/TileViewer.xrc:174
msgid "Close"
msgstr "Закрити"

#: xrc/IOViewer.xrc:335
msgid "&Apply"
msgstr "&Встановити"
```

**Comment by StanleyKid-22** [comment]
UPDATE:
If delete _**#, c-format**_ in that unit, Poedit won't give an error about % sign, 'cause in this case it isn't a macro, like %s, %d, etc.
```
#: xrc/GeneralConfig.xrc:96 xrc/SpeedupConfig.xrc:27
#, c-format
msgid "% of normal:"
msgstr ""
```

**Comment by rkitover** [comment]
I'll just change it to "percent".

**Comment by rkitover** [comment]
These strings are in the wxWidgets source code, I need to see if they provide translations or a way to translate their strings.

**Comment by rkitover** [comment]
They do provide a translations catalog, but I need to do more research on how to integrate this with our build system so that it works on macOS and Windows as well.

In the meantime, I'll add some translation markers for these strings that you found specifically.

**Comment by rkitover** [comment]
I've added translation markers for these strings and pushed the updated source to transifex, also fixed our transifex job while I was at it, they changed their API and stuff.

Sorry this took so long, please resubmit your translations for those strings on transifex.

**Comment by rkitover** [comment]
Also fixed the percent thing.

**Comment by StanleyKid-22** [comment]
> I've added translation markers for these strings and pushed the updated source to transifex, also fixed our transifex job while I was at it, they changed their API and stuff.
> 
> Sorry this took so long, please resubmit your translations for those strings on transifex.

Oh, great thanks.
P. S. You forgot delete string:
```
# --- Not approved ---
```
before
```
#: extra-translations.cpp:17
msgid "License"
msgstr "Ліцензія"
```
I've simply separated approved and non-approved strings in PO by _# --- Not approved ---_. Now that strings are approved, so it's superfluous now.

**Comment by Felipefpl** [comment]
> Also fixed the percent thing.

Thanks for this! I reported this problem to the dev of poedit and the guy just didnt give a damn... Instead he complained about me not reading something related to the report of issues but this is a reall problem.

**Comment by StanleyKid-22** [comment]
> Thanks for this! I reported this problem to the dev of poedit and the guy just didnt give a damn... Instead he complained about me not reading something related to the report of issues but this is a reall problem.

There is, however, an idea - to write the percentage as macro %% everywhere, and there are such samples in POT:
```
#: cmdevents.cpp:2229 cmdevents.cpp:2243
#, c-format
msgid "Volume: %d%%"
msgstr ""

#: sys.cpp:448
#, c-format
msgid "%d%%(%d, %d fps)"
msgstr ""

#: sys.cpp:456
#, c-format
msgid "%d%%"
msgstr ""
```
etc.
So, IMHO, the above problem with percent can be fixed in the same way by macro:
```
#: xrc/GeneralConfig.xrc:96 xrc/SpeedupConfig.xrc:27
#, c-format
msgid "%% of normal:"
msgstr ""
```
and now Poedit shouldn't give an error.
_Probably, I should have suggested that right away, but for some reason I didn’t think of it. Only problems added._ :full_moon_with_face:

**Comment by StanleyKid-22** [comment]
**And now little offtop-moment.**

@Felipefpl
But there's yet another problem, which is partially related with #993.
It happens that lines do not need translation. That's, **msgstr** matches with **msgid**.
There is an example right at the start of POT:
```
#: wxvbam.cpp:259
msgid "visualboyadvance-m"
msgstr ""
```
I think, **msgstr ""** should be left to show empty untranslated strings. But precisely 'cause of this nonsense, empty strings that don't need translation are considered as untranslated too in Poedit, Transifex, etc.
My proposition: it wouldn't hurt to come up with a variant for avoid confusion, so that **msgstr** simply inherits the **msgid** text with some other declaring or no declaring, for example:
```
#: wxvbam.cpp:259
msgid "visualboyadvance-m"
```
and that's all. The string will be assumed to be non-empty, 'cause it'll simply inherit original **msgid** text.

BUT! When you've written:
> I reported this problem to the dev of poedit and the guy just didnt give a damn... Instead he complained about me not reading something related to the report of issues but this is a reall problem.

then now I'm afraid to write something there.

**Comment by Felipefpl** [comment]
> then now I'm afraid to write something there.

You should be, the guy isnt exaclty the most friendly fellow. ;)

**Comment by rkitover** [comment]
> I've simply separated approved and non-approved strings in PO by _# --- Not approved ---_. Now that strings are approved, so it's superfluous now.

I've never seen this before, does "not approved" mean the strings are not in the source pot?

**Comment by rkitover** [comment]
> There is, however, an idea - to write the percentage as macro %% everywhere, and there are such samples in POT:

Fixed, thanks!

**Comment by rkitover** [comment]
> It happens that lines do not need translation. That's, msgstr matches with msgid.

I would have to test thoroughly that such a change would be supported by the tooling you guys and we use, such as the aforementioned poedit, transifex, gettext, etc..

In the meantime I can propose a different solution, we can remove the translation markers for all of these strings.

It would help if you guys could prepare a list of these strings for me because you are more familiar with our translations catalog, and I will do my best that they are not, and ever translated in the sources.

**Comment by StanleyKid-22** [comment]
> I've never seen this before, does "not approved" mean the strings are not in the source pot?

My fail.
I thought that you grabbed "Not approved" too by including new strings to the POT.
But in fact, when I merged files, I forgot that "Not approved" was left in old **uk.po**. And accordingly, it migrated to new, updated **uk.po**.
So everything is OK. I'll thoroughly review the translation one more time and send it to Transifex again. Sorry for that discomfort and thanks for understanding.

> It would help if you guys could prepare a list of these strings for me because you are more familiar with our translations catalog, and I will do my best that they are not, and ever translated in the sources.

But small obstacles begin here.
I'll give one example, when the text, it would seem, doesn't need translation, but the grammar of a certain language allows the possibility of translation. A purely human factor.
The author of AIMP (audioplayer) Greek translation for some time translated word "OK" into the similar letters of the Greek alphabet, and also with dots, then changed it to the traditional counterpart "Εντάξει".
There are such variants in the Ukrainian too: "Гаразд", "Добре", etc.
But I'm personally used to the generally agreed - "OK". If it's possible to "shorten" texts, why not use it?
Therefore, it's necessary to treat it responsibly. I can try to generate a list of such strings, but whether it'll be agreed with other languages - difficult question.
However, the idea is interesting.

**Comment by StanleyKid-22** [comment]
> It would help if you guys could prepare a list of these strings for me because you are more familiar with our translations catalog, and I will do my best that they are not, and ever translated in the sources.

I've made a list of probable strings that, IMHO, don't need translation.
[wxvbam_test.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/10252748/wxvbam_test.zip)
Additional:
1. Of course, it may be necessary to coordinate with other localizers (at least a few).
2. Some of the original English strings need to be corrected and clarified, if authors agrees. I'll send file with these corrects later when I can.

**Comment by rkitover** [comment]
> Of course, it may be necessary to coordinate with other localizers (at least a few).

Probably not possible, we don't really talk to the transifex contributors, we just pull their changes, I don't know if there are any facilities for that.

However, I've looked at your list and I don't think anything there would be in question.

> Some of the original English strings need to be corrected and clarified, if authors agrees. I'll send file with these corrects later when I can.

Absolutely, please do that, and I will replace the strings as well as mark them to not be translated.

**Comment by StanleyKid-22** [comment]
> Some of the original English strings need to be corrected and clarified, if authors agrees. I'll send file with these corrects later when I can.

I wanted to write back about the suggestion only, but other than that I have bad news. The moment with percent still doesn't work true:
![0](https://user-images.githubusercontent.com/97188687/208918314-35cbaa38-c985-4264-a53e-938f98597ba5.png)
This will have to do, as I said already at the beginning:
replace
```
#: xrc/GeneralConfig.xrc:96 xrc/SpeedupConfig.xrc:27
#, c-format
msgid "%% of normal:"
msgstr "%% норми:"
```
to
```
#: xrc/GeneralConfig.xrc:96 xrc/SpeedupConfig.xrc:27
msgid "% of normal:"
msgstr "% норми:"
```
That has worked in old POT, where _msgid "% of normal:"_ was. **I'm sure, after that, everything it'll be as it should be! :)**

I'm also sending PO with **ONLY** corrected strings. Note that the file contains both strings' types: those that, according to wxvbam_test.po, don't need translation, and those that do. Probably, part of the suggested corrections will be controversial. Therefore, @rkitover, the last word is yours.
[wxvbam_fixed.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/10278978/wxvbam_fixed.zip)

**Comment by rkitover** [comment]
In that case I will change it back to the word "percent" if there are no objections.

**Comment by rkitover** [comment]
Changed the percent thing in 87bdc93e.

@StanleyKid-22 I'll take a look at implementing that list of strings soon. Was dealing with a Wayland issue.

**Comment by rkitover** [comment]
@StanleyKid-22 Can you explain the format of your last attachment, is it your corrected strings for the current source file?

**Comment by StanleyKid-22** [comment]
> @StanleyKid-22 Can you explain the format of your last attachment, is it your corrected strings for the current source file?

Yes, it's only corrected strings for POT.

**Comment by rkitover** [comment]
@StanleyKid-22 Hey, sorry just getting back to this, I need a name and email you want to use for the git commit.

**Comment by StanleyKid-22** [comment]
> @StanleyKid-22 Hey, sorry just getting back to this, I need a name and email you want to use for the git commit.

If I understand correctly, you need my **current** nickname and mail?

Stanley Kid
stanley.udr.kid@gmail.com

**Comment by rkitover** [comment]
The nickname or name and email you want to appear in the git log for the authorship.

**Comment by rkitover** [comment]
Oh you posted that already, thanks!

**Comment by rkitover** [comment]
Your changes have been committed and pushed to transifex, please check that everything is ok.

**Comment by rkitover** [comment]
Let's move localization discussion here:

https://github.com/visualboyadvance-m/visualboyadvance-m/discussions/1071

**Comment by Steelskin** [comment]
The strings like `AutoA` or `Alt-Shift-F1` are string literals used in the INI file, they must not be localized.
