### ISSUE TITLE
Xbox 360 Controller does not work on Linux

### ISSUE THREAD

**Issue by 1ShotSniper** [visualboyadvance-m/visualboyadvance-m#103]
### Expected behavior
Controller works normally
### Actual behavior
Does not accept controller input in joypad config
### Steps to reproduce the behavior
Have controller plugged in
Go to Options>Joypads
Select control and press buttons
### ROM details

Which games are affected by the issue (please state if GBA or GB game):
N/A
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
N/A
### Option details

Video driver (simple, opengl or cairo):
opengl
Sound driver (directsound, xaudio, openal, SDL):
default
### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Manjaro Linux Stable
If using Linux, specify if using xorg or Wayland:
xorg
Version of code (pre-built binary version, or commit ref, or just "master"):
Commit:  1eb768578bc0c4fa17396f573a4b37a652f12acd
### Hardware details:

If relevant, the joystick you are using and the drivers you are using for it:
Standard Xbox 360 controller, kernel 4.10

**Comment by rkitover** [comment]
Have you tried some of the solutions here:

https://wiki.archlinux.org/index.php/Gamepad

Specifically:

https://wiki.archlinux.org/index.php/Gamepad#Joystick_not_working_in_FNA.2FSDL_based_games

but other solutions on that page as well.

**Comment by onhernandes** [comment]
I'm having the same problems here. I'm on Ubuntu 18.04, using standard Xbox 360 Controller. Tried with xpad and xboxdrv. When I open VBA-M and navigate to input settings, no controllers buttons are being recognized by the emulator =(

**Comment by rkitover** [comment]
@onhernandes please use master, the joystick code has been rewritten, I recommend xpad.

**Comment by onhernandes** [comment]
Hey @rkitover just to let you know that it's working! Thanks!
