### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Mwasduqw** [visualboyadvance-m/visualboyadvance-m#1036]
### Expected behavior?

No weird sounds.

### Actual behavior?

There is a sound that keeps playing and I can't stop it. I reset but it wont work.

### Steps to reproduce the problem

1.Playing Pokemon Fire Red
2.Using speed up button
3.During or after a battle a weird sound started.
4.The sound started playing

### Error messages?

No error message

### What game were you playing

Pokemon Fire Red

### What settings are you using?

Realtek Audio

### Specifications and Build details

VBA-M: 2.1.4
OS: 22000.1098

CPU:Intel Core i7 -8700

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
use a nightly build.
