### ISSUE TITLE
[Bug]: "We hope to see you again." PokeGold.gbc Glitch

### ISSUE THREAD

**Issue by dev01111** [visualboyadvance-m/visualboyadvance-m#1038]
### Expected behavior?

Expected behavior. Regular background.

### Actual behavior?

Strange background (URL)
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKAAAACQCAIAAAAA1/fXAAANL0lEQVR4nO1dIbervBKd+60nkEdWVlYiKyORlUgk8kh+ArISiURWIpGVyMrKSmTlE2nTNGQCScOB0Ox11100h27SbCbJMJPw79hEIEOVddLyMAz5j23b0oOf8IzwtNLyKE6d4O/avbT89wDHE/weAAAu1+tuuz2eoMgPRXWV8tdVIeWJ0520PCFEix+r//+kpQoIDRSGYVmWgDcEhqaRl5fl4vhJKruHbmG/LM1OSZJI+TFUxUVaXleSQgU/Vn9tgeNIJKIXwO4gDPcbckf3OpR5+WnDbbZE/MOtK/JDmp2okXH88vbBgPU0vwfQ4rdmwRh0LWwd/LSjjkIAgCi8GjD8/DTIX4gWvzULrmr5naJrYa7wq4Xf7Q+/cDqetrvtAL8ZxvNbs2Chw2FDgi0Lc47/qQEAbAEAWjm/MUbyW7NgxhtHe378sGVhS+PHGu5yvQKcdvsDPDWg5ceTnF8XuvyWx+CyLHkHIIpTu2OkE/yCBo/S00nKj5F0HbHCj9X/nyt+MOZHBhu5HwlACHk6S3kLWUgI1FWR5W88g/zlNZOWJ9v8rRp1d69/ASCo5O1wv12En4xdkSGK0ybJ7/VvEB0BgJRZk+T36Ef9LQGoBS/NT7WCKE51/VQMQf0wANri9+gngCPVGANVNIrTQWkBNwBdoAIvzU81QF0VhKTCnaTrp2Ig5cOyG8h5jQ2oRl6urgqo5d2qAs74wWZoGiAE6CjURC0A3C0x15s7AATRkZQZ09giKD/Fo3M24nHGDzbD/VY0TUpI2DxHUrv8AFBv7hNpTBHdAoOhl8EZP9gYT40BgI7udvijWwAADQAANElOyqyOhkdWXX4wmljxcMYP1kbeBllKR3qqMS0mxBL/O5okJ3HaJLniHHY5eqCeajEqpu5joh6VWhVzxg82YXnX+FmaWuE3+NaYyTODYLXMDdPFv+6q56cCQF0VQd2RMqs390dPAgAAcS7pSZJtLr1hdf3gOP8RXHN6OcEfNeafOh48NT/WPqgFk6iRljc1iVhfdCybumMOgxqC/zdy8OP9VFrjKuukd5JYz0ZebuDHy6valf0yg3it1Kyxu1Mdb5a2DypwlsgD0U09XA8MvMZ9fxSDmZ9qNx7cr21dlVbitUIbNs2r5lbizeZ+sDChMLPj5WDqeLDCgoNNCs87kpCUz+X4PN5sKLBk4l6O+uKgutb91JH8U8eDFV7G/VYEmzTYpP1e5/N4s7UnWWMwxnat+8Ej+aeOB6v5HxqX+6ezrs2PwVDgQPZQtB+A4kd7rZ5Z6qcyfnowZqo1nn/qeDDGzwz3fisCeF3LIN4sbR9DgamPxJfE+QY72WDQlfqpnyg6yD91PBjlz9sA9vfkDAD35Az1SzPdeLO0fZyJB88Vb1ZkPbqdF720eLCCXxpIF7wLhu5HO94sfQB56iReg0t50UuLB6v9SGYfUZxST+zVp71juzWJB0u8hsqOn+rzogf46QjEN9Nf+tk+L1obuvyYBevym8HnRWvDuXizz4uelr/KWoMu+u/zlqfmX3NetC0/Wxdu5EXrxoN1/cjrtZaWp9nJCr+tvGjA49n9YS+O9nWVWonXYs8bbPnZ1vxgXbiSF13V5zja8xrTj9KHagbxWsCe0J0lwhv42db8YF04lBfNa8yLbcUPprhdm6Z4u7N1/WAMfxpN+nvYyoumGkPPS/ncD37UswjZPgKPxebnzgq/NT/YFtzKi57CD75dG7ahwAzx4Lnitcawkhct7aIppvCDb9dm8wwMf8j/n8HlKe+kTwQt8OctTYWBh8ZA/yn4q6wT/tFyXlTWV1+u18v54Qjs9offA9B/g/z8gQIG/FJY84PNeKbl18mLxoLNfZOlGh9bO/Fahvb8Nj3YW/KzrfnB2A+wlbfs86It50Uv0A/2edE286Jd94N9XjTFyv3g8fB50Q+45QeP5/d50Q845weP5Pd50W9Q5+UyGCe6+rzomfOix/uRtvjB50Ur+cH1vGjdB1sYP8ZzzOXtULdbLR4s3oy1z2kTyMuD8LvyotXop0bLN3nGgQkpHeQUVdLdT/uO3biV5AZdc160AtLEyjgnWvXBnJC+36mex37oBzN8XV60AtLUaGwLQpQEseDfT2rGAWsfGqXu4wQhfFVetAKIBevNyD4J1/PQbx/5GEzxRXnRU8OWBWu3D2LBDN+SF62AlS7algVT6LSP3IK/Li9aff7n2Qd2x+Dx7UMQhii8ftd+0br8unnLWsuZ4mhfXrMq60jatud7uA/gmTiXEXk9aX64kA1O58lI/e342c74wVZ6CJP1u0hedFUO5NxIUeQHWg16QKHV/ej62c74wQZjvK28ZSwvmkdThHH+c7vq1vF1CaEa6I4Aa/WD53qvEUU/L/rZoK/OGR9Ph1GWJetaxm8Rx8N5P9iMf+r1uwDQtXuStpJXo5mC3UzYX6XlzvvB877XqN9F0/o0LdhVl0KhsW77OOMH6/JbXL/bz4uu6rO40gTgdm3a813dT7M5Mz3gp1paWKEfPNd7jbC86PJK+MKHukNQKMonIMPQSDyDHwz6edG0ZnVVBOUespCu4uVn1/xuG3mz77dguA8wvzPYpJD3XOQspDu+0x/Stm1dFf0ZrPCLbtdGKN9sCQHCVh4w7PaHNDux35XlBb1KGIa6UyfsSdyl2vIfl7s+GKgGAFTd+62ABOD2+iu1KqYxfZ7Aa/z4SBD2vH3cNAyPjyH0blPo3Z0su5guBeM1ph8vt263P/Aas4/U4qm6cbQ3mxVjwPxgDLPlRQMA5G0TAanDBlqWjkSTV3j7lmosiI3xvzR+HvSl7UPIHec15sW+nE9MVF5sarLUtpiF5Zmd1T0u5UWTOhQOAKBOxD2lqcZ0gzr2XHDMgAfw1JgecKDtLp1CS1dOsCWdQndNNaYHAjn0htVZMGdeNIt18wID9wo4eJpyXRVxPmx5Y6CQFkavi1GDdRJTCOxqXjQTmxomb8T8sV4XDdDvohUPjBTqSrto4HpmYTxmGDMiaEG3/efOi85CQqCJWlKHWPIKAy9qf84lJX/1zNx4LJ31sJW7/frzovLjMS8qPx7Dc+7DptDq32WA8X78nHnRpA6hfh48/6+TFyfjB5nJsvFYDmEKDQ+N45t8TjtouwxU491WdJMe4/Hp1LYtP8OaoqOeYX3w1PtkzRVv7tp9kiR9kci21Yo3A3IP2dona/J4sC7cijf3nZxaM29ZASv7ZE0eD9aFK/Hmrt2XZdn/jbb2saL4fJ+syePBU2PGeDMyS2phSftkTR4PtoWlxZttrQ8eD7N9siaPB9vCd8abBRjskzV5PNgulhNvtrU+GDSfEywuL9qMZzz/jPFmqSMbhXrx5sHnBB/uk+V8XjTMtA8XIPHgzbmzkndt671MgLSPM3nRurC1DxcWD970NtMAIz/Y4j5ZUjiTF60Li/xYPHiK9yaRqGFvbl7WPlkzrg/+A2Dx4M/94Loq8nIHzzdyRzHJktetuaB9smZcHzwjvxU/OEsuebnLy13/resL2ifLlfXBZvxYPBgs+cFUY+mLKpeyT9YfrA+eax8uaTzYVt41M9wsucTnl8C2/Gxn8qLn2ocLiwd359ZK3nV7hvi8o+8grYpLFL/+ZMXPtuYHT72fs+57kwhLgP6M35afOvV+0X+RFz3pfs66sMhv5f3BmJBaWQD+vUlT8X/+/mD8Sd/b+fxStmX5wd+Jz+O1cf7D5ucAUGVhzPUXC/KDbcEtfhv7RUd0HseHgQ34MTgTD14s/6f7RccAz7l6XdUA4mlL8YNh4v2c7eJzflvx2ts1oIa72RI4vzJQbfnZNuPBk+7nbIvZIr+VeG0LZzjXURwBQBRHVfuaP9t5b9L9Pm4Vl4ebMHy1nYcr8AKvHG9jcBDgS308HIEw5r4EDoLAj8crgKDjY5LFSr0ROw1BTRDGYK+u6+grKPGDfUftKKT2Kc6ivbruQqqdd5NWDi/wyuEFXjm8wCuHF3jl8AKvHF7glQMVuO81Gz/n8g/IZsT6LfjLb6/hlB1plIlvtU8efkl5BEl4fq3rspPpgTGP4nzdcoyc/+2DPIrz+xgQmH6/f1XFR4xHqKWaR1que13ptwx4sBMwHoP2GXNdMx6VwIyRaiz8Sesy4+84NWbpb4Wfj1kYj+WMC4ZZlVPHJLAGnSsWMqanwc4fQz7dDaESWGhZvptVDJPjobAMKaHZddm3eFXMxnLhfKw+BvWUzj+wemrdEG8ZHQvJ2llINf4MtmasINNxiYvPvkpdmPj3rt8P/nJ4gVcOL/DK4QVeObzAK4cXeOXwAq8cXuCV4+8EXs7z96/CcLiQHvQjbvzH/qPU/tMZLOKmPsHjQwwIPCbIPBiUxkoGv+LxOcZa8Ej4fnhpGBXwB2UYa/B8A/STbDzMMBAP5nVSpNQMnu8xF8aOwTwU0WyFouoBeDyPhxZM4sG+9R2Cf9CxcniBV463LnrS9D6PP0B/9BT3yfLjq+sQTPSfLc/VYzngrfQ/aamHuxB09NsJrxz/B8qEs3rsxjNzAAAAAElFTkSuQmCC

### Steps to reproduce the problem

1. Play PokeGold.gbc from (source removed)
2. Go to a Poke Center many times
(it may be unreproducable

### Error messages?

There was no crashes or sounds or error messages. Just a really screwed up background

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title: POKEMON_GLD
GB, GBC or GBA: GBC
ROM CODE: ???
BIOS Used?: None
SAVE TYPE: Natural game saving
Clean, Intro'd or Hacked?: Clean, I think. Built from [pret/pokegold](https://github.com/pret/pokegold) on [this repo](https://github.com/dev01111/pokegold).

### What settings are you using?

Video driver (simple, opengl): OpenGL
Sound driver (directsound, xaudio, openal, SDL): SDL
Scale Filter Used?: ???

### Specifications and Build details

VBA-M: v2.1.4: Commit 09fbcba
OS: Windows 10 Education
CPU: ???
GPU: ???
RAM: ???

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
You linked to a ROM. Please remove the link.

**Comment by rkitover** [comment]
Please try a nightly.

**Comment by Squall-Leonhart** [comment]
First gen pokemon games were horrible with leaving memory set between scenes, and this is more likely an issue with the decomp process than anything

**Comment by dev01111** [comment]
> First gen pokemon games were horrible with leaving memory set between scenes, and this is more likely an issue with the decomp process than anything

Valid point, but I have tested the ROM on other emulators. It's fine.

**Comment by dev01111** [comment]
> Please try a nightly.

Ok, will install.

**Comment by ZachBacon** [comment]
if there isn't an update on this, I'm closing this.
