### ISSUE TITLE
[Bug]:1043

### ISSUE THREAD

**Issue by reditsai** [visualboyadvance-m/visualboyadvance-m#1043]
### Expected behavior?

I thought the emulator whould run let me use cheats

### Actual behavior?

when I tried to use the cheat list and add a cheat the website crashed and closed.

### Steps to reproduce the problem

1.Open vba-m v.2.1.4
2.Open rom Pokemon Emerald Version (U)
3.Open cheats list
4.Press add new cheat

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
Try a nightly, I'm pretty sure this has been resolved already. http://nightly.vba-m.com

**Comment by Squall-Leonhart** [comment]
it is

closed.
