### ISSUE TITLE
Cannot play GBA ROM (games) greater than 32 MB

### ISSUE THREAD

**Issue by GauravSahare1993** [visualboyadvance-m/visualboyadvance-m#1046]
### Expected behavior?

All types of GBA games should work fine

### Actual behavior?

As compare to other emulators, even as compare from VBA 1.8.0 beta 3, it doesn't load ROMS greater then 32 MB.

### Steps to reproduce the problem

1. Visual boy advance does not play GBA ROMS greater than 32 MB.

### Error messages?

No issues on original ROM, but I am facing this issue on some specific games (actually modified ROM) which is greater than 32 MB, big name is "Pokemon Adventure Red Chapter beta 15 + Expansion Fix C" which is not loading only in VBA-M, but I am not facing this issue on another emulators such as mGBA, and even VBA v1.8.0 beta 3.

![Screenshot (2)](https://user-images.githubusercontent.com/109745579/208123696-bade58ad-28d7-4605-9a74-828e5d875696.png)
![Screenshot (1)](https://user-images.githubusercontent.com/109745579/208123725-5ecdc2f9-9d15-4fe0-9ea0-f7e7b55d4991.png)

Video driver (simple, opengl): Intel HD Graphics 530
Sound driver (directsound, xaudio, openal, SDL): Realtek HD Audio
Scale Filter Used?:

### Specifications and Build details

VBA-M: 2.1.5
OS: (include version and OS build number using WinVer if on Windows): Windows 11 and Windows 10 (64 Bit)
If using Linux, specify if using xorg or Wayland:
CPU: Intel Core i5- 6500T
GPU: Intel HD Graphics 530
RAM: 8GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by rkitover** [comment]
IIRC we broke this on purpose, perhaps as a "security fix", will need to investigate and revert that change.

What would be a reasonable max size for a ROM?

**Comment by GauravSahare1993** [comment]
Exact ROM size is 32770 kb.

**Comment by rkitover** [comment]
Please try the nightly in about 20 minutes.

**Comment by GauravSahare1993** [comment]
Thank you so much for reply, I downloaded debug version of VBA nighty build, problem is still not fixed, but yes thanks to debug version, I am sharing log file.
[Adventure Red.log](https://github.com/visualboyadvance-m/visualboyadvance-m/files/10247616/Adventure.Red.log)

**Comment by GauravSahare1993** [comment]
If above information is not complete, then please provide me steps, so I can better report to my problem.

**Comment by rkitover** [comment]
Sorry it took me a while longer to rebuild the nightly, can you try downloading it again please.

**Comment by GauravSahare1993** [comment]
Nope! problem is still present.

**Comment by Squall-Leonhart** [comment]
This is a regression introduced between 2014 and 2015, it is not size related.

**Comment by GauravSahare1993** [comment]
It's not matter what type of regression we are facing, if any problem in ROM, then same problem also happens with other emulators, but I am facing this problem only in VBA-M, I am sharing ROM information which is captured from both VBA v1.8.0 beta 3 and VBA-M (latest nighty build), if you want, I can also provide ROM (for testing and development purpose only). 
![Screenshot (3)](https://user-images.githubusercontent.com/109745579/208226073-c5e44f02-4098-4ba0-9de1-63455a996ae7.png)

![Screenshot (4)](https://user-images.githubusercontent.com/109745579/208225996-6a54c8a1-e513-4918-812f-909dbd5d07f6.png)

**Comment by Squall-Leonhart** [comment]
and I just gave you a workaround until someone has had a chance to take a look at it, share a rom and i'll block you from the repo and make the bug a feature.

**Comment by GauravSahare1993** [comment]
I didn't know that sharing ROM isn't legal, but I am providing information to resolve this issue only.

**Comment by Squall-Leonhart** [comment]
@skidau this is a regression from a change you made in https://sourceforge.net/p/vbam/code/1381/

**Comment by GauravSahare1993** [comment]
I am not familiar with coding, but it might be possible that some traditional thinks makes VBA more stable.

**Comment by rkitover** [comment]
Have you tried disabling mirroring on the override tab like Squall suggested?

**Comment by rkitover** [comment]
Go to `Options -> Game Boy Advance -> Configure -> Game Overrides` and for `Mirroring` choose `Disabled`.

**Comment by GauravSahare1993** [comment]
@rkitover Thank you so much sir for your great help, this step resolved my issue. But some additional steps that I want to share, so others like me do not face any misunderstandings during configuration.
1. Open **VBA-M**, go to "Help" menu and perform "**Factory Reset**", click "**Yes**" to confirm.
2. Now load **(open)** game, white screen appears that means game loaded, then go to **Options -> Game Boy Advance -> Configure -> Game Overrides**, in **Mirroring** choose "**Disabled**" and click "**OK**", white screen still appears, then press **Ctrl+W** to **close** game (do not close/exit GBA).
3. Finally open your game, and enjoy.

Sir, what is the roll of mirroring, is it helps for logging info or any mirroring game save file?

**Comment by rkitover** [comment]
It has something to do with working around anti-emulation measures on some titles, not applicable to these roms. I'll try to add some code to disable it automatically.

**Comment by JayroJones** [comment]
Please add 256MB ROM support (including the mapper) for the 369-in-1 bootleg ROM.

**Comment by Squall-Leonhart** [comment]
no
