### ISSUE TITLE
Animation error on Pokemon 3 gen [RS/FRLG/E]

### ISSUE THREAD

**Issue by Unknown326** [visualboyadvance-m/visualboyadvance-m#1050]
So far I was using VBA-M 2.1.4 x64 bits or its respective nightly version and I didn't find any errors. My operating system is LINUX MINT 21 Vanessa [Cinnamon] x64 bits and I run it with WINE 8.0 - rc2. What caught my attention is the animation of the pokeball that the trainer throws when entering combat since in version 2.1.4 it happens normally.

With the current version 2.1.5, the animation flickers and the pokeball doesn't spin. I tested it on all 3 gen games. Although it does not affect the game, it caught my attention and that is why I report it. In advance, thank you very much for your time and thanks for so much effort :)

Test in GBA 3 gen Pokemon games [RS/FRLG/E]

Settings

Video driver (simple, opengl): opengl
Sound driver (directsound, xaudio, openal, SDL): No
Scale Filter Used?: xBRZ 4x

Specifications and Build details

VBA-M: 2.1.5 x64 bits
OS: Linux Mint Vannesa Cinnamon x64 bits

**Comment by Squall-Leonhart** [comment]
turn off frame skipping.
