### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by String123YT** [visualboyadvance-m/visualboyadvance-m#1055]
### Expected behavior?

it is supposed to play the game at regular speed

### Actual behavior?

it is running the game at a speed so much higher than its supposed to
if theres a way in the settings to fix this it needs to be more obvious because i was looking for 30 minutes for a way to fix it

https://user-images.githubusercontent.com/122235219/211220832-8f29c05f-991b-478d-84ae-ed96f7036bca.mp4

### Steps to reproduce the problem

1. i open the gba rom
2. when it starts to play it plays extremely fast

### Error messages?

there was no error message

### What game were you playing

i was playing spongebob battle for bikini bottom and super mario advance 4.
https://www.romsgames.net/gameboy-advance-rom-spongebob-squarepants---battle-for-bikini-bottom/
https://www.romsgames.net/gameboy-advance-rom-super-mario-advance-4---super-mario-bros-3-menace/

### What settings are you using?

im using the default settings on the emulator

### Specifications and Build details

VBA-M: VisualBoyAdvance-M 64-bit 2.0.2
OS: windows 11 home
CPU: AMD Ryzen 3 
GPU: AMD Radeon
RAM: 12 gigs

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by String123YT** [comment]
i dont know what half the stuff on there means but i did my best ;v;

**Comment by Felipefpl** [comment]
Are you really using 2.0.2 instead of 2.1.5 or any of nightly builds?

**Comment by Squall-Leonhart** [comment]
Closed, have some common sense

**Comment by ZachBacon** [comment]
Also next time a bug report is filed and you link to roms, and you click that checkmark box to say no infringing files attached. Well, let's just say I'll remove them, and you from the reporting any issues on this projects issue board. Linking or attaching infringing roms are a no no, and could have dire consequences for you and the project. Just don't link to roms PERIOD.

**Comment by String123YT** [comment]
it literally said to do exactly that (what roms were you using) im sorry
what the fuck did you want from me?

**Comment by String123YT** [comment]
also the only download i could find was of that version. how was i supposed to know there were more versions when i coulnd't find them? find some common sence fucktards

**Comment by Squall-Leonhart** [comment]
![image](https://user-images.githubusercontent.com/1098176/211231746-b4ddfd8f-fddc-4753-877c-8ef5700d17d1.png)

**Comment by String123YT** [comment]
what does any of that even mean? i never used github so idk what the hell that stuff is

**Comment by String123YT** [comment]
also what "common sence" you told me to all that stuff so i did. fix your bug reporting site. if you dont want people to link stuff when why tell ppl to do that

**Comment by ZachBacon** [comment]
Fix your ability to read is what should be done first.
