### ISSUE TITLE
[Bug]: Compiler Identification Unknown - Building with Chocolatey/Windows Powershell

### ISSUE THREAD

**Issue by VenomBottle** [visualboyadvance-m/visualboyadvance-m#1058]
### Expected behavior?

When following these steps:

`mkdir build
cd build
cmake .. -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_BUILD_TYPE=Release -DUPSTREAM_RELEASE=TRUE -G Ninja
ninja`

in Windows Powershell, after going through the chocolatey install, The Windows .zip build should be available.

### Actual behavior?

The cmake command results in some errors. 

In Windows Powershell, it mentions this:

> -- The C compiler identification is unknown
> -- The CXX compiler identification is unknown

In the CMakeError.log file, the following is appended:

> Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
> Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
> Checking whether the CXX compiler is IAR using "" did not match "IAR .+ Compiler":
> Checking whether the CXX compiler is IAR using "" did not match "IAR .+ Compiler":

I have tried to manually specify the compiler locations, doing it to gcc and g++ using "-D [Full path of compiler]" with the cmake command but that hasn't worked. I don't have the level of expertise to root cause the issue, but it seems likely that something is missing from the cmake files.

### Steps to reproduce the problem

1. Open Windows Power shell (with chocolatey installed)
2. cd to the vba-m directory
3. mkdir build
4. cd build
5. cmake .. -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_BUILD_TYPE=Release -DUPSTREAM_RELEASE=TRUE -G Ninja
ninja

### Error messages?

In Windows Powershell, it mentions this:

> -- The C compiler identification is unknown
> -- The CXX compiler identification is unknown

In the CMakeError.log file, the following is appended:

> Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
> Checking whether the C compiler is IAR using "" did not match "IAR .+ Compiler":
> Checking whether the CXX compiler is IAR using "" did not match "IAR .+ Compiler":
> Checking whether the CXX compiler is IAR using "" did not match "IAR .+ Compiler":

### What game were you playing

N/A: Attempting to build VBA-M for windows (and have a valid reason for wanting to do so)

### What settings are you using?

Windows Power Shell with Chocolatey as per the linked guide:
https://github.com/rkitover/windows-dev-guide

### Specifications and Build details

VBA-M: 2.1.5 64-bit
OS: Windows 10 21H2 19044.2364
CPU: Intel Core i7-4710MQ
GPU: NVIDIA Quadro K3100M 
RAM: 24.0 GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by rkitover** [comment]
Did you install Visual Studio or Visual Studio build tools and load the environment in your `$profile`?

**Comment by VenomBottle** [comment]
Hi, I believe the recommended Windows dev environment (Chocolately in Power Shell (Admin)) has VS as one if its components. I also have an actual installation of Visual Studio which I’ve also tried. In Visual Studio the errors are a little different, “you specified x64 but your compiler is for x86. I guess the reason is the same here but VS has picked a compiler bu default that was incompatible. Do you know which compiler(s) should be specified?

On 14 Jan 2023, at 18:41, Rafael Kitover ***@***.***> wrote:

﻿

Did you install Visual Studio or Visual Studio build tools and load the environment in your $profile?

**Comment by rkitover** [comment]
If you are building from the Visual Studio command prompt or powershell prompt shortcut, you need to use the 64 bit version to build the 64 bit binary.
