### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by AAide** [visualboyadvance-m/visualboyadvance-m#1059]
### Expected behavior?

Quit the emulator when you click on the cross or choose quit in the menu 

v2.1.5

### Actual behavior?

When I quit via the cross or the menu, the emulator remains open and freezes, I have to kill the process

v2.1.5

### Steps to reproduce the problem

1.
2.
3.
4.
5.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: 64
OS: windows 11 22621.1105
CPU: 9900k
GPU: rtx 2080
RAM: 64

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by AAide** [comment]
iam tested v2.1.4 its working not problem in closed emulator

Problem in v2.1.5

**Comment by Squall-Leonhart** [comment]
report it on microsoft feedback hub, its not our bug.
