### ISSUE TITLE
incorrent ROM type detection

### ISSUE THREAD

**Issue by condret** [visualboyadvance-m/visualboyadvance-m#106]
https://github.com/visualboyadvance-m/visualboyadvance-m/blob/fec17c7900cbf8e30d6caf535a51339f18d996e4/src/libretro/UtilRetro.cpp#L100

this is wrong, because the ending of a filename says nothing about the content of a file.

I once took part in a reverse-engineering contest. One of the crackmes was a gb-rom, named flux.dat.
vbam refused to emulate it, until I renamed the file to flux.gb.

I would expect vbam to check the header of the file instead of the name.

**Comment by ZachBacon** [comment]
So what you're saying this is a specific issue for the libretro interface? Also follow the issue tracker template. It keeps things in perspective of what issues are for what interfaces.

**Comment by condret** [comment]
To be honest, I didn't use the template, because I didn't think this bug fits into the template, since it a bug in concept which can be spotted at easiely in the codebase.

I don't think this is a pure libretro interface issue, because something similar is done in unused code here:
https://github.com/visualboyadvance-m/visualboyadvance-m/blob/9b65a9cf29ccd626968b40f5fa9b91a9bd8bb5fb/src/gb/GB.cpp#L808

If you think that is something that should be fixed. I could send a pr for this. I allready did that for radare2

**Comment by ZachBacon** [comment]
I wouldn't say no really, especially since I don't know when I could get to it. At the moment I'm rather stuck at my day job.

**Comment by condret** [comment]
I found another one https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/src/Util.cpp#L400 so which one of the three do you want to keep maintained, I'd like to delete the other 2 then
