### ISSUE TITLE
[Bug]: The game i am playing is unreasonably dark 

### ISSUE THREAD

**Issue by AmiJustStupid** [visualboyadvance-m/visualboyadvance-m#1063]
### Expected behavior?

the game i am playing (Mario and Luigi Superstar saga) is much Darker in comparison to VBA-M 2.0.1 where i started on 

Is This a new feature? 
![igje](https://user-images.githubusercontent.com/123308579/213920140-3e1137ad-7056-46b9-bf88-d894f181e0cb.png)

![Mario   Luigi - Superstar Saga (U)](https://user-images.githubusercontent.com/123308579/213920146-b805717c-16e1-49f8-9e83-30b7f2530210.png)

### Actual behavior?

the game is much darker then how it was before i switched to  Version 2.1.5

### Steps to reproduce the problem

1.
2.
3.
4.
5.
...
i dont know how to reproduce this problem

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

Title: Mario and luigi Superstar saga
GB, GBC or GBA: GBA
ROM CODE: 
BIOS Used?: no
Clean, Intro'd or Hacked?: Clean

### What settings are you using?

Video driver (simple, opengl): OpenGL
Sound driver Directsound
Scale Filter Used?: No

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by AmiJustStupid** [comment]
Dont know if this is a bug 

If this is the wrong place to post this kind f issue ill just delete it post it where its meant to be

**Comment by Squall-Leonhart** [comment]
Turn off LCD filter.

**Comment by AmiJustStupid** [comment]
> Turn off LCD filter.

Im an Idiot how do i do that?

**Comment by Squall-Leonhart** [comment]
Options > Gameboy Advance. >

**Comment by AmiJustStupid** [comment]
> 

Thanks A lot!

**Comment by ZachBacon** [comment]
I'm going to mark this as resolved, feel free to comment if it hasn't fixed your issue.
