### ISSUE TITLE
My game freeze and i cant do anything[Bug]: 

### ISSUE THREAD

**Issue by capefg** [visualboyadvance-m/visualboyadvance-m#1064]
### Expected behavior?

I was about to enter in a combat and the game just freeze

### Actual behavior?

The game is just freeze, and i dont want to loose all my progress

### Steps to reproduce the problem

1.I dont know, I just enter in a combat with a Team Rocket member
2.
3.
4.
5.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (pengl):
Sound driver ( SDL):
Scale Filter Used?:Fullscreen

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Filling out the template is not optional.
