### ISSUE TITLE
possibly remove ELF parser?

### ISSUE THREAD

**Issue by condret** [visualboyadvance-m/visualboyadvance-m#107]
This is not a bug report in the first place, more a question:

Why do you have an elf-parser?

**Comment by ZachBacon** [comment]
You'd have to ask the original author for that, sadly forgotten isn't really around to answer such questions.

**Comment by condret** [comment]
I think that should better get deleted, since there seems to be no reason for maintaining it, and the code is buggy (found a few potential buffer-overflow because of sprintf)

**Comment by ZachBacon** [comment]
Drop by IRC.freenode.net channel #vba-m and we can discuss more freely there
