### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by OscarThePupper** [visualboyadvance-m/visualboyadvance-m#1082]
### Expected behavior?

The cheat should work (Rare candies should be present in the PC).

### Actual behavior?

The cheat does not work (Rare candies are absent in the PC).
![image](https://user-images.githubusercontent.com/83546841/219007605-b9d85cd1-8a20-4f27-9eb5-bb801eb2a302.png)

### Steps to reproduce the problem

1. Boot up game.
2. Add the rare candy cheat and enable it.
3. Get past the intro.
4. Boot up PC.
5. Withdraw Items.
6. Nothing present except Potion.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title: Pokémon FireRed V1.1
GB, GBC or GBA: GBA
ROM CODE: 
BIOS Used?: No
SAVE TYPE: Flash 128K
Clean, Intro'd or Hacked?: No

### What settings are you using?

Video driver (simple, opengl): OpenGL
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?: HQ 2X

### Specifications and Build details

VBA-M: V2.1.5 64 Bit for Windows
OS: Windows 11 Insider Beta Build 22623.1255
CPU: Intel i5 8265U
GPU: Intel UHD 620
RAM: 8GB DDR4 2400Mhz Single-Lane Memory

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
This isn't an emulator bug, the cheats do not work on 1.1

**Comment by OscarThePupper** [comment]
But these are Codebreaker Advance codes..?

**Comment by Squall-Leonhart** [comment]
Codebreaker codes only exist for 1.0

**Comment by OscarThePupper** [comment]
They don't work on 1.0 either..

**Comment by Squall-Leonhart** [comment]
The Red master codes on most lists have been made against a bad dump.

**Comment by Squall-Leonhart** [comment]
> They don't work on 1.0 either..

![image](https://user-images.githubusercontent.com/1098176/219019742-683696b1-3fbb-4e22-9614-1db4b65165df.png)

Did for me.
