### ISSUE TITLE
[Bug]: Some settings are not saving.

### ISSUE THREAD

**Issue by kam92** [visualboyadvance-m/visualboyadvance-m#1083]
### Expected behavior?

When I change some options like enable RTC and savetype, the settings should be saved in vbam.ini.

### Actual behavior?

It doesn't save the settings.

A lot of roms, specially romhacks, require 128k flash as save type, I set that using emulator options, but after restarting the software, I have to set again or the game will give me warning in main menu.

The solution right now I edited vbam.ini with notepad and set saveType=3 and flashSize=1, it works, stays saved. 

Personally I think this is one of the main reasons people are recommending to not use vba-m, because settings don't save so they think is not working even tho is configured.

I think a quickfix could be shipping pre-configured settings with real world clock enabled and save type of GBA default to Flash 128k, since 99% is playing the same genre, while you figure it out why is not saving...

### Steps to reproduce the problem

1. Open VBA-M
2. Options > Game Boy Advanced > Configure...
3. Set Save Type to Flash and 128k
4. Save and exit 
5. Restart VBA-M and check the values, unchanged
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl): simple
Sound driver (directsound, xaudio, openal, SDL): sdl
Scale Filter Used?: none

### Specifications and Build details

VBA-M: last release 2.1.5
OS: Windows 10 Single Language - version  21H2 - compile 19044.2364
CPU: Ryzen 4700G
GPU: Integrated Vega Card
RAM: 16GB DDR4

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Steelskin** [comment]
I'll take a look at that one later today.

**Comment by Steelskin** [comment]
I tried to reproduce with a build from master but could not. Could you try the latest nightly? https://nightly.vba-m.com/

**Comment by Squall-Leonhart** [comment]
this doesn't happen on nightly or latest release

**Comment by kam92** [comment]
> I tried to reproduce with a build from master but could not. Could you try the latest nightly? https://nightly.vba-m.com/
I tryed and it seems to be working! I don't know what happened here, i will stick with nightly for now. Thank you.



> the rom hacked games that require 128KB are modifications of original titles that are meant to use 64KB, and because the hackers never change the ROM id there is no way to supply a preconfigured file that doesn't affect the original.
> Problem is more than likely environmental.

Oh, that scenario didn't cross my mind. On romhacks I play, the original rom already requires 128kb... That is indeed a good point to not do it.
