### ISSUE TITLE
[Bug]: HuC-3 support is incomplete

### ISSUE THREAD

**Issue by DJSwayde** [visualboyadvance-m/visualboyadvance-m#1084]
### Expected behavior?

HuC-3 games are supposed to save starting from 2.1.5

### Actual behavior?

HuC-3 games are not saving

### Steps to reproduce the problem

1. Start Robopon: Sun Version
2. Save
3. See if a .sav file was created
4. If so, start again to see if Robopon reads save file or if have to start new game
5.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA: Robopon: Sun Version
ROM CODE: SUN
BIOS Used?: (Share crc hash) 32CAEF11
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl): Simple (I think, emulator crashes whenever I try to configure video)
Sound driver (directsound, xaudio, openal, SDL): SDL
Scale Filter Used?: No

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version) 64-bit
OS: (include version and OS build number using WinVer if on Windows): WinVer10
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
it is only fully implemented on libretro's end.

**Comment by DJSwayde** [comment]
Appreciate the insight, thank you so much!

**Comment by Squall-Leonhart** [comment]
lets leave this open, but can you edit the title to something like "HuC-3 support is incomplete"

**Comment by DJSwayde** [comment]
Absolutely, done. Thank you.

**Comment by Squall-Leonhart** [comment]
Just to document this,

The absense of the sav file does indicate that atleast part of the issue is that the huc-3 save support isn't wired up to the file read/write in some way,  the save itself does appear to be correctly created in the emulators memory as the reset button allows the game to be loaded.

**Comment by Squall-Leonhart** [comment]
Attached is a test build for you, it already has past my testing with this game but if you have any more HUC3 stuff please test.

[visualboyadvance-m.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/10834150/visualboyadvance-m.zip)

**Comment by DJSwayde** [comment]
Thank you! I have tested that one and if you start a new file in Robopon (SUN) with that VBA build and save it, then it works great, and I am able to continue the save file that I created in the session after resetting. However, it seems to have issues reading .sav files created from other sources. I tried to use a save created from mGBA and it wouldn't read that particular save file. I am not sure if this is functioning as designed or if I am doing something incorrectly. Thank you, I genuinely appreciate your assistance.

**Comment by Squall-Leonhart** [comment]
VBAM has some binary differences to mgba that might be a result of the inaccuracies in negative exponentials implementation.

**Comment by DJSwayde** [comment]
Awesome either way, thank you so much for this!

**Comment by Squall-Leonhart** [comment]
MGBA doesn't create hardware exact sav files, the extra 16 bytes are RTC data appended specically by mgba for use by mgba.

https://github.com/mgba-emu/mgba/issues/2718
