### ISSUE TITLE
[Bug]: Cannot map new input to a specific key.

### ISSUE THREAD

**Issue by chancesorton** [visualboyadvance-m/visualboyadvance-m#1089]
### Expected behavior?

Should be able to map the in game control of L to another key. I tried mapping it to D and does nothing in game when the button is pressed. Still works using the default keyboard selection of I though.

### Actual behavior?

When pressing D, nothing happens. I still allows the emulator to perform the button press.

### Steps to reproduce the problem

1. Map the input to D.
2. Go in game and press D, nothing happens.
3. Press I in game and the selected button works.

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

Any ROMS I have tried ended up with the same behavior.

### What settings are you using?

Mostly default settings with the input remapped.

### Specifications and Build details

32-Bit VBA-M 2.1.5

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
by 32bit. you mean 32bit windows? We need complete details about your system to make a better diagnosis

**Comment by chancesorton** [comment]
My apologies, 64-bit Windows running 32-bit Visual Boy.

**Comment by ZachBacon** [comment]
just out of curiousity? Why remain using a 32bit build, we have 64bit builds. Aside from that have you tried to do a factory reset from the help menu?

**Comment by chancesorton** [comment]
Yeah I tried to use the 64 bit version and that let me remap the key and use it. Not sure why I selected the 32 bit. Thanks!

**Comment by ZachBacon** [comment]
still an issue to look into, I don't really use windows much anymore, but I'll fire up a vm and see if I can get this figured out.

**Comment by PrimaIVoid** [comment]
I already reported this problem for 32bit version here: https://github.com/visualboyadvance-m/visualboyadvance-m/issues/1061#issue-1538494296

**Comment by ZachBacon** [comment]
Because there's still some use cases for 32bit, albeit a dwindling case for it, but since we still support it, I'll be doing what I can go try and fix it, so while I'm choosing to believe your response @PrimaIVoid as not snark, as I've stated I'll do what I can, time for me is limited though given a day job I work at. So either myself or someone else in the team will deal with it, until then, be patient.

**Comment by Squall-Leonhart** [comment]
I cannot reproduce this
