### ISSUE TITLE
[Feature request]: Port to Vita

### ISSUE THREAD

**Issue by RinMaru** [visualboyadvance-m/visualboyadvance-m#1095]
### Request box

Port VBAM to Vita

### Reason box

MGBA seems to fall short of perfection simply because it can't reach full speed and I think VBA M would fix this.

### Examples

N/A

**Comment by Squall-Leonhart** [comment]
No, sorry, although the Vita uses an arm processor which will eventually be supported (for Windows for Arm) support for Vita also requires creating a GUI from scratch using toolsets that none of us have the time or energy to play with and learn.

RA already has a Vita compatible core (VBA-Next) but it is also no better performance wise as the Vita users a fair bit older Arm architecture than modern phones and notebooks.
