### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Migi645** [visualboyadvance-m/visualboyadvance-m#1096]
### Expected behavior?

"Unable to find link driver"
<img width="277" alt="Screen Shot 2023-03-15 at 4 59 45 PM" src="https://user-images.githubusercontent.com/127999923/225471880-6dbdbda7-fd79-4088-ad55-03141dbc91a4.png">

### Actual behavior?

I would like to play multiplayer but the GBA will not link. I remember trig it a while ago and it worked I wonder why not now? Am I doing something wrong? 

### Steps to reproduce the problem

1. Down load VBAm 
2. Open VBAm "unable to find link drivers" 
<img width="542" alt="Screen Shot 2023-03-15 at 5 08 22 PM" src="https://user-images.githubusercontent.com/127999923/225474573-c6628d47-1739-438f-9c57-2739a93cf737.png">

3. Change type to "Nothing" and re-open. (Error message gone).
4.  Start link network it blacked out... Why?? Genuinely confused. 
5. Tried running 2 instances but that didn't work. 
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

Title: Kirby AM 
GB, GBC or GBA: GBA
ROM CODE: Im not sure 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

I don't know how to find this information, but I'm willing to learn. 

### Specifications and Build details

VBA-M: 2.1.5 64-bit version
OS: Im using a Macbook pro 
<img width="347" alt="Screen Shot 2023-03-15 at 5 04 29 PM" src="https://user-images.githubusercontent.com/127999923/225473324-015d5948-df73-4e24-bba7-3fa32750fe08.png">

If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Migi645** [comment]
I hope this is sufficient information for this issue, I'll provide more if necessary. Thank you Dev GODS!

**Comment by Squall-Leonhart** [comment]
Local mode and "Start **Network** Link" are self explanatory in means of incompatible, really.

**Comment by Migi645** [comment]
I'm gonna pretend like I just didn't have a total brain fart there. *facepalm* I've been trying for two days to figure this out. Just to have it right under my nose. bruh moment bruh moment bruh moment. Thank you for your help.
