### ISSUE TITLE
[Bug]: cheats causing vba (color) to crash trying to add cheats for pokemon crystal clear

### ISSUE THREAD

**Issue by iSaluteU** [visualboyadvance-m/visualboyadvance-m#1097]
### Expected behavior?

the emulator should be working normally when i add a cheat to it

### Actual behavior?

https://user-images.githubusercontent.com/126745468/225524996-049e69fe-2fa1-4c4d-94c7-a5178f16ad02.mp4

### Steps to reproduce the problem

1. click tools
2. press cheats
3. press list cheats
4. the window crashes

https://user-images.githubusercontent.com/126745468/225525380-a2707d84-1938-4c23-91fa-94ea8771cc42.mp4

### Error messages?

there was no error code

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title: Pokemon Crystal Clear
GB, GBC or GBA: GBC
ROM CODE: does not show
BIOS Used?: (Share crc hash) i have no clue
SAVE TYPE: (Attach Battery or Savestate here) battery
Clean, Intro'd or Hacked?:(Attach Patch here) clean

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

none

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version) 32 bit
OS: (include version and OS build number using WinVer if on Windows): winver
If using Linux, specify if using xorg or Wayland:
CPU: 2.55
GPU: no clue
RAM: 400

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Closed Invalid / Out of date.
