### ISSUE TITLE
[Bug]: Digimon Racing (GBA) unplayable in EUR/USA version

### ISSUE THREAD

**Issue by Sonny35** [visualboyadvance-m/visualboyadvance-m#1099]
### Expected behavior?

VBA should be able to run the game.

### Actual behavior?

In the EUR version it is not able to advance from the opening credits. It freezes on one screen with sound only.

![image](https://user-images.githubusercontent.com/9279268/226143951-e0bcc5ac-f8f4-4d8c-9f13-25900fec238e.png)

In the USA version you can advance from that screen, but when you start any race, the terrain is rendered glitchy, is completly broken (In the screenshot you can't see it as much as playing the game).

![image](https://user-images.githubusercontent.com/9279268/226143918-1d591854-9846-46ec-9334-bf6264e0306f.png)

I don't know how the game behaves in other versions.

### Steps to reproduce the problem

1. For EUR version only start the game.
2. For USA version only start any race.

### Error messages?

NO error message.

### What game were you playing

**Title:** Digimon Racing
**GB, GBC or GBA:** GBA
**ROM CODE:** BDGP (EUR) / BDGE (USA)
**BIOS Used?:** Default
**SAVE TYPE:** Default
**Clean, Intro'd or Hacked?:** Both clean

### What settings are you using?

**Video driver (simple, opengl):** Both
**Sound driver (directsound, xaudio, openal, SDL):** Default
**Scale Filter Used?:** All the same

### Specifications and Build details

**VBA-M:** 2.1.5 64 bits
**OS:** Windows 10 64 bits v22H2 OS 19045.2728
**CPU:** AMD A10-7850K Radeon R7
**GPU:** AMD Radeon R9 200 Series (3 GB)
**RAM:** 16 GB 1333 MHz DDR3

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
The EU version despite having no support for the wireless adapter actually fails if its not emulated and enabled.

the US version is already fixed in nightly

**Comment by Sonny35** [comment]
Oh okay, thanks.

Where can i find the last version of nightly?

**Comment by Squall-Leonhart** [comment]
https://github.com/visualboyadvance-m/visualboyadvance-m/files/10843208/visualboyadvance-m.zip

**Comment by Squall-Leonhart** [comment]
EU variant is now resolved in https://github.com/visualboyadvance-m/visualboyadvance-m/commit/1ab46f704f9885afbc517e4267cf3860e7b46d68
