### ISSUE TITLE
Unable to configure input without having English as system language on Fedora

### ISSUE THREAD

**Issue by KingMucus** [visualboyadvance-m/visualboyadvance-m#110]
### Expected behavior

Being able to change input configurations normally using the gui when the Fedora system language is set to German.

### Actual behavior

I open the input configuration window and, after attempting to change the key bindings, the controls dont work when I go to the game. After I go back to the input configuration window after that, the fields for all key that were configured to joypad buttons are blank. The emu registers the joypad buttons as Joy1-Achse1-, Joy1Taste2, etc. and the emu doesn't recognize it. if I run the emu through the command LANG=en_US.UTF-8 it does not happen. This but also affect translated keyboard buttons, like shift (this was translated to UMSCHALT in German) – so there are many keyboard buttons that con't be used if the LANG variable is set to German and it may also affect some other languages. The fields are blanked even if there are other valid, non-translated and recognized key bindings besides the translated ones.

### Steps to reproduce the behavior

Just run "LANG=de_DE.UTF-8 visualboyadvance-m" and try to configure input using a joystick and certain keyboard buttons.

### ROM details

Pokémon Kristall Version.

Which games are affected by the issue (please state if GBA or GB game):

Pokémon Kristall Version. It is a GBC game.

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

### Option details

Video driver (simple, opengl or cairo):

I tried simple and opengl.

Sound driver (directsound, xaudio, openal, SDL):

SDL

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):

Fedora Linux

If using Linux, specify if using xorg or Wayland:

I'm using xorg because I'm using the KDE spin atm.

Version of code (pre-built binary version, or commit ref, or just "master"):

I downloaded the rpmfusion rpm.

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

dmesg recognizes it as a PS3/PC WireGamePad . It works wonderfully if LANG is set to English

**Comment by denisfa** [comment]
@KingMucus If you are still around for some reason... This was fixed with #437 and it will be available on next release!
