### ISSUE TITLE
[Bug]: UI does not work properly with Mac OS dark mode

### ISSUE THREAD

**Issue by Longtime4321** [visualboyadvance-m/visualboyadvance-m#1102]
### Expected behavior?

UI properly displays elements when using dark mode on Mac OS

### Actual behavior?

<img width="611" alt="Screenshot 2023-03-25 at 8 56 41 AM" src="https://user-images.githubusercontent.com/40969041/227721562-f2e8415d-7fd8-491b-a7e9-bd49b4a92ffa.png">

### Steps to reproduce the problem

1. Go to appearance in the Mac settings
2. Select Dark

### Error messages?

no

### What game were you playing

I was in the menu, no game was loaded yet

### What settings are you using?

Stock settings for mac.

### Specifications and Build details

VBA-M: Nightly, mac os x86-64
OS: Mac OS ventura 13.1 
CPU: 1.1 GHz Dual-Core Intel Core i3
GPU: Intel Iris Plus Graphics 1536 MB
RAM: 8GB

### Copyright Compliance

- [x] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
I believe this is an upstream issue, @ZachBacon is anything special needed for dark mode on mac apart from building with a Wx version that supports it?

**Comment by ZachBacon** [comment]
> I believe this is an upstream issue, @ZachBacon is anything special needed for dark mode on mac apart from building with a Wx version that supports it?

Not that I'm aware of. But I don't currently run macos anymore. I'm down to one computer for the time being.

**Comment by Squall-Leonhart** [comment]
This appears to be an issue affecting Ventura widely across apples own apps too.

**Comment by rkitover** [comment]
I am using an old Wx version for mac builds right now, I was planning to also do more modern builds with a target later than 10.7.

**Comment by rkitover** [comment]
This is fixed in the new nightlies, but there are still issues with the dialogs on mac that need to be looked into.
