### ISSUE TITLE
[Bug]: Cheats will not go away even though the list is empty, cheats are disabled and the emulator has been restarted

### ISSUE THREAD

**Issue by OdinsRaven23** [visualboyadvance-m/visualboyadvance-m#1107]
### Expected behavior?

I expect cheats to disappear from save files after they are disabled

### Actual behavior?

The cheats are still reflected in my save file 

### Steps to reproduce the problem

1. enable cheats
2. add cheats to list 
3.
4.
5.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title: final fantasy tactics advance
GB, GBC or GBA: gba
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
yeah, thats working as expected.
