### ISSUE TITLE
[Bug]: Pokéballs and related sprites in Pokémon Ruby/Sapphire not behaving like they should

### ISSUE THREAD

**Issue by RoutetoVictoryRoadPod** [visualboyadvance-m/visualboyadvance-m#1112]
### Expected behavior?

First off: I'm not very tech experienced. So, I'm sorry that I can't offer much information into what I'm doing or what's going on, but any information will be greatly appreciated.

My girlfriend and I are using VBA to run Pokémon Ruby and Sapphire. I'm using a much older version of VBA since I have been using it for a long time (1.8.0-beta 3) while my girlfriend only recently downloaded the newer version (M 2.1.5). 

Pokéballs fall to the ground and shake when they have a Pokémon "inside" them. While shaking, they maintain their size and shape and merely rock back and forth.

The Berry Blender is a mini-game in which players are using an in-game item to make stat increasing blocks. The mini-game consists of a spinner that spins counter-clockwise and has a pointer that, when it passes your marked area on the board, you press the interact button and you get a success if it's before the pointer reaches your area, but it's in your quadrant; a critical success if you're able to press interact when the pointer is directly on your marked area; or a failure if you are too early or late.

### Actual behavior?

Funny enough, my emulator, though extremely outdate, runs the emulation perfectly, but with hers we have issues:

- Pokéballs shrink to a size only a few pixels across while "shaking"

- The "Berry Blender" mini-game is completely unplayable, as the layer that houses the "spinner" bugs out completely, shrinking in size and pointing in random directions.

### Steps to reproduce the problem

1. 
2.
3.
4.
5.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title: Pokémon Ruby Version (USA, Europe) (REV 2)
GB, GBC or GBA: GBA
ROM CODE: AXVE (or maybe B)
BIOS Used?: (Share crc hash) None
SAVE TYPE: (Attach Battery or Savestate here) Flash
Clean, Intro'd or Hacked?:(Attach Patch here) Clean (I think, I am not sure what this means, but I don't think the ROM is altered)

### What settings are you using?

Video driver (simple, opengl): Both (I tried troubleshooting)
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version) M 2.1.5 64-bit
OS: (include version and OS build number using WinVer if on Windows): Windows 10
If using Linux, specify if using xorg or Wayland:
CPU: intel i7 7700 CPU @3.60ghz
GPU: nvidia geforce gtx 1060 3GB
RAM: 32GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Already fixed in Nightly

**Comment by RoutetoVictoryRoadPod** [comment]
Thank you so much for your time, and your prompt reply!
