### ISSUE TITLE
[Bug]: Real-time clock in some games is not recognized

### ISSUE THREAD

**Issue by IXARKI** [visualboyadvance-m/visualboyadvance-m#1113]
### Expected behavior?

real time clock work normally

### Actual behavior?

real time clock don't recognized in some games

### Steps to reproduce the problem

1. Open the file (in this case de game is Pokemon Unbounded)
2. The message "The correct system time could not be read." when you start the game.
3. 
4.
5.
...

### Error messages?

No.

### What game were you playing

Pokemon Unbound v2.1.1.1
Pokemon FireRed

### What settings are you using?

Video driver (simple, opengl): OpenGL
Sound driver (directsound, xaudio, openal, SDL): XAudio2
Scale Filter Used?: xBRZ 2x

### Specifications and Build details

VBA-M: 2.1.5 x64
OS: (include version and OS build number using WinVer if on Windows): 
If using Linux, specify if using xorg or Wayland: W10 22H2 OS19045.2604
CPU: Intel(R) Core(TM) i7-2630QM CPU @ 2.00GHz QuadCore
GPU: Intel HD Graphics 3000
RAM: 16GB 1600Mhz

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Read the pinned issue for pokemon games.
