### ISSUE TITLE
[Bug]: Crashing while opening PC in pokemon emerald

### ISSUE THREAD

**Issue by TheDiscoQueen12** [visualboyadvance-m/visualboyadvance-m#1117]
### Expected behavior?

![issue](https://user-images.githubusercontent.com/130921634/232326796-cea7208e-55c8-4cd8-b0c5-c3f4e6b36b17.png)

### Actual behavior?

When I want to open the PC (Pokémon emerald) It's freezing and the healer is turning green..
I tried to play this game on my boy app and it's working great, and even the shiny Pokémons cheat works..! but in this emulator it's broken..
  You need to fix it asap..please..

### Steps to reproduce the problem

1. I walked into the poke-center
2. I enable Infinite rare candies and masterballs cheat
3. I opened the PC
4. I selected "MAY's PC" (my PC)
5. The game Froze and crashed.

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA: GBA
ROM CODE: I don't know
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here) AutoSave
Clean, Intro'd or Hacked?:(Attach Patch here)
[Pokemon - Emerald Version (U).zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/11242858/Pokemon.-.Emerald.Version.U.zip)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:
I don't know because i never checked.

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:
I Don't know how to check it, sorry but i can say that my Computer is very old and a bit slow.

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
Try a nightly at http://nightly.vba-m.com please and report back.
