### ISSUE TITLE
[Bug]: DPAD key mapping problem in ver 2.1.5; Direction key keep spamming when pressed only once

### ISSUE THREAD

**Issue by qes-fhliew** [visualboyadvance-m/visualboyadvance-m#1118]
### Expected behavior?

Hi. Good day to you dear developers.
Recently I downloaded version 2.1.5, and map my bluetooth joystick using DPAD for Directions: Up, Down, Left and Right.
It had mapped to "Joy1-Button13", "Joy1-Button14", "Joy1-Button15" and "Joy1-Button16" respectively. This mapping causing when I just clicked the button once, it keep triggering the directions non stop until I need to close the application.

Before this I was using the version 2.1.1, and it Mapped to "Joy1-Hat0N, Joy1-Hat0S, Joy1-Hat0E, Joy1-Hat0W" and these were working completely fine without keep spamming the directions. But the downside of ver 2.1.1 is the key mapping doesn't allow to map the secondary keys.

Hardware: The controller I using is Mocute-054 from online store. This device working fine for PC games like GTA5, DMC.
O/S: Window 10 Pro 64 bits
RAM: 32GB

### Actual behavior?

Recently I downloaded version 2.1.5, and map my bluetooth joystick using DPAD for Directions: Up, Down, Left and Right.
It had mapped to "Joy1-Button13", "Joy1-Button14", "Joy1-Button15" and "Joy1-Button16" respectively. This mapping causing when I just clicked the button once, it keep triggering the directions non stop until I need to close the application.

### Steps to reproduce the problem

1. Connected to Remote Device
2. Open the visualboyadvance-m ver 2.1.5
3. Configure the Input for Joysticks for Directions
4. Directions mapped to my DPAD as Button 13, 14 ,15 and 16 respectively
5. Load the any game, then tryout the directions using my DPAD button. It keep spamming the direction without stop.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title: Legend Of Zelda The Minish Cap, Advance War II
GB, GBC or GBA: GBA
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl): OpenGL
Sound driver (directsound, xaudio, openal, SDL): DirectSound
Scale Filter Used?: Display Filter: Super Salx2, Scale at 3x

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU: Intel i5-4670K
GPU: Asus Radeon RX470
RAM: 32GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
the stuck input is due to wireless interference, a common issue on 2.4Ghz bands such as that of bluetooth.

try turning on bluetooth coexistence support in your wireless router.

**Comment by qes-fhliew** [comment]
Hi, @Squall-Leonhart.
Yet, others buttons are working fine for the mapped keys.
Except for DPADs in the version 2.1.5.
If the interference is valid, the others keys might impacted. 
I'm not so sure on this too LOL

**Comment by Steelskin** [comment]
I ordered that gamepad. It's going to be a few weeks but I'll take a look.

**Comment by Steelskin** [comment]
I received the controller but I am sorry to report I cannot reproduce this issue. I also suspect interference on the 2.4 GHz band but it is odd that this does not reproduce with version 2.1.1. I suspect that something changed in the SDL handling of events in case of packet drops, resulting in SDL interpreting a disconnect as a "button up" event, when it used to consider it a continuous press.

One thing I can suggest is to report what you see at this website when holding a D-Pad direction : https://gamepad-tester.com/ (oddly enough, the Chromium stack interprets the D-Pad as different discrete values for an axis control). Otherwise, it seems the manufacturer has firmware updates for the controller, you could try these too.

**Comment by qes-fhliew** [comment]
Hi, I had updated the controller firmware to latest one still facing the same issue on version 2.1.5.
However, I noticed the version 2.1.1-d66e8108 is working fine for me as it allow for multi key binding.
In this version  2.1.1-d66e8108 the Input had mapped the DPAD buttons as "Joy1-Hat0N, Joy1-Hat0S, Joy1-Hat0E, Joy1-Hat0W"
where in version 2.1.5 it mapped to button 13~16. 
I think is the difference for the SDL thing, sorry im not sure how is the SDL works :)

**Comment by Steelskin** [comment]
There is a new option in the gamepad controls to use the older API. I have no idea if it is going to solve your problem but it is worth a try. Could you try the latest nightly here and report back, please? https://nightly.visualboyadvance-m.org/ You want the `visualboyadvance-m-Win-x86_64.zip` file.

**Comment by Steelskin** [comment]
@qes-fhliew Thank you very much for confirming. I would very much like to get to the bottom of this issue. I believe the problem is deep within SDL but I don't have any way of testing it as the controller is working fine for me. Would it be okay to leave the issue open and ask you to try a couple of things? If not, I understand and I'll just close the issue.

**Comment by qes-fhliew** [comment]
Sure I would like to offer my help if it within my ability haha.
