### ISSUE TITLE
Super Game Boy Mode stops working on VBA-M 2.0.0 Beta 2

### ISSUE THREAD

**Issue by Zombie-Ryushu** [visualboyadvance-m/visualboyadvance-m#112]
### Expected behavior
Super Game Boy enabled games such as Wario Land II boot as Super Game Boy color pallettes.
### Actual behavior
Super Game Boy enabled games such as Wario Land II boot as  Grayscale pallettes.
### Steps to reproduce the behavior
run vbam Wario\ Land\ II\ \(UE\)\ \[S\]\[\!\].zip 
### ROM details

Which games are affected by the issue (please state if GBA or GB game):
Super Game Boy enabled Roms with no Game Boy Color Support

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
GB color Roms.
GBA Roms
GB Classic (DMG) Roms.

### Option details

Video driver (simple, opengl or cairo):
opengl
Sound driver (directsound, xaudio, openal, SDL):
sdl
### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Linux, Mageia
If using Linux, specify if using xorg or Wayland:
X.org 1.17
Version of code (pre-built binary version, or commit ref, or just "master"):
master
### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

Rolling back to 1.8.0.1231 resolves the issue.

**Comment by ZachBacon** [comment]
Yeah... Beta 2 is old. Don't use it. We made progress since then.
https://github.com/visualboyadvance-m/visualboyadvance-m/releases/tag/throttle

That's the latest tag we have.
