### ISSUE TITLE
[Bug]: Save states not loading everything in Wario Land II both GB/SGB and GBC versions

### ISSUE THREAD

**Issue by avengah** [visualboyadvance-m/visualboyadvance-m#1123]
### Expected behavior?

The game should load the position exactly when the save state was made.

### Actual behavior?

The game puts Wario in the correct position and the screen looks right at first, but the level data isn't loaded correctly. If you load the state from a fresh reset, you'll fall through the floor. If you collect some coins and/or break some blocks then load the save, the coins and/or blocks won't be there any more; if they're on the screen at the point of the save state, you'll walk through them and if they aren't on the screen or you scroll them off and on again, they disappear.

### Steps to reproduce the problem

1. Play Wario Land II
2. Make a save state
3. Do anything in the game; collect or break stuff; reset even
4. Load the save state
5. The things you changed between saving and loading stay changed, and a full reset means the level data doesn't load at all.
...

### Error messages?

No

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA: GB
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)
![image](https://user-images.githubusercontent.com/285430/235061629-2abf1b99-ba8b-4147-95e2-4e0e299327b5.png)
[Wario Land II (USA, Europe) (SGB Enhanced)-01.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/11350229/Wario.Land.II.USA.Europe.SGB.Enhanced.-01.zip)

### What settings are you using?

Video driver (simple, opengl): OpenGL
Sound driver (directsound, xaudio, openal, SDL): SDL
Scale Filter Used?: HQ 2x

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version) 2.1.5-1f57d5f7 64-bit
OS: (include version and OS build number using WinVer if on Windows): Windows 10 Pro Version 21H2 OS Build 19044.2846
If using Linux, specify if using xorg or Wayland:
CPU: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz, 2496 Mhz, 2 Core(s), 4 Logical Processor(s)
GPU: Intel(R) HD Graphics 520
RAM: 8GB RAM

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by avengah** [comment]
The same exact thing happens when using the GBC version of Wario Land II.
[Wario Land II GBC (USA, Europe) (SGB Enhanced)-01.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/11350293/Wario.Land.II.GBC.USA.Europe.SGB.Enhanced.-01.zip)
![image](https://user-images.githubusercontent.com/285430/235063673-26f8e9dc-285d-4af5-941e-6309cee5004d.png)

**Comment by Squall-Leonhart** [comment]
WFM, validate your dumps against the hashes on datomatic
