### ISSUE TITLE
[Bug]: White screen

### ISSUE THREAD

**Issue by Juninh567** [visualboyadvance-m/visualboyadvance-m#1124]
### Expected behavior?

The game should open.

### Actual behavior?

White screen.

### Steps to reproduce the problem

1. Open VisualBoyAdvance
2. Open any game

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

Title: Pokemon - Ruby Version (USA, Europe)
GB, GBC or GBA: GBA
ROM CODE: AXVE
BIOS Used?: (Share crc hash)
SAVE TYPE: Default
Clean, Intro'd or Hacked?: Clean

### What settings are you using?

Video driver (simple, opengl): Crashes when checking
Sound driver (directsound, xaudio, openal, SDL): SDL
Scale Filter Used?: None

### Specifications and Build details

VBA-M: 2.1.5 64-bit
OS: Windows 7 Compilation 7601 Service Pack 1
CPU: Intel Atom D525
GPU: Intel Graphics Media Accelerator 3150
RAM: 2GB

### Copyright Compliance

- [x] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
So I want to say this is a your system issue, buuuuut I'm not going to dismiss it out of hand right now, can you try a nightly from https://nightly.vba-m.com and see if that works?

**Comment by rkitover** [comment]
Try this:

In explorer, open `%USERPROFILE%\AppData\Local\visualboyadvance-m`
.

Edit the file `vbam.ini`.

Change:

```
RenderMethod=opengl
```
, to:

```
RenderMethod=simple
```
and try running a game again.

**Comment by Juninh567** [comment]
The problem was solved
