### ISSUE TITLE
[Bug]: turbo mode 

### ISSUE THREAD

**Issue by Ryzeboy** [visualboyadvance-m/visualboyadvance-m#1125]
### Expected behavior?

Normaly when you active the turbo mode. The game are suppose to be faster 

### Actual behavior?

When a active the turbo mode my game dosen’t go faster 

### Steps to reproduce the problem

1.
2.
3.
4.
5.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

Pokemon radical fire red 

### What settings are you using?

I use my iPhone for this 

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Steelskin** [comment]
You are probably using a retroarch frontend for iOS. There is no official VBA-m release for iOS.
You will have to contact the devs you downloaded this package from.
