### ISSUE TITLE
[Bug]: I just found that the codes that i was using for the cheats weren't working, I don't know if it was just me no understanding it (even if I did everything right) or just a bug.

### ISSUE THREAD

**Issue by Zanderchezcake** [visualboyadvance-m/visualboyadvance-m#1126]
### Expected behavior?

I was supposed to get 99 rare candies from the PC in pokemon light platinum

### Actual behavior?

There were zero rare candies when I opened the PC

### Steps to reproduce the problem

I followed the wikihow guide ->https://www.wikihow.com/Get-Infinite-Rare-Candy-in-Pok%C3%A9mon-Light-Platinum 

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

There was no error message 

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

I was using GBA

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

I don't know what that is

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:6-bit
RAM:8.00 GB (7.65 GB usable)

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
take it up with the rom hack developer, cheats are fine in original games.
