### ISSUE TITLE
[Bug]: cheats aren't working

### ISSUE THREAD

**Issue by ERENPROO** [visualboyadvance-m/visualboyadvance-m#1127]
### Expected behavior?

After entering the cheat (or using find cheat) it should work, but it doesn't work.

### Actual behavior?

Cheat doesn't work(can't get infinite dp)

### Steps to reproduce the problem

1.Open emulator.
2.Open Mother 3
3.After game is loaded, constantly changing dp value to get cheat of it
4.Setting the new value(of the cheat)to 999
5.Restarting the game
6.Cheat doesn't work

### What game were you playing

Needed things:
ROM INFO:![Ekran Görüntüsü (92)](https://user-images.githubusercontent.com/89633652/235838310-08c59ac4-cc72-4f97-8db9-f3ff6383a632.png)
SAVE FILE TYPE: BATTERY
ROM STATUS: HACKED(TRANSLATION PATCH)
i hope the info is enough

### What settings are you using?

Video driver (simple, opengl):opengl
Sound driver (directsound, xaudio, openal, SDL):SDL
Scale Filter Used?:(idk this one. so... Simple 4x?)

### Specifications and Build details

VBA-M: 2.1.5 1f57d5f7
OS: Windows 10 Pro 22H2(19045.2846)
CPU:(dont know)
GPU:(dont know this one either.)
RAM:4GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
You didn't create a cheat, you created a memory patch

Not every game has deterministic memory usage, and these games are known to have both anticheat and antipiracy mechanics.

**Comment by Squall-Leonhart** [comment]
Yes, as happens.

Which is why gameshark and action replay codes do more than patch a single memory address, i suggest using one of the many available DP codes available for one of those devices instead of relying on memory patches.

**Comment by ERENPROO** [comment]
The actual problem starts here. Even if i do use a master code, and restart the game, cheats doesnt work
