### ISSUE TITLE
[Feature request]: Video Synchronization

### ISSUE THREAD

**Issue by marky-1204** [visualboyadvance-m/visualboyadvance-m#1131]
### Request box

I'd love to have the video synchronization feature that VBA 1.8.0 had.

### Reason box

If my eyes aren't deceiving me, the emulator doesn't run games as smooth as VBA 1.8.0 with the Synchronization turned on, even with VSync and Auto Frame Skip activated.

### Examples

VBA 1.8.0 had this feature.

**Comment by ZachBacon** [comment]
Turn off vsync, it should fix that.

**Comment by marky-1204** [comment]
VSync or not, it still looks a bit slower than the other emulator.
I tried both of them (VBA-M 2.1.5 x86_64 and VBA 1.8.0, downloaded both from the official website) at the same time, and I noticed this. I also tried the Nightly version but nothing changed...

**Comment by ZachBacon** [comment]
You couldn't have downloaded vba 1.8 from us. Just let me correct you on that one. But as for your issue, please tell me more of your system, we have a GitHub issue template for a reason that you seemingly ignored completely. Like what your operating system is, what graphics driver you're using within vba-m (simple or open gl) all the important bits we need to better diagnose your issue.

**Comment by marky-1204** [comment]
I'm sorry for having used the feature request tab but I didn't think It would've become an issue.

**Comment by ZachBacon** [comment]
That site is unofficial and completely rips off our releases. Official site is https://vba-m.com

**Comment by marky-1204** [comment]
My god... Ok, gonna download from there and see if the issue is still there. Sorry again for the misunderstanding.

**Comment by ZachBacon** [comment]
It's alright, it's an on going issue, we've put out some PSA'S but there's not much we can do outside of awareness.

**Comment by Squall-Leonhart** [comment]
Your eyes are in fact decieving you, there is no difference in the vsync implementation between the 2.

**Comment by marky-1204** [comment]
Updated the emulator to the latest release (It's been a while since I last played on it). Whatever the problem I had was, it got solved. The games run as smooth as they should now.
