### ISSUE TITLE
[Bug]: "Error occurred. Please try again." When trying a Network Link online multiplayer

### ISSUE THREAD

**Issue by joejoe4477** [visualboyadvance-m/visualboyadvance-m#1134]
### Expected behavior?

We were supposed to be able to play multiplayer online, as if we had linked multiple gbas together in a room.

### Actual behavior?

When my friends try to connect to the server, They just get an error saying: "Error occurred. Please try again." However, after the error message, it says we are connected at the top of our screens with me as player 1 and them as player 2. When we open a rom, it stops responding and crashes.

Things to note
* I have port forwarded
*I can connect to myself by opening another window of the emulator.
*We have tried the nightly build

We Have tried a lot of things so there may be some things I havent mentioned here. Please help, and thank you
![asdfs](https://github.com/visualboyadvance-m/visualboyadvance-m/assets/134009295/4f298876-ed02-4084-99e5-21149649512b)

### Steps to reproduce the problem

1.Port forward
2. Try to connect to a friend via the "Start Network Link" feature
3. Error Occurred. Please try again.
4. Open the Rom anyway
5. Crash
...

### Error messages?

Don't know how to do that

All we get is Error occurred. Please try again.
![asdfs](https://github.com/visualboyadvance-m/visualboyadvance-m/assets/134009295/8a57b95d-7e03-4df7-a54a-404a7683f031)

### What game were you playing

The Error itself does not occur while playing a game. However, when I have ignored the error and tried to play the game anyway I was playing "The Legend of Zelda: A Link to the Past and Four Swords"

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version): 2.1.5 64 Bit
OS: (include version and OS build number using WinVer if on Windows): Microsoft Windows 10 Home. Version 10.0.19044 Build 19044

CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz   3.60 GHz
GPU: NVIDIA GeForce RTX 2070 SUPER
RAM: 32.0 GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Closed because theres 100 of these topics already, and no new resolutions to be had.

**Comment by joejoe4477** [comment]
Please do direct me towards some of these topics. I have looked through them all and found none like mine.
