### ISSUE TITLE
[Bug]: No text in Pokemon fire, it all disappeared

### ISSUE THREAD

**Issue by DarsSwift** [visualboyadvance-m/visualboyadvance-m#1137]
### Expected behavior?

text when there's meant to be text. 

### Actual behavior?

No text anywhere, in poke mart or poke center, or even the UI, if I click enter to bring up the bag, there is no UI

### Steps to reproduce the problem

1.i actually have no idea, i had a few cheats active but idk
2.
3.
4.
5.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title: Pokemon fire red
GB, GBC, or GBA:  GBA
ROM CODE: 
BIOS Used?: (Share CRC hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
fill out the things you skipped, or i'm closing this as invalid.

**Comment by Squall-Leonhart** [comment]
closed invalid, probably the bios regression though.
