### ISSUE TITLE
[Bug]: Horribly Pale, Dull, Poor Contrast Color Rendering in VBA-M

### ISSUE THREAD

**Issue by Welding-Torch** [visualboyadvance-m/visualboyadvance-m#1138]
### Expected behavior?

Hi! So I've been into emulation for many years now, primarily playing on my android smartphone with a physical controller. But I wanted to try out GBA emulation on my PC, so I downloaded the latest stable release of VBA-M. I have really fond memories of playing on the original VBA emulator, so it was great to see it being continued by the community. However, I was quite taken aback when I tried VBA-M with one of my favourite games- Metroid - Zero Mission and found that the game did not look at all the way I remembered it. I think this is a pretty serious and major issue for this emulator, because I downloaded it fresh and loaded a game out of the box and it looked like this, which is **not at all** what it should look like. 

See below for image comparison.

### Actual behavior?

![Screenshot (2552)](https://github.com/visualboyadvance-m/visualboyadvance-m/assets/46340124/880c3436-b453-4329-8e43-9d012fc672be)

Here I have attached a screenshot of the same game (Metroid - Zero Mission) running on first the original VBA emulator beta3 released on October 2nd, 2005 and then on the latest stable release of VBA-M (v2.1.5).

As you can see, the color rendering is extremely dull in comparison.

### Steps to reproduce the problem

1. Download VBA-M.
2. Run VBA-M.
3. Load any ROM

### Error messages?

No error messages

### What game were you playing

Title: Metroid - Zero Mission
GB, GBC or GBA: GBA
ROM CODE: BMXE
Clean, Intro'd or Hacked?: Clean

But this issue persists with any ROM that I try.

### What settings are you using?

Video driver (simple, opengl): opengl
Sound driver (directsound, xaudio, openal, SDL): default
Scale Filter Used?: default

### Specifications and Build details

VBA-M: visualboyadvance-m-2.1.5-Win-x86_64
OS: Windows 10 Version 22H2 (OS Build 19045.2965)

CPU: Intel Core i5-9300H
GPU: Nvidia Geforce GTX 1650
RAM: 16GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by rkitover** [comment]
Try turning off LCD Filter or download a nightly which has it off:

https://nightly.vba-m.com/

**Comment by Welding-Torch** [comment]
I tried downloading and installing nightly as it said before opening this issue, but it wouldn't run on my computer.
