### ISSUE TITLE
[Feature request]: Version bump to fix build on various Linux distros

### ISSUE THREAD

**Issue by NetaliDev** [visualboyadvance-m/visualboyadvance-m#1141]
### Request box

Please release a new version from a recent commit (like 2.1.6).

### Reason box

It seems like `vbam` 2.1.5 fails to build with the recent version 1.23.1 of `openal`, but building succeeds on the current master branch (commit 9331dbf9c881bf26f86ca819748460d482e29153) with `openal` on version 1.23.1.

I can confirm this for NixOS where I maintain the `vbam`-Package and I think the build will break on more distros when they update their `openal` to 1.23.1 (see [repology](https://repology.org/project/openal-soft/versions) for the current versions in the different distros).

So it would be nice if you could release a new version from a recent commit to fix building with `openal` 1.23.1.

**Comment by rkitover** [comment]
I'll try to get a new version out as soon as I can, I need to fix an issue with codesigning on mac first.

**Comment by rkitover** [comment]
The patch you want is https://github.com/visualboyadvance-m/visualboyadvance-m/commit/1d7e8ae4edc53a3380dfea88329b8b8337db1c52 .

**Comment by rkitover** [comment]
2.1.6 is out.
