### ISSUE TITLE
[Bug]: VBA-M 2.1.5 32-bit not doing anything when pressing letter A in the keyboard that is assigned to input Joypad1, L button

### ISSUE THREAD

**Issue by spasquier** [visualboyadvance-m/visualboyadvance-m#1143]
### Expected behavior?

I configured the Joypad/1 L button as my Keyboard letter A, so when I press the letter A, the emulator should register it as pressing the L button.

### Actual behavior?

I configured the Joypad/1 L button as my Keyboard letter A, so when I press the letter A, it doesn't register anything, the letter A works, since I'm writting from my keyboard right now. Also the Input config let me set the letter A as the L button, it saves it correctly. But when playing, I can't never press L because it doesn't recognize my letter A key presses.

See my attached vbam.ini [vbam.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/11783237/vbam.zip)

### Steps to reproduce the problem

1. Open game
2. Play normally
3. Try to press A in my keyboard to use the L button as in a GBA
4. It doesn't do anything.

### Error messages?

There is no crash, but the emulator doesn't read my Keyboard input, specifically the letter A assigned to the L button in the Joypad1.

### What game were you playing

Title: Metroid Zero Mission
GB, GBC or GBA: GBA
ROM CODE: ZEROMISSIONE
BIOS Used?: No
SAVE TYPE: SGM [Metroid Zero Mission-10.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/11783233/Metroid.Zero.Mission-10.zip)
Clean, Intro'd or Hacked?: Clean

### What settings are you using?

Video driver: opengl
Sound driver: SDL
Scale Filter Used?: HQ 2x, Billinear filter

### Specifications and Build details

VBA-M: version 2.1.5 from official website, 32-bit version
OS:
Edition          Windows 10 Pro
Version         22H2
Installed on  02/‎22/‎2023
OS build	     19045.3086
Experience    Windows Feature Experience Pack 1000.19041.1000.0
CPU: AMD 5900x
GPU: Nvidia 3070 TI
RAM: G.Skill 32 GB 3600Mhz

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Already fixed in nightly
