### ISSUE TITLE
[Bug]: Unable to find Link driver for cable link in macOS Ventura

### ISSUE THREAD

**Issue by dcarvalho-bridge-mt** [visualboyadvance-m/visualboyadvance-m#1146]
### Expected behavior?

Be possible to Link two VBA's.

### Actual behavior?

When VBA is started a message appear saying that it was Unable to find link driver and the button start network driver keeps disabled.

### Steps to reproduce the problem

1. Go To Options
2. Link
3. Select type cable
4.Close and open again VBA
5.The error message appears.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl): opengl
Sound driver (directsound, xaudio, openal, SDL): SDL
Scale Filter Used?: NO

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version) 64
OS: (include version and OS build number using WinVer if on Windows): macOS Ventura
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by rkitover** [comment]
You must be using a version other than ours, we don't have anything like a "link driver" option.

**Comment by 3m1l29** [comment]
<img width="1096" alt="Screenshot 2023-11-07 at 23 44 27" src="https://github.com/visualboyadvance-m/visualboyadvance-m/assets/150198593/4b65f0c3-6a19-40d7-a4b6-879e522e7b57">

I seem to have the same issue with the newest version (2.1.7.), am I doing something wrong?

**Comment by aronson** [comment]
I get the same issue on macOS Sonoma.

<img width="305" alt="image" src="https://github.com/visualboyadvance-m/visualboyadvance-m/assets/1026348/b40eaf17-40f8-488e-a0ef-b03ef4de60ea">

I downloaded straight from here.

@rkitover 
> You must be using a version other than ours, we don't have anything like a "link driver" option.

You commented on [a thread in 2020 where someone had the same issue](https://github.com/visualboyadvance-m/visualboyadvance-m/issues/123#issuecomment-455823502).

It's in the codebase. See [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/390482a719d60be723f0ec4a84f2c07f7a822389/src/gba/GBALink.cpp#L349).

This functionality does not work on any Mac I try it on. I haven't loaded a game at the point this error occurs.

**Comment by Squall-Leonhart** [comment]
Disable local mode, doesn't work anyway.
