### ISSUE TITLE
Segmentation fault when reconnecting GDB

### ISSUE THREAD

**Issue by xTibor** [visualboyadvance-m/visualboyadvance-m#115]
### Expected behavior
To be able to reconnect GDB after disconnecting it.

### Actual behavior
Segmentation fault.

### Steps to reproduce the behavior

I built the application with default settings from the master branch.

1. Open `visualboyadvance-m`
2. File -> Open..., load any GBA ROM file
3. Tools -> GDB -> Break into GDB
4. Open `gdb` 
5. Run `target remote localhost:55555`
6. Tools -> GDB -> Disconnect
7. Tools -> GDB -> Break into GDB
8. Segmentation fault

### ROM details

Which games are affected by the issue: Any GBA game I tried

### Option details

Video driver: Any

Sound driver: Any

### Build details

Operating System: KDE neon 5.9 (based on Ubuntu 16.04 LTS)

If using Linux, specify if using xorg or Wayland: xorg

Version of code: fed6f2389ebeb33c803a9ccc173214c327dd06d2
Version on GDB: GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.04) 7.11.1

**Comment by condret** [comment]
Have you tried with radare2 gdb-client, just for curiosity?
You cannot really blame them btw, gdb is such a broken protocol.
Can you provide valgrind output?

**Comment by xTibor** [comment]
No, I haven't tried with radare2 yet. I'll get a valgrind output but currently I'm away from my pc for some weeks.

**Comment by knightsc** [comment]
I was able to reproduce this on macOS 10.14.1 using the latest code from master with commit db8aaeca

Here's a snippet from the crash stack trace

```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   ???                           	000000000000000000 0 + 0
1                                 	0x000000010368e5ed GameArea::OnIdle(wxIdleEvent&) + 2813
2   libwx_baseu-3.0.0.4.0.dylib   	0x000000010481441d wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) + 119
3   libwx_baseu-3.0.0.4.0.dylib   	0x00000001048156c3 wxEvtHandler::TryHereOnly(wxEvent&) + 73
4   libwx_baseu-3.0.0.4.0.dylib   	0x00000001048155f2 wxEvtHandler::ProcessEventLocally(wxEvent&) + 34
5   libwx_baseu-3.0.0.4.0.dylib   	0x0000000104815523 wxEvtHandler::ProcessEvent(wxEvent&) + 85
6   libwx_baseu-3.0.0.4.0.dylib   	0x00000001048157b8 wxEvtHandler::SafelyProcessEvent(wxEvent&) + 12
```

It looks like the Disconnect GDB event handler sets `dbgMain` (and other variables) to NULL and then this section of the  `GameArea::OnIdle` method tries to call it

```C
if (debugger) {
            was_paused = true;
            dbgMain();

            if (!emulating) {
                emulating = true;
                UnloadGame();
            }

            return;
        }
```

The crash is a null pointer exception when trying to call `dbgMain`
