### ISSUE TITLE
[Feature request]: Stream Mode

### ISSUE THREAD

**Issue by lisalavitz** [visualboyadvance-m/visualboyadvance-m#1152]
### Request box

I would love to see a safety mode where things like directory information is hidden from view when enabled. 

### Reason box

Some people's directories have personal information in them. It is not uncommon that phone numbers, initials, email addresses etc are the names given to user folders. Having this information visible can be dangerous to show on screen during things like streams.

### Examples

Upon rom startup, red text currently appears:
"Loaded battery C:\Users\JaneDoe\Desktop\VBA\ROMS\Game.sav"

Propose when feature disabled text remains

Propose when feature enabled text instead reads

"Directory messaages hidden due to stream safety mode enabled. To disable do X"

**Comment by Squall-Leonhart** [comment]
1. The transparency on screen display can be disabled.
2. The user can configure all directories so that they aren't in the user folder at all.

**Comment by ZachBacon** [comment]
Click on options->Video->Disable On-Screen Display
