### ISSUE TITLE
[Feature request]: Please Add Chinese Simplified and Traditional,or More Language

### ISSUE THREAD

**Issue by Satoshi2310** [visualboyadvance-m/visualboyadvance-m#1158]
### Request box

As a Chinese Pokemon fan,I need to use VBA-M to play games on my PC.
But there is English in the program only,it is hard for a people whose English is poor to setting it or,etc.
So,please add Chinese and more language!!! We need it!!!!!!

### Reason box

As a Chinese Pokemon fan,I need to use VBA-M to play games on my PC.
But there is English in the program only,it is hard for a people whose English is poor to setting it or,etc.
So,please add Chinese and more language!!! We need it!!!!!!

### Examples

(Nothing)

**Comment by ZachBacon** [comment]
Properly install the localization files for it and it will be in your language.
