### ISSUE TITLE
[Bug]: partial freeze/softlock with Megaman Battle Network 3 Blue

### ISSUE THREAD

**Issue by tykequickfly** [visualboyadvance-m/visualboyadvance-m#1160]
### Expected behavior?

text completes, which allows for one to press any button to proceed

### Actual behavior?

text doesn't complete as expected, and gets stuck before its completion, which then soft-locks the game.

Essentially the same issue as described here: https://www.reddit.com/r/emulation/comments/11lpd0/help_using_vba_having_a_weird_bug_with_megaman/

[link to the save file for fast loading if applicable?](https://drive.google.com/file/d/1Z0ez510m0IERdIQ3bgpfViB-wtm0V5CQ/view?usp=drive_link)

### Steps to reproduce the problem

1. In this case, it happens right after finishing the Zoo outbreak scenario of the game.
2. Talk to the main characters (Mayl, Dex, and Yai) to progress the game
3. Doing so will trigger an email notification from Megaman
4. And then voila, you encounter the bug that softlocks the game.
5. The music and NPC movement still occurs as normal in the game
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: 2.1.5, also tried the latest nightly build as of 07/22/2023
OS: Windows 10 Pro, Version 10.0.19044 Build 19044
CPU: Intel(R) CORE(TM) i5-5300U CPU @ 2.30GHz, 2295 Mhz, 2 Core(s), 4 Logical Processor(s)
GPU: Intel(R) HD Graphics 5500
RAM: 8 GB DDR3

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by tykequickfly** [comment]
Somehow, spamming a bunch of random buttons very quickly fixed this. I guess this bug is resolved!

**Comment by ZachBacon** [comment]
Also don't be afraid to update vba-m. We have 2.1.6 out now https://vba-m.com/2023/07/visualboyadvance-m-216-released
