### ISSUE TITLE
[Bug]: When trying to start network linking, the emulator crashes

### ISSUE THREAD

**Issue by NODDYSHAURYA** [visualboyadvance-m/visualboyadvance-m#1161]
### Expected behavior?

It should have opened a dialogue box.
![Screenshot (25)](https://github.com/visualboyadvance-m/visualboyadvance-m/assets/140909539/7f9bc95b-b4c2-47b3-b4f2-2bd62cf6afc9)

### Actual behavior?

It was just crashing

### Steps to reproduce the problem

1.Open a game
2.Go to options
3.Go to link
4.Go to start network link

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:
 

### Specifications and Build details

VBA-M: (2.1.4 64-bit version)

 

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
* isn't a valid server.
2.1.4 isn't latest.
