### ISSUE TITLE
Linux: "Could not create main window" error

### ISSUE THREAD

**Issue by Daniel-Khodabakhsh** [visualboyadvance-m/visualboyadvance-m#117]
Having issues running the application. This is my first time trying vba-m out so I'm not sure if this was a recent break, or if my installation procedure or environment is incomplete.

### Expected behavior
Application compiled on Fedora 25 should launch and a window appear.

### Actual behavior
Upon attempting to launch, an error dialogue appears with the following text and the program closes.

`Could not create main window:
04:46:49 PM: Cannot load resources from 'memory:wxvbam.xrs#zip:*.xrc'.
04:46:49 PM: XRC error: XRC resource "MainFrame" (class "wxFrame") not found
04:46:49 PM: Could not create main window`

![vba-m](https://cloud.githubusercontent.com/assets/9839187/25975341/99374db0-3662-11e7-8f68-014ab5477637.png)

### Steps to reproduce the behavior

1. Install 64-bit Fedora 25.
2. Install dependencies via `# dnf install ...`
3. Clone git repository. `$ git clone https://github.com/visualboyadvance-m/visualboyadvance-m.git`
4. cd into the directory. `$ cd visualboyadvance-m`
5. Create the build directory and cd into it. `$ mkdir build` `$ cd build`
6. Run cmake. `$ cmake ..`
7. Run make. `$ make` (also tried `make -j8`)
8. Try to run VBA-M. `$ ./visualboyadvance-m`

### Build details

I'm compiling on 64bit Fedora 25 pulling from a recent commit (fed6f2389ebeb33c803a9ccc173214c327dd06d2) on master.

Attached are the outputs of cmake and make:
[cmake_output.txt](https://github.com/visualboyadvance-m/visualboyadvance-m/files/994640/cmake_output.txt)
[make_output.txt](https://github.com/visualboyadvance-m/visualboyadvance-m/files/994642/make_output.txt)

Once I get home from vacation I'll try the latest changes from today and update this ticket accordingly.
I will also check if I'm using xorg or Wayland.

**Comment by ZachBacon** [comment]
looks like vba-m was built without zip being installed. You need zip as a build dep so that the individual xrc files are compressed and then through our bin2c program is then loaded as a c converted header and loaded in memory.

**Comment by Daniel-Khodabakhsh** [comment]
Thanks for the reply.

Checking the cmake_output.txt, it looks like I do have zip and it's being found:
`-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.8")`

Just in case, I did a dnf list to see if I had zip installed and it appears that I do:

    [dan@localhost build]$ dnf list zip
    Last metadata expiration check: 5 days, 21:55:27 ago on Sat May  6 15:20:47 2017.
    Installed Packages
    zip.x86_64                          3.0-16.fc24                          @fedora
    [dan@localhost build]$ dnf list zlib
    Last metadata expiration check: 5 days, 21:55:39 ago on Sat May  6 15:20:47 2017.
    Installed Packages
    zlib.i686                          1.2.8-10.fc24                         @fedora
    zlib.x86_64                        1.2.8-10.fc24                         @fedora
    [dan@localhost build]$ 

Also tried building with the latest commit, and using a super user, but I'm still having the same issue.

I belive I'm on xorg (x11) via `echo $XDG_SESSION_TYPE`.

One thing I should mention is that cmake does have this line: 
`-- Could NOT find SSP (missing:  SSP_LIBRARY)`

**Comment by ZachBacon** [comment]
No, I said zip, not zlib. They are two different things. One being a library and the other command line interface. And that missing bit is fine. SSP Is a stack smashing protector, we use it in our release builds, helps mitigate potential attacks (not all mind you) like unauthorized code from being executed and attacking your computer.

Anyways if you do have /usr/bin/zip.  I wonder because that shouldn't be causing you issues if you do

**Comment by Daniel-Khodabakhsh** [comment]
I can confirm that I do have `/usr/bin/zip`.

**Comment by rkitover** [comment]
@Daniel-Khodabakhsh it looks like the wx resources are not being compiled into the app correctly.

Do you have the `wxrc` executable installed?

See around line 250 in `src/wx/CMakeLists.txt` if you want to try to debug this.

Also, why did you not use `./installdeps` ?

**Comment by Daniel-Khodabakhsh** [comment]
I can confirm I have `wxrc`

    [dan@localhost build]$ wxrc
    Usage: wxrc [-h] [-v] [-e] [-c] [-p] [-g] [-n <str>] [-o <str>] [--validate] [--validate-only] [--xrc-schema <str>] input file(s)...
      -h, --help          	show help message
      -v, --verbose       	be verbose
      -e, --extra-cpp-code	output C++ header file with XRC derived classes
      -c, --cpp-code      	output C++ source rather than .rsc file
      -p, --python-code   	output wxPython source rather than .rsc file
      -g, --gettext       	output list of translatable strings (to stdout or file if -o used)
      -n, --function=<str>	C++/Python function name (with -c or -p) [InitXmlResource]
      -o, --output=<str>  	output file [resource.xrs/cpp]
      --validate          	check XRC correctness (in addition to other processing)
      --validate-only     	check XRC correctness and do nothing else
      --xrc-schema=<str>  	RELAX NG schema file to validate against (optional)
    The required parameter 'input file(s)' was not specified.

I also looked into the `installdeps` file and ran these commands manually:

    dnf --best --allowerasing install gcc gcc-c++ make cmake git nasm redhat-rpm-config pkgconfig libgcc glibc-devel
    dnf --best --allowerasing install zlib-devel mesa-libGL-devel ffmpeg-devel gettext-devel libpng-devel SDL2-devel SFML-devel openal-soft-devel wxGTK3-devel cairo-devel gtk2-devel gtk3-devel

Running these only installed `nasm` and `redhat-rpm-config`. Tried to clean and rebuild but I'm getting the same error.

The reason I'm not using the `installdeps` script is because usually scripts like these aren't well maintained (you'd see some similar scripts using 'yum' instead of 'dnf' for example).
Looking at this one though, it seems pretty well maintained. I'll try running it but I doubt it will make a difference.

I'll also check that `src/wx/CMakeLists.txt` file out.

**Comment by rkitover** [comment]
@Daniel-Khodabakhsh I'll describe what happens for you:

`wxrc` compiles `src/wx/xrc/*.xrc` into `wxvbam.xrs`
(it will be in `./src/wx/wxvbam.xrs` under `build/`)

`bin2c` translates `wxvbam.xrs` into a C header with a byte array, called `builtin-xrc.h`
(it will be in `./src/wx/builtin-xrc.h` under `build/`)

You can run make with `VERBOSE=1` to have cmake produce more detailed output including what commands it's running, e.g. `make -j8 VERBOSE=1`.

**Comment by RoadrunnerWMC** [comment]
Sorry for the bump, but I managed to solve this issue on Linux Mint 18.3.

Just ensure that the path you're compiling from doesn't contain spaces. Spaces seem to confuse `wxrc`, causing it to only compile a single file from `src/wx/xrc/` into the `xrs` file (whereas it's supposed to compile all of them).

Hope this helps anyone else with the same problem!

**Comment by ZachBacon** [comment]
Closing this and marking it solved then
