### ISSUE TITLE
[Bug]: pokemon glazed frozen

### ISSUE THREAD

**Issue by jonnyd1234** [visualboyadvance-m/visualboyadvance-m#1172]
### Expected behavior?

trying to move pokemon in somebodys pc
![Pokemon Glazed (Unofficial v9 1 0)](https://github.com/visualboyadvance-m/visualboyadvance-m/assets/142660733/4d97b269-fd52-4aa6-9c7c-87364a549b49)

### Actual behavior?

its frozen and cant do anything music still playing in background
![Pokemon Glazed (Unofficial v9 1 0)](https://github.com/visualboyadvance-m/visualboyadvance-m/assets/142660733/5931b183-5ac6-447a-a2a3-f9307dc85d5f)
 

### Steps to reproduce the problem

1.
2.
3.
4.
5.
...
i dont know

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)
[Pokemon Glazed (Unofficial v9.1.0).zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/12385486/Pokemon.Glazed.Unofficial.v9.1.0.zip)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
Please fill out the template in full or face having the issue closed. Also have you even tried reading this? https://github.com/visualboyadvance-m/visualboyadvance-m/issues/324

**Comment by Squall-Leonhart** [comment]
This could happen in 2.1.5, but its fixed in 2.1.6, was related to the SWI's unfortunately being clamped to positive signs only.

**Comment by durandlicciardellojoseantonio-ctrl** [comment]
Bro se bugean las medallas cuando cargas mucho un save estate
