### ISSUE TITLE
[Bug]: Kirby Tilt 'n' Tumble: Savedata gets "deleted" when the emulator is reset (Ctrl+R)

### ISSUE THREAD

**Issue by saulfabregwiivc** [visualboyadvance-m/visualboyadvance-m#1173]
### Expected behavior?

I expected that after saving a game, for then reset the ROM, close/open again the ROM or turn off and later on the emulated GBC hardware, after selecting "GAME START", display the actual saved files in the FILE SELECT screen.

### Actual behavior?

Kirby Tilt 'n' Tumble does not save at all.

I see all files on FILE SELECT screen that are empty (NEW), even when the progress was supposedly saved.

Any fix??? Thanks ;)

### Steps to reproduce the problem

1. Load the game ROM (unpatched, the original one.)
2. Play for a while until you see a "SAVING..." screen, then let it save.
3. Reset the game (by any way), and choose "GAME START". The FILE SELECT screen shows there's no saved data.

### Error messages?

None

### What game were you playing

![image](https://github.com/visualboyadvance-m/visualboyadvance-m/assets/66485640/3fb3f473-86e0-479d-8348-1a701b48e6df)

Title: KIRBY TNT (Kirby Tilt 'n' Tumble)
GB, GBC or GBA: GBC
ROM CODE: CGB-KTNE-USA
BIOS Used?: none
SAVE TYPE: EEPROM
Clean, Intro'd or Hacked?: Clean, unpatched (from No-Intro)

### What settings are you using?

Video driver (simple, opengl): OpenGL
Sound driver (directsound, xaudio, openal, SDL): SDL
Scale Filter Used?: none

### Specifications and Build details

VBA-M: VBA-M for Windows x64 bits, latest VBA-M 2.1.6-14a4b6f8 (until git https://github.com/visualboyadvance-m/visualboyadvance-m/commit/14a4b6f8)
OS: Windows 10 x64 v22H2 - Build: 19045.3324
CPU: Intel Core i7-5500U @ 2.40 GHz 2.40 GHz
GPU: Intel HD Graphics 5500
RAM: 12,0 GB

**DISCLAIMER: Every platform i tried to save data on Kirby TnT, it happens the same issue.
Tested on Windows, Android (libretro), Wii (Libretro), Wii U (Libretro).**

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Steelskin** [comment]
I was certain I had tested my changes with Kirby. I'll take a look this weekend.

**Comment by saulfabregwiivc** [comment]
Hey there, i dont want to disturb you but... how's the progress in this?

**Comment by Squall-Leonhart** [comment]
I have a working fix, but i'm not sure its in lines with how Steelo wants to do it.

**Comment by Steelskin** [comment]
Sorry for the delay. I'll take a look tomorrow.

**Comment by saulfabregwiivc** [comment]
> I have a working fix, but i'm not sure its in lines with how Steelo wants to do it.
> 
> [visualboyadvance-m.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/12446871/visualboyadvance-m.zip)

Tested this build.
And...
Now after saving, if I close the emulator and open it again for then open the game file again, the savefile and progress are loaded as it should.
But there's still the problem that when i reset usign the "Reset" button (Ctrl+R), the savedata gets deleted (or it just doesn't read the savedata again) by any reason.
Any clues why when I reset (Ctrl+R) the game it doesn't re-read the savedata again?

**Comment by Squall-Leonhart** [comment]
huh, its actually writing out a blank file in the process.

**Comment by Squall-Leonhart** [comment]
ok, thats a totally seperate issue and seems to go back a long while, I guess somewhere in the reset emulation code, mbc7 initialization is missing.

**Comment by saulfabregwiivc** [comment]
> ok, thats a totally seperate issue and seems to go back a long while, I guess somewhere in the reset emulation code, mbc7 initialization is missing.

I see. Instead of opening a new issue, i changed the name of this issue.
But is there any workaround for stop the Reset command to "delete" the savegame?

**Comment by saulfabregwiivc** [comment]
I checked a bit the gbReset code...
and it has for almost every savedata to not get corrupted except MBC7 (sadge because sometimes the game can be buggy and it needs to reset but because of this issue MBC7 savedata is not loaded)...

So im asking here: any fix for stop gbReset to corrupt MBC7 saves?

**Comment by Steelskin** [comment]
The issue was the unlike other mappers, we handled the MBC7 EEPROM at `gbMemory[0xa000]`. For every other mapper with RAM or EEPROM, the data goes into `gbRam`. `gbMemory` gets reset in `gbReset()`, resulting in the data being cleared.

Saving the EEPROM data to `gbRam` solves the issue.

**Comment by saulfabregwiivc** [comment]
Tested with a compiled build of VBA-M for Libretro on the Nintendo Wii - yep, that fixed the problem!

I'm positive that will also fix it in the Windows version of VBA-M. (Any nightly with that commit for Windows please?)

**Comment by rkitover** [comment]
I rebuilt the nightlies just now.
