### ISSUE TITLE
[Bug]: DOOM (Ported By DOOMHack) Does not save

### ISSUE THREAD

**Issue by Emendo12** [visualboyadvance-m/visualboyadvance-m#1177]
### Expected behavior?

Save game.

### Actual behavior?

Not save game.

### Steps to reproduce the problem

1. Build the project via DOOMHack's project page for GBA DOOM
2. Launch the game
3. Save.
4. Try load.
5. See that there are no saves to load.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title: GBA DOOM by DOOMHack
GB, GBC or GBA: GBA
ROM CODE: N/A
BIOS Used?: (Share crc hash) none
SAVE TYPE: (Attach Battery or Savestate here) Unknown
Clean, Intro'd or Hacked?:(Attach Patch here) Clean Port

I will attach the save file generated on real hardware as well as a savestate from VBA.
[DOOM GBA Saves (Homebrew Port).zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/12516790/DOOM.GBA.Saves.Homebrew.Port.zip)

### What settings are you using?

Video driver (simple, opengl): opengl
Sound driver (directsound, xaudio, openal, SDL): realtek
Scale Filter Used?: none

### Specifications and Build details

VBA-M: 2.1.4 64bit
OS: Win10 19045.3324
If using Linux, specify if using xorg or Wayland:
CPU: Ryzen
GPU: GTX 970
RAM: 32GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
Try again using the latest version. Which is 2.1.6

**Comment by Squall-Leonhart** [comment]
This is the hacks fault, it isn't using a header that we  can pull save type from.

**Comment by Emendo12** [comment]
> Try again using the latest version. Which is 2.1.6

Same result, however I changed the save settings to be SRAM 64k and got it to save.

**Comment by Emendo12** [comment]
> This is the hacks fault, it isn't using a header that we can pull save type from.
> 
> Here is a patch for a build i found. [GBADoom.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/12520232/GBADoom.zip)

Any means for me to fix my ROMs on my own? I think I know the save-type now so I would like to fix the ROMs to have their save-types detectable.

**Comment by Steelskin** [comment]
I created a PR for this here: https://github.com/doomhack/GBADoom/pull/45
Closing this bug since it is now tracked in https://github.com/doomhack/GBADoom/issues/44
