### ISSUE TITLE
[Bug]: Snap package for Linux missing the joystick plug.

### ISSUE THREAD

**Issue by sappergr** [visualboyadvance-m/visualboyadvance-m#1182]
### Expected behavior?

Should be able to use gamepads/etc

### Actual behavior?

Apart from keyboard No other input methods work.

### Steps to reproduce the problem

1. Try to configure a gamepad/joystick/etc

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: 2.1.7
OS:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
Issue is known. And a fix has been in the works including upgrading the core snap runtime.
