### ISSUE TITLE
Each time close and reopen, the window will resize weirdly

### ISSUE THREAD

**Issue by Yave-Yu** [visualboyadvance-m/visualboyadvance-m#1186]
### Expected behavior?

Keep my scale size setting, no black edge like this:
![Scr20231005202337](https://github.com/visualboyadvance-m/visualboyadvance-m/assets/54294476/d745e94d-47a5-4634-9aca-8a6a852d27f6)

### Actual behavior?

Each time close and reopen, the window will resize weirdly, leave top and bottom black edge. Well, if not enable retain aspect radio, it will stretch each pixel.
![Scr20231005202409](https://github.com/visualboyadvance-m/visualboyadvance-m/assets/54294476/09282637-1a3a-4d58-8b33-652c526d7f56)

### Steps to reproduce the problem

1. Open VBA-M and run any game.
2. Close VBA-M.
3. Reopen VBA-M and run any game.

### What settings are you using?

OpenGL, no filter, any scaled size.

### Specifications and Build details

VBA-M: 2.1.7 stable 64-bit
OS: Windows 10 1809
150% DPI

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by rkitover** [comment]
This is fixed in the nightly.
