### ISSUE TITLE
Gamepad Keymappings cannot be set in the settings

### ISSUE THREAD

**Issue by Erim24** [visualboyadvance-m/visualboyadvance-m#119]
### Expected behavior
That the buttons of the gamepad are mapped correctly it they are set through the userinterface.

### Actual behavior
When I try to set the buttons in the settings, it uses the localized names of the buttons (e.g. Joy1-Taste1). But with that values it does not work and at the next start of the emulator it reports invalid values for that keys...
If I delete the config file it works after running vba-m until it is restarted.
If I enter the english version of that keys (Joy1-button1) it works until I change anything in the settings.

### Steps to reproduce the behavior
try to assign the keys.

### ROM details

Which games are affected by the issue (please state if GBA or GB game):

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

### Option details

Video driver (simple, opengl or cairo):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
manjaro (arch derivate)

If using Linux, specify if using xorg or Wayland:
Wayland

Version of code (pre-built binary version, or commit ref, or just "master"):
wx-version of vba-m
1eb768578bc0c4fa17396f573a4b37a652f12acd
(present in the repositories)

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
sdl2-jstest works fine...

If relevant, the joystick you are using and the drivers you are using for it:
Logitech Rumblepad F510
Default driver of manjaro

**Comment by ZachBacon** [comment]
This has been fixed in later commits as of https://github.com/visualboyadvance-m/visualboyadvance-m/commit/6ecab805e00e99c37bd23c425835ca35507cb593

**Comment by Erim24** [comment]
I just built the master branch and there the I am experiencing the same issue...

Also the commit you specified does not seem to be related to the issue I reported.
For me when I try to set up the key bindings of my gamepad, I go to the Joypad configuration and I can enter one of the fields, press the button and if I click on "OK" the dialog closes. But when I open it again all fields are empty..

**Comment by Erim24** [comment]
I think it is related to issue #66

**Comment by rkitover** [comment]
@Erim24 This is actually in #110, I'll try to fix this soon.

**Comment by Erim24** [comment]
Weird... I didn't see that issue. Sorry for opening a duplicate.
And thank you to take care of it!

**Comment by josehfurtado** [comment]
Still not working. Setting joystick in options/input menu, joystick don't respond. Re opening menu can see everything is empty. Looks like applications don't set inputs.
