### ISSUE TITLE
error: file ": unexpected character

### ISSUE THREAD

**Issue by GBAJoe** [visualboyadvance-m/visualboyadvance-m#1191]
### Expected behavior?

Everytime I open Emulator. I get error
": unexpected character
![error](https://github.com/visualboyadvance-m/visualboyadvance-m/assets/148111461/ddf70b0b-75ce-4bf2-8462-df90e3884d1c)
Emulator continues to run with no problems after clicking ok.
Tried factory reset to no avail.

### Actual behavior?

Every time, emulator starts. it gets a error
": unexpected character

### Steps to reproduce the problem

Not really sure.
Initially no problems 
Only until I was fiddling with the SAVE TYPE setting to get a homebrew 1942 to run.

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

Running Win 10 x64
2.1.5 reports error
2.1.7 also error
I remember I had this error bfore on Win 7 x32.
Same issue, after configuring SRAM type for a homebrew game 1942

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
remove the blank entry from  the vba-over file.

**Comment by Squall-Leonhart** [comment]
this is caused by editing the rom settings of a game that has no proper rom code in its header.

**Comment by GBAJoe** [comment]
Thanks, 
Initially, I had problem finding the vba.ini.
But after deleting the vba.ini files. Everything seems to be ok.
