### ISSUE TITLE
[Bug]: Input settings saved but not loaded correctly when using Joy1-Hat (Win64)

### ISSUE THREAD

**Issue by PhraKhanong** [visualboyadvance-m/visualboyadvance-m#1192]
### Expected behavior?

Expected input settings to be correctly saved to the ini file and then loaded when re-launching VBA.

### Actual behavior?

When changing the input settings using a single-joystick controller that registers as a POV hat, VBA correctly recognizes the movements as Joy1-Hat0N, Joy1-Hat0S, Joy1-Hat0E, Joy1-Hat0W, correctly saves these settings in the ini file, and correctly uses them when playing games. However, when re-starting VBA, all of the hat directions in the ini file are ignored and are changed to Joy1-Hat0N. All other input settings are read correctly from the ini file.

### Steps to reproduce the problem

1. Change any directional input setting to a POV Hat direction other than Joy1-Hat0N
2. Exit the emulator (can confirm that the settings are correctly saved to the ini file)
3. Restart the emulator (the emulator sets all Hat settings to Joy1-Hat0N)
4.
5.
...

### Error messages?

N/A

### What game were you playing

Applies to all games

### What settings are you using?

Default

### Specifications and Build details

Win64 2.1.6

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by rkitover** [comment]
Which gamepad out of curiosity, on my xbox controller the d-pad is mapped to discrete buttons by current versions of SDL2.

I am looking into this regardless.

**Comment by PhraKhanong** [comment]
It's a weird one -- Atgames Gamer Mini arcade panel. When connected to USB
it's recognized by Windows as "2 axis 24 button gamepad with hat switch"
and joystick movements are sent as hat directions rather than discrete
buttons. I think it's recognized differently when connected with bluetooth,
but I haven't tried that. For the time being, I'm using VBA with JoyToKey
and it works fine, but it would be nice to have native support working
(even for obscure controllers).

**Comment by rkitover** [comment]
Please try the nightly, I believe this is fixed.

**Comment by PhraKhanong** [comment]
Works like a charm! Thanks so much!
