### ISSUE TITLE
GBC games crashing the emulator upon clicking the rom[Bug]: 

### ISSUE THREAD

**Issue by Lostoneonesix** [visualboyadvance-m/visualboyadvance-m#1194]
### Expected behavior?

I expect the emulator to run the GBC roms.

### Actual behavior?

Emulator crashes upon clicking the rom to run, no matter how I try to run it.

### Steps to reproduce the problem

1.Open the program
2.select file from the menu items
3.choose a GBC rom
4.emulator crashes upon selecting the open option or double clicking/ pressing enter to open the rom
5.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).
there was no error message

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)
Title: pokemon crystal
GBC
BIOS used was GBA
Clean rom

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:
VBA-M 2.0.1 
8 GB of ram
Nvidia GBU and Intel CPU

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Felipefpl** [comment]
Are you really using vba-m 2.0.1.....?

**Comment by Lostoneonesix** [comment]
Yes I am

**Comment by ZachBacon** [comment]
> Yes I am

So you're asking for support on an unsupported version. Update to 2.1.7 and try again.

**Comment by Lostoneonesix** [comment]
It kept saying it was up to date. Maybe I'm looking in the wrong spot then. Thank you

**Comment by ZachBacon** [comment]
> It kept saying it was up to date. Maybe I'm looking in the wrong spot then. Thank you 

GitHub has a release tab, and you can also check https://vba-m.com for information for current releases.

**Comment by Squall-Leonhart** [comment]
Closing with prejudice.
