### ISSUE TITLE
[Bug]: game crashes when joining LAN

### ISSUE THREAD

**Issue by danivanspelden** [visualboyadvance-m/visualboyadvance-m#1195]
### Expected behavior?

it's supposed to open the multiplayer game, and then play with 2 players.

### Actual behavior?

my game turns black upon joining, host's game doesn't continue the game until he cancels the LAN. 

### Steps to reproduce the problem

1.join the LAN game of a friend.
2.
3.
4.
5.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Template wasn't respected.
