### ISSUE TITLE
[Bug]: In Fire Red Rocket addition anytime you go to the key items menu it freezes and you have to restart the program from your last save 

### ISSUE THREAD

**Issue by Flamingcobra** [visualboyadvance-m/visualboyadvance-m#1199]
### Expected behavior?

It was supposed to keep scrolling through options of items

### Actual behavior?

It froze to the point of crashing making me lose 20 minutes of progress

### Steps to reproduce the problem

1. get fire red rocket edition
2. get to the point where you can have independent actions
3. open the bag
4. got to key items.
5.
6.
7.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title: Fire Red Rocket Edition
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Steelskin** [comment]
Could you upload a save game just before the crash with instructions on how to reproduce it, please? Do not upload the ROM itself, just the save file.

Otherwise, have you tried this rom hack on a real GBA?

**Comment by Flamingcobra** [comment]
Don’t have a GBA that’s why


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
