### ISSUE TITLE
[Bug]: `str pc, [...]` not emulated correctly

### ISSUE THREAD

**Issue by Aikku93** [visualboyadvance-m/visualboyadvance-m#1200]
### Expected behavior?

`pc` is stored to Rm+Rn/#IMM, where `pc` is equal to the address of the instruction plus 12 bytes.

For example: `str pc, [sp, #-4]! ; nop ; nop ; add r0, r1, r2` should store the address of the `add` instruction.

### Actual behavior?

`pc` is stored to Rm+Rn/#IMM, where `pc` is equal to the address of the instruction plus 8 bytes (instead of 12 bytes).

### Steps to reproduce the problem

Execute any `str` instruction with `pc` as Rd.

### Error messages?

No program crashes or anything, just the application doing wrong things due to an incorrect value being stored.

### What game were you playing

My own program (I don't think anyone has ever used `str pc, [...]` before, so I'm not surprised this issue was missed).

### What settings are you using?

Default settings (not really applicable; this is a CPU emulation problem, not the application itself).

### Specifications and Build details

VBA-M: 2.1.7, but also present on 1.8.0 at least

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Steelskin** [comment]
Thanks for the report!

Do you have a test ROM or source for it that I could compile myself? I'll take a look when I have some time.

**Comment by Aikku93** [comment]
[Sure](https://www.mediafire.com/file/wv4pmkdm2catz9a) (sorry for the ad-filled MediaFire link, I don't really know what people prefer to use at the moment).

I wrote a simple test that displays a green screen if the instruction succeeds, or a red screen if it fails. mGBA and no$gba both succeed and display a green screen, VBA fails and displays a red screen.

**Comment by Steelskin** [comment]
Thanks, that's useful, I'm taking a look now.
