### ISSUE TITLE
wonky sound after toggling sound off/on in pokemon emerald  [Bug]: [sound]:

### ISSUE THREAD

**Issue by Lawrence-Of-Canadia** [visualboyadvance-m/visualboyadvance-m#1201]
### Expected behavior?

Expected to hear normal audio while playing pokemon emerald 

### Actual behavior?

many sound elements are missing, for example a great deal of the percussion of the music, the chime when you advance through menus. 

### Steps to reproduce the problem

1. Be playing pokemon emerald 
2. press options > audio > toggle sound to turn sound off
3. press options > audio > toggle sound to turn sound back on
4. notice how much of the audio is just not there, specifically a lack of a chime sound when in menus
5. 
...

### What game were you playing

![Screenshot 2023-11-13 233659](https://github.com/visualboyadvance-m/visualboyadvance-m/assets/101752381/05040784-9719-4b16-8c46-15cf1ef1b007)
Title: Pokemon - Emerald Version (U)
GB, GBC or GBA: GBA
ROM CODE: couldnt find 
BIOS Used?: (couldnt find)
SAVE TYPE: (couldnt attach .sgm file)
Clean, Intro'd or Hacked?:(i dont know )

### What settings are you using?

Video driver (simple, opengl): opengl
Sound driver (directsound, xaudio, openal, SDL): SDL
Scale Filter Used?: could not find 

### Specifications and Build details

VBA-M: 2.1.6, 64 bit
OS: (include version and OS build number using WinVer if on Windows): windows 11 version 22h2 os build 22621.2428
If using Linux, specify if using xorg or Wayland:
CPU: AMD athlon silver 3050u with radeon graphics 
GPU: AMD radeon graphics processor
RAM: 8gb

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
I would recommend testing with 2.1.7, we released that in September. https://vba-m.com/2023/09/visualboyadvance-m-217-released worst case scenario, try a nightly at https://nightly.vba-m.com/ and see if the problem persists. If it does, we'll mark this as solved, if not, we will investigate further.

**Comment by Lawrence-Of-Canadia** [comment]
Thanks for the quick reply - i tried 2.1.7 and the nightly 64 bit released on nov 11 yet the problem is persisting. 

The issue is not present in an older save state i have from a few weeks ago, it only present in the save ive been using exclusively for a few weeks in which i toggled the sound off/on. It happened basically right away, on route 110 if that helps. its too bad because id lose so much progress if i went back to the older save.

**Comment by Squall-Leonhart** [comment]
This is a duplicate, noise channel and dma don't come back to full volume after toggling between sound backends.

**Comment by Squall-Leonhart** [comment]
https://github.com/visualboyadvance-m/visualboyadvance-m/issues/143

**Comment by Squall-Leonhart** [comment]
also https://github.com/visualboyadvance-m/visualboyadvance-m/issues/342
