### ISSUE TITLE
Bug: Was playing some Rocket Edition and my game froze. I haven't made a save state or save at all in hours.

### ISSUE THREAD

**Issue by PhoenixFire1223** [visualboyadvance-m/visualboyadvance-m#1202]
### Expected behavior?

I expected to be able to move and continue the journey. 

### Actual behavior?

I talked to the dude at Nugget Cave (the one who sells you a Flashlight for $1000) and I went to another tab to get codes for the infinite money cheat, and when I came back and picked up the controller, I couldn't move, talk to the dude or do anything.
<img width="1280" alt="Screenshot 2023-11-17 233807" src="https://github.com/visualboyadvance-m/visualboyadvance-m/assets/151351763/f667d97f-3778-41fc-b659-64ae87a28827">

### Steps to reproduce the problem

1. I don't know if it's possible to reproduce, but what I did was: Talk to the guy
2. Decline his offer
3. Open cheats
4. Add both master codes for the infinite money cheat
5. And that was it
6. Enjoy listening to the route music for eternity.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title: Pokemon: FireRed Rocket Edition
GB, GBC or GBA: GBA
ROM CODE: BPRE
BIOS Used?: I don't know what this is but i ticked skip BIOS
SAVE TYPE: Automatic
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver Open GL
Sound driver SDL
Scale Filter Used?:
I'm not sure, but I used Simple x3 for pixel filter

### Specifications and Build details

VBA-M: M 2.1.7 64-bit
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:  3.30 GHz
GPU: ADM Radeon 
RAM: 16 GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
This mod was developed around older versions of the emulator rather than hardware, tests poorly on hardware and other emulators and making fixes for romhacks that require faulty behavior is not on our list of things to do.
