### ISSUE TITLE
[Bug]: Automatic SGB Border option doesn't work

### ISSUE THREAD

**Issue by ReyVGM** [visualboyadvance-m/visualboyadvance-m#1207]
### Expected behavior?

When loading a Super Game Boy game, the game should boot and show the border.

### Actual behavior?

When the game loads, the border doesn't show. 

In order to see the border, you have to set the display border to "always", which means that when playing a regular GB game, an empty border will always show too.

### Steps to reproduce the problem

1. Go to the GB options. 
2. Set emulated systems to SGB
3. Set display border to Automatic
4. reboot the emulator

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

Title: Game Boy Donkey Kong
GB, GBC or GBA: SGB

### What settings are you using?

Video driver (simple, opengl): default
Sound driver (directsound, xaudio, openal, SDL): default
Scale Filter Used?: none

### Specifications and Build details

VBA-M: visualboyadvance-m-Win-x86_64 [v2.1.7]
OS: (include version and OS build number using WinVer if on Windows): Windows 10 Pro 22H2
CPU: Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz   3.60 GHz
GPU: none
RAM: 12GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Regressed between 2.5 and 2.6, i'll assign @steelskin because I believe this is another sanitization fallout.

**Comment by Squall-Leonhart** [comment]
Thanks for this report, brought to light that our emulated system overrides are not working at all on top of the auto borders not working.
