### ISSUE TITLE
[Bug]: Black screen and save reset

### ISSUE THREAD

**Issue by Idkwhatonamemyself1** [visualboyadvance-m/visualboyadvance-m#1209]
### Expected behavior?

My game was supposed to be at the 13:56 mark and I should have had all 7 badges and going to victory road (Dbz team training) 

### Actual behavior?

I opened the app it played the flashback cutscenes as usual I fly to ginger town; I go into the warden's house giving him the golden teeth. around here I realized future Gohan was on my team even though I replaced him, so I just ignored it, and I gave HM04 to garlic jr I press the yes button and boom black screen I restarted my computer the cutscenes played and after the cutscenes instead of spawning me in west city it instantly goes to the black screen.

### Steps to reproduce the problem

1.I open game
2.Skipped cutscenes
3.Fly toward ginger town
4. give man his teeth
5.Give HM04 I got from man to Garlic and black screen

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA: 
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)
Dbz team training

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
Please fill out the template in full. What's the version you're using, what's your operating system etc. Those details help

**Comment by Squall-Leonhart** [comment]
Another crappy fire red port that doesn't include the media type in its header.

**Comment by Laki5522** [comment]
I have the exact same Issue

**Comment by Squall-Leonhart** [comment]
This is a bug in the romhack and we cannot fix it.

**Comment by sillybilly28** [comment]
Is there any work being done to fix this? I just got the same issue. If not, is there any way to rewind my save?
