### ISSUE TITLE
volume slider in windows not appearing right

### ISSUE THREAD

**Issue by NinFanBoyFTW** [visualboyadvance-m/visualboyadvance-m#121]
### Expected behavior
in the windows volume slider i should see 1 line with vba and the volume slider
### Steps to reproduce the behavior
![untitled-1](https://user-images.githubusercontent.com/21354941/27121282-a3b7bf92-50b4-11e7-9b90-2675654fc56d.png)

**Comment by rkitover** [comment]
Fixed in master in 3d792457.

**Comment by rkitover** [comment]
Fixed in the `2.0.1` release.
