### ISSUE TITLE
[Bug]: WAV audio-only recording is broken

### ISSUE THREAD

**Issue by Aikku93** [visualboyadvance-m/visualboyadvance-m#1214]
### Expected behavior?

On using `File->Record->Start sound recording...` and selecting the WAV format, a WAV file is created to capture the audio.

### Actual behavior?

Everything works as expected, but the RIFF and data chunk headers are broken (the sizes are set to FFFFFFFFh). I believe this is caused by [this line](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/f915ec5972eb517f0972570bd1f017b01083c1a4/src/common/ffmpeg.cpp#L417), which only calls `av_write_trailer()` when _not_ recording in audio-only mode.

Inspecting the ffmpeg source, the call to `av_write_trailer()` should invoke `wav_write_trailer()` in libavformat/wavenc.c, which then writes the correct chunk sizes, as they'd been set to FFFFFFFFh when `avformat_write_header()` invoked `wav_write_header()`. So in other words: the call to `av_write_trailer()` should _always_ be performed, not only when doing a video recording.

### Steps to reproduce the problem

1. Start audio recording with WAV output.
2. Stop recording.
3. Inspect the resulting file.

### What settings are you using?

Default settings, but N/A; this is an ffmpeg interfacing issue.

### Specifications and Build details

VBA-M 2.1.8 (64-bit). Should be present in all current builds, though. Not sure how far back this issue goes, since it seems to be related to ffmpeg's API changing through the years.

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by rkitover** [comment]
Any chance you could give us a PR for this, since you know exactly what to do?

**Comment by Aikku93** [comment]
I wanted to, but was having way too much trouble getting the project to compile for testing. So because I can't test to see if that is the root cause, I just opened an issue instead of a PR to comment out that line.

**Comment by rkitover** [comment]
What problems were you having building the project? On what OS/distribution? If there are problems building the project I'd like to know, because I'm primarily responsible for that.

**Comment by Aikku93** [comment]
I tried again just now, and the main issue seems to be CMake-related: I cloned the repo, opened in VS2022 v17.8.3 (running under 64-bit Windows 7) using CMakeLists.txt, and then waited for the CMake cache to be generated. All the dependencies are downloaded, but then installation fails at different points: the first time it complained that NASM couldn't be found for installation, the next time it was complaining the `cl` wasn't a valid command line. There is also a lot of warnings about vcpkg not being found or something - I don't remember exactly, because the CMake output is cleared on every retry, and I gave up after it started re-downloading all the dependencies for the third time.

Honestly, this is probably just an issue on my end from using an outdated operating system, so unless other people are having weirdly similar problems on a newer system, I wouldn't worry about it too much.

**Comment by rkitover** [comment]
Can you try with MSYS2? It's pretty straightforward, just run `./installdeps`.

I will try running the build in a Windows 7 VM, and perhaps you can give me some assistance in debugging your build issues if I am not able to reproduce them.

**Comment by Aikku93** [comment]
I opened a MinGW shell, and ran `./installdeps`; all dependencies were installed successfully. But attempting to build fails:
```
Aikku@AIKKU-PC00 MINGW64 /c/users/aikku/documents/github/visualboyadvance-m
# mkdir build && cd build

Aikku@AIKKU-PC00 MINGW64 /c/users/aikku/documents/github/visualboyadvance-m/build
# cmake .. -DCMAKE_BUILD_TYPE=Release -G Ninja

Aikku@AIKKU-PC00 MINGW64 /c/users/aikku/documents/github/visualboyadvance-m/build
# ninja
ninja: error: loading 'build.ninja': The system cannot find the file specified.
```

The `cmake` command exits abnormally quickly (just a fraction of a second). Removing `-DCMAKE_BUILD_TYPE=Release` didn't make a difference, either, and the same issue happens inside a Clang shell.

> perhaps you can give me some assistance in debugging your build issues if I am not able to reproduce them.

Sure, I'm happy to do that. I'm probably just missing something obvious, to be honest - this is the first project I've tried to build that uses CMake.

**Comment by rkitover** [comment]
It's strange that MSYS2 cmake is exiting abnormally.

Let's try this, open the x64 native developer command prompt for Visual Studio, or the x64 powershell native developer command prompt.

Navigate to the source directory, and execute the following:

```powershell
mkdir build-msvc64
cd build-msvc64
cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_BUILD_TYPE=Release -G Ninja
ninja
```
, this will give you the cmake output without clearing the screen so we can see what the errors are.

**Comment by Aikku93** [comment]
Alright, I ran cmake inside the developer Powershell. Using cmake inside the build-msvc64 folder failed (`CMake Error: The source directory "/c/Users/Aikku/Documents/GitHub/visualboyadvance-m/build-msvc64" does not appear to contain CMakeLists.txt.`), so I moved up one directory to the root folder and ran cmake again. [I've attached the console output from doing this](https://github.com/visualboyadvance-m/visualboyadvance-m/files/14006504/CMakeErrors.txt).

**Comment by ZachBacon** [comment]
You didn't run cmake properly then. From the build folder you then need to run cmake ../ 

That tells cmake to look for the cmakelists file one directory above

**Comment by Aikku93** [comment]
Alright, I ran `cmake ../ -DVCPKG_TARGET_TRIPLET=[...]`, and then ran `cmake -DVCPKG_TARGET_TRIPLET=[...]`, both from inside the build-msvc64 directory. The warning about `No source or binary directory provided.  Both will be assumed to be [...]` doesn't display anymore, but now it stops earlier:

```
[...]
-- Downloading https://nightly.vba-m.com/vcpkg/x64-windows-static/zlib_1.3_x64-w
indows-static.zip ...
-- done.
Import-Module: The specified module '/c/Users/Aikku/Documents/GitHub/visualboyad
vance-m/vcpkg-binpkg/vcpkg-binpkg.psm1' was not loaded because no valid module f
ile was found in any module directory.
vcpkg-instpkg: The term 'vcpkg-instpkg' is not recognized as a name of a cmdlet,
 function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
Could NOT find SFML (missing:  SFML_NETWORK_LIBRARY SFML_SYSTEM_LIBRARY)
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230
(message):
  Could NOT find OpenGL (missing: OPENGL_opengl_LIBRARY OPENGL_glx_LIBRARY
  OPENGL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILU
RE_MESSAGE)
  /usr/share/cmake/Modules/FindOpenGL.cmake:545 (FIND_PACKAGE_HANDLE_STANDARD_AR
GS)
  C:/Program Files/Microsoft Visual Studio/2022/Community/VC/vcpkg/scripts/build
systems/vcpkg.cmake:859 (_find_package)
  CMakeLists.txt:429 (find_package)
```

**Comment by rkitover** [comment]
It's failing to fetch my vcpkg related powershell module using FetchContent in cmake, what version of Visual Studio do you have and what does `cmake --version` say?

**Comment by Aikku93** [comment]
I'm running Visual Studio 2022 Community Edition, and cmake version is 3.28.1 (as tested inside Powershell, which is 4.0; I've got version 7.1.4 installed, but I don't think VS is interfacing with it).

**Comment by rkitover** [comment]
The cmake code in question is [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/cmake/Set-Toolchain-vcpkg.cmake#L269), for some reason it's not activating in your environment.

I'm sorry I gave you the wrong cmake command, I'm in a difficult life situation here, anyway, let's try this:

delete your clone and make a new clone, then:

```powershell
sl <your-clone>
ni -it dir build-msvc64
sl build-msvc64
cmake .. -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_BUILD_TYPE=Release -G Ninja
```
, at this point it will fail to fetch the powershell module, so put it in manually. First from the build directory:

```powershell
ni -it dir vcpkg-binpkg
```
, then download [this](https://raw.githubusercontent.com/rkitover/vcpkg-binpkg-prototype/master/vcpkg-binpkg.psm1) file and place it in the `vcpkg-binpkg` directory as `vcpkg-binpkg.psm1`. Then, run cmake again from the build directory:

```powershell
cmake .. -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_BUILD_TYPE=Release -G Ninja
```
, hopefully this time cmake will run through to completion. If it does, run `ninja` to build. If it does not, tell me what the errors are and we'll go from there.

**Comment by Aikku93** [comment]
Okay, I think there's something seriously wrong with my computer rather than the project.

I did that, and it's now getting stuck a in loop displaying:
```
Import-Module: The specified module '/c/Users/Aikku/Documents/GitHub/visualboyad
vance-m/build-msvc64/vcpkg-binpkg/vcpkg-binpkg.psm1' was not loaded because no v
alid module file was found in any module directory.
vcpkg-list: The term 'vcpkg-list' is not recognized as a name of a cmdlet, funct
ion, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path
is correct and try again.
```
over and over again.

I've confirmed that the file exists at that location, which is really getting me confused as to why it can't find it.

**Comment by rkitover** [comment]
Maybe the `powershell.exe` in Windows 7 is too old, so perhaps it was that and not the `FetchContent` that was failing, that makes more sense.

On [this](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/cmake/Set-Toolchain-vcpkg.cmake#L281) line, change the command to:

```cmake
set(powershell pwsh)
```
, assuming you have a recent version of PowerShell installed, and try again.

**Comment by Aikku93** [comment]
That didn't seem to help, unfortunately. I tried opening the Environment->Terminal dialog in VS to see if I can get Powershell 7 to run instead of the default, but that caused a bunch of errors, so I'm currently running that down, since it may be related.

In the meantime, I'm attempting to build with the VS2019 developer Powershell, since VS2022 is not officially on Windows 7, so it may be related to that, too. I'll update with the results when I'm done figuring that out.

**Comment by rkitover** [comment]
Ok, from the build directory, once all the packages are downloaded by a `cmake` run, try running this from `pwsh`:

```powershell
import-module ./vcpkg-binpkg/vcpkg-binpkg.psm1
vcpkg-instpkg ./vcpkg-binary-packages
```
, then try invoking `cmake` again.

**Comment by Aikku93** [comment]
I deleted the privateregistry.bin file from AppData\Microsoft\VisualStudio\17.0 to forcefully "reset" the environment, then after getting some errors and re-starting VS2022, I opened the project again using Open->Folder..., and this time it all went well and the program compiled.

I have no idea what's happening anymore, but at least I can get it to compile now. Thanks for pushing me to keep trying instead of just giving up like I had.

---

As for your above suggestion, I had to use `C:\Users\Aikku\Documents\GitHub\vcpkg` or it formed a bad path (`C:\Users\Aikku\Documents\GitHub\visualboyadvance-m\build-msvc64\Users\Aikku\Documents\GitHub\vcpkg`), but that still resulted in an error:
```
Get-ChildItem: C:\Users\Aikku\Documents\GitHub\visualboyadvance-m\build-msvc64\v
cpkg-binpkg\vcpkg-binpkg.psm1:290
Line |
 290 |              else { gci $zips -filter '*.zip' | % fullname | order_zip .
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find path
     | 'C:\Users\Aikku\Documents\GitHub\visualboyadvance-m\build-msvc64\vcpkg-bi
nary-packages' because it does not exist.
InstallVcpkgPkgZip: No packages to install
```

And this time there really isn't anything called "vcpkg-binary-packages" in the folder.

---

Overall, I guess the moral of the story is: If things are acting /really/ weird for no apparent reason, clear the cache.

**Comment by rkitover** [comment]
I have no idea what that is, but I'm glad you got it working!
