### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Phazoning** [visualboyadvance-m/visualboyadvance-m#1218]
### Expected behavior?

Emulator instance of game A recognizes emulator instance game B on the same computer and connects for link trade

### Actual behavior?

Neither emulator instances recognize one another, thus preventing link trade

### Steps to reproduce the problem

With fresh emulator from nightly releases (latest win x86)
1. Start first instance of the emulator load base rom w/ .sav (game A). Set link options to "Local mode", "Type -> Gameboy", "Configuration > Timeout -> 20000ms"
2. Start second instance of the emulator, load clone (copy & paste) of base rom with clone .sav (game B)
3. Go to any pokemon center in both instances, to the second floor where the link club is
4. Attempt to start link trade on game A
5. Attempt to start link trade on game B
6. After a delay, both games fail to connect, "your friend is not ready" message

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

![image](https://github.com/visualboyadvance-m/visualboyadvance-m/assets/40458828/bc49bc33-9a4d-455c-b94f-bd276e31cde4)
BIOS Used?: none
SAVE TYPE: .sav. Unable to attach, will provide if requested

### What settings are you using?

Video driver: opengl
Sound driver: SDL
Scale Filter Used: retain aspect ratio

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: Win 10 22H2
CPU: Intel Core i5 7400
GPU: AMD Radeon RX 6600
RAM: 16 GB DDR4

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
2000ms is too much, closing because we already know linking is stuffed.
