### ISSUE TITLE
[Bug]: RTC (Real Time Clock) Game not able to detect RTC.

### ISSUE THREAD

**Issue by GitHubUser0220Yu** [visualboyadvance-m/visualboyadvance-m#1219]
### Expected behavior?

It was supposed to let the game load and be able to play.

### Actual behavior?

I am trying to play Saiph 2 and getting a message that the RTC is not able to be read (game language). I have turned on the RTC on the Visualboy but still says it can not be detected. I have used the RTC for other games and they worked fine. I tried reinstalling the game, but still does not work.

### Steps to reproduce the problem

1. Open VisualBoy Advance
2. Click on files
3.  Click open
4. Bowser and the game (Saiph 2)
5.  Run game
6.  Get a WARNING! A message saying the RTC can not be detected.
7.  after the message black screen and no sound from the game.
...

### Error messages?

The error message is just a WARNING! The RTC can not be detected or something along the line. Now I am getting a black screen instead.

### What game were you playing

Pokemon Saiph 2

### What settings are you using?

I do not know what to put here

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version) 
OS: (include version and OS build number using WinVer if on Windows): Windows
If using Linux, specify if using xorg or Wayland:
CPU:?
GPU:?
RAM:?
I am using the 128K and the version number is v1.3.2

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
see that pinned pokemon issue, read it.

**Comment by GitHubUser0220Yu** [comment]
> see that pinned pokemon issue, read it.

What and where?!

**Comment by ZachBacon** [comment]
https://github.com/visualboyadvance-m/visualboyadvance-m/issues/324
