### ISSUE TITLE
[Bug]: Inaccurate Emulators making people lose save files with RST 38 crashes.

### ISSUE THREAD

**Issue by BloxyReimu** [visualboyadvance-m/visualboyadvance-m#1220]
### Expected behavior?

With real gameboy hardware, and accurate emulators, there is some form of SRAM locking so crashes like RST 38 crashes don't corrupt your save data. RST 38 crashes first destroy the VRAM, then SRAM where your save data lies, and eventually loops so you must reset. If your SRAM is protected, you are fine with not losing your save file. This has been tested with Pokemon RBY and GSC.

### Actual behavior?

With inaccurate emulators though, the SRAM locking isn't implemented correctly meaning if your SRAM bank is 1 where your save data lies which can happen if you try to save before researching glitches in Pokemon RBY. Your save data will die if you get an RST 38 crash which will absolutely suck. It also can happen during speedruns too in the Blue Catch Em' All category where there's a ton of menus you have to go through and one wrong move and you crash which is very frustrating. This has been a problem with VBA in the past so I'm wondering if it will happen with the most accurate form of VBA.

### Steps to reproduce the problem

1. Open a Red or Blue rom.
2. Start a new game, and after you get your starter Save
3. Enable a walk through walls cheat
4. Go to the OoB grass
5. There you go, you get an RST 38 crash since you walked on an 0xFF loading zone tile which contains an RST 38 opcode.
6. See if your save data is gone.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs). It's available in the memory viewer and palette data so you will see when the RST 38 opcode occurred when you walk onto the freeze tile.

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title: Pokemon Blue
GB, GBC or GBA: GB
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Pokemon Blue.gb) Clean unmodified rom.

### What settings are you using?

Video driver (simple, opengl): OpenGL
Sound driver (directsound, xaudio, openal, SDL): Direct Sound
Scale Filter Used?: Default

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version) 2.1.9, 64 bit.
OS: (include version and OS build number using WinVer if on Windows): Windows 10 Home Edition
If using Linux, specify if using xorg or Wayland:
CPU: Amd A6-7310
GPU: Radeon R4
RAM: 8 gb DDR3

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Bugs are not for "Try this and see" they are for "I reproduced this issue, can you fix it"
