### ISSUE TITLE
[Bug]: no matter what settings i change and what keys i press or how many times i factory reset, the game runs at about 500% speed

### ISSUE THREAD

**Issue by Erickmaciasa** [visualboyadvance-m/visualboyadvance-m#1225]
### Expected behavior?

For it not to be fast

### Actual behavior?

Everything is moving fast ahh hell

### Steps to reproduce the problem

1: you play the game
2: its fast (wow)

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

DO NOT UPLOAD ROMS

### What settings are you using?

i dont even know bro it just started doing this after i closed it.

### Specifications and Build details

not a problem with my computer.

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
I removed your rom. NEVER EVER upload roms to github. That's asking for trouble.

Also https://github.com/visualboyadvance-m/visualboyadvance-m/issues/324

**Comment by Squall-Leonhart** [comment]
see https://github.com/visualboyadvance-m/visualboyadvance-m/discussions/1226
