### ISSUE TITLE
[Bug]: RTC not working with any settings

### ISSUE THREAD

**Issue by Erickmaciasa** [visualboyadvance-m/visualboyadvance-m#1227]
### Expected behavior?

The RTC working so i can catch Girattina 

### Actual behavior?

<img width="496" alt="Screenshot 2024-02-29 215715" src="https://github.com/visualboyadvance-m/visualboyadvance-m/assets/160649082/b4763527-c4b2-434f-92af-807cf9553701">

### Steps to reproduce the problem

1. Downloaded the rom
2. Played for 55 hours with no RTC
3. looked up how to activate it
4. nothing is working
5. mad.
...

### Error messages?

" The correct time system could not be read"

### What game were you playing

Pokemon unbound

### What settings are you using?

Bleeh :b

### Specifications and Build details

Radeon intergrated graphics 
8 gigs of ram

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
Obviously you didn't read the pinned issue on how to played hacked pokemon games https://github.com/visualboyadvance-m/visualboyadvance-m/issues/324

**Comment by Erickmaciasa** [comment]
> Obviously you didn't read the pinned issue on how to played hacked pokemon games #324

believe it or not, any setting means any settings. Im currently trying to Hex code the code in, but since i just learned abou emulators a literal week ago, its proving difficult so id like if you can recomend me a Hex code editor.
