### ISSUE TITLE
link functionality not working

### ISSUE THREAD

**Issue by NinFanBoyFTW** [visualboyadvance-m/visualboyadvance-m#123]
### Expected behavior
I should be able to select my link settings and the link connection should just work
### Actual behavior
on older builds, i used to have no problems link connecting to another VBA, or even dolphin games. Now, I cant get any link functionality working. I have tried save type, saving at bios, anything that it could have been. Like I said, on older versions I had no problems. This effects GBA, GB, and dolphin. This happens with all of the pokemon games I have tested

**Comment by Jookia** [comment]
Spent the past week trying to find a working version of VBA-M that supports linking. On Linux and in Wine on Linux, I've been completely unable to do so. I've tested Pokemon Puzzle Challenge and just normal Pokemon Crystal and it seems there's some type of corruption happening.

**Comment by gitbadger** [comment]
Any updates on the issue?

I'm trying to trade pokemons on Fire Red Edition, without success. I use the same rom, but different saves.

I set the client-server local connection. I talk to the npc asking for trade pokemons. The games are saved. Then it happens the error. No games crashes or connection crash. But the game points link connection problem.

On tcpdump, I see the sync-ack handshake right after clicking ok on client side instance. Only after game saves, packages are exchanged. But then the game stops trade process, pointing the connection problem. Both games still goes on, without crashes.

**Comment by grepwood** [comment]
I'm experiencing this issue with vbam-2.1.0

**Comment by retro-wertz** [comment]
we already know there are problems with link, especially on windows. what we need is more info/data as for my initial testings, i can link in most games fine in gb or gba under linux even vba to dolphin (though my pc does not handle 4 players fast enough to be fully playable.

**Comment by grepwood** [comment]
Problems? The whole damn thing doesn't even come up... I tried running with verbose, but it doesn't tell me anything more.
![obraz](https://user-images.githubusercontent.com/4225739/51433162-127cca00-1c45-11e9-9ac2-55d6cdd428f2.png)

**Comment by retro-wertz** [comment]
see what i mean when i said more data is needed instead of just saying or showing "it does not work"? you are using non-english which seems to be a problem atm(well, it could be).

**Comment by ZachBacon** [comment]
@grepwood the build you're using, is that a distro specific build or a build you made yourself?

**Comment by grepwood** [comment]
@ZachBacon spot on!
```
mdec@Leela ~ $ equery uses vbam
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for games-emulation/vbam-2.1.0:
 U I
 - - ffmpeg    : Enable ffmpeg/libav-based audio/video codec support
 - - link      : Enable GBA linking functionality
 - - lirc      : Add support for lirc (Linux's Infra-Red Remote Control)
 + + nls       : Add Native Language Support (using gettext - GNU locale utilities)
 - - openal    : Add support for the Open Audio Library
 + + sdl       : Add support for Simple Direct Layer (media library)
 - + wxwidgets : Add support for wxWidgets/wxGTK GUI toolkit
```
I'll rebuild with `link` and let you know if that changed.

**Comment by ZachBacon** [comment]
Also looks like our polish translation file isn't 100%, I'll check our transifex, but sorry not having it fully translated. Things have been slow on user contributed translations as of late it seems.

**Comment by grepwood** [comment]
@ZachBacon Translation is less important than working link imho.

**Comment by ZachBacon** [comment]
@grepwood true, but I still like seeing localizations complete too for users, completes the experience if they can use an app in their language.

**Comment by grepwood** [comment]
I made some discoveries along the way. `USE="link"` requires `media-libs/libsfml`. There are 3 versions of this package as of now:
```
=media-libs/libsfml-2.4.2 (stable)
=media-libs/libsfml-2.4.2-r2 (keyworded)
=media-libs/libsfml-2.5.1 (keyworded)
```
Interestingly enough, only 2.5.1 manages to build.

**Comment by JackoboLeChocobo** [comment]
@grepwood Do you have the same issue on others versions of VBA-M than 2.1.0? History to see if the implemented code of GB Link was a mess like the GBA Link code and never tested / tested incorrectly ...

**Comment by Squall-Leonhart** [comment]
> 
> 
> I tried network mode. Not working :(
> ![obraz](https://user-images.githubusercontent.com/4225739/51433436-1a8b3880-1c4a-11e9-808d-8c7b531d5cd5.png)

DMG and CGB Serial link are not functional under VisualBoy advance M, there was a adamn build (since lost thanks to forum software changes) that could do CGB link.

VBALink 1.6a has gold/silver link working, but not Red/Blue.

**Comment by Paulus88** [comment]
Having the same issue with the nightly and public build of 2.4
![link](https://user-images.githubusercontent.com/25663775/78470659-67620e80-772b-11ea-995a-d4a334ba2239.PNG)

**Comment by rkitover** [comment]
This bug is too general I think, while it is true that the link functionality in vba-m is extremely buggy, and things like GB link are pretty much non-functional, GBA link generally works just fine, and Dolphin link often works well enough to be playable.

We have been discussing all of this at length recently, and development resources will be allocated to various link issues, but this will take months if not years.

So, please go to a more specific issue for the link functionality relevant to your situation.

Closing this.
