### ISSUE TITLE
Game starts up but when I click start it crashes to a black screen[Bug]: 

### ISSUE THREAD

**Issue by xsevert9** [visualboyadvance-m/visualboyadvance-m#1245]
### Expected behavior?

Expected to start up and work after pressing start game
Note: Doesn't happen on most ROMS I play only a few every now and then

### Actual behavior?

Crashes when clicking on start

### Steps to reproduce the problem

1.Open up ROM
2.Wait for it to get to title screen
3.Press key to start

### Error messages?

No error message

### What game were you playing

Pokemon Fire Red Multiverse v1.6

### What settings are you using?

Skip BIOS
Auto IPS/ UPS/ IPF Patch

### Specifications and Build details

Visual Boy Advance- M 2.1.9

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Steelskin** [comment]
Romhack does not boot on real hardware.
