### ISSUE TITLE
[Bug]: Lost my save file even after putting in 2 save files.

### ISSUE THREAD

**Issue by Xtrabyte13** [visualboyadvance-m/visualboyadvance-m#1259]
Nvm Lmao the IT guy came and deleted ALL my game files. even my other game files so ye

**Comment by ZachBacon** [comment]
Filling out the report details are not optional. Fill them out.

**Comment by Steelskin** [comment]
Could you clarify what you mean by "save file"? Your screenshot shows the save state menu. Did you make a save state and it didn't work? Or did you save in game and when you re-opened the emulator the save was gone?

**Comment by Xtrabyte13** [comment]
Sorry I was out for a bit never got time to finish the report details but like what steelskin said I saved the game and I re opened the emulator the save was gone. I don't know what happened but I believe that the data was removed from the emulator thus erasing my save.
I can't finish the report details now but I will get them up tomorrow.

**Comment by ZachBacon** [comment]
> Fixed report details.

Incorrectly at it too... CPU etc means hardware, like my CPU is a ryzen 9 5900x etc.

**Comment by ZachBacon** [comment]
At anyrate, by default vba-m writes the saves to where the rom is located. By any chance is that folder the rom is located write protected? That would potentially explain why the saves aren't being written perhaps.

**Comment by Xtrabyte13** [comment]
Yea i didnt really know what to do for cpu but the other part i will check it but my emerald rom on the same emulator runs perfectly fine so i will check and get back to you. also i am running on a school computer so i dont really know how to check that
