### ISSUE TITLE
[Bug]: Build fails with LTO

### ISSUE THREAD

**Issue by eli-schwartz** [visualboyadvance-m/visualboyadvance-m#1260]
### Expected behavior?

Build should succeed.

### Actual behavior?

Build fails.

### Steps to reproduce the problem

I tried to build with the following *FLAGS to optimize the build: `-flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing`

Note the -Werror=* flags are used to help detect cases where the compiler tries to optimize by assuming UB cannot exist in the source code -- if it does exist, ordinarily the code would be miscompiled, and this says to make the miscompilation a fatal error.

### Error messages?

I got this error:
```
FAILED: vbam 
: && /usr/bin/x86_64-pc-linux-gnu-g++ -march=native -fstack-protector-all -O2 -pipe -fdiagnostics-color=always -frecord-gcc-switches -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-clash-protection -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing  -Wformat -Werror=format-security -Wl,-O1 -Wl,--as-needed -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing -Wl,--defsym=__gentoo_check_ldflags__=0 CMakeFiles/vbam.dir/src/sdl/ConfigManager.cpp.o CMakeFiles/vbam.dir/src/sdl/SDL.cpp.o CMakeFiles/vbam.dir/src/sdl/filters.cpp.o CMakeFiles/vbam.dir/src/sdl/text.cpp.o CMakeFiles/vbam.dir/src/sdl/inputSDL.cpp.o CMakeFiles/vbam.dir/src/sdl/expr.cpp.o CMakeFiles/vbam.dir/src/sdl/exprNode.cpp.o CMakeFiles/vbam.dir/src/sdl/expr-lex.cpp.o CMakeFiles/vbam.dir/src/common/version.cpp.o -o vbam  libvbamcore.a  fex/libfex.a  /usr/lib64/libSDL2main.a  /usr/lib64/libSDL2.so  /usr/lib64/libOpenGL.so  /usr/lib64/libGLX.so  /usr/lib64/libGLU.so  /usr/lib64/libz.so  -pipe -Wno-unused-command-line-argument -Wformat -Wformat-security -feliminate-unused-debug-types -march=core2 -fPIC -fopenmp -mfpmath=sse -msse2 -Ofast -fomit-frame-pointer -Wno-error  -Wl,-allow-multiple-definition && :
expr-lex.cpp:187:8: error: type ‘struct yy_buffer_state’ violates the C++ One Definition Rule [-Werror=odr]
debugger-expr-lex.cpp:444:8: note: a different type is defined in another translation unit
expr-lex.cpp:196:15: note: the first difference of corresponding definitions is field ‘yy_buf_size’
debugger-expr-lex.cpp:454:6: note: a field of same name but different type is defined in another translation unit
expr-lex.cpp:187:8: note: type ‘yy_size_t’ should match type ‘int’
lto1: some warnings being treated as errors
lto-wrapper: fatal error: /usr/bin/x86_64-pc-linux-gnu-g++ returned 1 exit status
compilation terminated.
/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

Also reported downstream at https://bugs.gentoo.org/926080
Full build log: [build.log](https://github.com/visualboyadvance-m/visualboyadvance-m/files/14716648/build.log)

### What settings are you using?

I wasn't using the program, just building it.

### Specifications and Build details

VBA-M: 2.1.7 -- but the files with the errors haven't changed since then
OS: Linux
If using Linux, specify if using xorg or Wayland: GCC doesn't care whether it is run under xorg or wayland
CPU: not sure it matters
GPU: not sure it matters
RAM: not sure it matters

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
Don't use those lto flags, we set our own using the cmake option ENABLE_LTO

**Comment by eli-schwartz** [comment]
> Don't use those lto flags, we set our own using the cmake option ENABLE_LTO

Okay. I won't use those LTO flags.

```
# These are not LTO flags
CXXFLAGS+="-Werror=odr"
LDFLAGS+="-Werror=odr"

# THese are the official LTO flags for vbam
mycmakeargs+=('-DENABLE_LTO=ON')

build_with_cmake "${mycmakeargs[@]}"
```

Same error.

```
FAILED: vbam 
: && /usr/bin/x86_64-pc-linux-gnu-g++ -march=native -fstack-protector-all -O2 -pipe -fdiagnostics-color=always -frecord-gcc-switches -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-clash-protection   -Wformat -Werror=format-security -Werror=odr -Wl,-O1 -Wl,--as-needed  -Wl,--defsym=__gentoo_check_ldflags__=0 CMakeFiles/vbam.dir/src/sdl/ConfigManager.cpp.o CMakeFiles/vbam.dir/src/sdl/SDL.cpp.o CMakeFiles/vbam.dir/src/sdl/filters.cpp.o CMakeFiles/vbam.dir/src/sdl/text.cpp.o CMakeFiles/vbam.dir/src/sdl/inputSDL.cpp.o CMakeFiles/vbam.dir/src/sdl/expr.cpp.o CMakeFiles/vbam.dir/src/sdl/exprNode.cpp.o CMakeFiles/vbam.dir/src/sdl/expr-lex.cpp.o CMakeFiles/vbam.dir/src/common/version.cpp.o -o vbam  libvbamcore.a  fex/libfex.a  /usr/lib64/libSDL2main.a  /usr/lib64/libSDL2.so  /usr/lib64/libOpenGL.so  /usr/lib64/libGLX.so  /usr/lib64/libGLU.so  /usr/lib64/libz.so  -pipe -Wno-unused-command-line-argument -Wformat -Wformat-security -feliminate-unused-debug-types -march=core2 -fPIC -fopenmp -mfpmath=sse -msse2 -Ofast -fomit-frame-pointer -flto=8 -ffat-lto-objects -Wno-error  -Wl,-allow-multiple-definition && :
expr-lex.cpp:187:8: error: type ‘struct yy_buffer_state’ violates the C++ One Definition Rule [-Werror=odr]
debugger-expr-lex.cpp:444:8: note: a different type is defined in another translation unit
expr-lex.cpp:196:15: note: the first difference of corresponding definitions is field ‘yy_buf_size’
debugger-expr-lex.cpp:454:6: note: a field of same name but different type is defined in another translation unit
expr-lex.cpp:187:8: note: type ‘yy_size_t’ should match type ‘int’
lto1: some warnings being treated as errors
lto-wrapper: fatal error: /usr/bin/x86_64-pc-linux-gnu-g++ returned 1 exit status
compilation terminated.
/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

This is because your cmake option ENABLE_LTO simply tells cmake to use its builtin LTO handling, which passes `-flto=8 -ffat-lto-objects`. There's no difference from a code correctness perspective. Well, fat LTO is different in the sense that it is slow and in this case purposeless.

I am not sure what point you're trying to make. Are you saying the vbam code *doesn't* violate the C++ One Definition Rule?

The warning flags I used at the same time as the LTO flag do not change how LTO works, or cause cmake to build a different binary. They just instruct GCC to detect *miscompilations*.

Please also note the ODR violation is in `yy_buffer_state`, across two files:
- expr-lex.cpp
- debugger-expr-lex.cpp

They are both lex-generated files, generating *different* code but under the same name. The ideal solution here is probably to ensure that the generated definitions are named something different. Consider regenerating with the `--prefix` option to flex, to ensure that they don't clash with each other.

The default prefix is always "yy" which is inconvenient whenever it turns out you use lex for multiple files in the same project, but that is POSIX for you.

**Comment by eli-schwartz** [comment]
Sorry for not providing this additional context in the beginning -- I couldn't find a good box in the issue template to put it into, and then I stepped out for a bit.

**Comment by rkitover** [comment]
I have reproduced this and am working on a fix, I'd like to note that passing `-DENABLE_SDL=OFF` will build successfully.
