### ISSUE TITLE
[Bug]: In-game character froze/unable to give any input

### ISSUE THREAD

**Issue by Parth17x** [visualboyadvance-m/visualboyadvance-m#1261]
### Expected behavior?

Game running smoothly

### Actual behavior?

Game is just stuck here, unable to do anything 
![Screenshot 2024-03-26 011519](https://github.com/visualboyadvance-m/visualboyadvance-m/assets/148569075/058afae2-ef17-4102-b442-158ff072e055)

### Steps to reproduce the problem

Didn't do anything specific, was running normally with turbo mode on and it suddenly froze

### Error messages?

No error message was shown

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title: Pokemon AshGray Version
GB, GBC or GBA: GBA
ROM CODE: ???? [ it shows BPRE under Options > Game Boy Advance > Config>Game overrides>game code ]
BIOS Used?: none
SAVE TYPE: (Attach Battery or Savestate here)
[battery.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/14748892/battery.zip)

![Screenshot 2024-03-26 012613](https://github.com/visualboyadvance-m/visualboyadvance-m/assets/148569075/31d5abec-0eb1-4a8f-babb-b6af62130cff)

Clean, Intro'd or Hacked?:(Attach Patch here): Clean

### What settings are you using?

Video driver (simple, opengl): simple
Sound driver (directsound, xaudio, openal, SDL): xaudio2
Scale Filter Used?: none

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version); VBA-M 2.1.9, 64 bit
OS: (include version and OS build number using WinVer if on Windows): windows 11 home version: 23H2 OS Buikd: 22631.3296
If using Linux, specify if using xorg or Wayland:
CPU: 12th gen intel(r) core i5-12450H 2.00GHz
GPU: Intel Integrated
RAM: 16GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Steelskin** [comment]
I was not able to reproduce your issue. Could you let me know what you did right after loading the save file? I also suspect that the issue might be from the ROM hack itself. I noticed a number of graphical glitches. Was the emulator UI still responsive or did the entire program hang?
