### ISSUE TITLE
[Build]: Build warning questions

### ISSUE THREAD

**Issue by Unknown326** [visualboyadvance-m/visualboyadvance-m#1266]
### Expected behavior?

Compile without warnings.

### Actual behavior?

The following warnings appear during and after compilation:

New definition:
 #define UPDATE_REG(address, value) WRITE16LE(((uint16_t*)&g_ioMem[address]), value)

Files:
/home/home/Descargas/VBA-M/src/core/gba/gbaLink.cpp:44
/home/home/Descargas/VBA-M/src/core/gba/gbaLink.cpp:37

Previous definition:
 #define UPDATE_REG(address, value)

File:
/home/home/Descargas/VBA-M/src/core/gba/gbaCpu.h:27
 
New definition:               
 #define HAVE_VARIADIC_MACROS 1

Files:
from /usr/include/wx-3.0/wx/platform.h:183,
from /usr/include/wx-3.0/wx/defs.h:27,
from /usr/include/wx-3.0/wx/event.h:14,
from /usr/include/wx-3.0/wx/window.h:18,
from /home/home/Descargas/VBA-M/src/wx/widgets/dpi-support.cpp:3:
from /usr/include/wx-3.0/wx/version.h:16,
from /home/home/Descargas/VBA-M/src/wx/widgets/dpi-support.h:4,
from /home/home/Descargas/VBA-M/src/wx/widgets/dpi-support.cpp:1:
 
Previous definition;
#define HAVE_VARIADIC_MACROS

File:
/usr/include/wx-3.0/wx/cpp.h:133:
   
### Steps to reproduce the problem

The basic formula to build.

### What settings are you using?

Standar setup.

### Specifications and Build details

VBA-M: [8eae2e5]
OS: LINUX MINT 21.3 Cinnamon / Xorg
CPU: AMD A9-9420 Radeon R5
GPU: AMD STONEY
RAM: 4GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Unknown326** [comment]
I was trying to fix warnings that occur during compilation, but I had several questions.
1. Regarding **serial compilation LTRANS jobs**: does this in any way affect how the emulator works? My understanding is that this is a harmless warning, as it only interferes with compilation speed. I am right?
2. Regarding the macros that are redefined: I cannot understand who this change depends on. When I corrected the names in the files, I couldn't compile.

I appreciate your time in advance.

**Comment by rkitover** [comment]
> I was trying to fix warnings that occur during compilation, but I had several questions.
> 
> 1. Regarding **serial compilation LTRANS jobs**: does this in any way affect how the emulator works? My understanding is that this is a harmless warning, as it only interferes with compilation speed. I am right?

Yes you are right. This happens because we need to pass `-lfto=NUM_THREADS` instead of just `-flto`. We've recently changed the cmake code for this but we should fix this.

> 2. Regarding the macros that are redefined: I cannot understand who this change depends on. When I corrected the names in the files, I couldn't compile.

Don't know about that, but by the way I fixed the `-Wodr` warning a few days ago, please update your fork.

**Comment by Unknown326** [comment]
Thanks for the quick reply. I've already updated the post and included the macros I mentioned before and the files that invoke them.

**Comment by Steelskin** [comment]
We already have issue #1003 tracking building with no warning. Yes, there are a lot of them but the situation has somewhat improved since I filed that issue. For now, unless this is something specific that needs to be handled separately, could you move the discussion to #1003?
