### ISSUE TITLE
Error window when open "Memory Viewer"

### ISSUE THREAD

**Issue by ticktackboom** [visualboyadvance-m/visualboyadvance-m#127]
### Expected behavior

Memory Viewer should open smoothly

### Actual behavior

When I open the window of Memory Viewer, appears a dialog box with the following errors:

6:47:44: XRC error: 12: "wxEXPAND" is incompatible with vertical alignment flag ""wxALIGN_CENTRE_VERTICAL"" in a horizontal box sizer
6:47:44: XRC error: 42: "wxEXPAND" is incompatible with vertical alignment flag ""wxALIGN_CENTRE_VERTICAL"" in a horizontal box sizer

And when I activate "Automatic update", the window blinks.

### Steps to reproduce the behavior

Go to the menu Tools and click Memory Viewer

### ROM details

Which games are affected by the issue (please state if GBA or GB game):

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

### Option details

Video driver (simple, opengl or cairo):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by ZachBacon** [comment]
Not so much a bug as a toolkit programming thing. Chances are though it'll be fixed regardless in the next version. TYVM for the report.

**Comment by rkitover** [comment]
This looks simple to fix, just an error in the xrc, unless there are other issues, will take a look.

**Comment by rkitover** [comment]
@ticktackboom reproduced the problem on wx master and fixed the xrc in our master in fb15aed2 .

Automatic update seems to work fine as well (you may want to turn off `Pause when inactive` under `Emulation` when using this.)

Can you please try master?
