### ISSUE TITLE
I think my emulator's date overflowed some way.

### ISSUE THREAD

**Issue by santo998** [visualboyadvance-m/visualboyadvance-m#1270]
I think my emulator's date overflowed some way.

When I save state, it saves it as 01/01/1970.

I tried different games, and the same happens. So I think the problem is on VisualBoyAdvance.

Any clues on how to fix this?

_Originally posted by @santo998 in https://github.com/visualboyadvance-m/visualboyadvance-m/discussions/1264_

**Comment by santo998** [comment]
Issue https://github.com/visualboyadvance-m/visualboyadvance-m/issues/1269 was closed unproperly

**Comment by ZachBacon** [comment]
It was not closed improperly. You created this first, and then you created the other 2 days later.

**Comment by ZachBacon** [comment]
Duplicate of https://github.com/visualboyadvance-m/visualboyadvance-m/discussions/1264

Stop making the issue, there's a discussion open, use that.
