### ISSUE TITLE
[Bug]: the audio is not working, it says "could not initialize the sound driver!"

### ISSUE THREAD

**Issue by Derfertermo** [visualboyadvance-m/visualboyadvance-m#1278]
### Expected behavior?

that the audio is not working

### Actual behavior?

audio not working and turbo is active by himself

### Steps to reproduce the problem

1.literally just opened pokemon emerald and it says that
2.i tried with any game and it says the same
3.
4.
5.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Steelskin** [comment]
Please, fill the rest of the template. Namely, what operating system are you using, which version of vba-m are you using, which audio driver are you using?

I do not doubt that you have encountered a bug but I can't help fix it without that information.

**Comment by HPD1995** [comment]
Having the same issue here after downloading VBA-M on my wife's laptop. 
XAudio2 is the culprit it seems, as the "audio not working" text is regarding XAudio2, and with it selected in Sound Settings, turbo seems permanently enabled.
Changing Device in the Advanced tab to OpenAL or Direct Sound seems to fix the performance issue for now!

**Comment by ZachBacon** [comment]
> Having the same issue here after downloading VBA-M on my wife's laptop. 
> XAudio2 is the culprit it seems, as the "audio not working" text is regarding XAudio2, and with it selected in Sound Settings, turbo seems permanently enabled.
> Changing Device in the Advanced tab to OpenAL or Direct Sound seems to fix the performance issue for now!

And yet you're still not helping us to help you by providing your system details. This solves nothing.

**Comment by HPD1995** [comment]
OS: Windows 11 23H2 (Build 22631.3296)
VBA-M Version: 2.1.9
Sound Driver: The Realtek driver shown in system details is 10.0.66.131

**Comment by Squall-Leonhart** [comment]
The old readme used to point out that the DX Redist is required for some aspects of the emulator, but this was not carried forward after the swap over from MFC to Wx,  this requirement still holds true for Xaudio 2.7.

**Comment by gregdos910** [comment]
> > Having the same issue here after downloading VBA-M on my wife's laptop.
> > XAudio2 is the culprit it seems, as the "audio not working" text is regarding XAudio2, and with it selected in Sound Settings, turbo seems permanently enabled.
> > Changing Device in the Advanced tab to OpenAL or Direct Sound seems to fix the performance issue for now!
> 
> And yet you're still not helping us to help you by providing your system details. This solves nothing.

This worked for me. Thanks!

**Comment by ZEROTT140** [comment]
VISUAL BOY ADVANCE BETA SOUND TROUBLE IN TALES OF PHANTASIA DO NOT DIFILE AND SOUND CUT PLEASE HELP
