### ISSUE TITLE
[Bug]: Failed to allocate memory for trace 

### ISSUE THREAD

**Issue by Berrrye** [visualboyadvance-m/visualboyadvance-m#1279]
### Expected behavior?

my laptop not going black and no error message saying "Failed to allocate memory for trace"

### Actual behavior?

my laptop getting black screen for some time and then after it come back to normal there is an error message saying "Failed to allocate memory for trace"

### Steps to reproduce the problem

1. i open more than 1 window of VBA and shiny hunt on all of them at the same time in pokemon Fire red
2. i  soft reset a couple of times 
3. after some time the error message pops up and my screen goes black and i cant soft reset again or it keeps going black and the error message appears
4.
5.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).
i couldnt follow through, sorry

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title: Pokemon fire red
GB, GBC or GBA: GBA
ROM CODE: IDK
BIOS Used?: (Share crc hash) IDK
SAVE TYPE: (Attach Battery or Savestate here) Automatic 128K
Clean, Intro'd or Hacked?:(Attach Patch here)
I downloaded the rom form the rom megathread (https://r-roms.github.io/megathread/popular/)

### What settings are you using?

Video driver (simple, opengl): opengl
Sound driver (directsound, xaudio, openal, SDL): openal
Scale Filter Used?: i couldnt find out

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:
im using VBA-M version 2.1.9 64 bit version

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
nothing we can do about your system instability.

**Comment by Berrrye** [comment]
i have version 23H2 (OS build 22631.3296) windows 11

**Comment by starfoxed64** [comment]
I am also receiving this error, but my system is not running out of memory. Coincidentally I am also running a Fire Red ROM. I open 6 instances simultaneously, run them turbo, and after about 60-100 soft resets I get the same error message Failed to allocate memory for TRACE. I am shiny hunting like I see a lot of others do.

I can confirm that the user's VBA settings above are all the same as mine. I am running the 64-bit version because the 32-bit version crashes after 2 soft resets. 

I am Windows 11 23H2, AMD Ryzen 7 3800X, 32GB DDR4 RAM, RTX 3080.

I hope this gets reopened and reviewed.

**Comment by Squall-Leonhart** [comment]
it won't be, you're hitting GDI resource exhaustion.
