### ISSUE TITLE
I can't get cheats to work on VBA-M at all.  

### ISSUE THREAD

**Issue by hoover1979** [visualboyadvance-m/visualboyadvance-m#128]
### Expected behavior
set cheats to auto load/save,enablie cheats, load cheat list select cheats, play without dying all the time

### Actual behavior
set cheats to auto load/save, enabling cheats, load cheat list, cheat list is garbled, but cheats that work in regular VBA are checked, play game, cheats not working, get killed quickly.

### Steps to reproduce the behavior
load VBA-M, enable cheats, set enable auto save/load, load cheat list and play game.  _(VBA-M says cheats enabled, but they aren't)._

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
All GBA roms _(most likely GB and GBC roms too, but I have no cheats for them to test)._

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
none.  All my games are affected

### Option details

Video driver (simple, opengl or cairo):
OpenGL

Sound driver (directsound, xaudio, openal, SDL):
OpenAL _(Creative ALchemy)_/Direct Sound

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 7 professional 64bit
Latest Drivers for Gigabyte Xtreme Gaming GTX1080 Waterforce.
Latest VBA-M build from Sourceforge page.
latest drivers for Creative Sound Blaster Zx
Latest Mobo drivers
Latest intel drivers for my i7-4790k

### Hardware details:
If relevant, the joystick you are using and the drivers you are using for it:
Afterglow Wired Xbox360 controller _(Xinput)._

**Comment by hoover1979** [comment]
I would really appreciate a solution.  VBA-M is the only emulator I can find with aspect correct fullscreen and 6xBRz filtering, a neccesity for running the low resolution GBA roms on a 27" 1080p Monitor without extreme blockiness/bluriness.  I can get cheats working on VBA, however it dowsn't do filtering better than HQ2X, crashes fulscreening in DDrwa and won't keep aspect _(stretches to fill entire 16:9 screen)_ in OpenGL and Direct3D

**Comment by ZachBacon** [comment]
This a 3rd time this has been opened. And as before it is being investigated, Please do a search before posting a bug to avoid duplicate issues.

**Comment by hoover1979** [comment]
Is there a later version than the 2016 version I got from Souceforge, with this bug fixed?
