### ISSUE TITLE
[Bug]: Video isn't working

### ISSUE THREAD

**Issue by Seanofthedead92** [visualboyadvance-m/visualboyadvance-m#1280]
### Expected behavior?

The video of the game should play.

### Actual behavior?

There is only a white screen, however I know the game is running because you can hear the game audio.

### Steps to reproduce the problem

1.Turn game on
2.That's it
3.
4.
5.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
Not providing any details is not gonna help us, help you. We need your operating system, the version it is, what graphics API you're using (on Windows it's usually simple and opengl etc)

We need these details.

**Comment by Squall-Leonhart** [comment]
Your intel Atoms gpu is not supported.

Duplicate #1124
