### ISSUE TITLE
[Bug]: Screen turns black while teaching charizard wing attack, after hitting level 36 and evolving

### ISSUE THREAD

**Issue by xxCharizardxx** [visualboyadvance-m/visualboyadvance-m#1282]
### Expected behavior?

Normally I'd try to teach charizard wing attack because it just evolved.

### Actual behavior?

The screen turns black as I am deleting a move to replace it with wing attack

### Steps to reproduce the problem

1.charmeleon evolve into charizard
2.try teaching wing attack
3.black screen
4.
5.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)
Visual boy advance

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:
na

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:
windows 10

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
You have to fill out the entire form. What's the version of vba-m you are using?

**Comment by xxCharizardxx** [comment]
visual boy advance

**Comment by ZachBacon** [comment]
> visual boy advance

So you're using an unsupported version if it's not the -m. Use a build from https://nightly.visualboyadvance-m.org

**Comment by xxCharizardxx** [comment]
![Screenshot 2024-04-16 191114](https://github.com/visualboyadvance-m/visualboyadvance-m/assets/166407061/b44709c2-02d4-443d-aa7b-7ef3a85c6474)
use this one?

**Comment by ZachBacon** [comment]
If you have an arm64 device, but considering you most likely don't know what you have (and I apologize for the phrasing of that) you'll want the x86_64 version

**Comment by xxCharizardxx** [comment]
nothin taken. thats why im here. to ask for help from people who would know
alright gonna download it, ill be back if i need anything else. Thank you!
