### ISSUE TITLE
White screen with SpongeBob SquarePants: ROTFD (GCN)'s radar.bin ROM

### ISSUE THREAD

**Issue by escape209** [visualboyadvance-m/visualboyadvance-m#129]
### Expected behavior
Expected the ROM's title screen to show up. The ROM works fine in Bizhawk, but that doesn't have GBA link support. Here's a screenshot of the title screen from Bizhawk using its mGBA core:

![radar 2017-07-03 17 50 53](https://user-images.githubusercontent.com/8225831/27801848-324cb97a-6018-11e7-8759-0183ab684f7d.png)

### Actual behavior
White screen.

### Steps to reproduce the behavior
After having extracted the files of the GameCube version of SpongeBob SquarePants: Revenge of the Flying Dutchman, get the radar.bin file and try to play it in VBA-M. 
### Option details

Video driver: Simple
Sound driver: XAudio

### Build details

Operating System: Windows 10 Pro x64
Version of code: latest SourceForge version

### Hardware details:

CPU: i5-6400
GPU: AMD Radeon HD 7770
RAM: 8GB @ 2133MHz

Also using a PS4 controller with DS4Windows.

**Comment by fancymelonub** [comment]
can't you just use VBA-M or mGBA + Dolphin to emulate GBA Link to GC?
