### ISSUE TITLE
[Feature request]: Limit framerate

### ISSUE THREAD

**Issue by icantfindanamecool** [visualboyadvance-m/visualboyadvance-m#1291]
### Request box

Limit framerate would limit the framerate of any game to 60Fps

### Reason box

In pokemon games its anoying that this does not exist because the game is realy sped up

### Examples

![image](https://github.com/visualboyadvance-m/visualboyadvance-m/assets/168103978/38762c45-1d42-4593-8edb-dd9c0c679b0e)

**Comment by Squall-Leonhart** [comment]
Duplicate https://github.com/visualboyadvance-m/visualboyadvance-m/issues/51

Search before opening please.

**Comment by icantfindanamecool** [comment]
sorry will do next time
