### ISSUE TITLE
[Bug]: VBA-M crash after load GBA rom

### ISSUE THREAD

**Issue by shaikezam** [visualboyadvance-m/visualboyadvance-m#1292]
### Expected behavior?

ROM should be loaded successfully 

### Actual behavior?

After load ROM (pokemon Emerald, or any other ROM) VBA-M crash immediately. 

### Steps to reproduce the problem

1. Install VBA-M via snap
2. start VBA b exeucte visualboyadvance-m emerald.gba

### Error messages?

22:44:35: Debug: GetUserLocalDataDir(): /home/shaikezam/snap/visualboyadvance-m/725/.visualboyadvance-m
22:44:35: Debug: GetUserDataDir(): /home/shaikezam/snap/visualboyadvance-m/725/.visualboyadvance-m
22:44:35: Debug: GetLocalizedResourcesDir(wxGetApp().locale.GetCanonicalName()): /snap/visualboyadvance-m/725/usr/share/visualboyadvance-m/en_IL
22:44:35: Debug: GetResourcesDir(): /snap/visualboyadvance-m/725/usr/share/visualboyadvance-m
22:44:35: Debug: GetDataDir(): /snap/visualboyadvance-m/725/usr/share/visualboyadvance-m
22:44:35: Debug: GetLocalDataDir(): /etc/visualboyadvance-m
22:44:35: Debug: plugins_dir: /snap/visualboyadvance-m/725/usr/lib/visualboyadvance-m
22:44:35: Debug: XdgConfigDir: /home/shaikezam/snap/visualboyadvance-m/725/.config/visualboyadvance-m

(visualboyadvance-m:12588): IBUS-WARNING **: 22:44:35.635: Failed to mkdir /home/shaikezam/snap/visualboyadvance-m/725/.config/ibus/bus: Not a directory

(visualboyadvance-m:12588): GLib-GIO-WARNING **: 22:44:35.736: Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)
Segmentation fault (core dumped)

in the 2nd time it prints:

22:44:40: Debug: GetUserLocalDataDir(): /home/shaikezam/snap/visualboyadvance-m/725/.visualboyadvance-m
22:44:40: Debug: GetUserDataDir(): /home/shaikezam/snap/visualboyadvance-m/725/.visualboyadvance-m
22:44:40: Debug: GetLocalizedResourcesDir(wxGetApp().locale.GetCanonicalName()): /snap/visualboyadvance-m/725/usr/share/visualboyadvance-m/en_IL
22:44:40: Debug: GetResourcesDir(): /snap/visualboyadvance-m/725/usr/share/visualboyadvance-m
22:44:40: Debug: GetDataDir(): /snap/visualboyadvance-m/725/usr/share/visualboyadvance-m
22:44:40: Debug: GetLocalDataDir(): /etc/visualboyadvance-m
22:44:40: Debug: plugins_dir: /snap/visualboyadvance-m/725/usr/lib/visualboyadvance-m
22:44:40: Debug: XdgConfigDir: /home/shaikezam/snap/visualboyadvance-m/725/.config/visualboyadvance-m

(visualboyadvance-m:12814): IBUS-WARNING **: 22:44:40.421: Failed to mkdir /home/shaikezam/snap/visualboyadvance-m/725/.config/ibus/bus: Not a directory

(visualboyadvance-m:12814): GLib-GIO-WARNING **: 22:44:40.522: Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)

**(visualboyadvance-m:12814): Gtk-CRITICAL **: 22:44:40.826: gtk_distribute_natural_allocation: assertion 'extra_space >= 0' failed**
Segmentation fault (core dumped)

### What game were you playing

Title: Pokemon Emerald
GB, GBC or GBA: GBA
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here) clean

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:
All without changed, frash install from snap version 2.1.8

### Specifications and Build details

VBA-M: installation from snap
OS: Lubuntu 22.04.4
CPU: I3 10100
GPU: none
RAM:16GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
That's a bug in your distro, not our issue.

**Comment by shaikezam** [comment]
what do u mean? it worked few week ago
