### ISSUE TITLE
How's vbaemulator allowed to go on unchecked?

### ISSUE THREAD

**Issue by MediaMaquina** [visualboyadvance-m/visualboyadvance-m#1294]
### Request box

Hello! This user: https://github.com/vbaemulator
Basically he's impersonating popular defunct VBA)

He registered a domain to look legitimate: https://visualboyadvance.org/
Besides this seemingly official site, hides a full blown piracy site hosting Nintendo ROMS all powered by Github!
His repository is just Nintendo roms, no code whatsoever.

### Reason box

asap!

### Examples

What can we do to stop this?

**Comment by Squall-Leonhart** [comment]
Discord will only act on a dmca made by the original rights holder, and i've already at one point notified microsoft about the various rare games being hosted over there, its out of our hands.
