### ISSUE TITLE
[Feature request]: Windows XP/Vista support

### ISSUE THREAD

**Issue by DellM-79** [visualboyadvance-m/visualboyadvance-m#1300]
### Request box

Add support for Windows Vista and earlier, especially on Windows XP

### Reason box

Because I've used a GBA emulator on Windows XP several times, so why not??

### Examples

I ran it on my Dell Latitude E6410.

**Comment by DellM-79** [comment]
> While we are not going out of our way to remove compatibility with earlier Windows versions, it is challenging to do so as time goes on. We rely on a number of external libraries that may have abandoned earlier versions, especially Windows XP, though we do not track this very closely. I tried using the build on a Windows Vista VM a while ago and it was working fine but a lot has changed since then. Does it no longer work?

I tested it on my XP Pentium Dual machine; version 2.1.8 opens flawlessly.

**Comment by rkitover** [comment]
@DellM-79 Does 2.1.9 not work? I built 2.1.8 on mingw specifically for this reason, I may have forgotten to do that for 2.1.9 in which case I will redo the build.

**Comment by rkitover** [comment]
Can you try a nightly, I updated my nightly scripts to build on mingw.

**Comment by rkitover** [comment]
I redid 2.1.9 on mingw just to make sure, please someone with an XP try it and the nightly.

**Comment by rkitover** [comment]
Just tested 2.1.9 on an XP vm, works fine, xaudio2 does not work until you install the 2010 directx redist however.

**Comment by rkitover** [comment]
Ok, the nightly runs on XP now, there's a bug with the config but that's unrelated and will be resolved in short order.
