### ISSUE TITLE
Colors rendering in the latest version of VBA-M

### ISSUE THREAD

**Issue by slacknk** [visualboyadvance-m/visualboyadvance-m#131]
Why colors became more darker / less contrast in the new versions of program? 
in older version games look good... but now I have ugly color..

Here is example of colors rendering of the game Shantae in the VBA-M:

- Beta3 / Keyboardfixes / waylandplus
http://storage4.static.itmages.ru/i/17/0721/h_1500665332_7476865_77a3808395.png

- throttle / git20170603_throttle from master
http://storage5.static.itmages.ru/i/17/0721/h_1500665338_2728810_aed9c2ac81.png

Option details: both screenshots were made with default config files (rm -rf ~/.vbam).

Build details: builded from sources in slackware64-14.2. Keys for All build-ver:
```
if [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
...

[ $ARCH = i?86 ] && ASM=ON || ASM=OFF
...

cmake \
 \
 -DCMAKE_C_FLAGS:STRING="$SLKCFLAGS" \
 -DCMAKE_CXX_FLAGS:STRING="$SLKCFLAGS" \
 \
 -DENABLE_ASM_CORE=${ASM} \
 -DENABLE_ASM_SCALERS=${ASM} \
 \
 -DENABLE_SDL=ON \
 -DENABLE_NLS=ON \
 \
 -DENABLE_WX=ON 
 -DwxWidgets_CONFIG_EXECUTABLE=/usr/lib$LIBDIRSUFFIX/wx/config/gtk2-unicode-3.0 \
 -DwxWidgets_USE_DEBUG=OFF
  \
 -DCMAKE_INSTALL_PREFIX=/usr \
 -DCMAKE_INSTALL_MANDIR=/usr/man \
  \
 -DCMAKE_BUILD_TYPE=Release ..
```

**Comment by rkitover** [comment]
Try using the Simple video renderer, the OpenGL renderer does not do color correction.

**Comment by slacknk** [comment]
with Simple video (Menu:Options - Video - Configure... - Basic - Output module: Simple), too.
```$ LC_ALL=en_US.UTF8 visualboyadvance-m```
http://storage7.static.itmages.ru/i/17/0722/h_1500746145_2016789_3fc4ad8c0f.png

**Comment by rkitover** [comment]
Ok, thanks for checking!

**Comment by rkitover** [comment]
@slacknk just tried the Shantae ROM on a mac with master, colors correct (like in your first screenshot.)

I will also try in a linux VM.

**Comment by rkitover** [comment]
@slacknk here's a screenshot for reference:

![Shantae GBC colors in master](https://www.dropbox.com/s/2g5xj7snqtxja3b/VBA-M%20Shantae%20GBC%20colors.png?dl=1)

**Comment by slacknk** [comment]
hmm(
> I will also try in a linux VM

distro? I'm tried build vba-m from master git20170809_throttle. Colors too...
And, other bug, visualboyadvance-m freezes-from-menu https://github.com/visualboyadvance-m/visualboyadvance-m/issues/67 https://github.com/visualboyadvance-m/visualboyadvance-m/issues/139 , too.

**Comment by zen-tools** [comment]
Hello, all!

I have builded visualboyadvance-m from master and all looks fine with defaults settings:
https://cdn.scrot.moe/images/2017/08/13/2017-08-13-142358_740x663_scrot.png
I tried to change render mode, but nothing changed.

About my linux distro:
Debian GNU/Linux 8.9 (jessie) + backports

Installed dependencies:
```
$ for i in build-essential g++ nasm cmake gettext zlib1g-dev libgl1-mesa-dev libavcodec-dev libavformat-dev libswscale-dev libavutil-dev libgettextpo-dev libpng12-0 libsdl2-dev libopenal-dev libwxgtk3.0-dev libgtk2.0-dev libgtk-3-dev libcairo2-dev; do echo $i; LC_ALL=C apt-cache policy $i | grep Installed; done
build-essential
  Installed: 11.7
g++
  Installed: 4:4.9.2-2
nasm
  Installed: 2.11.05-1
cmake
  Installed: 3.6.2-2~bpo8+1
gettext
  Installed: 0.19.8.1-1~bpo8+1
zlib1g-dev
  Installed: 1:1.2.8.dfsg-2+b1
libgl1-mesa-dev
  Installed: 13.0.6-1~bpo8+1
libavcodec-dev
  Installed: 7:3.2.5-1~bpo8+1
libavformat-dev
  Installed: 7:3.2.5-1~bpo8+1
libswscale-dev
  Installed: 7:3.2.5-1~bpo8+1
libavutil-dev
  Installed: 7:3.2.5-1~bpo8+1
libgettextpo-dev
  Installed: 0.19.8.1-1~bpo8+1
libpng12-0
  Installed: 1.2.50-2+deb8u3
libsdl2-dev
  Installed: 2.0.2+dfsg1-6
libopenal-dev
  Installed: 1:1.15.1-5
libwxgtk3.0-dev
  Installed: 3.0.2-1+b1
libgtk2.0-dev
  Installed: 2.24.25-3+deb8u2
libgtk-3-dev
  Installed: 3.14.5-1+deb8u1
libcairo2-dev
  Installed: 1.14.0-2.1+deb8u2
```

**Comment by slacknk** [comment]
zen thx, interesting. From me slackware64-14.2:
```
gcc-g++-5.3.0_multilib-x86_64-3alien
nasm-2.13.01-x86_64-1_slack14.2
OpenAL-1.18.0-x86_64-1_SBo
gtk+2-2.24.31-x86_64-1_slack14.2
gtk+3-3.18.9-x86_64-1
wxGTK3-3.0.3.1-x86_64-1_SBo

cmake-3.5.2-x86_64-1
gccmakedep-1.0.3-noarch-1

gettext-0.19.8.1-x86_64-1
gettext-tools-0.19.8.1-x86_64-1

zlib-1.2.8-x86_64-1
zlib-compat32-1.2.8-x86_64-1compat32

mesa-11.2.2-x86_64-1
mesa-compat32-11.2.2-x86_64-1compat32

SDL2-2.0.5-x86_64-1_SBo
SDL2_image-2.0.1-x86_64-2_SBo
SDL2_mixer-2.0.1-x86_64-2_SBo
SDL2_ttf-2.0.14-x86_64-1_SBo
SDL_sound-1.0.3-x86_64-2alien

cairo-1.14.6-x86_64-2
cairo-compat32-1.14.6-x86_64-2compat32
cairomm-1.12.0-x86_64-1
pycairo-1.10.0-x86_64-1
```

**Comment by slacknk** [comment]
zen thx, interesting. From me slackware64-14.2:
```
gcc-g++-5.3.0_multilib-x86_64-3alien
nasm-2.13.01-x86_64-1_slack14.2
OpenAL-1.18.0-x86_64-1_SBo
SFML-2.4.2-x86_64-3_SBo
glibmm-2.46.4-x86_64-1
gtkglextmm-1.2.0-x86_64-2_SBo
gtkmm2-2.24.4-x86_64-1
gtkmm3-3.18.1-x86_64-1
gtk+2-2.24.31-x86_64-1_slack14.2
gtk+3-3.18.9-x86_64-1
wxGTK3-3.0.3.1-x86_64-1_SBo

cmake-3.5.2-x86_64-1
gccmakedep-1.0.3-noarch-1

gettext-0.19.8.1-x86_64-1
gettext-tools-0.19.8.1-x86_64-1

zlib-1.2.8-x86_64-1
zlib-compat32-1.2.8-x86_64-1compat32

mesa-11.2.2-x86_64-1
mesa-compat32-11.2.2-x86_64-1compat32

SDL2-2.0.5-x86_64-1_SBo
SDL2_image-2.0.1-x86_64-2_SBo
SDL2_mixer-2.0.1-x86_64-2_SBo
SDL2_ttf-2.0.14-x86_64-1_SBo
SDL_sound-1.0.3-x86_64-2alien

cairo-1.14.6-x86_64-2
cairo-compat32-1.14.6-x86_64-2compat32
cairomm-1.12.0-x86_64-1
pycairo-1.10.0-x86_64-1
```
I don't have any idea, but maybe i wrong in configure options, [my.SlackBuild](https://github.com/slacknk/slackware/blob/master/slackbuilds/_games/vbam/vbam.SlackBuild) need help for solve.
And tried build 2da2d9c in VBox with slackware32-14.2, pure + upgraded, but colors doesn't correct yet.

**Comment by slacknk** [comment]
I'm tried 2.0.1 - colors ugly too... and my search from Google -maybe- desaturation ?
http://emulation.gametechwiki.com/index.php/Game_Boy_Advance_emulators#Oversaturation

**Comment by frozenMustelid** [comment]
I think I found the culprit. Try changing the emulated device from GBC (or automatic) to GBA. Reload the ROM. Look at the ugly colors. Then set the emulated device to GBC and reload the ROM. It looks good again.

I think it's only on GBA enhanced GBC games. Both Zelda Oracle games have the weird ugliness in GBA mode, but Pokemon Gold and Crystal both look fine in GBC or GBA mode.

OS: Linux Mint 18.2
Render mode: OpenGL (Simple doesn't actually run at full speed on a PC using hardware from 1 gen ago, WTF dev team)
Graphics: AMD card using proprietary drivers

**Comment by slacknk** [comment]
Hi all! Yes, I'm founded it! This is SDL=ON, If build
```
-DENABLE_SDL=ON  # Ugly_colors
-DENABLE_SDL=OFF # Best_colors
```
Tried on [v2.0.1](https://github.com/visualboyadvance-m/visualboyadvance-m/archive/v2.0.1/visualboyadvance-m-2.0.1.tar.gz) and c7c6ad6_git d5c9c6ba

**Comment by rkitover** [comment]
@slacknk that's very interesting, that option is supposed to only control whether the separate SDL port is built, I'll need to investigate how it can affect the regular wx port.

**Comment by rkitover** [comment]
@slacknk I just looked at the cmake files and it's impossible for the `ENABLE_SDL` option to affect the wx port in any way, so something else is happening.

**Comment by slacknk** [comment]
maybe in this problem: [force GBA or GBC modes](http://www.romhacking.net/forum/index.php?topic=16827.0)

**Comment by Moonkis** [comment]
I'll add to this. Colors seems to be very saturated and the color correction seems absent. Here is a comparison between two emulators (sorry if this is bad manners) as well as my real Gameboy Advance SP:
![gba comparison](https://user-images.githubusercontent.com/1334297/67242306-8a3a8800-f455-11e9-86ed-d495a3b56ccc.PNG)
![gba sp](https://user-images.githubusercontent.com/1334297/67242283-80b12000-f455-11e9-9328-ae8cc6ae9010.jpg)


My settings might be wrong but I tried Simple and OpenGL to no effect. Can't really find a lot of settings related to this. I tried the latest release and the same result.

**Comment by rkitover** [comment]
@Moonkis which rom is that, and is that a GBC rom you are running in GBA mode?

**Comment by kode54** [comment]
In GBA mode, the emulator should be using the GBA color filter, even for GBC games, since some GBC games expect a GBA display and do their own oversaturation to account for the GBA's display.

**Comment by negativeExponent** [comment]
lcd_filter (the one that is ran during utilUpdateSystemColorMapsXX) and gbColorOption is not exposed to UI, so there are no possible saturations options available.

**Comment by Moonkis** [comment]
> @Moonkis which rom is that, and is that a GBC rom you are running in GBA mode?

That is my (authentic) Fire Emblem Tactics Advance (European) GBA rom running on both emulators and my GBA SP.

How can I force another mode?

**Comment by Passingby1** [comment]
Even with the latest nightly as of Feb 04/2020 this issue is still present, no gbColorOption is available anywhere to configure, the colors are overly saturated in GBA games.

**Comment by TheCoderCell** [comment]
Hey, this can be turned off with the Options>Game Boy Advance>LCD Filter. Hope this helps!
