### ISSUE TITLE
[Bug]: complett save state is gone

### ISSUE THREAD

**Issue by frite420** [visualboyadvance-m/visualboyadvance-m#1311]
### Expected behavior?

it should have the save state of the game 

### Actual behavior?

i load the game the isnt the save state

### Steps to reproduce the problem

1.i started the emulator
2. there wasnt any recent game even tho it should
3. i load the game 
4. no save state

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title: pokemon light platinum
GB, GBC or GBA: gba
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
read the pinned issue for anything involving pokemon mods and saving or rtc

**Comment by frite420** [comment]
its not like its only for pokemon my complett progress in every game is gone its like i downloaded it
