### ISSUE TITLE
GameBoy Config Colors Won't Stick

### ISSUE THREAD

**Issue by jmc92** [visualboyadvance-m/visualboyadvance-m#132]
While playing gameboy pokemon red, after configuring the color pallette to match how it looks on a gba, it only sticks so long as you don't enter any doors. This is a problem I have noticed only since trying out vba m.

### Expected behavior
A stable color pallette that sticks throughout the game.

### Actual behavior
Color pallette reverts back to how it was before I set it, when I restart the game or go through doors.

### Steps to reproduce the behavior
Play pokemon red, test the pallettes.

### ROM details
Pokemon Red (U) [S][!]

Which games are affected by the issue (please state if GBA or GB game):
Gameboy

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
Unsure

### Option details

Video driver (simple, opengl or cairo):
OpenGL
Sound driver (directsound, xaudio, openal, SDL):
OpenAL
### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows7

Version of code (pre-built binary version, or commit ref, or just "master"):
Using latest Git commit.

Washed out pokemon red > ![pokemon red u s 01](https://user-images.githubusercontent.com/23234604/28483477-4fbb4be4-6e22-11e7-9ded-dc7d4c7e58b1.png)
How pokemon red is supposed to look, or close to it > ![pokemon red u s 02](https://user-images.githubusercontent.com/23234604/28483478-54717c94-6e22-11e7-8717-7031acf2743a.png)

**Comment by rkitover** [comment]
Try the Simple video renderer, the OpenGL renderer does not do color correction.

How did you configure the palette by the way?

**Comment by jmc92** [comment]
Simple render seems to produce the same problem. As for configuring the colors, I went to options>gameboy>configure>custom colors>user 1
Then I clicked "use this palette" and reloaded the game.
The visual boy advance beta 3 works to keep the colors somehow if that helps.

To find the pallette for this game, I have screenshots with the correct colors from a psp emulator that matches my actual cartridge. I loaded the screenshot into photoshop, color picked the different parts of the game, and found the best combination of colors to make it look as close to the original as possible.

**Comment by rkitover** [comment]
Ok, thanks for the info! I can't promise if and when someone will look, we don't really have any active devs right now unless I manage to get back to working on this project.

**Comment by jmc92** [comment]
Glad to be of help. I can understand that, and with emulators in existence that do work for it, it's not of the upmost importance on the list of bugs, but to make the emulator the best it can be, I hope someday the bugs are all worked out.

**Comment by rkitover** [comment]
@jmc92 just tried latest master on a mac, colors look different than in your screenshot:

![VBA-M Pokemon Red GBC, master](https://www.dropbox.com/s/1i3jvo5fxhlhy9e/VBA-M%20Pokemon%20Red%20GBC%20colors.png?dl=1)

I noticed there are some differences between your correct screenshot and this one, like the hair is green on the people, but at least the ground is the correct color.

I will try this on Windows as well.

**Comment by jmc92** [comment]
You are right about the green, this is closer http://i.imgur.com/wYmnUsn.png
Still, it's alot different than the washed out version vba seems to give by default.

**Comment by rkitover** [comment]
@jmc92 which drivers did you update, Nvidia, AMD or something else?
