### ISSUE TITLE
[Bug]: constant tearing with dialogue boxes in advance wars games

### ISSUE THREAD

**Issue by Manvel20** [visualboyadvance-m/visualboyadvance-m#1320]
### Expected behavior?

that there's no tearing

### Actual behavior?

there is screen tearing when I sometimes click through dialog boxes, even with v-sync. here is a youtube link with the tearing shown: https://youtu.be/93aWoeaDk-4  . 

### Steps to reproduce the problem

1. start up advance war
2. play until you reach dialogue after a mission has started

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing: advance wars 2. although I also have this bug with advance wars 1

Title:
GB, GBC or GBA: default
ROM CODE: default
BIOS Used?: default
SAVE TYPE: default
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver: simple
Sound driver : default
Scale Filter : no filter

### Specifications and Build details

VBA-M: 
x86_64

OS: (include version and OS build number using WinVer if on Windows): windows 11
CPU: 
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
This occurs on hardware
