### ISSUE TITLE
[Bug]: Keybind is run with and without modifier

### ISSUE THREAD

**Issue by leandroosfleal** [visualboyadvance-m/visualboyadvance-m#1321]
### Expected behavior?

https://github.com/user-attachments/assets/0ffb91ed-c8d0-46ac-9667-9238f5194a31

When i try to save my progress to a specific key (like f1), it auto loads to the previous save state in the mencioned key before saving. I lose my progress because of it, and i don't want to keep using only ctrl + s, the only that works.

### Actual behavior?

When i try to save my progress to a specific key (like f1), it auto loads to the previous save state in the mencioned key before saving. I lose my progress because of it, and i don't want to keep using only ctrl + s, the only that works

### Steps to reproduce the problem

1. Press shift + f1, or shift + f2
2. Then press again
3. Eventually it will trigger the bug
4.
5.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title: Radical Red 4.1
GB, GBC or GBA: GBA
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Savestate)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: (64 bit)
OS: (windows 11):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM: 8gb

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Windows (and hardware) are responsible for queued writes, not the emulator.

**Comment by Squall-Leonhart** [comment]
This is fixed in nightly
