### ISSUE TITLE
[Bug]: my real time clock feature is not working, I am playing ROM HACK Pokemon Adventure Red Chapter 

### ISSUE THREAD

**Issue by Subrat010** [visualboyadvance-m/visualboyadvance-m#1333]
### Expected behavior?

My ingame time should be synced to my pc time
![image_2024-09-09_181910382](https://github.com/user-attachments/assets/c61d4ef6-49f1-4727-9bcc-fd1199532c8d)

### Actual behavior?

nothing happened no matter how many time i tried the time is stuck to 12 pm 

### Steps to reproduce the problem

1.
2.
3.
4.
5.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
I just had another look at your screenshot, and I do see that you did follow that issue I linked to, reopened.

**Comment by Squall-Leonhart** [comment]
Follow the comment here

https://github.com/visualboyadvance-m/visualboyadvance-m/issues/579#issuecomment-1337133989
