### ISSUE TITLE
[Bug]: Key Shortcuts modifications reset after exit

### ISSUE THREAD

**Issue by Ocatopuss** [visualboyadvance-m/visualboyadvance-m#1334]
### Expected behavior?

Shortcut key modifications can be saved.

### Actual behavior?

Regardless if I add a new shortcut key directly, delete the default key(s) then add a new key, replace/add some shortcut key with another shortcut default key, or just delete the default key(s), all modified shortcuts reset on next reboot.

Joypad modifications are functioning normally.
And If I used some key(s) that occupied by default shortcut key(s) (e.g. numeric keys) as Joypad key(s), the indirectly shortcut key modification(s) won't be reset after exit.

### Steps to reproduce the problem

1.Modify some shortcut keys
2.Exit the emulator
3.Reboot the emulator
4.All modified shortcuts reset
5.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl):OpenGL
Sound driver (directsound, xaudio, openal, SDL):XAudio
Scale Filter Used?:xBRZ 3x

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)2.1.10 64bit
OS: (include version and OS build number using WinVer if on Windows):Win10 22H2 19045.4894
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Steelskin** [comment]
Thank you very much for the bug report. Could you try the latest [nightly](https://nightly.vba-m.com/) too?

**Comment by Ocatopuss** [comment]
> May be an issue with the config file, try doing `Help -> Factory Reset`.

I did consider using the Factory Reset before, after reading your suggestion I tried it and unfortunately it didn't solve the problem. Thank you for the suggestion.

**Comment by Ocatopuss** [comment]
> Thank you very much for the bug report. Could you try the latest [nightly](https://nightly.vba-m.com/) too?

Hi there, thank you for the advice. I'm using the exact version you referred to – normally I always use the latest nightly. Sorry for not being more clear before.

**Comment by Steelskin** [comment]
> > Thank you very much for the bug report. Could you try the latest [nightly](https://nightly.vba-m.com/) too?
> 
> Hi there, thank you for the advice. I'm using the exact version you referred to – normally I always use the latest nightly. Sorry for not being more clear before.

Thanks for trying. This is definitely odd. Could you do the following, please?
1. Set up your shortcuts and save by clicking "OK" in the shortcut config dialog.
2. Make a copy of your `vbam.ini` file (it's in `%LOCALAPPDATA%\visualboyadvance-m`)
3. Exit the emulator 
4. Make a second copy of your `vbam.ini`
5. Start the emulator.
6. Make a third copy of your `vbam.ini`

And upload all 3 files with your reply.

**Comment by Ocatopuss** [comment]
> > > Thank you very much for the bug report. Could you try the latest [nightly](https://nightly.vba-m.com/) too?
> > 
> > 
> > Hi there, thank you for the advice. I'm using the exact version you referred to – normally I always use the latest nightly. Sorry for not being more clear before.
> 
> Thanks for trying. This is definitely odd. Could you do the following, please?
> 
>     1. Set up your shortcuts and save by clicking "OK" in the shortcut config dialog.
> 
>     2. Make a copy of your `vbam.ini` file (it's in `%LOCALAPPDATA%\visualboyadvance-m`)
> 
>     3. Exit the emulator
> 
>     4. Make a second copy of your `vbam.ini`
> 
>     5. Start the emulator.
> 
>     6. Make a third copy of your `vbam.ini`
> 
> 
> And upload all 3 files with your reply.

[vbam.ini.zip](https://github.com/user-attachments/files/16973456/vbam.ini.zip)
It seems after reboot, the emulator somehow erased all contents under the tag “[Keyboard]” of vbam.ini.

**Comment by Steelskin** [comment]
Thank you very much for the files! I have a fix, it'll be landing shortly. In the meantime, here's a workaround. Once you have your shortcuts configured the way you want them, exit the emulator and remove the `[Keyboard/Keyboard]` line in the INI file, keeping the `[Keyboard]` line.

**Comment by Ocatopuss** [comment]
> Thank you very much for the files! I have a fix, it'll be landing shortly. In the meantime, here's a workaround. Once you have your shortcuts configured the way you want them, exit the emulator and remove the `[Keyboard/Keyboard]` line in the INI file, keeping the `[Keyboard]` line.

I suspected that it might be the “[Keyboard/Keyboard]” that's causing the problem, but I'm not sure because I'm not a professional. Thanks for your working, have a nice one.

**Comment by rkitover** [comment]
@Ocatopuss I've rebuilt the nightly and it has the fix for this, we are going to do another release.

**Comment by Ocatopuss** [comment]
> @Ocatopuss I've rebuilt the nightly and it has the fix for this, we are going to do another release.

It works. Thanks for what you have done, have a great one.
