### ISSUE TITLE
openSUSE Tumbleweed compile errors on latest branch

### ISSUE THREAD

**Issue by avindra** [visualboyadvance-m/visualboyadvance-m#134]
Besides a pile of warnings, getting errors such as:

```c++
error: no matching function for call to 'wxXmlResource::DoGetXRCID(wxString&)'
/home/abuild/rpmbuild/BUILD/visualboyadvance-m-master/src/wx/wxhead.h:113:47: 
 #define XRCCTRL(win, id, type) XRCCTRL_I(win, XRCID(id), type)
                                               ^
```

```c++
error: invalid cast from type 'wxString' to type 'const char*'
/home/abuild/rpmbuild/BUILD/visualboyadvance-m-master/src/wx/wxvbam.cpp:571:45: 
     home = strdup((const char*)wxApp::argv[0]);
                                             ^
```

```c++
error: no matching function for call to 'ToString(wxString&)'
/home/abuild/rpmbuild/BUILD/visualboyadvance-m-master/src/wx/guiinit.cpp:3217:67: 
                 wxWindow* w = SafeXRCCTRL<wxWindow>(d, ToString(pn).c_str());
                                                                   ^
```

You can see the full log from the build here: 

https://pastebin.com/u4DLqTbA

Tumbleweed is currently using gcc 7.

They also have [a note on this specific issue](https://en.opensuse.org/openSUSE:Packaging_wxWidgets):

> The openSUSE wxWidgets is built in Unicode and STL mode. This is the recommended upstream mode. If your wx-using code fails to compile, that is usually because it sucks at strings. The use of wxString::c_str and wxChar[] is an indicator of this. Talk to the upstream authors of the end-user program to rectify it.

Here is the spec file being used to compile `vbam`

https://build.opensuse.org/package/view_file/home:avindra/vbam/vbam.spec?expand=1

Here, you can see some things I tried to do to get the package to build:

https://build.opensuse.org/package/revisions/home:avindra/vbam

----

If all goes well, my goal is to have this submitted to the `Emulators` project in openSUSE ([link](https://build.opensuse.org/project/show/Emulators)), which will enable openSUSE users to easily install a pre-compiled version of vbam for openSUSE. The [current snapshot of vbam](https://build.opensuse.org/package/show/Emulators/vbam) there is 4 years old and is failing to build.

**Comment by avindra** [comment]
Quick update, seems SUSE has 

https://software.opensuse.org/package/wxWidgets-3_0-nostl

to tackle this issue. Will retry with this version of wxWidgets.

**Comment by rkitover** [comment]
This codebase does some things that are actually illegal in C++, if gcc7 is more strict about things that may have resulted in these errors.

I will try to take a look sometime soon.

**Comment by avindra** [comment]
Got rid of all of the errors regarding wxWidget strings by using the `nostl` version available at openSUSE.

These are all of the errors coming through now:

```
[  175s] I: Program causes undefined operation
[  175s]    (likely same variable used twice and post/pre incremented in the same expression).
[  175s]    e.g. x = x++; Split it in two operations.
[  175s] W: vbam sequence-point /home/abuild/rpmbuild/BUILD/visualboyadvance-m-master/src/gba/GBALink.cpp:1921
```

https://github.com/visualboyadvance-m/visualboyadvance-m/blob/783475bf39af6baf5ae512c3b6b3452b670a729f/src/gba/GBALink.cpp#L1921


and the rest:

```
I: Program returns random data in a function
E: vbam no-return-in-nonvoid-function /home/abuild/rpmbuild/BUILD/visualboyadvance-m-master/src/wx/openal.cpp:363
E: vbam no-return-in-nonvoid-function /home/abuild/rpmbuild/BUILD/visualboyadvance-m-master/src/wx/panel.cpp:1661
E: vbam no-return-in-nonvoid-function /home/abuild/rpmbuild/BUILD/visualboyadvance-m-master/src/wx/widgets/wxmisc.cpp:396

I: Program returns random data in a function
E: vbam no-return-in-nonvoid-function /home/abuild/rpmbuild/BUILD/visualboyadvance-m-master/src/wx/openal.cpp:363
E: vbam no-return-in-nonvoid-function /home/abuild/rpmbuild/BUILD/visualboyadvance-m-master/src/wx/panel.cpp:1661
E: vbam no-return-in-nonvoid-function /home/abuild/rpmbuild/BUILD/visualboyadvance-m-master/src/wx/widgets/wxmisc.cpp:396

I: File is compiled without RPM_OPT_FLAGS
W: vbam no-rpm-opt-flags <cmdline>:/home/abuild/rpmbuild/BUILD/visualboyadvance-m-master/src/wx/bin2c.c
```

**Comment by avindra** [comment]
Checking with SUSE docs to see if I can temporarily disable these checks for the build, but these do seem like things that should legitimately be fixed.

**Comment by avindra** [comment]
So I was able to get it to build for SUSE by explicitly disabling the post build checks in the meantime.

Here is a PR for potential fixes for the 2nd batch of errors:

https://github.com/visualboyadvance-m/visualboyadvance-m/pull/135#pullrequestreview-54554616

**Comment by avindra** [comment]
![vbam](https://user-images.githubusercontent.com/126848/29010195-93f92696-7af7-11e7-83fa-3478375498fb.png)


And here it Megaman Zero running on openSUSE Tumbleweed! 

Woohoo!

I'll leave it up to your discretion to close out the issue.

I think a good marker is to see if we can get it accepted into the `Emulators` project (which would only happen after I re-enable the post build checks).

**Comment by rkitover** [comment]
We definitely need to fix this anyway, since most shipped configurations are not `-nostl`, and it should compile in any configuration.

**Comment by rkitover** [comment]
An update on this, apparently I looked at this before but forgot about it.

Not a gcc-7 issue, build is fine with gcc-7 as you already noticed when using a `-nostl` wx.

Most dists build wx without `--enable-stl`, so we generally don't get reports about this, but it needs to be fixed anyway, especially if OpenSUSE defaults to `--enable-stl`. And this is likely the future direction for wx code anyway.

**Comment by avindra** [comment]
I completely agree. For opensuse I will use the nostl build of wxwidgets for now and then switch it back when the vbam code is cleaned up. From a packaging perspective that will be cleaner as well since 99% of other packages use the stl enabled build. So instead of being 16MB, the download drops to <2MB for installation since most users have wx3 programs already installed.

Id love to help with this effort if I can. If you have any docs you can point me to I can read up and try to figure it out. I tinkered with c++ a little and even wxwidgets years ago on dolphin's cheat manager.

**Comment by avindra** [comment]
https://www.wxwidgets.org/docs/faq/general/#stl

Seems reasonably straightforward. I can take a stab at it and open up a PR Unless someone else wants to grab it

**Comment by rkitover** [comment]
Sure take a look and let me know how it goes.

This is actually not completely trivial, and I remember now looking at it before and deciding not to do it then, because in many places the code expects implicit conversions between `wxChar*` and `wxString` to work. There is a lot of code using pointer arithmetic on `wxChar*` strings. While this can be solved with e.g. a copy constructor, to do it more cleanly would require rewriting the relevant code, while also trying to maintain wx 2.8 compatibility as much as possible, which means sticking mostly to the 2.8 `wxString` [api](http://docs.wxwidgets.org/2.8.12/wx_wxstring.html#wxstring).

`wxChar` I believe is a typedef to either `char` or `wchar`, depending on how wx was built (and of course our code should be independent of wx configuration.)

**Comment by rkitover** [comment]
@avindra just finished refactoring things so that Wx with `--enable-stl` works, in f5cb7b2b.

You should be able to build with the regular Wx package now.

**Comment by avindra** [comment]
And compile with the regular wx package it did:

https://build.opensuse.org/package/rdiff/home:avindra/vbam?linkrev=base&rev=41

For Tumbleweed as well as Leap 42.3 

https://build.opensuse.org/package/binaries/home:avindra/vbam?repository=openSUSE_Tumbleweed
https://build.opensuse.org/package/binaries/home:avindra/vbam?repository=openSUSE_Leap_42.3

I'm closing this issue since basically everything that came out of it is :hocho:  now

Great stuff @rkitover 

I tried with some of the wxString stuff and gave up :sweat_smile:
