### ISSUE TITLE
[Bug]: pokemon hyper emerald lost artifacts after talking to steven the screen went red

### ISSUE THREAD

**Issue by kaleom1108** [visualboyadvance-m/visualboyadvance-m#1340]
### Expected behavior?

the game should have functioned properly

### Actual behavior?

the red screen destroyed my progress

### Steps to reproduce the problem

1.i was playin the game as usual
2.after a tough gym battle i moved on to complete net task 
3.i gave the letter to steven and after talking to him in few moments the screen turned red
4.and i sadly forgot to save earlier
5.please help
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)
<removed>

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
We will not assist with rom hacks that only come as prepatched binaries.
