### ISSUE TITLE
[Bug]: Shining Soul II VC gets frozen just before the town portal (the one that comes after you defeat bosses) appears.

### ISSUE THREAD

**Issue by Ocatopuss** [visualboyadvance-m/visualboyadvance-m#1343]
### Expected behavior?

The town portal appears normally.

### Actual behavior?

The game gets frozen, any in-game actions are invalidated, only the bgm is still playing.

I didn't test all the stages but every stage I chose triggered this bug.
Only VC version has this problem, the orginal (Japanese) version is normal.
VC version runs normally on mGBA.

### Steps to reproduce the problem

1. Just defeat a boss (except the final boss) to wait the timing that the town portal is supposed to appear.
2.
3.
4.
5.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA: GBA (Virtual Console version on Wii U)
ROM CODE: AU2J
BIOS Used?: (Share crc hash) Yes (81977335)
SAVE TYPE: (Attach Battery or Savestate here)[Shining Soul II state saves.zip](https://github.com/user-attachments/files/17082913/Shining.Soul.II.state.saves.zip)
Clean, Intro'd or Hacked?:(Attach Patch here) Clean

About the state saves: including both original and VC version, just let the Dark Wizard's Dancing Dagger/Dagger Dance auto-deal with the last monster.

### What settings are you using?

Video driver (simple, opengl): Both
Sound driver (directsound, xaudio, openal, SDL): XAudio
Scale Filter Used?: xBRZ or none.

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version) 2.1.11-d5e1a1f3 64 bit
OS: (include version and OS build number using WinVer if on Windows): Win10 22H2 19045.4894
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Undefined Thumb instruction, nifty.

**Comment by Squall-Leonhart** [comment]
The instrution being used is unique to the Thumb version inside the nintendo DS and the emulated VC GBA core, it is not a defined capability of the GBA and fixing it will require us to catch and drop the opcode when its encountered as shown in [mgba](https://github.com/mgba-emu/mgba/commit/17cfee015d3d0c60128244551791d6f6b0c91fed)

**Comment by Ocatopuss** [comment]
> The instrution being used is unique to the Thumb version inside the nintendo DS and the emulated VC GBA core, it is not a defined capability of the GBA (and technically undefined in DS documentation too). Fixing it will require us to catch and drop the opcode when its encountered as shown in [mgba](https://github.com/mgba-emu/mgba/commit/17cfee015d3d0c60128244551791d6f6b0c91fed)
> 
> This VC dump will not function on GBA hardware.

So that's how it comes about...Thank you for the information.

**Comment by Squall-Leonhart** [comment]
Fixed by #1351
