### ISSUE TITLE
[Feature request]: Per-game settings for each rom & auto save type detection?

### ISSUE THREAD

**Issue by tomaccess0** [visualboyadvance-m/visualboyadvance-m#1358]
### Request box

Pokemon needs 128k save while Super Robot Wars need 64k. Haven't tried, but maybe 128k will work for all, I guess? Otherwise, really don't want to change that everytime I switch a rom. Plus, it wasn't done automatically. I have to go through all the menus each time. 
In the past, I created a seperate folder for each rom and a VBA exe with it inside, so when it loads the ini inside that folder, the settings will always be correct & seperate. Set and forget!
Now, will that be good idea to have per-game settings like some PS emu? e.g. DuckStation?

### Reason box

Convenience

### Examples

DuckStation

**Comment by ZachBacon** [comment]
It's called vba-over.ini https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/src/vba-over.ini

**Comment by tomaccess0** [comment]
OK, but I have to type the ini myself?

**Comment by tomaccess0** [comment]
> It's called vba-over.ini https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/src/vba-over.ini

OK, but I have to type(edit) the ini myself?

**Comment by Squall-Leonhart** [comment]
the automatic system works well enough, and anywhere its not working is a romhack and not our problem beyond having to hear whining about it.

**Comment by tomaccess0** [comment]
> the automatic system works well enough, and anywhere its not working is a romhack and not our problem beyond having to hear whining about it.

Yes, it may be good enough, I'm just suggesting more automation for convenience, as I see other emu has already achieved. And it's not "not working".
Thanks anyway!
