### ISSUE TITLE
[Bug]: Fire Emblem bug

### ISSUE THREAD

**Issue by JaviGare** [visualboyadvance-m/visualboyadvance-m#1359]
### Expected behavior?

It should be reproducing the game

### Actual behavior?

A black screen, without any sound

### Steps to reproduce the problem

1. Chapter 23, when you kill the boss of that chapter, story pops up
2. When story for that chapter ends, the game is supposed to load the next one
3. The game loads a black screen without any sound

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

Sorry i dont know how to do this, i dont know what is debug mode, neither how to access it 

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title: Fire Emblem (USA, Australia)
GB, GBC or GBA: GBA
ROM CODE: AE7E
BIOS Used?: (Share crc hash): (None)
SAVE TYPE: (Attach Battery or Savestate here)  
[Fire Emblem (USA, Australia)-08.zip](https://github.com/user-attachments/files/17369253/Fire.Emblem.USA.Australia.-08.zip)
Clean, Intro'd or Hacked?:(Attach Patch here) Clean

### What settings are you using?

Video driver (simple, opengl): opengl
Sound driver (directsound, xaudio, openal, SDL): xaudio
Scale Filter Used?: None? I dont know what this is

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows): Windows 11, Version 23H2, SO 22631.4317
If using Linux, specify if using xorg or Wayland:
CPU: AMD Ryzen 7 7730U
GPU: AMD Radeon Graphics
RAM: 8GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
Please include the emulator version.

**Comment by JaviGare** [comment]
VisualBoyAdvance-M 2.1.9-23e15734

**Comment by ZachBacon** [comment]
> VisualBoyAdvance-M 2.1.9-23e1573

Use a new nightly and try again https://nightly.visualboyadvance-m.org

**Comment by JaviGare** [comment]
Hi Zach, tried and is not working yet, thanks you for trying

**Comment by ZachBacon** [comment]
> Hi Zach, tried and is not working yet, but thanks you for trying 

I'll try looking at it on Thursday unless someone beats me to it.

**Comment by Squall-Leonhart** [comment]
a savestate of the black screen is pointless.

**Comment by Squall-Leonhart** [comment]
You've abused the use of save states, the game proceeds to chapter 24 just fine.
