### ISSUE TITLE
[Bug]: alleyway not work (key left, right not work)

### ISSUE THREAD

**Issue by ludo77** [visualboyadvance-m/visualboyadvance-m#1368]
### Expected behavior?

the left button had to move the sprite to the left, and the right button to the right.

### Actual behavior?

the button left and right not work.

in the emulator (mgba ) : alleyway is work fine

### Steps to reproduce the problem

1.start alleyway
2. the start button and A  work, left and right not work
3. 
4.
5.
...

### Error messages?

no message errors

### What game were you playing

title : Alleyway

### What settings are you using?

nvidia 535.183.01

### Specifications and Build details

VBA-M: version 2.1.9-67e4944c
OS: linux
If using Linux, specify if using xorg or Wayland: xorg
CPU: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
GPU:  nvidia 535.183.01 geforce gtx1650ti
RAM: 32 go

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
They all work fine.

**Comment by Steelskin** [comment]
> They all work fine, update to 2.1.11+, config you controller correctly so there are no emulated controller inputs overlapping with emulator hotkeys.

This should no longer be a problem in recent releases either, now that input handling has been unified.

**Comment by ludo77** [comment]
I install the last version, and the game not work.

**Comment by Squall-Leonhart** [comment]
![image](https://github.com/user-attachments/assets/e55af819-bcdf-41a4-8562-187e28dfe5fe)
![image](https://github.com/user-attachments/assets/2914101c-d86f-4cda-820c-72ff68d24891)

**Comment by ludo77** [comment]
under linux, not work

**Comment by ZachBacon** [comment]
Under Linux does work.

**Comment by ludo77** [comment]
not work  for me , very strange

**Comment by rkitover** [comment]
Could you please provide:

- Your Linux distribution and version.
- Whether you are using Xorg or Wayland, and if Wayland which desktop environment.
- Where you got your Linux build, did you build it yourself?
- How you configured your inputs.
- Your `~/.config/visualboyadvance-m/vbam.ini`, as Steelskin has mentioned.

Also, try going to `Help -> Factory Reset` and reconfigure your inputs and see if that helps.

Thank you.

**Comment by rkitover** [comment]
Also, can you please specify whether you are using the keyboard or a game controller.

And if you are using a game controller, which one.

Thank you.

**Comment by ludo77** [comment]
Hello,
My file: [vbam.ini.zip](https://github.com/user-attachments/files/17712442/vbam.ini.zip)
My linux distribution : debian 12 in siteweb : https://www.debian.org/index.fr.html
[vbam.ini.zip](https://github.com/user-attachments/files/17712442/vbam.ini.zip)
I use Xorg, and mate enviroment.
I configure my inputs : options>input>configure , I use a keyboard.
and if i factory reset: not work

Thank you

**Comment by rkitover** [comment]
Your config looks fine.

Where did you get your Linux binary?

Can you try this one please:

https://launchpad.net/~xtradeb/+archive/ubuntu/play/+build/29095837/+files/visualboyadvance-m_2.1.11-1xtradeb1.2404.1_amd64.deb
.

**Comment by ludo77** [comment]
I compile the code : https://github.com/visualboyadvance-m/visualboyadvance-m/archive/refs/heads/master.zip

**Comment by rkitover** [comment]
The code has been broken by US government ****s right now, can you try the deb I linked please.

**Comment by Squall-Leonhart** [comment]
Whats your keyboard layout @ludo77

**Comment by rkitover** [comment]
This is the input config from the config file he uploaded:

```console
[Joypad/1]
Up=UP
Down=DOWN
Left=LEFT
Right=RIGHT
A=Q
B=S
L=A
R=Z
Select=SPACE
Start=ENTER
```
.

**Comment by rkitover** [comment]
Are you using a French AZERTY keyboard?

**Comment by Steelskin** [comment]
I can repro. I believe this is a Debian-specific issue and I don't think it has anything to do with keyboard layout. Spinning up a debugger to figure out what is going on.

**Comment by Steelskin** [comment]
I can repro but I have no idea what is going on. The register is being fed the right value but, somehow, Alleyway keeps believing that "left" is always pressed, from what I can tell. Other software recognizes our input just fine. This is also only reproducible on Debian, which is even weirder.

**Comment by Steelskin** [comment]
I have no idea why this is not working. The values we are returning for the joypad input register at `0xff00` is correct and identical to the one we return on other platforms. From disassembly, it seems Alleyway is then storing the d-pad value to RAM at address `0xff8c` and re-reading it later.

This requires more in-depth debugging of the emulated software itself, which is really hard to do. Since this works properly on other Linux distros, it seems there is some bug somewhere else that is only being surfaced on Debian. I don't think it has anything to do with the user locale, it certainly has nothing to do with the keyboard layout as the core emulator is getting the correct input. I cannot dig any further into this issue at this time. It is my hope that when the core emulator will be refactored, it will go away but I cannot be certain of it. In the meantime. I am leaving this bug open.

**Comment by Squall-Leonhart** [comment]
@endrift can I call upon your knowledge here?

**Comment by Squall-Leonhart** [comment]
Ok, in this particular case our defaults are biting us in the ass because of a bug this game has.

We enable Printer by default, which is attached to the serial port, this game doesn't like that and will throw the paddle left on hardware.

**Comment by Steelskin** [comment]
The fundamental issue here is that the game itself is buggy and does not work properly on a real Game Boy with a Game Boy Printer attached. I think the right way to solve this would be to have a set of overrides for Game Boy, like we do for GBA, where we disable the Game Boy Printer option for this game.

@ludo77 If you disable the GB Printer option (Options -> Game Boy -> Game Boy printer), the game should work correctly.

**Comment by Steelskin** [comment]
I ended up implementing per-game overrides for Game Boy, this fixes the issue for me locally.

**Comment by ludo77** [comment]
Thanks Steelskin, 
if i disable GB printer: it's work fine
