### ISSUE TITLE
On screen garbage (full-screen mode).

### ISSUE THREAD

**Issue by Achaean** [visualboyadvance-m/visualboyadvance-m#138]
### Expected behavior
Clear  the video memory contents of windowed mode.
### Actual behavior
At the top left of the screen, remains contents of the windowed mode.
### Steps to reproduce the behavior
Going full-screen.
### ROM details

Which games are affected by the issue (please state if GBA or GB game):

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
**GBA games, randomly at ~ 25% rate.**
### Option details

Video driver (simple, opengl or cairo):
**opengl**
Sound driver (directsound, xaudio, openal, SDL):
**openal**
### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
**Debian Jessie (oldstable) x64 KDE.**
If using Linux, specify if using xorg or Wayland:
**xorg**
Version of code (pre-built binary version, or commit ref, or just "master"):
**master**
### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:
**Typical Keyboard.**

**Comment by ZachBacon** [comment]
Are you able to produce a screenshot?

**Comment by Achaean** [comment]
Yes of course! :-)
Her's a screenshot:
![vbam1](https://user-images.githubusercontent.com/3608053/29177522-84efb8c4-7df7-11e7-925f-014cde29f731.png)

**Comment by rkitover** [comment]
I'm guessing that painting the whole panel with a black brush on every size event will fix this, should be simple to do.

If you have a moment, can you try the simple video driver?

**Comment by Achaean** [comment]
Indeed! Simple driver, runs flawlessly! :-)

**Comment by rkitover** [comment]
@Achaean I hopefully fixed this in 4d7e102, can you please try master?

**Comment by Achaean** [comment]
Well...I still have the same artifact on top-left.

**Comment by rkitover** [comment]
@Achaean I'm guessing this is some weird interaction with the mesa OpenGL driver, I have not seen this behavior before so I have no way to test, but I'll try something else.

**Comment by Squall-Leonhart** [comment]
External bug
