### ISSUE TITLE
[Bug]: "Error: Can't write battery on C:/dir/dir/harvestmoon.gba" Since im adding new cheats 

### ISSUE THREAD

**Issue by alertdev** [visualboyadvance-m/visualboyadvance-m#1385]
### Expected behavior?

![image](https://github.com/user-attachments/assets/060ea947-bf2c-458c-bed8-49bb8d274c2e)

### Actual behavior?

I can't save the game **AGAIN** Since i add ne cheats

### Steps to reproduce the problem

idk

### Error messages?

Error: Can't write battery on C:/dir/dir/harvestmoon.gba

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M:64bit
OS: Windows 10 23H2 Ghost Spectre
CPU: Intel i7 gen 10
GPU: Nvidia RTX 3080
RAM: 24 GB Ram DDR 4

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Closed before

Incomplete version info
Tampered with Windows Image
Rom is clearly not the users own dump.
