### ISSUE TITLE
[Bug]: Stuttering, speed seems to not be set at 100%

### ISSUE THREAD

**Issue by grian32** [visualboyadvance-m/visualboyadvance-m#1389]
### Expected behavior?

Game stays at a stable 100% speed

### Actual behavior?

if I turn on the speed display i'll see it stutter from 95-99% to 100+%, this is noticeable when reading stuff like text in pokemon

### Steps to reproduce the problem

boot into pokemon leafgreen, get to any textbox like professor oak when you make a new save and it'll be very noticeable there

### Error messages?

not a crash bug but i do get this in the logs, not sure if it's relevant whatsoever: 
`(visualboyadvance-m:72911): Gtk-CRITICAL **: 21:22:07.779: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton`

### What game were you playing

Title: Pokemon LeafGreen
GB, GBC or GBA: GBA
ROM CODE: BPGE
BIOS Used?: (Share crc hash)  none
SAVE TYPE: (Attach Battery or Savestate here) flash 128k
Clean, Intro'd or Hacked?:(Attach Patch here) Clean

### What settings are you using?

Video driver (simple, opengl): tried both, same thing
Sound driver (directsound, xaudio, openal, SDL): openal soft
Scale Filter Used?: none
 

### Specifications and Build details

VBA-M: c6da07f
OS: PopOS 22.04 LTS/ xorg
CPU: Ryzen 5 5600g
GPU: Nvidia RTX 3050
RAM: 16GB 

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by grian32** [comment]
now it seems stuck at like 89-91, weird stuff

**Comment by Squall-Leonhart** [comment]
Configure your power management properly so your cpu isn't in battery saver.
