### ISSUE TITLE
Sound channel volumes too low after opening the audio settings and confirming them

### ISSUE THREAD

**Issue by ShadowStkr** [visualboyadvance-m/visualboyadvance-m#143]
### Actual behavior

Once I open the audio settings and press "OK" to confirm any settings (even without changing anything), the audio should be reproduced normally.

### Steps to reproduce the behavior

Certain sound channels seem to be set to a low volume when I do the action described above. I first thought this was caused by loading a savestate, but I was mistaken: only by loading a savestate of a "session" in which the audio problem happened after opening the audio settings and pressing the OK makes the problem happen. To solve, restart the emulator or load a savestate without the audio problem present.

Additionaly, if I change the audio driver while doing this the audio gets very glitchy. If I restart the emulator or load a savestate without the problem, it goes back to normal, however. SDL sound is also very garbled at all times, no matter if I opened the audio settings before or not.

### ROM details

Which games are affected by the issue: I tried it with both Harvest Moon: Friends of Mineral Town and Sonic Advance 2, both had the problem. Was going to try it with Golden Sun as well but it has a strange bug after the initial screen about which I'm going to open a separate issue later. All of them are GBA games.

### Option details

Video driver: OpenGL

Sound driver: OpenAL/SDL

### Build details

Built and tested in Arch Linux, with xorg. Commit 4d7e102e2650d9d66ac0ef49fac3869dd29df8da.

**Comment by retro-wertz** [comment]
Sound filtering was not applied before that causes this issues where some channels becomes very low in volume...

This should be fixed in latest commit.

**Comment by yommomabois** [comment]
This issue seems to still be occurring on the latest release. It could just be because I updated from a version from ~2016.

**Comment by Squall-Leonhart** [comment]
APU state wasn't restored after the sound system went through a shutdown and soundinit, this only affected GBA games on the APU channels.
