### ISSUE TITLE
Windows 10 Updated (1703 "Creator" version), VBA-M now crashes when I load a ROM

### ISSUE THREAD

**Issue by FlameNoir** [visualboyadvance-m/visualboyadvance-m#152]
### Expected behavior
ROM loads normally, as it did literally 2 days ago

### Actual behavior
Since windows 10 update, VBA-m opens fine, but upon loading a ROM crashes

### Steps to reproduce the behavior
Have Windows 10 Creator (v1703); that is the only change to my system since VBA-m was working as intended.

### Crash bugs
I would have created a symblic backtrace, but even the instructions to do so are beyond my understanding.

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
-Fire Emblem (GBA, the first one)
-Yu Gi Oh Ultimate Masters World Championship 2006

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
Both of the above ROMs worked fine with VBA-m until the windows update. I do not have access to any other ROMs. I apologize if this issue is redundant or if I've failed to provide adequate information.

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 10 Home v.1703 (creators edition)

It may be worth noting that all versions of Yu Gi Oh World Championship 2006 ROMs I have been able to find fail to load and return an error message (unsupported BI0S function) with *MOST* emulators I have tried. I started using VBA-m because it was able to run the ROm properly without issue--until now. Oddly, the same ROM runs fine on my mobile emulator (My Boy for Android). The other ROM (fire emblem) does NOT have this BI0S issue; so, since they now both cause VBA-m to crash, I suspect that this is a different problem entirely. if anyone has any advice for how to make Yu Gi Oh 2006 run on other emulators in the meantime I'd appreciate it... I really like that game and I am quite upset that Windows has f*cked with it.

**Comment by FlameNoir** [comment]
It randomly started working again today. I guess this was just Windows being weird.

**Comment by ZachBacon** [comment]
The creators update iirc caused a lot of problems for other projects too
