### ISSUE TITLE
Game slows down after awhile 

### ISSUE THREAD

**Issue by frozenMustelid** [visualboyadvance-m/visualboyadvance-m#157]
### Expected behavior
Game plays at a consistent frame rate throughout play session

### Actual behavior
After awhile, game seems to lower max framerate. System monitor does not indicate the VBAM is hogging memory or processor, and background processes continue to run as expected, but game slows down, frame rate is reduced, emulator indicates that it is not running at full speed, and audio gets choppy. In other words, VBAM acts like it's being run on insufficient hardware in all respects, except that it ran fine when I started the emulator up 30min-1hr ago (the timing varies a little bit, but it's almost always within the hour). I think the fast-forward button may speed up the slowdown, but I'm not 100% sure on that. Saving the game, exiting the program, and restarting the program fixes the issue for another 30min-1hr.

You can even save state before closing the program and load the state when you reload the ROM, and the problem will still wait the normal amount of time before slowdown starts to happen.

Once the slowdown starts, it continues to get worse if you keep playing. I haven't bothered to find out if there's an upper limit.

### Steps to reproduce the behavior
Start game. Play game for awhile. Notice slowdown. You can change ROMs in the middle of a session, as long as you don't exit the window.

### ROM details

Only tested with GBA and GBC games, though I suspect GBO will have this issue too. Tested with Metroid Zero Mission, Pokemon Gold, Pokemon Crystal, and the Zelda Oracle games.

### Option details

Video driver - OpenGL:
Sound driver - SDL:

### Build details

Operating System - Linux Mint 18.2 Cinnamon:
Display server: xorg

Version of code (pre-built binary version, or commit ref, or just "master"):
Master. This first showed up when I in a source package I downloaded from Github a few weeks ago, though a package I downloaded on the 2 days ago also has the issue.

### Hardware details:

CPU: 6th gen i5
GPU: AMD (proprietary drivers)

**Comment by rkitover** [comment]
We're planning to fix as many memory/valgrind errors as possible soon, and this may help with this problem and others like it.

**Comment by retro-wertz** [comment]
i see "slow downs" and linux...

this should be fixed in latest version...

**Comment by retro-wertz** [comment]
if you are on ubuntu variant, you should check the ppa, someone should already be making this available based on latest commit...

this one for example seems to have the latest commit even it it seems to say its v2.0.1

https://launchpad.net/~sergio-br2/+archive/ubuntu/vbam-trunk
https://launchpadlibrarian.net/377004096/vbam_2.0.1-r201807021718-459a1fb-22~ubuntu18.04.1_2.0.1-r201807031721-a8d0508-22~ubuntu18.04.1.diff.gz

**Comment by rkitover** [comment]
@frozenMustelid it looks like something is wrong with your nvidia or AMD graphics drivers, e.g. this person had a similar issue which they resolved by updating their drivers:

https://github.com/godotengine/godot/issues/16000

**Comment by frozenMustelid** [comment]
I fixed my AMD drivers. Build succeeds, problem did not reappear during a 2hr play session. I used release 2.1.0, but I applied the changes from a8d0508cf299a58b2a659d6017b049db121de8ba to src/wx/panel.cpp before building.

Thanks for all your hard work!

**Comment by retro-wertz** [comment]
The way is over... Thanks for using VBA-M

please feel free to request to reopen thread if any other related issues arises.
