### ISSUE TITLE
Directories folder values not saving

### ISSUE THREAD

**Issue by BanCrash** [visualboyadvance-m/visualboyadvance-m#159]
### Expected behavior
I set a folder for whatever option in Options -> Directories and want to save the modifications I made.

### Actual behavior
When I close the application and open it again, it's empty all the directories I setted before.

### Steps to reproduce the behavior
Open VBA-M. Go to Options -> Directories. Set a folder for whatever option you want (GBA games, Native savegames, etc). I tried with everything and no one is saved.

### Option details

Video driver (simple, opengl):
I didn't touch anything.

Sound driver (directsound, xaudio, openal, SDL):
I didn't touch anything.

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 10 with fall creators update.
If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):
Release: Oh look! a wild 2.0.1 appeared!

Thanks in advance.

**Comment by ZachBacon** [comment]
This is a duplicate, closing this as a result. But it is a confirmed bug. Please in future make sure this bug hasn't been reported before posting it by using the issue search bar.
