### ISSUE TITLE
Built VBA-M on Windows, exe gives System Error

### ISSUE THREAD

**Issue by cooperate** [visualboyadvance-m/visualboyadvance-m#161]
### Expected behavior
For the emulator to launch.
### Actual behavior
Throws these errors:
---------------------------
visualboyadvance-m.exe - System Error
---------------------------
The code execution cannot proceed because avutil-55.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------
---------------------------
visualboyadvance-m.exe - System Error
---------------------------
The code execution cannot proceed because avcodec-57.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------

---------------------------
visualboyadvance-m.exe - System Error
---------------------------
The code execution cannot proceed because avformat-57.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------
---------------------------
visualboyadvance-m.exe - System Error
---------------------------
The code execution cannot proceed because libopenal-1.dll was not found. Reinstalling the program may fix this problem. 
---------------------------
OK   
---------------------------

### Steps to reproduce the behavior
Compiled vba-m using MSYS2

### Build details

Windows 10 64 bit

### Hardware details:
980ti/6700k/16GB RAM

**Comment by ZachBacon** [comment]
Someone didn't read the readme fully. Either keep vba-m in and run it via msys2 terminal or pull the dll's from msys2's mingw directory.
