### ISSUE TITLE
Xbrz 1.5 released

### ISSUE THREAD

**Issue by LuismaSP89** [visualboyadvance-m/visualboyadvance-m#164]
Xbrz 1.5 has been released. This is not an issue, but i think Vba-m can be faster with this plugin with the latest improvements.

**Comment by ZachBacon** [comment]
Thank you for the update, but keep in mind, it's a cpu filter. It won't make anything "faster" :P

**Comment by rkitover** [comment]
Thanks for the update! I'll see if we can perhaps pull the upstream lib in as a submodule or something. Right now it's hardcoded.

**Comment by rkitover** [comment]
So I finally got around to trying this.

I got the xbrz 1.6 release and modified some things to make it run.

There's some kind of diagonal line through the middle and it looks terrible.

Don't know if it's related to not having support for the pitch parameters anymore.

It's in the xbrz1.6 branch if you want to look.

**Comment by LuismaSP89** [comment]
@rkitover Sorry, but I don't know how to compile it in order to test.

Btw, other emulators use the actual xbrz 1.6 and all works ok, so maybe there's some other problem with the xbrz implementation in vba-m to show that diagonal line?

**Comment by rkitover** [comment]
It's probably because there's no support for pitch, whatever that is.
