### ISSUE TITLE
directories always blank everytime i open it (mac)

### ISSUE THREAD

**Issue by quack0709** [visualboyadvance-m/visualboyadvance-m#165]
i feel like i need to tell this first cause i dont know the best way to explain it. So, i download vba-m 2.0.1. Then i want to costumize where the app put my save file. (Option -> directories...->tell where my save folder -> ok). It work great but everytime i close it, then open it again, the directories is not saved, i need to do it again

### Expected behavior
Directories is saved. I dont have to tell where is mu save folder everytime i open the application

### Actual behavior
Directories isnt saved. everytime i open the app, it is blank

### Steps to reproduce the behavior
close the application

### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details
GBA game. Everygame i think though i only try in metroid fusion and the sims bustin out

Which games are affected by the issue (please state if GBA or GB game):

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details
Macos High Sierra 10.13
Operating System (Windows, Mac, Linux (state distribution), etc.):

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

![always blank everytime i open](https://user-images.githubusercontent.com/33302679/32306443-d21dfb9a-bfad-11e7-8017-b0d2e51e5908.png)

**Comment by ZachBacon** [comment]
same issues as #153 please in future search for open issues before opening a new one.
