### ISSUE TITLE
2.0.1 fails to load gba bios

### ISSUE THREAD

**Issue by RealRexen** [visualboyadvance-m/visualboyadvance-m#168]
In the 2.0.1 version VBA-M seems to have trouble loading the gba bios on 2.0.1 but when I use the last pre-released 64-bit it works just fine, whats even odd is if you reopen 2.0.1 the path to the bios disappears in the options. 
Current OS is Windows 10 Home 64-bit build 17046.1000 (insider build)

**Comment by ZachBacon** [comment]
Duplicate of #153

**Comment by ZachBacon** [comment]
Please, please, it's important you make an effort to search to see if the issue has been reported or not before opening a new one.
