### ISSUE TITLE
My harvest Moon has no sound

### ISSUE THREAD

**Issue by oyoumino** [visualboyadvance-m/visualboyadvance-m#169]
### Expected behavior
When I open the game, it should be sound and music
### Actual behavior
no sound or music is playing while is game is working well
### Steps to reproduce the behavior
Changed different audio settings, and reopened the game, still no sound
### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
Harvest Moon (friends of mineral town); golden sun (lost ages)
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Mac

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by oyoumino** [comment]
I tried all possible ways to bring in the sound, it still does not have sound. I tried the same game on a different emulator, it had sound (but it had other bugs). It will be great if I can have sound for my harvest moon (minernal town game) thanks!

**Comment by rkitover** [comment]
You used 2.01 from the releases page here? Sound should work fine in that mac build for GBA in general.

**Comment by Squall-Leonhart** [comment]
Stale
