### ISSUE TITLE
Fire Emblem: The Binding Blade translation non-working

### ISSUE THREAD

**Issue by xensyria** [visualboyadvance-m/visualboyadvance-m#182]
### Expected behavior
Display of dialogue in intro, presence of cursor and response to button presses during gameplay.

### Actual behavior
When starting a new game, all dialogue boxes appear briefly and then are automatically skipped without showing any text. When reaching the game itself, the cursor isn't present, and buttons don't do anything.

### Steps to reproduce the behavior
Load the game below, start a new game (the menu should work fine, unless you have a saved game).

### ROM details
Which games are affected by the issue (please state if GBA or GB game):
Fire Emblem: The Binding Blade [English translation 1.0 by Gringe, 2013](http://www.romhacking.net/translations/2511/) autopatched.

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
Fire Emblem - Fuuin no Tsurugi (Japan) base ROM (CRC32: d38763e1)

### Option details

Video driver (simple, opengl): OpenGL (also Simple)

Sound driver (directsound, xaudio, openal, SDL): OpenAL

### Build details

VisualBoyAdvance-M 2.0.0-beta-3 installed with aptitude via ppa:sergio-br2/vbam-trunk repo running on Linux Mint 17.3 Cinnamon x64

**Comment by orbea** [comment]
Does it work without the patch?

**Comment by xensyria** [comment]
Yes, perfectly!

**Comment by retro-wertz** [comment]
probably a bad .ips (or whatever the patch you are using) or something? game works fine at least for latest commits. can you retest with latest version?

![screenshot_2018-06-07_12-50-22](https://user-images.githubusercontent.com/23315382/41078792-68acb260-6a51-11e8-800e-44a42c83d950.png)

**Comment by retro-wertz** [comment]
PR sent. this should be fixed in next release of you can compile vba-m yourself atm.

![screenshot_2018-06-07_12-50-22](https://user-images.githubusercontent.com/23315382/41411136-573b244a-700e-11e8-9455-068c7a3dd373.png)

**Comment by retro-wertz** [comment]
this should be already fixed in latest commit....
