### ISSUE TITLE
release binaries are 64bit....

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [visualboyadvance-m/visualboyadvance-m#184]
### Expected behavior
to run on a 32bit machine

### Actual behavior
executables are 64bit :)

### Steps to reproduce the behavior
run the app on 32bit system :)
### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game):

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by ZachBacon** [comment]
Simple fact. For the most part the majority of people have 64bit machines, I rather support the majority than the minority.  But if it's that much of a need. I'll support 32bit for one more year after that it'll only be 64bit.

**Comment by MyTDT-Mysoft** [comment]
but, the emulator have absolutely no need to be 64bit also... since that is windows... having it 32bit means it works both on 32 and 64... without needing anything different unlike linux.... so there's no reason to make it be 64bit on windows

**Comment by ZachBacon** [comment]
Except the fact that you can leverage more memory on Windows on 64bit among a host of benefits of being 64bit.  Almost every modern computer bought and sold are now 64bit.

**Comment by MyTDT-Mysoft** [comment]
even if that is "half true" because there's PAE, and because a 32bit OS can still have 64bit VMs if there would ever need some 64bit IMPORTANT program, (as that is not really necessary for most things)... VBA-M no matter how you think wont ever get close of REQUIRING 64bit for anything.... if it was for a hypothetical speed gain... then it's worthless because it's emulating something so slow... that if you require more power is because the emulator itself is being slow.... and for the machines that such speed would be benefical would now become impossible... because those would probabily be running a faster... and 32bit OS, and so on.... so all in all... nothing applies to VBA-M ... so not doing 32bit would just be silly with all respect...

**Comment by ZachBacon** [comment]
Again I stand by my decision

**Comment by ZachBacon** [comment]
I'll do a 32bit binary and if the need is still there I'll continue it, however if the opposite is true, it'll die
