### ISSUE TITLE
How to Detele VBA-M Config files?

### ISSUE THREAD

**Issue by fefe7198** [visualboyadvance-m/visualboyadvance-m#188]
okay so i changed some options that i didn't want and i wanted to know how to reset the emulator to its default options

**Comment by ZachBacon** [comment]
So we have an issue template for a reason. If you aren't going to use it. We can't help you much. We need to know what operating system you're using to start off with.

**Comment by fefe7198** [comment]
i don't even know how to use that "template" you're talking about though. and im using a windows 10 32 bits

**Comment by ZachBacon** [comment]
The template has spots under the questions it asks that you just write under (the applicable ones anyways, it's straightforward easy.)
Anyways in your file manager type in the location bar %appdata%/ and look for the folder vba-m

**Comment by fefe7198** [comment]
Ah! i see thank you. and il try to use this template if any more issues come up. (closing this issue right now)

**Comment by ZachBacon** [comment]
This weekend I'll post a new binary for vba-m 32bit and also. Try and see about keeping vbam.ini by the executable to keep settings saved in a portable manner for easier managing.
