### ISSUE TITLE
Not a valid ROM file

### ISSUE THREAD

**Issue by Anthomedal** [visualboyadvance-m/visualboyadvance-m#190]
### Expected behavior

Play with visualboyadvance-m

### Actual behavior

Visualboyadvance-m runs but can't open any rom.

### Steps to reproduce the behavior

All paramaters are default parameters. I just did File > Open > Pokemon.zip > confirm and that doesn't work, I have 2 error messages.

### Message 1

Cannot open file /home/anthony/Documents/Emulateurs/GameBoyAdvance/Jeux/Pokemon - Version Emeraude (France).zip:  wrong file type

### Message 2

/home/anthony/Documents/Emulateurs/GameBoyAdvance/Jeux/Pokemon - Version Emeraude (France).zip is not a valid ROM file

### ROM details

All my games failed. 

### Option details

Default

### My computer details (inxi -Fx)

System:    Host: debian Kernel: 4.14.0-3-amd64 x86_64 bits: 64 gcc: 7.2.0
           Desktop: Xfce 4.12.4 (Gtk 2.24.31)
           Distro: Debian GNU/Linux buster/sid
Machine:   Device: laptop System: Dell product: Inspiron 15-3567 serial: 6JJPSJ2
           Mobo: Dell model: 05269N v: A00 serial: /6JJPSJ2/CNWSC007A7000B/
           UEFI: Dell v: 1.9.0 date: 07/10/2017
CPU:       Dual core Intel Core i5-7200U (-MT-MCP-) 
           arch: Kaby Lake rev.9 cache: 3072 KB
           flags: (lm nx sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx) bmips: 10848
           clock speeds: max: 3100 MHz 1: 1908 MHz 2: 2200 MHz 3: 2200 MHz
           4: 2200 MHz
Graphics:  Card: Intel HD Graphics 620 bus-ID: 00:02.0
           Display Server: x11 (X.Org 1.19.5 )
           drivers: modesetting (unloaded: fbdev,vesa)
           Resolution: 1366x768@60.00hz
           OpenGL: renderer: Mesa DRI Intel HD Graphics 620 (Kaby Lake GT2)
           version: 4.5 Mesa 17.3.3 Direct Render: Yes
Audio:     Card Intel Sunrise Point-LP HD Audio
           driver: snd_hda_intel bus-ID: 00:1f.3
           Sound: Advanced Linux Sound Architecture v: k4.14.0-3-amd64
Network:   Card-1: Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter
           driver: ath10k_pci bus-ID: 01:00.0
           IF: wlp1s0 state: down mac: be:23:08:b1:41:c5
           Card-2: Realtek RTL8101/2/6E PCIE Fast/Gigabit Ethernet controller
           driver: r8169 v: 2.3LK-NAPI port: e000 bus-ID: 02:00.0
           IF: enp2s0 state: up speed: 100 Mbps duplex: full
           mac: 58:8a:5a:01:68:cb
           Card-3: Atheros usb-ID: 001-005
           IF: null-if-id state: N/A speed: N/A duplex: N/A mac: N/A
Drives:    HDD Total Size: 1000.2GB (2.8% used)
           ID-1: /dev/sda model: TOSHIBA_MQ01ABD1 size: 1000.2GB temp: 31C
Partition: ID-1: / size: 908G used: 19G (3%) fs: ext4 dev: /dev/sda2
           ID-2: swap-1 size: 8.45GB used: 0.00GB (0%)
           fs: swap dev: /dev/sda3
Sensors:   System Temperatures: cpu: 38.0C mobo: N/A
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 162 Uptime: 20 min Memory: 1518.0/7850.1MB
           Init: systemd runlevel: 5 Gcc sys: 7.3.0
           Client: Shell (bash 4.4.121) inxi: 2.3.56 

### Note 

I was on ubuntu 17.04 and on this system I had no any problem with this software and with same roms.

**Comment by ZachBacon** [comment]
Unzip and tell me what the file extension of the room also please report the version of vba-m you're using, that's very important

**Comment by Anthomedal** [comment]
I'm very very sorry, when i tried to unzip my game i saw that all my games was corrupted by my transfer between computers... visualboyadvance-m works, that was my games. Thank you !

**Comment by ZachBacon** [comment]
No worries stuff happens
