### ISSUE TITLE
vba-m.com requires signing in/where can I get old builds?

### ISSUE THREAD

**Issue by Nicholas-Steel** [visualboyadvance-m/visualboyadvance-m#192]
I can't view the vba-m website nor the downloads section. Originally it let me view the news page but when I went to the forum it showed a 404 Page Not Found error. I decided to Log In and now every single page on the website insists I change my password, even if I log out.

I've lost the ability to access downloads for the v1229 MFC release or whatever it was before v2.x. I want to downgrade for a couple reasons, 1) bugs in the current release and 2) Lack of Fullscreen Exclusive display mode support.

I expect it may be a long while before both the issues and the feature request to be done, hence the desire to downgrade in the interim (yes I know not to make feature requests, the lack of a previously existing feature is just being used as an example and I did make it appear to be a passive feature request I guess).

**Comment by ZachBacon** [comment]
at the moment sf.net has the old builds (we'll keep the project available there for historic purposes) and more recent ones being https://github.com/visualboyadvance-m/visualboyadvance-m/releases

**Comment by Nicholas-Steel** [comment]
It'd be nice if you could put the 1229 MFC release here on GITHub if you do dismantle the Sourceforge site. It's still a pretty nice version of the emulator.

**Comment by ZachBacon** [comment]
I'd rather not because mfc is utter shit. But that's personal feelings. We are invested in getting the new UI as good as the old one. For now the old resource will remain at SF.net and will remain for the foreseeable future.

**Comment by Squall-Leonhart** [comment]
Stale
