### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by MrMagolor** [visualboyadvance-m/visualboyadvance-m#193]
### Expected behavior
A relatively simple install, similar to the old VBA
### Actual behavior
Nowhere to see how to actually install the emulator, nor any guides for this version
### Steps to reproduce the behavior
Be an idiot, like me
### Crash bugs
None
If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
All of them, I guess.
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
None of them, I guess.
### Option details

Video driver (simple, opengl):
opengl
Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 10
If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):
master
### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by MrMagolor** [comment]
There was no exe though.

**Comment by ZachBacon** [comment]
Except there is if you selected the right one.

**Comment by ZachBacon** [comment]
https://github.com/visualboyadvance-m/visualboyadvance-m/releases/download/v2.0.1/vbam-2.0.1.7z

**Comment by MrMagolor** [comment]
I copied the "master" file, that's what I assumed to do since there was no other instruction to do otherwise.

**Comment by ZachBacon** [comment]
There's a release tab, all builds we do go there...

**Comment by MrMagolor** [comment]
Regardless, thanks for the download
