### ISSUE TITLE
Multiple issues with saving and xbox one gamepad and random lag

### ISSUE THREAD

**Issue by kael070** [visualboyadvance-m/visualboyadvance-m#194]
### Expected behavior
1)I tell the emu to keep the saves and savestates in a folder
2)Configuring a xbox one controller with 1 movement
3)The emulator should run at max fps constantly
### Actual behavior
1)When I tell the emu where i want my saves and savestates to be, after closing it just forgets everything and keeps saving in the same folder the rom is
2)The emulator recognizes 2 movements instead of one, causing a down forward up input to be a down x2 forward x2 up x2
3) After a few minutes there is a random lag, and there is no real source, looked at hard drive, gpu and cpu and none show a spike
### Steps to reproduce the behavior
1)Select another save location for saves and savestates, press ok then close the emu, when opened it forgot where the folders were
2)Try configuring a xbox one controller (the bluetooth one if it matters) and move the joysticks fully in one direction, it will produce 2 bindings instead of one
3)Play for some time, and a random stutter occurs
### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
All games I tested have the same problem, seems to be a emu problem
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

### Option details

Video driver (simple, opengl):
Opengl
Sound driver (directsound, xaudio, openal, SDL):
The one that comes by default
### Build details
Latest github build as of 11-02-2018
Operating System (Windows, Mac, Linux (state distribution), etc.):
Winows 10 Single language
If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:
Xbox One Controller with Bluetooth

I used a 2013 build for a long time and it still works without any of these issues, will keep using that one for now

**Comment by retro-wertz** [comment]
a lot things has been updated since then.. please test with latest version.
