### ISSUE TITLE
GB/GBC Emulator Infrared Sensor Support 

### ISSUE THREAD

**Issue by zero35** [visualboyadvance-m/visualboyadvance-m#195]
yes some cartridges use GB/GBC infrared for linking,like these games：
Bomberman MAX Blue Champion
Bomberman MAX Red Challenger
Harry Potter & the Chamber of Secrets
Mary-Kate and Ashley: Pocket Planner
Mission Impossible (thanks SparTonberry)
Super Mario Bros DX (combine your high score table with a friend's)
Pokemon Gold/Silver/Crystal (get mystery gifts)
Pokemon TCG (thanks Nionel)
Robopon (technically doesn't - it has its own infrared sensor built into the cart)
Xena: Warrior Princess (supposedly, but I can't find more details online)
so the VBA-M are plan to support it？

**Comment by ZachBacon** [comment]
At the moment, most likely not at the moment, we are kinda focusing on fixing the current issues, however once we do finish that, chances are we'll look at implementing it, so it's not an outright rejection, just the idea will be on hold until the immediate bug fixes for the GUI are complete.

**Comment by Squall-Leonhart** [comment]
Duplicate https://github.com/visualboyadvance-m/visualboyadvance-m/issues/133
