### ISSUE TITLE
Downloaded wrong?

### ISSUE THREAD

**Issue by Kynan-12** [visualboyadvance-m/visualboyadvance-m#198]
### Expected behavior
Downloading a series of files
### Actual behavior
Downloaded as notepad
### Steps to reproduce the behavior
Idk

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows

Version of code (pre-built binary version, or commit ref, or just "master"):
https://github.com/visualboyadvance-m/visualboyadvance-m/releases/download/c7c6ad6/visualboyadvance-m-64bit-c7c6ad6.7z

**Comment by ZachBacon** [comment]
Issue is on your end.
