### ISSUE TITLE
Minor UI problem: the version was not update.

### ISSUE THREAD

**Issue by ofernandofilo** [visualboyadvance-m/visualboyadvance-m#205]
I downloaded the 64 bit version of:

 https://github.com/visualboyadvance-m/visualboyadvance-m/releases/tag/v2.0.2

and the user interface doesn't show "2.0.2" version, but "2.0.1".

https://kek.gg/i/4smXHh.png

cheers

**Comment by ZachBacon** [comment]
Issue known, it's an issue with me and doing my changelog, the cmake script reads my changelog and tries to set the version that way.
