### ISSUE TITLE
Audio Keeps on Hanging

### ISSUE THREAD

**Issue by Grip555** [visualboyadvance-m/visualboyadvance-m#210]
### Expected behavior
Audio should play in-game like normal

### Actual behavior
Game audio keeps on hanging (Freezing) randomly, even though the game still plays fine. I can't get rid of the audio hanging even when I enter a building or go to a new area.

### Steps to reproduce the behavior
Play the game for about 10 mins.

### ROM details
Pokémon FireRed U/E

Which games are affected by the issue:
GBA

Video driver:
Open GL

Sound driver:
XAudio2

### Build:
2.0.1

Operating System:
Windows 10

Version of code:
Master

### Hardware details:
16GB RAM
GeForce GTX 1070
3.50 GHz

**Comment by rkitover** [comment]
Please try the SDL sound driver and see if there's any improvement.

**Comment by Grip555** [comment]
No sound comes out at all with SDL.

**Comment by eden881** [comment]
SDL is broken completely for me too, but DirectSound works well.

**Comment by Mokai0** [comment]
Try going to Options -> Audio -> Configure...
Advanced -> DirectSound ->(in dropdown) Speakers
in my case this was "Speakers (Realtek High Definition Audio)"
Hope this helps!

**Comment by rkitover** [comment]
FWIW I fixed SDL sound on windows in master.

**Comment by Squall-Leonhart** [comment]
Stale
