### ISSUE TITLE
Turbo buttons speed adjust [feature]

### ISSUE THREAD

**Issue by Cibomatto2002** [visualboyadvance-m/visualboyadvance-m#212]
Is there a way to adjust the turbo buttons to make them slower or faster? In the game Meta Slug Advance it's to fast so it will not shoot with the turbo button.

I'm using  VisualboyAdvance-M 2.0.2

**Comment by rkitover** [comment]
You could try using a throttle setting in the general preferences instead, we could add a custom throttle button option maybe.

**Comment by Cibomatto2002** [comment]
I tried that all it did was slow down the game. A custom throttle butt option was be great. :) Fceux was a good way of doing it. 
![1](https://user-images.githubusercontent.com/21169038/37930511-96ae699c-3108-11e8-8e89-b7af5aff7694.jpg)

**Comment by Cibomatto2002** [comment]
That's true but it does not fix my problem with Meta Slug Advance.

**Comment by retro-wertz** [comment]
I see AutofireThrottle from vbam.cfg, currently defaults at 1. Increasing this also increases the time between turbo pulse.

@rkitover this should be enough if this can be added to menu options as a Turbo delay option.

**Comment by rkitover** [comment]
moving related discussion to #404
