### ISSUE TITLE
availability of skins?

### ISSUE THREAD

**Issue by SandboxProgramming** [visualboyadvance-m/visualboyadvance-m#216]
Am I just missing the option, or does this build lack skins like the original VBA?

**Comment by rkitover** [comment]
No the current front end does not have any built in theming functionality.

**Comment by SandboxProgramming** [comment]
Thanks for letting me know!

**Comment by fab1o** [comment]
Would you mind pointing out what the latest version with skins support is, and the link I could download it from?

**Comment by fab1o** [comment]
Would you mind pointing out what the latest version with skins support is, and the link I could download it from please?

**Comment by ZachBacon** [comment]
We don't support skins period. The version that did is old and isn't supported anymore.

**Comment by fab1o** [comment]
Gotcha. What was the reason behind it? Is there a known workround?

**Comment by fab1o** [comment]
Gotcha. What was the reason behind it?

**Comment by rkitover** [comment]
We should probably consider implementing something like this, I don't know what sort of theming support wxWidgets has available, but I will look.

For what it's worth, on Linux you can use GTK themes.

**Comment by ZachBacon** [comment]
@rkitover I think he's looking for super game boy themes, stuff that is usually done through a special SNES cartridge.
