### ISSUE TITLE
RTC read failure 

### ISSUE THREAD

**Issue by jbs1** [visualboyadvance-m/visualboyadvance-m#221]
### Expected behavior
Load savegame without error

### Actual behavior
I have the following setup of folders:
dropbox
-->game
---->crystal.gbc
-->save
---->crystal.sav
---->crystal.rtc

If i load the game in that setup and then import the battery file (crystal.sav) form the save folder it shows an error: "Failed to load RTC from save game <.sav-path>" and it will not load the game which means ingame i only have a "new game option".

What is interesting, if i delete the .rtc file on battery file import it will show the exact same error.
However this time it will actually load the file and i can press "Continue" form the ingame menu.
When it attempts to write to battery file it will not write to the .sav in the save folder as it should,
but it will create a new .sav in the game folder next to the .gbc file and write to that one.

On a sitenote:
The .sav and .rtc are created by the "John GBC Lite" emulator for android.

### Steps to reproduce the behavior
see above

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
US version pokemon crystal gbc

### Option details

Video driver (simple, opengl):
opengl
Sound driver (directsound, xaudio, openal, SDL):
directsound because sdl is broken for some reason
### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Win 7 64bit

Version of code (pre-built binary version, or commit ref, or just "master"):
prebuilt 2.0.2 64bit

### Hardware details:
Geforce GTX1060
16gb ram
i5-6500

**Comment by retro-wertz** [comment]
to make my reply as short as it can be, the save files are incompatible. the (whatever emulator name here) you used has .sav and .rtc while vbam handles sram and rtc data in the same .sav file. the new sav file is also created on the same folder of the rom which mean you have not configures vbam's native saves option.
