### ISSUE TITLE
Game freezes when you talk to a Rhydon statue in Pokemon Flora Sky

### ISSUE THREAD

**Issue by RithvikKasarla** [visualboyadvance-m/visualboyadvance-m#222]
### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game):

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by ZachBacon** [comment]
Can I ask why you closed this? Because if it's still an issue, we need to keep it open.

**Comment by RithvikKasarla** [comment]
I think it

**Comment by arnavb** [comment]
@RithvikKasarla Are you sure this is a problem with the emulator and not with the ROM hack itself?(many have bugs)

**Comment by retro-wertz** [comment]
can you provide savestate file?

**Comment by Squall-Leonhart** [comment]
closing this because of lack of followup
