### ISSUE TITLE
Mario tennis and Mario Golf not working

### ISSUE THREAD

**Issue by 5kyl4rk** [visualboyadvance-m/visualboyadvance-m#223]
### Expected behavior
Game to be playable
### Actual behavior
Title screen works but after that the game bugs out (Characters won't appear/ invisible, black screen with no dialogue)
### Steps to reproduce the behavior
at first I thought it was a bad ROM so I used a different one, but got the same results.  I tried the same ROM instead on an old GBA emulator on my Android, and it works perfectly fine which leads me to think it the emulator that's causing the problem, not the ROM.
### ROM details

Which games are affected by the issue (please state if GBA or GB game):
GBA Mario Tennis: Power Tour (U) and Mario Golf: Advance Tour (U)
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows VBA-M 2.0.2 64bit

**Comment by RitaPena** [comment]
Yeah its a bug that's apparently happening in all Camelot Games. See [here](https://github.com/visualboyadvance-m/visualboyadvance-m/issues/144)

**Comment by retro-wertz** [comment]
issue is related to this https://github.com/visualboyadvance-m/visualboyadvance-m/issues/238

fixed in latest commit
