### ISSUE TITLE
Find Cheat does not work for Game Boy

### ISSUE THREAD

**Issue by Cibomatto2002** [visualboyadvance-m/visualboyadvance-m#224]
### Expected behavior
Find cheats
### Actual behavior
Does not find Cheats
### Steps to reproduce the behavior
Play a Gameboy Game try to make a cheat with the find cheat
### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
All Gameboy games
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
GBA, GBC Games
### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details
VisualboyAdvance-M 2.0.2
Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 10 
If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):
master
### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by retro-wertz** [comment]
I am not sure how you are using the search cheats function.. but i am able to manually add some using this on Shantae making available lives to 99

@Cibomatto2002 Please add more details regarding this issue...

**Comment by Cibomatto2002** [comment]
It's when you use Find cheats you can't make any cheats try the game Metroid 2.

**Comment by retro-wertz** [comment]
its not that the search engine does not work. its that games stores variables at different ways and locations in memory. Metroid 2 saves Health in hexadecimal format for example:

![final](https://user-images.githubusercontent.com/23315382/43671550-b474ef82-97ce-11e8-859e-fef5eecd1b30.png)

since the health value is located in $D051 the actual or final value is located somewhere else since this memory portion supports bank switching, in this case its on 07:D051 from my experiment.

this is the gameshark code based from the search above
99-Energy
979951D0

(the first 2-digits is the bank#. so a 95 first 2 digits specifies you are updating value in bank 5)

**Comment by retro-wertz** [comment]
Update. test above was done in GBC mode. its easier in GB mode since there is no bank switching 
![bw](https://user-images.githubusercontent.com/23315382/43671771-a7953ade-97d2-11e8-9a79-2d9c192b1f72.png)

**Comment by Cibomatto2002** [comment]
I understand now sorry about that I'm used to making NES codes The first code I was trying to make in Metroid 2 was Infinite Missles and found out it was 2 codes to make it work not just one. 972353D0
972386D0.  Thanks for helping me.

**Comment by Cibomatto2002** [comment]
I don't see a way to do a random search like when looking for Energy bars is that something that will be added?

**Comment by retro-wertz** [comment]
Inifinite missile is on bank#7 of D053, so GS code is:

979953D0 = Infinite Missile
(97) = address bank or page #, (its also bank7 same as health)
(99) = value you want
(53D0) = address of value to change, (shown is change value in address
$D053)
