### ISSUE TITLE
vba-m v2.0.2 win-32bit launching issue

### ISSUE THREAD

**Issue by cyberdyne-sys** [visualboyadvance-m/visualboyadvance-m#225]
### Expected behavior

Starting the application smoothly, without any problems.

### Actual behavior

I don't know, whether anyone else experienced this, or not, but when i try to double-click on the binary, simply nothing happens. Though, i can see the process in the task manager for a couple of seconds, it just terminates shortly, without any error messages (werfault.exe starts almost immediatelly, right after the program starting attempt and disappears, with the vba-m process).
Tried to run it with or w/o admin privileges and/or compatibility modes, but no fun. Results are also the same, regardless i put an earlier config file - for v2.0.0 - next to the binary, or not. In the second case, a new cfg was created in the appropriate appdata folder, just like normally.
_Note:_ 32bit version of v2.0.0 works like a charm on the same environment, with the same system configurations.

### Build details

Operating System: Windows 7 32bit / Windows XP SP3 32bit
Version of code (pre-built binary version): v2.0.2

**Comment by Mondranex** [comment]
I have the exact same problem.

**Comment by ChaosZeroX** [comment]
I'm experiencing the same issues @cyberdyne-sys and @Mondranex are having.  I've tried four different computers so far and all of them will not load the 32-bit version of vba-m 2.0.2.  The 64-bit version will launch and function as expected on 64-bit OS installs.

Devices tested:
Windows 10 Home ver 1803 - 32-bit (Dell Venue 8 Pro)
Windows 10 Pro ver 1803 64-bit 
Windows 10 Home ver 1803 64-bit
Windows 7 Enterprise SP1 64-bit

Normally, I'd stick with the 64-bit version, but my Dell Venue 8 Pro is running a 32-bit OS.  I know I could install a 64-bit OS on this device and start from scratch but it'd be a waste as it only has 2GB RAM soldered on.

Thanks!

**Comment by cyberdyne-sys** [comment]
This problem seems to be fixed entirely in v2.1.0, thank you for it. In addition, a major graphical bug, where games, like NFSU2 appeared only as a bunch of colored artifacts, also gone.

- I'm closing this report, because the bug is fixed now -
