### ISSUE TITLE
Codebreaker Codes don't work

### ISSUE THREAD

**Issue by adiktus** [visualboyadvance-m/visualboyadvance-m#226]
### Expected behavior
Codebreaker codes work

### Actual behavior
Displays cba codes are for a different game

### Steps to reproduce the behavior
input any cba code for a game

### ROM details
Medabots Metabee/Rokusho
Megaman Battle Network

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 10

Version of code (pre-built binary version, or commit ref, or just "master"):
Latest in releases page (2.0.2) although actual program says it's 2.0.1
A 4/21/2018 build from emucr.com

Note:
If the CBA code is converted into ARv1/2 via ARCrypt, then it works when inputted as Gameshark Advance code

**Comment by KatherineFtw** [comment]
Same issue. Link to ARv1/2? I just want my cheats.

**Comment by adiktus** [comment]
DL ARCrypt. Copy the codes into the left window and select codebreaker in the option below. Convert it into ARv1/2
