### ISSUE TITLE
WXGTK20 Unknown CMake command "PKG_CHECK_MODULES"

### ISSUE THREAD

**Issue by noabody** [visualboyadvance-m/visualboyadvance-m#227]
### Please fill out this form:
```
mkdir build && cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr ..
```
Runs fine the first time but any attempt to reconfigure the WX GTK2.0 version generates error.
```
CMake Error at src/wx/CMakeLists.txt:326 (PKG_CHECK_MODULES):
  Unknown CMake command "PKG_CHECK_MODULES".
```
### Expected behavior
No error on reconfigure.
### Actual behavior
Error as noted.
### Steps to reproduce the behavior
Any attempt to run "cmake .." in existing "build" folder
### Crash bugs
N/A
### ROM details
N/A
### Option details
N/A
### Build details
Ubuntu Artful 17.10 using xorg and branch master.
### Hardware details:
N/A
### non-working /src/wx/CMakeLists.txt
```
        IF(WX_USING_GTK2)
            # try to use pkg-config to find gtk2 first
            PKG_CHECK_MODULES(GTK2 REQUIRED gtk+-2.0)
```
### working /src/wx/CMakeLists.txt
```
        IF(WX_USING_GTK2)
            # try to use pkg-config to find gtk2 first
            FIND_PACKAGE(PkgConfig REQUIRED)
            PKG_CHECK_MODULES(GTK2 REQUIRED gtk+-2.0)
```

Works after adding that "FIND_PACKAGE(PkgConfig REQUIRED)" before "PKG_CHECK_MODULES(GTK2 REQUIRED gtk+-2.0)".

**Comment by rkitover** [comment]
Fixed in master, thanks!
