### ISSUE TITLE
Mario Golf: Advance Tour is broken

### ISSUE THREAD

**Issue by KatherineFtw** [visualboyadvance-m/visualboyadvance-m#228]
### Expected behavior
It runs as expected.
### Actual behavior
Graphical glitches everywhere, buttons lag, text boxes take 2 min at 1000% speed to appear, ETC.
### Steps to reproduce the behavior
Start the game.
### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
GBA
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

### Option details

Video driver (simple, opengl):
OpenGL
Sound driver (directsound, xaudio, openal, SDL):
Defult
### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 10
If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):
Master Release - Most Resent (2.0.1)
### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by RitaPena** [comment]
Try a previous version of vba-m, for example the one available at sourceforge. There's a bug in all Camelot titles in the more recent builds (see [#144](https://github.com/visualboyadvance-m/visualboyadvance-m/issues/144l) and [#223](https://github.com/visualboyadvance-m/visualboyadvance-m/issues/223)).

**Comment by retro-wertz** [comment]
bug was related to an opcode issue. this should be fixed in latest commits

related issue: #238

**Comment by KatherineFtw** [comment]
Oh, this is still open? Sorry, I switched to mGBA after getting no response for a day

Still want me to test anything or get footage?

**Comment by ZachBacon** [comment]
Tomorrow I'm going to push a new build, once I do some testing would be appreciated

**Comment by retro-wertz** [comment]
All Camelot games are affected with this kind of issues due to an error type used in some opcodes(Golden Sun for example). this, and other Camelot related issues should be working now with latest commit.
