### ISSUE TITLE
How do I record a video on my Macbook for a game?

### ISSUE THREAD

**Issue by arnavb** [visualboyadvance-m/visualboyadvance-m#229]
### Expected behavior

When I click Record > Start game recording..., I expect the emulator to be able to star recording the game I am playing.

### Actual behavior

When I actually do this, it prompts me to select an output file, which I can't seem to figure out how to do, as the finder window I get looks like below. Shouldn't this create an output file by itself?

![screen shot 2018-05-04 at 8 18 02 am](https://user-images.githubusercontent.com/30810402/39627392-b8cb71b2-4f73-11e8-84e9-0b4b8b8abb2a.png)

As evident, there is no option here for me to create a new file.

To try to get this to work, I decided that maybe this uses `.avi` files so I created an empty one in that directory. However, I still cannot select it.

### Steps to reproduce the behavior

Record > Start game recording...

### ROM details

Which games are affected by the issue (please state if GBA or GB game):

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

N/A

### Option details

Video driver (simple, opengl): Opengl

Sound driver (directsound, xaudio, openal, SDL): openAL

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Mac

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"): Pre-built binary, latest

**Comment by ZachBacon** [comment]
Right now, we need to redo video recording. So at the moment it's not very usable.

**Comment by rkitover** [comment]
Use some other screen recording app.

**Comment by ZachBacon** [comment]
I recommend OBS Studio for now until our implementation is properly fixed

**Comment by arnavb** [comment]
Gotcha, so it's just not working.
