### ISSUE TITLE
Loading a rom without any audio output device connected causes VBA-M to crash 

### ISSUE THREAD

**Issue by RyabDev** [visualboyadvance-m/visualboyadvance-m#233]
### Expected behavior
Not play sound

### Actual behavior
Crashes VBA-M
### Steps to reproduce the behavior
Have 0 audio output devices connect to your computer 

### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).
Currently dont have a linux install setup recently formatted my hard drive 
### ROM details

Which games are affected by the issue (please state if GBA or GB game):
All

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
All

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 8.1

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by ZachBacon** [comment]
So for gdb, you don't always need Linux for that, msys2 has native gdb which you can use.

**Comment by ZachBacon** [comment]
Also I'll see about checking that out. But it should pick system default audio...

**Comment by RyanmFisher** [comment]
Yeah well with my computer I dont have any speakers set up so my only audio output is headphones and say if they are not plugged in that is when it crashes

**Comment by retro-wertz** [comment]
thats kinda weird that a speaker or headphones has to be plug so the sound hardware would work... in most cases, it should still work since audio hardware device is still there regardless if headphones or speakers are plugged in...

**Comment by Squall-Leonhart** [comment]
This would occur because the audio core sync is based on device buffers, not internal ones. But it shouldn't be crashing or freezing in current master, so closing.
