### ISSUE TITLE
[Linux] Loading a rom crashes VBA-M (wxwidgets port)

### ISSUE THREAD

**Issue by UberNooga** [visualboyadvance-m/visualboyadvance-m#234]
### Expected behavior
The rom loads and plays normally

### Actual behavior
VBA-M crashes immediately upon opening a rom with no error message. Please note that this is NOT the same as the one caused by no audio output device connected. Even with headphones and speakers it will crash instantly.

### Steps to reproduce the behavior
1. Open VBA-M
2. Open a rom
3. Enjoy your crash

### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

I have no idea what I'm doing so no

### ROM details

Which games are affected by the issue (please state if GBA or GB game): All

Which games, if any, are NOT affected by the issue (please state if GBA or GB game): None

### Option details

Video driver (simple, opengl): Either

Sound driver (directsound, xaudio, openal, SDL): SDL, as it's the only one available

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Linux Mint Cinammon 18.3

If using Linux, specify if using xorg or Wayland: ???

Version of code (pre-built binary version, or commit ref, or just "master"): VBAM-Trunk PPA as the one on the mint repo is outdated, so master I guess maybe?

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by ZachBacon** [comment]
It's a string of numbers and letters after the version number. Please provide that either typing it out or as a screenshot.

**Comment by UberNooga** [comment]
I see no such thing in the title bar?

The Help -> About section also displays no such string, and I don't think the one in Synaptic is what you're after, as it says it's version 2.01, which it's not. Despite that I'll supply it anyway: 2.0.1-r201805011031-85dea8a-22~ubuntu16.04.1

![image](https://user-images.githubusercontent.com/22250603/40757219-a03d3c3a-64c6-11e8-9f43-b1152bd2ad63.png)

Also, the emulator has been behaving kind of oddly? I was going to post this issue before, but then it started working again, then on the next reboot it stopped again, and now it's started working again, though if you switch roms too many times it will get stuck at a black screen on loading a rom but not crashing. Could be something wrong on my end?

Sorry about my lack of technical knowledge in the area. I wish I could be more helpful. I'm just an enthusiast :/

**Comment by rkitover** [comment]
The issue with switching roms crashing is most likely due to the many memory errors in the codebase, I would recommend starting a fresh instance of the emulator for each rom. You can launch it from terminal with the rom as an argument.

**Comment by retro-wertz** [comment]
can you try retesting using latest commits? there should be a pre-compiled version somewhere if your using windows...

**Comment by UberNooga** [comment]
Yep, this works now. Thanks guys :+1:
