### ISSUE TITLE
Gameshark and codebreaker codes not working in Visual Boy Advance-M v2.0.1 64 Bit

### ISSUE THREAD

**Issue by GauravSahare27** [visualboyadvance-m/visualboyadvance-m#236]
### Please fill out this form:
I want to download VisualboyAdvance-M v2.0.2 64 bit, so I opened VBA release web page
https://github.com/visualboyadvance-m/visualboyadvance-m/releases
but this version is not actually available, it is still v2.0.1 beta, may be that developer forget to verify this version before upload. Now my issue is gameshark and codebreaker codes are not working, but it perfectly works in VBA v1.8.0 beta 3.
### Expected behavior
Gameshark and codebreaker codes should properly work.
### Actual behavior
Gameshark and codebreaker codes are not working.
### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
Pokemon FireRed GBA, Leaf Green, Emerald, Final Fantasy(all series).
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

### Option details

Video driver (simple, opengl):
Intel HD Graphics
Sound driver (directsound, xaudio, openal, SDL):
Realtek HD Audio
### Build details
VBA-M v2.0.1 beta
Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 8.1 64 Bit
If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by retro-wertz** [comment]
@GauravSahare27 hi, can you test with latest commits if issue is still there? i dont know how reliable emucr.com is but there should already be an available version there based on latest commit.

**Comment by retro-wertz** [comment]
code breaker and gameshark cheats for GBA should now be working as of latest commit...
