### ISSUE TITLE
No audio when playing ROMs

### ISSUE THREAD

**Issue by Aerisu** [visualboyadvance-m/visualboyadvance-m#237]
### Expected behavior
_Audio can be heard when playing a ROM game_
### Actual behavior
_No audio can be heard at all for GBA, GBC games (using the VBA 1.8.0 beta 3 audio can be heard however: http://www.emulator-zone.com/doc.php/gba/vboyadvance.html)
Audio is turned on and YouTube video in Google Chrome plays fine with audible audio_
### Steps to reproduce the behavior
_Load any GBA or GBC ROM, it should be noticed that no audio can be heard_
### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
_Pokemon Gold Demo (GBC)
Pokemon Rusty (GBA)_
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

### Option details

Video driver (simple, opengl):
_OpenGL_
Sound driver (directsound, xaudio, openal, SDL):
_SDL_
### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
_Windows 64 bit_
If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):
_64 bit v2.0.1 (downloaded directly from v2.0.2 release page though?  https://github.com/visualboyadvance-m/visualboyadvance-m/releases)_
### Hardware details:
_Dell Inspiron 15 7559 laptop
8GB RAM
1TB SHDD
i7 processor_

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by ZachBacon** [comment]
redo the template please we don't need to really know your OS drivers, the drivers in the driver section are the app drivers in the options menu.

**Comment by ZachBacon** [comment]
Also have you tried any of the app driver's, IE openal, etc?

**Comment by Aerisu** [comment]
Whoa, easy fix, after finding the drivers in the Options menu I changed the audio driver from SDL to OpenAL and DirectSound, SDL is silent for some reason but apart from XAudio2 everything else works!

**Comment by darkracer125** [comment]
i found another version of visualboy advance yesterday
the visualboyadvance-m  (32 and 64 bit) 

wich is the one aerisu is setting his settings in.   but just using this version of visualboyadvance has solved all my problems with sound that i had before.   (one verry noticeable game was pokemon yellow. where the pikachu sounds were just static)  this is now fixed

**Comment by Cannon-S** [comment]
> Whoa, easy fix, after finding the drivers in the Options menu I changed the audio driver from SDL to OpenAL and DirectSound, SDL is silent for some reason but apart from XAudio2 everything else works!

clutch
