### ISSUE TITLE
Cartoon Network Speedway does not display properly.

### ISSUE THREAD

**Issue by LofiSR** [visualboyadvance-m/visualboyadvance-m#238]
### Expected behavior:
Game displays graphics normally.

### Actual behavior:
After turning, random horizontal lines garble the screen where 3D rendering is supposed to occur, making the game unplayable.

### Steps to reproduce the behavior
Simply begin a race and turn. The screen glitches.

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
Cartoon Network Speedway (GBA)

### Option details

Video driver: OpenGL

Sound driver: OpenAL

### Build details

Operating System: Windows 10 64-bit Build 17134.rs4_release.180410-1804

VBA-M version: 2.0.1

Screenshot: https://vgy.me/nDRU1W.png

**Comment by retro-wertz** [comment]
confirmed on linux version too.

**Comment by ZachBacon** [comment]
What happens if the simple driver is used for graphics? Just out of curiosity.

**Comment by retro-wertz** [comment]
im on linux. using simple driver still has this issue

**Comment by ZachBacon** [comment]
Thanks for that, then problem is deeper than just simple graphics on the front end of things

**Comment by retro-wertz** [comment]
im having problems doing a bisect since previous commits past march 1 does not compile on my end for some reasons...

**Comment by ZachBacon** [comment]
Got an error log for me to look at? I know we've been doing successful compiling with the current setup for months even before March.

**Comment by retro-wertz** [comment]
something like this starting from oct 2017 

https://hastebin.com/qojoqunuyi.rb

**Comment by retro-wertz** [comment]
Pushed PR for this...

**Comment by ZachBacon** [comment]
![1260 - cartoon network - speedway u venom](https://user-images.githubusercontent.com/8948676/41011266-000507f0-690a-11e8-97aa-aa33aee7140f.png)
can confirm the fix

**Comment by ZachBacon** [comment]
I'll post a build shortly.
