### ISSUE TITLE
[Libretro] [GBA]Game Pak Error when loading classic nes/famicom rom

### ISSUE THREAD

**Issue by retro-wertz** [visualboyadvance-m/visualboyadvance-m#240]
### Expected behavior

roms should load and play as they previously used to

### Actual behavior

screen shows Game Pack Error when loading such roms (in my test, it was Classic NES Castlevania and Super Mario Bros. These same titles worked in the older vbam version).

Only affects the libretro port, since standalone works fine. Were there specific updates since the last sync to libretro that affects how the classic rom Works?

If this helps, retroarch has an option named Runahead. when this option is ON (set 2nd instance to OFF), the classic roms runs fine (aside from audio issues caused by runahead). Since runahead makes use of save/load states each (nth)frame, its probably something on there or related. It can also probably just a red herring.

### Steps to reproduce the behavior

Just need to load the game using latest version of vba-m (currently commit https://github.com/visualboyadvance-m/visualboyadvance-m/tree/893269d897f7512bc9edeed8d3fba9ed69538a80)

### Crash bugs

None

### ROM details

GBA Classic NES Castlevania and Super Mario Bros.

### Option details

default settings (libretro port)

Sound driver (directsound, xaudio, openal, SDL):

default settings (libretro port)

### Build details

tested on Windows 10 x64 and Linux Arch xorg

**Comment by ZachBacon** [comment]
Thanks much for the report, we'll look into it as soon as possible

**Comment by retro-wertz** [comment]
looks like something going on with passing saveType variable... forcing SetSaveType() to 1 (force EEPROM mode) makes these games work....

**Comment by ZachBacon** [comment]
I see that, and before I even got home.

**Comment by ButterCCM** [comment]
Hi, I have a web based gba emulator that I made with a friend and built off someone else's code. Would anyone be willing to help me patch that for my site. I tried loading Zelda II. butterccm.github.io/gba
