### ISSUE TITLE
[Linux] Unable to perform any kind of GBA battery save

### ISSUE THREAD

**Issue by UberNooga** [visualboyadvance-m/visualboyadvance-m#247]
### Expected behavior
Games battery save as normal

### Actual behavior
Games either throw a save error in-game or just don't record any progress at all. For example, in Pokemon Emerald it will throw a "save failed" error, checks the backup memory, claims the battery has run dry, then boot you to the title screen, or in Kirby and the Amazing Mirror, VBA-M will claim to have written to battery, but when you reopen the ROM there is no save there.

### Steps to reproduce the behavior
1. Open a GBA game
2. Autodetect the save type using "Detect now"
3. Get to a point where the game will save
4. Save
5. VBA-M will claim to have "Wrote battery", but the save fails

### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game): GBA games only

Which games, if any, are NOT affected by the issue (please state if GBA or GB game): GB games

### Option details

Video driver (simple, opengl): OpenGL

Sound driver (directsound, xaudio, openal, SDL): SDL

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Linux Mint Cinnamon 18.3

If using Linux, specify if using xorg or Wayland: ???

Version of code (pre-built binary version, or commit ref, or just "master"): Sergio's Launchpad PPA latest version, wxwidgets port

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by retro-wertz** [comment]
interesting that this PPA just recently compiled this build, but the version if rom an old release.

are you by any chance using x64 of Linux Mint? i should be able to compile you based on the latest commits for you to re-test.

**Comment by UberNooga** [comment]
I do have permission to write, yes. And I am using the x64 version of LinMint, yes. The .sav always shows up in the folder where the ROM is, but it's almost as if it doesn't recognise it's even there. So strange.

**Comment by UberNooga** [comment]
Latest commits have fixed it. Thanks guys.
