### ISSUE TITLE
import battery file doesn't work

### ISSUE THREAD

**Issue by bluekittyyoyo** [visualboyadvance-m/visualboyadvance-m#251]
### Expected behavior
Load a saved game that was created by a different emulator
### Actual behavior
It is as if nothing happened; game immediately returns to whatever was previously happening in the emulator
### Steps to reproduce the behavior
Open game. File>Import>Battery File. Choose the .sav file. Click okay when asked if you want to continue. 
### ROM details
Pokemon FireRed, GBA. I have no other games. 
### Build details
Windows 7
### Other Details
The .sav file I am trying to import was created by the No$GBA emulator. I have placed the file in several different folder locations including the same folder that the VBA files are in, but no such luck.

**Comment by retro-wertz** [comment]
works fine here. imported save file from standalone mednafen. No$GBA must be using its own save format thats incompatible. can you upload nogba's savefile so i can take a look?

**Comment by bluekittyyoyo** [comment]
I hope this zip file works; github doesn't support the .SAV
[1695 - Pokemon - Fire Red Version (E).zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/2087612/1695.-.Pokemon.-.Fire.Red.Version.E.zip)

**Comment by retro-wertz** [comment]
its indeed not compatible. there is probably a save option in NoGBA to save
the file as uncompressed format, then try to import that. im not on windows
so i cant test it myself.

**Comment by bluekittyyoyo** [comment]
I tried converting the file again and no such luck

**Comment by retro-wertz** [comment]
ok tested nogba in my crappy windows machine, and sadly the latest version doesnt seem to have a way to save in raw format. nogba still using its own save format so this cant be used in vbam sadly.

**Comment by bluekittyyoyo** [comment]
From reading other forums, I think you can change it to save in raw format by opening the .ini file (after saving preferences) and then change "SAV/SNA File Format == Compressed" to "Uncompressed"

**Comment by retro-wertz** [comment]
yeah, that works. but the file is still 137KB, with some nogba stuff still
in it. this cant be used directly without editing.. lemme see if i can
fetch your pokemon save here...

**Comment by retro-wertz** [comment]
[1695 - Pokemon - Fire Red Version (E).zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/2088345/1695.-.Pokemon.-.Fire.Red.Version.E.zip)

ok, i dont have the (E) version of this game, but the savefile seems to work with my (U) version so this probably will work now.

![untitled](https://user-images.githubusercontent.com/23315382/41207844-e0cb150c-6d4e-11e8-94c8-1a2e14b0bf29.png)

**Comment by bluekittyyoyo** [comment]
Works like a charm, thanks so much! For future reference, what did you do to change the file? I have some friends also want to change from nogba to vba-m.

**Comment by retro-wertz** [comment]
you need to know the save format and the save size used for the game. save
nogba in uncompressed format. open this uncompress save format in some hex
editor. the correct starting savefile will start a few offsets from the
flashtype indicated in the uncompressed savefile like so....



the real save file in this example starts at $4C, so start copying from
this offset, up to the size of the real save file type (for Pokemon its
128KB or $8000 in hex size)

**Comment by bluekittyyoyo** [comment]
Awesome, thanks!

**Comment by retro-wertz** [comment]
wierd.. image did not show up

**Comment by Askmewho** [comment]
I had this same problem on rpi3 (ive compiled master and it does work amazingly under mesa)
the savs are from tgb dual, and are the exact same size than the ones made by visualboyadvance...

**Comment by ELECTRODE69** [comment]
hey,if i give my mother 3 save can i get help too?

**Comment by rkitover** [comment]
@denisfa I think we should implement automatic nogba save file import. What do you think? The deleted user gave us the full algorithm for this, so it should be very straightforward to implement.

**Comment by Squall-Leonhart** [comment]
trouble is, nogba is creating the wrong format files for things like Eeprom
