### ISSUE TITLE
Option to disable "Wrote battery" message

### ISSUE THREAD

**Issue by Sun-in-jang** [visualboyadvance-m/visualboyadvance-m#264]
I didn't founded this one. Everytime when you see thismessage, it's a bit annoying (or can be). I would like to disable it, maybe other users too

**Comment by retro-wertz** [comment]
options > video then uncheck Transparent on-screen display

**Comment by retro-wertz** [comment]
its actually uncheck Disable On Screen Display but i think you already got it...
