### ISSUE TITLE
double speed vba

### ISSUE THREAD

**Issue by wesleyjacksonthepokemonplayer** [visualboyadvance-m/visualboyadvance-m#267]
when I use VBA, it plays games at double the speed of normal which sounds ok and lets people get through stuff quicker BUT it makes timing things a lot harder, and I cant find any throttle of any kind.
I don't know of any solutions and no one seems to have a problem with this. but there has to be a solution right?

**Comment by ZachBacon** [comment]
so. vba or vba-m. I'm asking this as vba-m is a way different beast than what vba used to be.

**Comment by wesleyjacksonthepokemonplayer** [comment]
its vba-m

**Comment by ZachBacon** [comment]
So it's dead simple to change, Go to the menu bar, select options, bring your mouse down to general and it's there.

**Comment by rkitover** [comment]
Do this:

- open file explorer
- in the location bar type `%USERPROFILE%\AppData\Local` and press enter
- delete the directory called `visualboyadvance-m`
