### ISSUE TITLE
Cannot Save Screen Captures on macbook pro running High Sierra

### ISSUE THREAD

**Issue by Hollydolly85** [visualboyadvance-m/visualboyadvance-m#268]
### Please fill out this form:
Im not a coder, just someone using the emulator, So I hope I give relevant info here, I just thought I should mention it just in case its not already known about. I couldn't find it in any other issues or in the description.  
### Expected behavior
When selecting "Screen Capture" I can choose a directory, file name, and file type to save it as and click the save button to save it.
### Actual behavior
I can only choose a directory and file type. There is no place to type a file name. In place of the Save button, is a greyed out Open button, as if I were trying to open a file instead of save one. This makes it impossible to save a screen capture, unless I'm missing something. Note, the open button replacing the save button also happens in windows (In windows 7 anyway) but that doesn't matter, since I can just type a file name and push enter to save it. but that's not the case on my Macbook Pro

### Steps to reproduce the behavior
On a macbook pro, running High sierra (maybe other versions I don't know), Click File-Screen Capture.
### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
GBA and GBC, I have no GB games si i cant test tat
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Mac
If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by ZachBacon** [comment]
Screen captures on Mac are a bit broken ATM. It's on our list of stuff to fix.

**Comment by Hollydolly85** [comment]
Ok thanks!

**Comment by rkitover** [comment]
This is fixed in master.

**Comment by rkitover** [comment]
Fixed in 2.1.0.
