### ISSUE TITLE
AGBPrint Logging non-functional

### ISSUE THREAD

**Issue by felixjones** [visualboyadvance-m/visualboyadvance-m#269]
### Expected behavior

Logging debug window displays AGBPrint output when "Debug print" is enabled.

### Actual behavior

Nothing printed out.

### Steps to reproduce the behavior

1. Enable Debug print via: _Options_ -> _Gameboy Advance_ -> _Debug print_
2. Open debug output log window via: _Tools_ -> _Logging..._
3. Enable _AGBPrint_
4. Launch ROM that uses AGBPrint or similar debug output logging

### ROM details

Any GBA ROM that uses AGBPrint will fail to output to the Logging window.

### Option details

N/A

### Build details

64bit VisualboyAdvance-M 2.0.2 92ba676 

Operating System: Windows 10 64bit

Version of code: master

**Comment by felixjones** [comment]
The read/write issues were related to my ROM file. Regardless, AGBPrint is still non functional.

**Comment by rkitover** [comment]
Once you figure this out, could you please help us make it work in the release version as well?

**Comment by felixjones** [comment]
I've investigated, indeed there is an issue in the release version where AGBPrint is not logging. I can only get it working with debug builds.

Re-opening as this is a confirmed issue now. Steps to re-produce are in the first comment.

@rkitover I am unable to create a release build environment, I am on Windows and the most I can get working is an SDL debug version without any user-interface. If someone can guide me on how to create a buildable release version on Windows then I will be happy to fix this myself.

I'm actually willing to fix a number of issues that I've encountered, but unfortunately I am having incredible difficulty creating a release project to do so. It's taken me 4 attempts over the course of 3 hours to get a basic SDL debug environment working so I could figure out there the issue lies with AGBPrint.

**Comment by rkitover** [comment]
The easiest way is to use the msys2 prompt as described in the README.md on the project page, we are working on proper Visual Studio support but it's some time away.

The release version is the default for the Wx frontend, to use debug mode pass in `-DCMAKE_BUILD_TYPE=Debug`.

**Comment by SBird1337** [comment]
Is there any progress on where this issue lies? I tried a debug build as well as of 2fedaa63a6720247822327d41bb909513be1c2f1 (now) but this is still non-functional.

**Comment by rkitover** [comment]
Can you give me a rom that uses print that I can test, or tell me how to get it without linking it if it's not legal.

**Comment by rkitover** [comment]
By the way, we are in initial stages of Visual Studio 2017 support and you should be able to build the GUI.

**Comment by felixjones** [comment]
I made a ROM that demonstrates AGBPrint:
[agb_print.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/3121922/agb_print.zip)
This prints out the text `AGBPrint %hu` between vblank and vdraw periods, with `%hu` replaced with a uint16 decimal integer that will count up from zero (and overflow at 0xffff).

**Comment by rkitover** [comment]
Thank you for this, I looked at it and it looks like I just need to implement the `dbgOutput()` callback to append to the relevant `wxTextCtrl`, and it does not look like this was ever implemented.

**Comment by rkitover** [comment]
Well, after looking at it further, it was definitely never implemented and the GUI code also needs to be completely rewritten, so this is a bigger work than I thought, I'll try to do it in a few days.

**Comment by rkitover** [comment]
@denisfa finally fixed this in d05e8fc1.

**Comment by NeoTechni** [comment]
still non-functional

**Comment by Squall-Leonhart** [comment]
> still non-functional

User Error.

**Comment by NeoTechni** [comment]
> > still non-functional
> 
> User Error.

I'm copy/pasting the code from the [add documentation] link above my comment, and the logging screen in VBA shows nothing, it also reports it is up to date. If it's user error, then maybe that request for documentation should be fulfilled.
