### ISSUE TITLE
Instant crash at startup

### ISSUE THREAD

**Issue by fdavidd** [visualboyadvance-m/visualboyadvance-m#270]
### Expected behavior
Program launches
### Actual behavior
Program crashes instantly, the main screen doesn't show
### Steps to reproduce the behavior
Launch the program

### Build details
Windows version, 32-bit, latest (2.0.2)
### Hardware details:
Core 2 Duo E8200
GeForce 7800GTX
2 GBs of RAM

**Comment by ZachBacon** [comment]
What version of Windows

**Comment by retro-wertz** [comment]
i think the latest 32bit windows released is broken. this will be fixed in the next release version....

**Comment by fdavidd** [comment]
@ZachBacon I'm using Windows 7.

@retro-wertz I see... guess I'll just use an older version. I hope that 2.0.1 works, because WX (I think that's the 2.0.0 release), has audio-stuttering issues which are really annoying.

**Comment by ZachBacon** [comment]
the latest build should work. I know the local one I built seems to be working. I didn't post the current binaries though for windows due to some build issues I had finally fixed earlier today.
