### ISSUE TITLE
[linux]Shortcut keys are not working and others...

### ISSUE THREAD

**Issue by retro-wertz** [visualboyadvance-m/visualboyadvance-m#276]
### Expected behavior

- shortcut keys should work.

### Actual behavior

- no shortcut keys / combinations work.directly clicking the desired option from menu works, hotkey remapping feature is also able to read inputs and assign new hotkeys but non is working.

- Just want to add that hotkeys do work, when no ROM is loaded, but non works when a game is running.. could be that the ingame keyboard-events is taking over?

### Steps to reproduce the behavior

Seems to only affect Linux builds... Windows version seems to work fine.

### ROM details
all affected

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): arch linux

If using Linux, specify if using xorg or Wayland: xorg

Version of code (pre-built binary version, or commit ref, or just "master"): master

**Comment by retro-wertz** [comment]
shortcuts is working in Windows.. so this is probably only a linux issue.

**Comment by retro-wertz** [comment]
[WINDOWS]
On windows, shift key doesnt seem to work with hotkeys, Shift+F1 for example saves states to slot 1 but its not working, even remapping it... there are also wrong labels on Load State and Save State menus on the Key Shortcut remapping feature:

![23456787](https://user-images.githubusercontent.com/23315382/42409228-e0481fd8-8209-11e8-8783-45b622b9d5f8.jpg)

the items on red box suppose to show slot numbers. this happens on Save State items too.

**Comment by retro-wertz** [comment]
Related or similar issues:
https://github.com/visualboyadvance-m/visualboyadvance-m/issues/88

**Comment by retro-wertz** [comment]
- Just want to add that hotkeys do work, when no ROM is loaded, but non works when a game is running.. could be that the ingame keyboard-events is taking over?

**Comment by Spaguetti** [comment]
Hi everyone. I got the same problem with v2.1.0 and v2.0.1.


Expected behavior

    shortcut keys should work.

Actual behavior

    no shortcut keys / combinations work.directly clicking the desired option from menu works, hotkey remapping feature is also able to read inputs and assign new hotkeys but non is working.

    Just want to add that hotkeys do work, when no ROM is loaded, but non works when a game is running.. could be that the ingame keyboard-events is taking over?

Steps to reproduce the behavior

I Have Windows and i got the problem. both version 2.0.1 and version 2.1.0 either.
Very annoying when saving / loading save states using keyboard shortcuts

Crash bugs
ROM details

all affected
Option details
Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Windows 10 x64

Version of code (pre-built binary version, or commit ref, or just "master"): master

Hardware details: i7-4770k, Asus Z-87 pro, Geforce GTX 780, 16 GB ram.

**Comment by retro-wertz** [comment]
Please continue in this link as this is a duplicate:
https://github.com/visualboyadvance-m/visualboyadvance-m/issues/88
