### ISSUE TITLE
Unresponsive Sections in Game

### ISSUE THREAD

**Issue by IronMan0002005** [visualboyadvance-m/visualboyadvance-m#280]
### Expected behavior

When playing megaman battle network 4 blue moon you unlock a customization called a navi customization. Upon unlocking this you have to complete a tutorial on how to use it and it requires you to place tiles in a certain order.

### Actual behavior

The tutorial loads up, but when it prompts you to place the tiles, the A,B,L, and R buttons no longer work. Being unable to place the tile, you are stuck moving the tiles around in the tutorial and unable to advance.

### Steps to reproduce the behavior

Play through game until you reach tutorial.

### Crash bugs

None, as the game doesn't recognize that it's crashed. It's just stuck in the tutorial. 

### ROM details

Megaman battle network 4 blue moon.

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Windows 10

### Hardware details:

No external hardware, just using keyboard. 

I'm new to roms and emulators, but I'll happily provide any other information that I can to help resolve the issue.

**Comment by Squall-Leonhart** [comment]
Closed: WFM.
