### ISSUE TITLE
Saves on pokemon yellow not working.

### ISSUE THREAD

**Issue by Longtime4321** [visualboyadvance-m/visualboyadvance-m#281]
### Please fill out this form:
Okay
### Expected behaviour
Having a continue option and continuing from where I saved.
### Actual behavior
Only having a "New Game" Option
### Steps to reproduce the behavior
1) Load up pokemon yellow 2) save 3) close and open up the emulator
### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
Pokemon Yellow GBC
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
Donkey Kong GB
Mario's Picross GB
Tetris DX GBC
### Option details

Video driver (simple, opengl):
Unknown
Sound driver (directsound, xaudio, openal, SDL):
Unknown
### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 10
If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):
master
### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by retro-wertz** [comment]
Works fine here.

![screenshot_2018-07-09_08-42-13](https://user-images.githubusercontent.com/23315382/42425777-0de3b2f4-8354-11e8-9229-9c3e73b95a56.png)

by default, save files are save where the roms are loaded from. if for some reasons this location is unwriteable or you dont have permission, saves will fail.

try to set a directory for "Native Saves" to some other folders.

**Comment by Longtime4321** [comment]
The savs are in the folder, but trying to load them up via the import saves battery paks gives me the same result

**Comment by retro-wertz** [comment]
are these saves from a different emulator? coz its certainly not stated in the issue template..

**Comment by Longtime4321** [comment]
No. Where is it suposed to be stated?

**Comment by retro-wertz** [comment]
write it on the report... details...

anyways your savestate is not compatible. from what emu does this save file come from? upload it here.

**Comment by retro-wertz** [comment]
if your not bz, head over to iirc freenod #vba-m or uset this glitter chat https://gitter.im/visualboyadvance-m/Lobby
so we can interact realtime.

**Comment by Longtime4321** [comment]
It comes from the same emu im trying to use it on.
The name of ash on the file shold be "Alecc'
If not correct then my sav is corrupted any my 100 saves from the other times i tried were too
http://www.mediafire.com/file/dxcubch092yr0jp/Pokemon%20-%20Yellow%20Version%20%28UE%29%20%5BC%5D%5B%21%5D.sav

**Comment by retro-wertz** [comment]
yup.save is corrupted...

**Comment by Longtime4321** [comment]
oh. Okay.
