### ISSUE TITLE
Unable to load GB/GBC save states between 32-bit and 64-bit versions of 2.1.0 in Windows

### ISSUE THREAD

**Issue by ChaosZeroX** [visualboyadvance-m/visualboyadvance-m#283]
### Expected behavior
Emulator should be able to load save states for Game Boy, Game Boy Color, and Game Boy Advance games regardless of which version/architecture of visualboyadvance-m was used to create the save state (load 64-bit save state on a 32-bit emulator and vice-versa).

### Actual behavior
Game Boy Advance games seems to work as expected. Game Boy and Game Boy Color games freeze when trying to load save state (sgm). 32-bit vba-m will load 32-bit save states with no problems but not 64-bit saves states. 64-bit vba-m will not load 32-bit states. Windows OS architecture does not seem to matter (tested with both x86 and x64 devices).

### Steps to reproduce the behavior
Create save state for GB/GBC game in 64-bit version of vba-m and then try to load that same save state file in 32-bit version of vba-m (and vice versa).

### ROM details

Which games are affected by the issue (please state if GBA or GB game): GB and GBC games - Kirby Dreamland 2, Super Mario Land 2 (original and DX), Zelda Link's Awakening DX, Zelda Oracle of Ages, and Zelda Oracle of Seasons,

Which games, if any, are NOT affected by the issue (please state if GBA or GB game): GBA games - Astro Boy Omega Factor, Metroid Fusion, Metroid Zero Mission, Zelda Link to the Past, Zelda Minish Cap, Megaman Zero, Megaman Battle Network

### Option details

Video driver (simple, opengl): OpenGL (Simple ends up breaking everything and crashes the application)

Sound driver (directsound, xaudio, openal, SDL): SDL (tried directsound as well but doesn't seem to affect anything)

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Windows 10 ver 1709 (32 and 64 bit OS)

Version of code (pre-built binary version, or commit ref, or just "master"): master V2.1.0 Security Fix

**Comment by retro-wertz** [comment]
sadly there's nothing that can be done with this atm without breaking backwards compatibility with older save files from lower versions. This though will be reconsidered in future refactoring...

thanks for the report.

**Comment by ChaosZeroX** [comment]
@retro-wertz was the previous comment for #285?

**Comment by Squall-Leonhart** [comment]
This should be working
