### ISSUE TITLE
Help menu

### ISSUE THREAD

**Issue by cyberdyne-sys** [visualboyadvance-m/visualboyadvance-m#284]
The "VBA-M Support Forum" element in the Help menu, points to an invalid target. Actually, the vba-m.com domain seems to be down completely for me.

Anyways, it'd nice to check and perhaps  accept new language request on Transifex. Thank you.

**Comment by ZachBacon** [comment]
It isn't down. Just server restructuring

**Comment by cyberdyne-sys** [comment]
Sorry for commenting an already closed issue, but since the forum is still under maintenance (HTTP 404), i can't see another way, for asking you for accepting my new language request on Transifex, if you need new translations. If not, please, just simply deny it, so i'll know, you don't need it at all. Thank you.

**Comment by ZachBacon** [comment]
It'll be done when it's done. We are kinda dealing with more priority issues than this. Please be patient

**Comment by cyberdyne-sys** [comment]
Sure, but i guess, you misunderstood something, cause it's not about impatience. I just kindly asked for an acceptance, or denial for the mentioned request (which, i bet, may not take more, than 5 mins.), since other people also can be busy - including me -, so it'd be especially useful to know, that you do such a "favor", like hiring me for this job for free, or not. Believe it, or not, other people can have their own life, daily scheduling, deadlines, etc. too. Thanks for understanding.

**Comment by ZachBacon** [comment]
Some of us are working at the moment at a day job ;) I'm doing things via my phone. You'll have to forgive me when I say I didn't misunderstand anything. Again please be patient.
