### ISSUE TITLE
[Build issue]Cmake fails when using clang/clang++ in Tumbleweed

### ISSUE THREAD

**Issue by ghost** [visualboyadvance-m/visualboyadvance-m#289]
### Expected behavior

cmake and then make should be successful in clang as it is when using gcc

### Actual behavior

cmake fails with this error:

```
- Looking for sem_timedwait
-- Looking for sem_timedwait - found
-- Looking for gettext
-- Looking for gettext - found
-- Performing Test WX_HAS_OPENGL
-- Performing Test WX_HAS_OPENGL - Failed
-- Found wxWidgets: -L/usr/lib64;-pthread;;;-lwx_gtk2u_xrc-3.0;-lwx_baseu_xml-3.0;-lwx_gtk2u_html-3.0;-lwx_gtk2u_adv-3.0;-lwx_baseu_net-3.0;-lwx_gtk2u_core-3.0;-lwx_baseu-3.0 (found version "3.0.4") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Looking for __WXGTK4__
-- Looking for __WXGTK4__ - not found
-- Looking for __WXGTK3__
-- Looking for __WXGTK3__ - not found
-- Looking for __WXGTK20__
-- Looking for __WXGTK20__ - not found
CMake Error at src/wx/CMakeLists.txt:365 (MESSAGE):
  Could not find gtk
-- Configuring incomplete, errors occurred!
```

[CMakeError.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/2222707/CMakeError.zip)

### Steps to reproduce the behavior

-Using the terminal, type "export CC=clang" and  "export CXX=clang"
-(follow guide on how to compile vbam)
-run cmake .. (or whatever your syntax is)
-this should fail
(no issue if using gcc)

## Crash bugs

no crash

### ROM details
not rom related

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): tumbleweed latest on kde

If using Linux, specify if using xorg or Wayland: xorg

Version of code (pre-built binary version, or commit ref, or just "master"): master as of writing

**Comment by rkitover** [comment]
Should be:

```
export CXX=clang++
```

**Comment by retro-wertz** [comment]
sorry type... i did type in its clang++

**Comment by rkitover** [comment]
Make sure to `rm -rf build` first, also can you post the whole cmake log?

**Comment by retro-wertz** [comment]
heres log:

https://hastebin.com/sufelefizo.coffeescript

**Comment by retro-wertz** [comment]
heres whats currently installed... and whats available...


ill probably test with wxWidgets 3_2....

**Comment by retro-wertz** [comment]
apparently, you need to compile in another partition, for e.g your $HOME folder for running cmake when using clang....

**Comment by rkitover** [comment]
The thing is, when you try to run the binary you built, it will fail because of an ABI error, we need to figure this out too.

**Comment by rkitover** [comment]
The binary you make with clang will not run, try it.

**Comment by retro-wertz** [comment]
well, i did close this issue coz the binary did ran..

but still, moving stuff just to compile does not seem normal..

**Comment by orbea** [comment]
The build succeeds here with `clang-9.0.0`, should this be considered fixed?
