### ISSUE TITLE
Leaderboard and achivement pop up appear and disappear continuously

### ISSUE THREAD

**Issue by PrinessValentina** [visualboyadvance-m/visualboyadvance-m#290]
### Expected behavior
leaderboard and achivements they should be shown at the start of the game and then disappear and do not come back
### Actual behavior
the windows of the achivement and the leaderboard continue to scroll right and left, occupying a lot of visible space
### Steps to reproduce the behavior
start kirby in pinball land all the other games I have for the moment are not affected

### ROM details

Which games are affected by the issue : kirby in pinball land (GB)

Which games, if any, are NOT affected by the issue: The Urbz - Sims in the City GBA, Fist of the North Star GB, The Legend Of Zelda - A Link To The Past GBA, Astro Boy - Omega Factor GBA

### Option details

Video driver Direct3D 9

Sound driver directsound 8

### Build details

Operating System Windows 10 10.0.16299 build 16299

**Comment by retro-wertz** [comment]
may i ask if are you really reporting this issue for this core and how you acquire this? did you compile from master branch?

**Comment by ZachBacon** [comment]
Considering we don't have this in vba-m. I think op is either posting about retroarch which would be their issue and not ours or its meant for something else entirely. 
Closing as it's nothing to do with us. I'll reopen though if there's more information involved.

**Comment by retro-wertz** [comment]
actually, our libretro port's difference with retroarch's port is that we
support playing  for GB/GBC games aside from enabling cheevos
(retroachievements) for these systems, that was why i am asking OP if he
did compiled this core and added needed core-info file or was just a
misplaced port...
