### ISSUE TITLE
Metroid Fusion Question

### ISSUE THREAD

**Issue by Cibomatto2002** [visualboyadvance-m/visualboyadvance-m#293]
I notice that there is different color on the bottom here is this correct? visualboyadvance-M
 2.1.0
![capture7-30-2018-11 31 04 pm](https://user-images.githubusercontent.com/21169038/43437938-2a38b22a-9451-11e8-8ddf-55be90c02a62.jpg)

**Comment by Cibomatto2002** [comment]
Here is a Save State 
[Metroid Fusion (USA, Australia)-01.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/2243769/Metroid.Fusion.USA.Australia.-01.zip)

**Comment by retro-wertz** [comment]
Hi
how far is this into the game? honestly i am not a metroid fan. did you try to see other reference for this section of the game? youtube runs (agdq for actual hardware runs) perhaps?

**Comment by Cibomatto2002** [comment]
it's not a bug I seen it in this video sorry about that. https://youtu.be/VrkDH8PMCZU?t=1531
