### ISSUE TITLE
Building VBA-M on CentOS

### ISSUE THREAD

**Issue by BackOrder** [visualboyadvance-m/visualboyadvance-m#297]
### Expected behavior

Building vba-m on CentOS.

### Actual behavior

Running **installdeps** seems to do nothing, no output.

### Steps to reproduce the behavior

On CentOS 7, clone project from github and run installdeps per the [instructions](https://github.com/visualboyadvance-m/visualboyadvance-m#building).

### Build details

Linux 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Using xorg with master branch.

**Comment by retro-wertz** [comment]
**`./installdeps is supported on MSys2, Linux (Debian/Ubuntu, Fedora, Arch or Solus) and Mac OS X (homebrew, macports or fink.)`**

system not supported. youll have to fetch depencies and if you want, you can paste those depencies here so it can be added or send a PR

**Comment by BackOrder** [comment]
So I went through a series of installing -devel packages according to the list provided on the main page. SFML is unavailable on CentOS and had to run with `cmake3 -DENABLE_LINK=NO ..`. Installed wxGTK3/wxGTK3-devel but there was `wxrc` missing from wxGTK2.

Now I'm getting the following error even though `/usr/lib64/libGL.so` is already on my system.

```
make -j`nproc`      
[ 11%] Built target wxvbam_translations
[ 32%] Built target fex
[ 82%] Built target vbamcore
make[2]: ***  No rule to make target « /usr/lib64/libGL.so », needed for « visualboyadvance-m ». Stop.
make[1]: *** [src/wx/CMakeFiles/visualboyadvance-m.dir/all] Error 2
make: *** [all] Error 2
```

Any clue how to fix this error?

**Comment by ZachBacon** [comment]
You need Mesa dev iirc. I don't think any of us took into account for centos to be honest.

**Comment by BackOrder** [comment]
What would you need to make it work on CentOS out of the box? I just got VBA-M working and thus might be able to give you a hand to make that happen. :)

**Comment by ZachBacon** [comment]
Not much, given what you mentioned, it should be simple to do.

**Comment by BackOrder** [comment]
Here is my shell history granted that I most likely already had some of the dependencies installed. Also, cmake3 seemed to perform better than cmake (2.x). Had some troubles with symlink on libGL.so pointing to an non-existing library. There is no SFML and building was a bit of a pain, so `-DENABLE_LINK=NO` with cmake would do the trick.

```
   96  yum install cmake3
  100  yum install zlib-devel
  104  yum install mesa-libGL-devel
  108  yum install libpng-devel libpng12-devel
  112  yum install SDL2-devel
  147  yum install wxGTK3 wxGTK3-devel wxBase3
  150  yum install wxGTK-devel
  153  ln -sf /usr/lib64/libGL.so.1.7.0 /usr/lib64/libGL.so
```

The instructions on the main page were otherwise fine.

Let me know if you have question or need some testing done.
