### ISSUE TITLE
Link is not working

### ISSUE THREAD

**Issue by bruhwhyarealltheusernamestaken** [visualboyadvance-m/visualboyadvance-m#304]
Hi there, I know that you are busy with other bugs following this app, but once you finish fixing the bugs, can you please try and fix these two problem with linking VBA to Dolphin?

1.Whenever I start VBA, it says "joybus host invalid, disabling," so can we please fix this? Maybe even bring back the option to edit the joybus?

2. If I try to start a network link, it also says "LAN Link is already active, disable link mode to disconnect" even though I don't have LAN. Is this possible to fix?

Thanks so much 
oh and great job with VBA, it is a great emulator. :)

**Comment by retro-wertz** [comment]
i am able to link with Dolphin using linux and Zelda fours words fine on my end. also you need to fill out the template. please edit your issue with the template

**Comment by Squall-Leonhart** [comment]
closed, stale and duplicate of most other linking issues.
