### ISSUE TITLE
Use print for debugging in emulator

### ISSUE THREAD

**Issue by vitorbaraujo** [visualboyadvance-m/visualboyadvance-m#305]
Is there any way I can use `printf` or any other function to log variables and stuff when I run a ROM in the emulator? By the way, I am running the emulator on a linux machine.

**Comment by retro-wertz** [comment]
try log() instead, although this causes memleak so running this on loop is
not a good idea.

**Comment by rkitover** [comment]
Another possibility, you could maybe find some code for some sort of in-game console that you'd pull down with a key press.

**Comment by vitorbaraujo** [comment]
After a while trying to make something work, I found a post in a gba forum with a functional example of print in gba development. It's an assembly code that contains a system call to `vbaprint`. This is the link to the original post: http://forum.gbadev.org/viewtopic.php?t=18125&highlight=print
