### ISSUE TITLE
Is it possible to load a black & white save in color?

### ISSUE THREAD

**Issue by BarbzYHOOL** [visualboyadvance-m/visualboyadvance-m#309]
### Expected behavior

I saved a game in GB (black and white) but I want to start it in GBA mode (with colors) without losing my data. Is it possible?

### Build details

Ubuntu 14.04 Xorg

Version of code (pre-built binary version, or commit ref, or just "master"):
2.0

**Comment by retro-wertz** [comment]
if your using savestates, probably not..

**Comment by Squall-Leonhart** [comment]
start > save

**Comment by rkitover** [comment]
Did you ever figure it out?

**Comment by BarbzYHOOL** [comment]
no, and I found another emulator which worked better for me (because visualboy kept losing my saves)

**Comment by retro-wertz** [comment]
if your still up to it can you tell which games and modes (gb/gbc) that you are losing saves? and if you still have the saves files for these game, can you upload it and send link here?

**Comment by BarbzYHOOL** [comment]
it's very rare game called "Cave Noire" that I patched from japanese to english

I can upload all of this if you really want to have a look at it but I only play scarcely so I don't really need it fixed anymore

**Comment by retro-wertz** [comment]
just the savefiles, (and if you are able to indicate which ones did not or has lost saves).

is this the correct patch? https://www.romhacking.net/translations/1707/

**Comment by BarbzYHOOL** [comment]
I uploaded the patched rom (and yes there is only one patch for this OBSCURE but really good game) 

https://www89.zippyshare.com/v/oyiJolHN/file.html

I also added all the save files I had, sorry don't know which one it is, it's been 6 months and I had done tests and forgot which one was what.
