### ISSUE TITLE
Add OS check to MainFrame::BindAppIcon; Couldn't find symbol 'LoadIconWithScaleDown' in a dynamic library

### ISSUE THREAD

**Issue by CaptainOGQueefmore** [visualboyadvance-m/visualboyadvance-m#315]
### Actual behavior
Starting the emulator on Windows XP produces this error message, Couldn't find symbol 'LoadIconWithScaleDown' in a dynamic library (error 127: The specified procedure could not be found.)
The error originates from "src/wx/guiinit.cpp" in the function "MainFrame::BindAppIcon" because the "LoadIconWithScaleDown" function requires Vista+.

Could you please add an OS check to prevent this error?
The error doesn't prevent the emulator from working so this is low priority, but it would be appreciated.

### Expected behavior
No error messages.

### Steps to reproduce the behavior
Run the emulator on Windows XP.

### Build details
Windows XP SP3 x86 (32bit)
visualboyadvance-m-Windows-32bit v2.1.0

Note: This error doesn't not happen in VisualBoyAdvance-M-2.0.0-beta2 (probably because this code didn't exist then).

**Comment by rkitover** [comment]
Thank you for the detailed report, I will try to fix this for the next release.

**Comment by lukechoe629** [comment]
Same problem was found in 64-bit version on Windows XP Professional x64 Edition.

**Comment by ZachBacon** [comment]
Newer version of wxwidgets iirc has dropped support for Windows XP there will be a time where we too will have to drop platforms no longer supported by microsoft

**Comment by ZachBacon** [comment]
Since this has been a month. And no response to the matter. I'm closing this issue.
