### ISSUE TITLE
Where is the vba-m.ini? and i thought stuck on throttle was fixed? Nope!

### ISSUE THREAD

**Issue by itoikenza** [visualboyadvance-m/visualboyadvance-m#316]
i can't find my .ini file. also the stuck on 500%+ throttle glitch is still there for ver. 2.1.0
i tried switching audio plugins/setting throttle to exactly 100% and nothing, still up to 1000%+ speed sometimes!!

------------------
System Information
------------------
Time of this report: 10/1/2018, 11:25:08
       Machine name: SEVENOFMINE-PC
   Operating System: Windows 7 Professional 64-bit (6.1, Build 7601) Service Pack 1 (7601.win7sp1_ldr_escrow.180815-1700)
           Language: English (Regional Setting: English)
System Manufacturer: Apple Inc.
       System Model: Macmini3,1
               BIOS: Default System BIOS
          Processor: Intel(R) Core(TM)2 Duo CPU     P7350  @ 2.00GHz (2 CPUs), ~2.0GHz
             Memory: 8192MB RAM
Available OS Memory: 7908MB RAM

**Comment by ZachBacon** [comment]
%LOCALAPPDATA% folder, just search for the folder visualboyadvance-m. If you want to make it easier for you, once removed, just make an empty vbam.ini file beside visualboyadvance-m.exe and It'll use that instead.
