### ISSUE TITLE
VBA-M Start up Message(s)

### ISSUE THREAD

**Issue by ghost** [visualboyadvance-m/visualboyadvance-m#318]
Whenever I launch VBA-M I get a red message and it appears every ten seconds , that happens when i launch a game (any)

How do i disable that ? In an older/different version of VBA had a option of disabling it by clicking 

Options-> Emulator-> "Disable status messages" and that would disable the red message(s) from popping up

**Comment by rkitover** [comment]
What does the message say?

**Comment by goldenwarriorgw** [comment]
Well @rkitover 
![screenshot 2018-10-18 12 43 45](https://user-images.githubusercontent.com/33986489/47170442-05fa7580-d2d4-11e8-863b-41552155a22d.png)

**Comment by rkitover** [comment]
That looks like some kind of unicode decoding issue.

As a temporary workaround, put the rom in a different directory.

**Comment by ZachBacon** [comment]
I'd suggest actually renaming the rom, or better yet, save a copy and then paste it with a new name, That should confirm if it's a unicode decoding issue or not.

**Comment by theblackwidower** [comment]
That doesn't really solve the issue. Because I'm getting the same problem, only it's not an error message, it's a message saying it did a battery save. On some games, this happens quite frequently, and is quite annoying. I'd like to not have a message pop up on the screen every time it undergoes normal operation.

**Comment by rkitover** [comment]
I think we could remove these messages.

**Comment by rkitover** [comment]
@theblackwidower I've removed the "wrote battery" message in master.

**Comment by aleksrbk** [comment]
I got this issue now, saying in big red words loaded battery.
![bug](https://user-images.githubusercontent.com/42532740/108438717-247c2d00-7250-11eb-9269-ab1e61ab40f6.PNG)

**Comment by Squall-Leonhart** [comment]
That's not an issue.

**Comment by Squall-Leonhart** [comment]
>That looks like some kind of unicode decoding issue.
@rkitover

This unicode glitching is just a visual error, the writing error is due to the user having controlled folder access enabled, without whitelisting the emulator to write into this location.

Closing this, because an option has been available for some time

**Comment by aleksrbk** [comment]
Thank you for the help
