### ISSUE TITLE
Game screen off-center while in fullscreen

### ISSUE THREAD

**Issue by SvSlazer18** [visualboyadvance-m/visualboyadvance-m#325]
### Expected behavior
Game screen is correctly centralized while in fullscreen (x3 magnification)

### Actual behavior
Game screen is grossly off-center (Top-center or upper-left) & cannot be adjusted while in fullscreen

### Steps to reproduce the behavior
1. Run the latest build (V 2.1 as of writing)
2. Limit maximum magnification to x3 (May be reproducible with other settings)
3. Load any game & engage fullscreen (GB games affected)

### ROM details
Pokemon Blue (SGB)
GB games affected

### Option details
OpenGL
XAudio

### Build details
V 2.1
Windows 7

**Comment by retro-wertz** [comment]
confirmed issue in linux as well

**Comment by 84L7H13R** [comment]
Also confirming this issue on Windows 8.1.  Games used for testing were:
Mario Golf USA version for GB Color
Mario Golf Advance Tour USA version for GB Advance

**Comment by rkitover** [comment]
Fixed in master.

**Comment by rkitover** [comment]
Here's a binary that has this fixed if anyone needs:

[visualboyadvance-m.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/2825884/visualboyadvance-m.zip)

**Comment by rkitover** [comment]
This is not quite ideal yet, it works correctly on Windows but for wxGTK the game area is not centered vertically.

**Comment by rkitover** [comment]
This and related geometry/sizing issues should all mostly be fixed in v2.1.3.
