### ISSUE TITLE
Crash on GBC when Command-x is pressed (and maybe command)

### ISSUE THREAD

**Issue by Coop-1** [visualboyadvance-m/visualboyadvance-m#334]
### Expected behavior
No response from VBA

### Actual behavior
Program crashes 

### Steps to reproduce the behavior
Load Pokemon Red rom, proceed past the title screen, and then hit the 'x' and Command keys at nearly the same moment. 

EDIT: Looks like the command-x macro may be the culprit, though it's possible that command alone may cause an intermittent crash.

### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

This is what I grabbed from the core dump:
```
* thread #1, stop reason = signal SIGSTOP
  * frame #0: 0x000000010d7b11c2 dyld`__abort_with_payload + 10
    frame #1: 0x000000010d7b09b9 dyld`abort_with_payload_wrapper_internal + 82
    frame #2: 0x000000010d7b09eb dyld`abort_with_payload + 9
    frame #3: 0x000000010d76eaea dyld`dyld::halt(char const*) + 343
    frame #4: 0x000000010d7719dd dyld`dyld::_main(macho_header const*, unsigned long, int, char const**, char const**, char const**, unsigned long*) + 6827
    frame #5: 0x000000010d76b4f6 dyld`dyldbootstrap::start(macho_header const*, int, char const**, long, macho_header const*, unsigned long*) + 1154
    frame #6: 0x000000010d76b036 dyld`_dyld_start + 54
```

Let me know how else I can help in debugging this!

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
Pokemon Red and Pokemon Blue are both affected (GBC). Those are the only ones I've tested so far.

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
Unknown.

Include screenshots of ROM Information (File > ROM Information):
<img width="299" alt="red" src="https://user-images.githubusercontent.com/20648014/50370907-c7a45f80-057d-11e9-8f23-814c522d9b68.png">
<img width="299" alt="blue" src="https://user-images.githubusercontent.com/20648014/50370910-ddb22000-057d-11e9-9dd8-64fcbbd3fb06.png">

### Build details

Mac OS 10.14.1

Version of code (pre-built binary version, or commit ref, or just "master"):
Compiled debug, commit hash 0d1b23c5e87f7cedd44e4b641e5900097ee567e4

### Hardware details:
Macbook Pro, 2017

**Comment by retro-wertz** [comment]
is command + x a quit shortcut as well in macos? (not familiar with mac keyboard) if so probably its doing something like saving/loading the state/save ram while it was still not finished. does the same thing happen if you command+x past title screen? (keyboard shortcuts is a known problem, especially when its already running a game)

**Comment by retro-wertz** [comment]
im not familiar with the interface as well, as i also want some interface worked on but i still dont understand a lot of it.

your free to send in PR's if you do find fixes or any...

**Comment by rkitover** [comment]
On macos the wxwdigets Ctrl key is the mac Command key.

You can see some assigned accelerators by doing e.g.

```bash
grep '<accel>' src/wx/xrc/*.xrc
```

Ctrl+x is not bound to anything.

Command+X on macos is the "cut" command by default ion text fields, and the interface may be trying to do some sort of operation on a widget because of this, will need to look into it in more detail to figure out what.

**Comment by rkitover** [comment]
Fixed in master.
