### ISSUE TITLE
cannot run ./installdeps

### ISSUE THREAD

**Issue by heav-4** [visualboyadvance-m/visualboyadvance-m#349]
`Installing deps...

W: GPG error: https://dl.winehq.org/wine-builds/ubuntu bionic InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 76F1A20FF987672F
E: The repository 'https://dl.winehq.org/wine-builds/ubuntu bionic InRelease' is not signed.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libsfml-graphics2
E: Unable to locate package libglew1.10
E: Couldn't find any package by glob 'libglew1.10'
E: Couldn't find any package by regex 'libglew1.10'
E: Unable to locate package libsfml-window2
E: Unable to locate package libsfml-network2

ERROR: command failed.

The failing command was:
sudo apt-get -qy install build-essential g++ nasm cmake gettext zlib1g-dev libgl1-mesa-dev libavcodec-dev libavformat-dev libswscale-dev libavutil-dev libgettextpo-dev libpng-dev libsdl2-dev libsdl2-2.0 libglu1-mesa-dev libglu1-mesa libgles2-mesa-dev libsfml-dev libsfml-graphics2 libglew1.10 libsfml-window2 libsfml-network2 libopenal-dev libwxgtk3.0-dev libwxgtk3.0 libgtk2.0-dev libgtk-3-dev ccache
`
any idea what is wrong?

**Comment by retro-wertz** [comment]
use the template provided...

**Comment by rkitover** [comment]
Are you on bionic? I just ran ./installdeps on ubuntu:bionic in docker, and everything works correctly.

Check your apt configuration (`/etc/apt/sources.list` `/etc/apt/sources.list.d` etc.)

**Comment by rkitover** [comment]
Oh yeah, you will need to add a key for your wine repository.
