### ISSUE TITLE
Sound Device Resetting to Default Device

### ISSUE THREAD

**Issue by DeadSkullzJr** [visualboyadvance-m/visualboyadvance-m#353]
**Expected behavior:**
Setting up the device to output the sound to should save and remain on the specific settings I set it to unless I change the settings.

**Actual behavior:**
Setting up the device to output the sound to does not save after closing the software.

**Steps to reproduce the behavior:**
Open Options>>Audio>>Configure

Once open navigate to the "Advanced" tab and select a device to use for the sounds. After setting that up, close the software and open it again, repeat the steps to navigate to the settings, as you will see the device settings is back to "Default device".

**Crash bugs:**
None

**Option details:**
Video driver (simple, opengl):
OpenGL

**Sound driver (directsound, xaudio, openal, SDL):**
XAudio2

**Build details:**
Operating System (Windows, Mac, Linux (state distribution), etc.):
Edition: Windows 10 Pro
Version: 1803

**Version of code (pre-built binary version, or commit ref, or just "master"):**
master

I am using the latest release version of the emulator, v2.1.0:
[https://github.com/visualboyadvance-m/visualboyadvance-m/releases/tag/v2.1.0](url)

**Hardware details:**
OS: Windows 10 Pro
System Type: 64x-based PC
Motherboard: Gigabyte Z270X-Gaming 7
CPU: Intel(R) Core(TM) i7-7700k CPU @ 4.20 GHz (Clocked at 5.00 GHz)
GPU: ASUS ROG Strix GTX 1060 OC (6GB)
RAM: 16.0 GB (DDR4)

**Comment by retro-wertz** [comment]
master branch means you are compiling from the latest source. the one current available is an old version. We possibly have fixed this already in latest commit (cant remember coz im not using windows)

**Comment by DeadSkullzJr** [comment]
> master branch means you are compiling from the latest source. the one current available is an old version. We possibly have fixed this already in latest commit (cant remember coz im not using windows)

Ah well unfortunately I have no experience with building commits, so I have to settle with release versions. The only other way is if nightly builds are already pre-built and available to download. Obviously the best solution would be to learn how to "makefile" and hop to the build.

**Comment by DeadSkullzJr** [comment]
> we sadly at the moment do not have automated build system, this is something that is planned though so eventually everyone would be able to test out development releases
> 
> @ZachBacon did create anightly version for windows here:
> #354
> 
> please feel free to test and report back if there are issues.

Yep, the issue still exists with this build as well.

**Comment by ZachBacon** [comment]
@DeadSkullzJr did you remove your old config or rename it? If not, do so.

**Comment by rkitover** [comment]
Fixed in master.

**Comment by rkitover** [comment]
Latest build here has the fix: https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354
