### ISSUE TITLE
GBA Link issues, GB Link issues and other subjects

### ISSUE THREAD

**Issue by JackoboLeChocobo** [visualboyadvance-m/visualboyadvance-m#356]
Hi everybody,

I am the developer of VisualBoyAdvance Link, the first working version of GBA Multiplayer Link support for Linux and Windows. I understand thanks to @ZachBacon that VBA-M code currently has several issues on some functions / features. I want to share to you guys all the modifications and new features that would be added in VBA-M : because honestly VBA-M had some interesting fixes and features that VisualBoyAdvance Link doesn't have today.

Firstly, with my previous works on VisualBoyAdvance Link, here is a list currently I want to study for a potential repair ( [ :white_check_mark: ] ) / have successfully repair on my modified source code of visualboyadvance-m that was on my PC for the moment ( [ :heavy_check_mark: ] ) :

**[ :white_check_mark: ] GB Link cable support working**
Currently, the connection between the Server and the Client works, but games don't see each other. I have currently the same issue as @grepwood for instance on this game : https://github.com/visualboyadvance-m/visualboyadvance-m/issues/123#issuecomment-455823735
gbSerialOn had the value 0 and after value 128 during the game. How can we check if data is correctly sended / received ?

**[ :heavy_check_mark: ] GBA Link support working**
GBA Link of VBA-M was only for WX GUI... But even here the GBA Link code couldn't be used without issue (so slow). I analyzed the file "GBA.cpp" with my "GBA.cpp" file on my project VisualBoyAdvance Link and found where are the culprits.

**[ :heavy_check_mark: ] GBA Link : General Purpose Mode added ( Fixes FFTA Multiplayer Link )**
@aawilson , the mysterious build wasn't a legend ^^ I have added this support that fixes all Link features on Final Fantasy Tactics Advance ^^. Thanks to No$GBA documentation that I could firstly release this feature some years ago.
Fixes https://github.com/visualboyadvance-m/visualboyadvance-m/issues/294

**[ :heavy_check_mark: ] Add GB Printer support for platforms that don't use WXWidgets GUI, pure code**
Now, all people can have this feature easily ^^ . A file, that have the date and time as name, with .pgm extension is created in the HOME Directory of the user for the moment ( suggestions for the directory for saving the files will be welcome ). This .pgm is a ASCII file that contains the data of the image and can be opened with an image software of your choice ( Me, I use GIMP ). 
Advantages : Pure code used for the creation of the file, the pgm image can be zoomed, resized easily in your image software.
_Example of the file name : 2019_1_28-11_29_13.pgm_
_Currently location for the save of a .pgm file : $HOME for Linux, %HOMEDRIVE%%HOMEPATH% for Windows_

We need your help to report all the issues, specially for GB Link cable support. We need more results and informations about that.

Thanks for your help.

Sincerely,
Jackobo Le Chocobo

**Comment by ZachBacon** [comment]
As for removing wxwidgets GUI, that's a no. We still maintain our own interface as well as libretro so the code, I'm sorry for being strict on this, will remain.

**Comment by JackoboLeChocobo** [comment]
@retro-wertz I have questions about serial-io. Is it indeed for GB Link cable right ?

**Comment by JackoboLeChocobo** [comment]
In the end, this PR is refused. I will create a fork on my Gitlab page as I originally wanted to do because of that. My fork will include all these features. Have a nice run.

**Comment by ZachBacon** [comment]
Your PR was refused due to the nature of the changes and the nature of libretro. There's a way to implement it without using SFML

**Comment by JackoboLeChocobo** [comment]
And remove some functionalities ? Sorry but no. For information, GBALink.cpp of my project didn't use SFML but a lot of features will be unavailable on Libretro Core. I prefer again that all GUIs ( Libretro , SDL, etc. ) have the same features instead of removing some on Libretro for example. I will not change my decision. My fork will keep the same features for all supports for a unique usage for all people.

**Comment by ZachBacon** [comment]
@JackoboLeChocobo you really aren't getting what I'm trying to convey. What I'm suggesting is that there's a way to get the work done without using SFML. Like using OS level sockets. Meaning functionality wouldn't be lost, and we drop a dependency on something like SFML

**Comment by rkitover** [comment]
@JackoboLeChocobo 

SFML includes many components, like graphics, windowing and sound, and for link we would only use the networking component, none of the other ones are needed.

What I would do is include this networking component in our codebase, and your code will work just the same as it does now.

Sound good?

I can do this over the next few days, I have a lot going on here, but it should be fairly simple.

**Comment by JackoboLeChocobo** [comment]
Before I begin, who is DoctorWho11 on Gitlab ? ^^

**Comment by JackoboLeChocobo** [comment]
Today I can confirm that even if we adapted the SFML Link code to the sockets mode, the compatibility with games is not good. I tested some games after reading more issues about Link issue.

I had the issue with the current code of the project. When I put my original code, GBA Link works. But we lost some functions that are used currently in your code, and could break WxWidgets GUI.

But all my current GBALink functions doesn't use SFML at all. It uses the sockets according to a define variable : 
- POSIX_LINK for Unix systems
- if POSIX_LINK not defined, it is Windows OS systems ( tested my code under Windows 10 - 64 bit )

**Comment by JackoboLeChocobo** [comment]
The main problem is how the Link code was modified by the team ( special thanks to Squall Leonhart for instance who , in the VBA-M team, never wanted to have Linux support of the Link code ). The code was never tested after I see so so many issues during connexions. Even the GB Link connexion wasn't tested.

But currently I have results. I am only blocked on the GB Link connexion due to order connexion (?) / sync issues (?) / timing issues (?) . The GBA Link works ( I disabled IPC code and RFU ) . We need to have only the necessary features for a GBA Emulator multiplayer : GB/GBC and GBA Link . Joybus and other features would be added after that...

**Comment by JackoboLeChocobo** [comment]
If someone can look after the GB link connexion with the SFML library ( current code of VBA-M ) to see where is the issue, it can be useful. If the bug is found, share the modifications under the SFML code and I can normally adapt it to my current code and test it if it resolves on my side too

**Comment by JackoboLeChocobo** [comment]
Could it be possible to change / slow down the transmission speed on serial cable for a  GB Link ? I think the transmission is currently too much fast.

**Comment by JackoboLeChocobo** [comment]
Second possibility : GB Master (J1) is not Master and GB Slave (J2) is not Slave. How can we check correctly the data sended between the two GB on the code ?

**Comment by ZachBacon** [comment]
I'd have to look at some documentation, I'll probably do that on Sunday when it's my day off, currently at work though

**Comment by JackoboLeChocobo** [comment]
I have successfully got a connection between two GB/GBs (on the current code, 1ms of timeout is too low). We have in some games sync issue. For instance during Pokemon Battle , after an attack of the Pokemon of Player 2 : 
-> on Player 1 screen, the Pokemon of Player 1 got 2 PV left
-> on Player 2 screen, the Pokemon of Player 1 is dead

On the same game, the exchange of pokemons works.

Need help for fix that.

**Comment by Squall-Leonhart** [comment]
> 
> 
> There's a way to implement it without using SFML

not if the intention is to keep dolphin support.

> 
> 
> The main problem is how the Link code was modified by the team ( special thanks to Squall Leonhart for instance who , in the VBA-M team, never wanted to have Linux support of the Link code ). The code was never tested after I see so so many issues during connexions in some games that my code doesn't have in these same games. Even the GB Link connexion wasn't tested.
> 
> But currently I have results. I am only blocked on the GB Link connexion due to order connexion (?) / sync issues (?) / timing issues (?) . The GBA Link works ( I disabled IPC code and RFU ) . We need to have only the necessary features for a GBA Emulator multiplayer : GB/GBC and GBA Link . Joybus and other features would be added after that...
> 
> Note : when I said disabled, I simply commented the lines in the aim to keep a note of these parts for the future

All linking code was broken when the 1.8 merge happened and various contributors have provided code fixes (and shuffle fucked it worse), You still come and claim to be the vba-link author when you aren't denopqrihg.

**Comment by JackoboLeChocobo** [comment]
`not if the intention is to keep dolphin support.`
I have a solution for that don't worry, I don't need any help from you Squall.

`All linking code was broken when the 1.8 merge happened and various contributors have provided code fixes (and shuffle fucked it worse).`

For all people, here is your original message that we can see on the editor history of your post : 
>All linking code was broken when the 1.8 merge happened and various contributors have provided code fixes (and shuffle fucked it worse), **You still come and claim to be the vba-link author when you aren't denopqrihg**.

VisualBoyAdvance Link was a fork of VBALink of denopqrihg for Linux only ( denopqrihg code **worked only for Windows** ). And now it is a fork of denopqrihg project and VBA-M project. And my GBA Link support works now without issue on Windows and Linux systems under Retroarch. I AM the author of the first GBA Link support that worked on Linux.

Oh, and I remember what you said several years ago : 
-> https://www.ngemu.com/threads/visualboyadvance-link-version-1-2-general-purpose-mode-for-ffta-available.134256/#post-1849206

Post of the first version of my project VisualBoyAdvance Link : 
-> https://www.ngemu.com/threads/visualboyadvance-link-a-gba-emulator-with-multiplayer-link-support-for-linux.134121/

Post of the 1..2 version of VisualBoyAdvance Link that added General Purpose Mode ( Matteo had no issues with my project )
-> https://www.ngemu.com/threads/visualboyadvance-link-version-1-2-general-purpose-mode-for-ffta-available.134256/#post-2046128 
-> https://www.ngemu.com/threads/visualboyadvance-link-version-1-2-general-purpose-mode-for-ffta-available.134256/#post-1935787

So yeah, I AM the man who released firstly a working version of GBA Link for Linux, whether you like it or not. Always there to annoy people who do better than you. Like for the Wifi support that I corrected on Desmume-Reloaded ( https://forums.desmume.org/viewtopic.php?id=11182 ) .

**Comment by PierreAime** [comment]
@Squall-Leonhart 

It is since many years that :
- you did not test modifications of your code
- you insult members who improve your code and resolve your trash works

My brother has claimed his work for Linux and Windows since April 2010 minimum !
Source : https://www.ngemu.com/threads/visualboyadvance-link-version-1-2-general-purpose-mode-for-ffta-available.134256/#post-2045554

You know it because you was a member of this forum and you have said toxic words and liars about my brother !

The code of my brother is not broken and his software is fully operationnal now in Windows 10 and Linux system perfectly ! It can too play with General Purpose functions from Final Fantasy Tactics Advance instead of your bad works.

9 years has passed since your intervention... You have not changed and still do bad works.... Great joking boy @Squall-Leonhart 
![proof](https://user-images.githubusercontent.com/25563622/52526344-5cdaef00-2cb7-11e9-82af-101faf2e8ac6.png)
!

**Comment by Squall-Leonhart** [comment]
Thanks for reminding me you're a little bitch.

**Comment by JackoboLeChocobo** [comment]
So you never builded the VBALink version patches... The code used only functions that Windows recognizes : 
-> Download versions of VBALink : http://www.vbalink.info/download-gba-emulator.htm
-> Linux support was started from these files on the first version of VisualBoyAdvance Link several years ago : www.vbalink.info/download/V172lsrc.zip . I transformed these files to have my own Linux support.

Linux didn't have these functions and variables for instance : DWORD WINAPI, WaitForSingleObject, ResetEvent. Because I refused to install Wine to use the emulator, I created from these files the Linux version.

Do you want like always to not respect my works and denopqrihg's Windows works ? You have done nothing, you are not the creator of Windows and Linux versions. You have a serious problem and are a great liar.

Oh, and from your post when we see editor history and for me on my personnal mailbox... 

![image](https://user-images.githubusercontent.com/42393934/52529897-4f475880-2cfb-11e9-844b-2b0ccd1d1f5e.png)
![image](https://user-images.githubusercontent.com/42393934/52529900-6d14bd80-2cfb-11e9-9192-9f778288ef0b.png)
![image](https://user-images.githubusercontent.com/42393934/52529910-a0efe300-2cfb-11e9-956e-207f3d8b6bca.png)
![image](https://user-images.githubusercontent.com/42393934/52529916-b95ffd80-2cfb-11e9-8459-60bcf1d7a7c6.png)

Like always lies and insults to people are your arguments.

1°) Several years ago, on the first versions of VisualBoyAdvance Link, my parents could not afford to buy a Windows license, which is why my dad taught me to use Linux. And I do not regret, having learned a lot of computers with this.
2°) Windows 98, WIndows XP wasn't stable on computers according to my experience at school computers. I never received a request from VBA-M or you to had this code on VBA-M : new lie... . Like I said on the forums, "If you wanted to have this support on Windows, you could contact the author of VBA Link Windows version" : https://www.ngemu.com/threads/visualboyadvance-link-version-1-2-general-purpose-mode-for-ffta-available.134256/#post-1849175

![image](https://user-images.githubusercontent.com/42393934/52529999-abab7780-2cfd-11e9-89b1-f5a52841fe06.png)

3°) About what you said...
> I realise that English isn't taught properly in France these, but no lies have ever been said about your brother and nothing bad was said about the VisualBoyAdvance Link 'project' other then "A java GUI is useless to us"

I'm a French man who don't say lies and insutls to people as arguments. Once again, I know better than you my first versions of my project ...

![image](https://user-images.githubusercontent.com/42393934/52530138-0b575200-2d01-11e9-9f71-39ca294b40a0.png)

3°) Like said my brother, my project VisualBoyAdvance Link nows works perfectly on Windows ( tested on Windows 10 - 64 bits ) and Linux ( tested on Xubuntu 18.04 - 64 bits ) on Retroarch (tested on 1.7.5 and 1.7.6)

4°) I'm maybe a bitch for you, but I'm the one who do tests on the code and don't say lies when I publish features on my works. 

You said that : 
> The code was tested and functionality or lack of was logged on either the commit or a forum thread dedicated to link development.

The code was tested but that's why people can't use the GBA / GB Link support ... : 
https://github.com/visualboyadvance-m/visualboyadvance-m/issues/123#issuecomment-455823735  

So I doesn't work... On my project and on denopqrihg's project,, the functionalities that we presented works without issue...

Ticket wil be closed for now. If poeple wants to use my project , they will find it and test it if wanted. VisualBoyAdvance Link will still exists. And once again, not thank to you, Squall-Leonart, but thanks to **denopqrihg** for the GBA Link support.

**Comment by Squall-Leonhart** [comment]
>The code was tested but that's why people can't use the GBA / GB Link support ... :

Whatever happened after the Wx interface was made the primary interface has nothing to do with me.

Linking was functional under MFC.

**Comment by JackoboLeChocobo** [comment]
> I know a number of french people, insults is 7/10's of the language through off cuff sarcasm.

You are the one who insults me in my case from the start since several years, and you continue always. PDFs of the ngemu forums and from the Github tickets here and libretro will be saved like from the start.

> PS: The reason I continue to assert that you are not the credited creator of Visualboy Advance Link is because that title existed before your usage of it for the linux version

... Your argument says all ... Just for a name ... My god ... 

I do not believe it, now you said that your bothered people about their project / fork that works better than the original, project / fork that is for a non-commercial purpose with source code for just a name ... I don't know why you're the only one on the team (?) who said this argument to prove that I haven't created the Linux support, even with the links on ngemu forums ..................

I thought I saw everything in this world...

For the honor of Squall-Leonhart, I will change the name of my project VisualBoyAdvance Link ( if it can help you get better and not insult )

So from today VisualBoyAdvance Link will be called now WVBAL - Working VisualBoyAdvance Link .

Nothing more to say after that... Just disgusted but at the same time happy with my project

**Comment by Squall-Leonhart** [comment]
1.72L by denopqrihg
![image](https://user-images.githubusercontent.com/1098176/52531061-a2ed8c80-2d63-11e9-8b1b-3b17626a913c.png)

1.73L by denopqrihg

![image](https://user-images.githubusercontent.com/1098176/52531066-bbf63d80-2d63-11e9-9827-025cc607d242.png)

1.8L by denopqrihg
![image](https://user-images.githubusercontent.com/1098176/52531079-f4961700-2d63-11e9-91d1-741381b1bade.png)

**Comment by JackoboLeChocobo** [comment]
![image](https://user-images.githubusercontent.com/42393934/52531120-d94dec00-2d10-11e9-882e-93eaf7206f5e.png)

You have to read the sentences again. This is clearly written on the website of denopqrihg.

> VBALink now supports **GBA/SP multiplayer** link cable emulation and linking of up to 4 gameboy emulators

"GBA/SP multiplayer" is different of "GB/GBC multiplayer"

**Comment by JackoboLeChocobo** [comment]
To close definitibely that, I will continue to develop independently my code (GBA/GB/GBC link support , etc. ) on my fork rather than having to justify myself on the creation of my project and the work I have done since the beginning of my fork for several years.

It will be useless to try to change my mind privately just in case.

For anyone who will fall on this ticket, if you want to test my project / report bugs / suggest changes / send patches, you will be welcome of course.

**Comment by ZachBacon** [comment]
Ok so, I go off working at my job, and then this happens when I finally have 2 days free. Things really got out of hand. @JackoboLeChocobo I'm sorry for all this. I should of been around to handle all this, also I did get confirmation from endrift of mgba that it is possible to have linking without the use of sfml using just plain sockets and maintain connection with dolphin as well (this also goes to you too @Squall-Leonhart)
There are ways to solve issues without stopping to the way things have.
I have and will always try to be diplomatic. Again, I apologize for letting things get out of hand while I was away. Squall no longer speaks for the project and doesn't contribute to the project anymore. He shouldn't of said anything.
