### ISSUE TITLE
VBA-M and Dolphin Link

### ISSUE THREAD

**Issue by mtcdood** [visualboyadvance-m/visualboyadvance-m#366]
### Expected behavior
After completing steps to reproduce:
1. VBA-M will display a "look at the television" screen
2. Wind Waker will detect Game Boy Advance and open Tingle Tuner

### Actual behavior
1. VBA-M displays "Joybus host invalid; disabling" upon boot
2. VBA-M continues to display the Game Boy logo
3. Wind Waker reports that a Game Boy Advance is not connected when trying to use Tingle Tuner

### Steps to reproduce the behavior
1. Select Options> Link > Type > Gamecube
2. Select Options > Link > Local
3. Select Options > Link > Link at boot
4. Select Options > Game Boy Advance > Configure > Boot ROM and select gba_bios.bin
5. Close VBA-M
6. Reopen VBA-M
7. Load Wind Waker in Dolphin
8. Select Controllers > Port 2 > GBA in Dolphin
9. Open VBA-M
10. Select File > Open and select gba_bios.bin
11. Use Tingle Tuner in Dolphin

### ROM details
gba_bios.bin only
### Which games are affected by the issue (please state if GBA or GB game):
Wind Waker
### Option details
Default options other than listed steps to reproduce
Video driver (simple, opengl):
OpenGL
Sound driver (directsound, xaudio, openal, SDL):
DirectSound
### Build details
VisualBoyAdvance-M 2.1.0
Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows
Version of code (pre-built binary version, or commit ref, or just "master"):
Pre-built binary

**Comment by JackoboLeChocobo** [comment]
I'm currently working on the Link code part of VBA-M. Can you add too please the Dolphin version yiu used here ? Can you add too please your Windows version ( Windows 10 - 64 bits for instance ) ?

**Comment by mtcdood** [comment]
Dolphin 5.0-9494

Windows 10 x64

**Comment by JackoboLeChocobo** [comment]
Thank you @mtcdood

**Comment by mtcdood** [comment]
Is the link feature intended to be usable with an instance of Dolphin running on another machine? I was unable to achieve that.

**Comment by JackoboLeChocobo** [comment]
> Is the link feature intended to be usable with an instance of Dolphin running on another machine? I was unable to achieve that.

That's the goal indeed ^^ Instead of using SFML, it will use original OS sockets code, more stable. It wasn't stable currently with the SFML code.

**Comment by denisfa** [comment]
Fixed in #448.
