### ISSUE TITLE
Games Crashes When I Open Any Game With 2.1.0

### ISSUE THREAD

**Issue by Grip555** [visualboyadvance-m/visualboyadvance-m#367]
### Expected behavior
For it not to crash.

### Actual behavior
Crashes as soon as I try to open any game, after extracting, then closes.

### Steps to reproduce the behavior
Start up any game after extracting. Without extracting from winRAR, it works fine.

### ROM details
I've tried:
ROM hacks (Pokémon Cloud White, Pokémon Jade and Pokémon Adventures)
Pokémon FireRed 1.0 (U)
Dragon Ball Z Supersonic Warriors (E)
Dragon Ball Z Supersonic Warriors (U)
Legend of Zelda - A Link to the Past + Four Swords (U)

### Option details
Default options.

### Build details
2.1.0

### PC Information:
Windows 10
1070 GTX
16GB RAM
4.0GHz

**Comment by ZachBacon** [comment]
Can you test with one of the nightlies that are provided in the stickied issue thread?

**Comment by Grip555** [comment]
I have the exact same issue.

**Comment by retro-wertz** [comment]
this confusing and need more details. if you are using WinRAR, i assume the files are .RAR? coz this is not supported. it does not make sense that compressed the game runs but not uncompressed? whats the original filename and extension the file is? and whats the actual filename or contents of this compressed file? did you change language something else other than english?

**Comment by Grip555** [comment]
It's in a .zip, but I use WinRAR to open it. Also, I found that if I put the emulator in any other folder but my VBA one, it will work.

**Comment by retro-wertz** [comment]
> It's in a .zip, but I use WinRAR to open it. Also, I found that if I put the emulator in any other folder but my VBA one, it will work. Which is odd, since other versions of VBA work in my VBA folder.

are you running this from another launcher?

**Comment by Grip555** [comment]
I'm using VBA, I just had to put it in another folder to keep it working. Though I do find that no matter which version I use, the audio always ends up hanging (I know it's another issue, but I thought 4.1.0 would fix it).

**Comment by retro-wertz** [comment]
must be a config issue try delete any existing config you have. you need to find where though since im not using windows.

all i can say even the very old vba works with especially with uncompress roms

**Comment by Grip555** [comment]
I did extract it though. I just don't get the audio hanging thing.

**Comment by retro-wertz** [comment]
i dont see the relevance of audio with the original issue that zip roms runs but not when unzipped..

in any case try to change the default audio device Option > Audio > Advance and see if helps with any of those issues you have.

**Comment by Grip555** [comment]
I tried all audio options, but they always end up hanging.

**Comment by Squall-Leonhart** [comment]
upgrade your audio drivers, they are faulty.

**Comment by rkitover** [comment]
@Grip555 can you please open a new issue for this and fill out the template as much as possible
