### ISSUE TITLE
Feature Request: Factory Reset Option.

### ISSUE THREAD

**Issue by srchronotrigger** [visualboyadvance-m/visualboyadvance-m#368]
Put a factory reset option to delete the config file in %appdata% automatically. Simple, direct and easy to implement.

**Comment by rkitover** [comment]
added in master

**Comment by srchronotrigger** [comment]
Hello, your project is amazing, thanks for the quick reply It is good to know that there are people who care about the old games. ;)

**Comment by rkitover** [comment]
Released in v2.1.1
