### ISSUE TITLE
failed to build

### ISSUE THREAD

**Issue by Askmewho** [visualboyadvance-m/visualboyadvance-m#371]
Hi devs! I am on the pi3 on raspbian
there is some issue with that cpp. or i need to include something...

-- Found SFML 2.4.1 in /usr/include
-- Found gcc-ar: /usr/local/bin/gcc-ar
CMake Error at cmake/HostCompile.cmake:27 (message):
  Failed compiling
  /home/pi/Desktop/src/visualboyadvance-m/build/gcc-ar-wrap.c for the host:
Call Stack (most recent call first):
  cmake/PathRun.cmake:70 (host_compile)
  cmake/UseGCCBinUtilsWrappers.cmake:81 (MAKE_PATH_RUN_WRAPPER)
  CMakeLists.txt:490 (include)

**Comment by rkitover** [comment]
Do you have a `cc` program in your PATH? What does:

```bash
which cc
```

say?

Also try building with `-DENABLE_LTO=OFF`.
