### ISSUE TITLE
GBA Hello Kitty Collection - Miracle Fashion Maker (Japan) black screen

### ISSUE THREAD

**Issue by benderscruffy** [visualboyadvance-m/visualboyadvance-m#375]
VisualBoyAdvance-M v2.1.1
nothing but a black screen fails to boot

**Comment by Testsr** [comment]
https://github.com/mgba-emu/mgba/commit/93633ea60524ac2983e747e13656b896544299cf

**Comment by Testsr** [comment]
https://mgba.io/2020/01/25/infinite-loop-holy-grail/

**Comment by ZachBacon** [comment]
@Testsr thanks for the relevant information, and @benderscruffy You're using an old version, current release is [2.1.4](https://github.com/visualboyadvance-m/visualboyadvance-m/releases/tag/v2.1.4) (though that won't matter as I'm positive it'll still not work.)

I'll look at about seeing if we can adapt this to vba-m.
