### ISSUE TITLE
GB Prehistorik Man (USA, Europe) scroller corrupt

### ISSUE THREAD

**Issue by benderscruffy** [visualboyadvance-m/visualboyadvance-m#379]
VisualBoyAdvance-M v2.1.1
on the title screen the scroller is corrput

**Comment by rkitover** [comment]
Hi,

maybe you could track GB compatibility in a single issue, they are editable.

Also are you using a bios file? That can sometimes help.

**Comment by benderscruffy** [comment]
yep always use the bios
have to change from gameboy colour to automatic
