### ISSUE TITLE
Localization?

### ISSUE THREAD

**Issue by TroudhuK** [visualboyadvance-m/visualboyadvance-m#381]
On portable version (v2.1.1):

### Expected behavior
Use the FR locale, french translation

### Actual behavior
English, no language configuration menu found.

### Steps to reproduce the behavior
Try to display non-English localization

### Build details
Windows 10 x64

**Comment by rkitover** [comment]
You need to extract `translations.zip` to the same directory as the executable.

**Comment by TroudhuK** [comment]
Ok. I forgot to explain that I have locale.7z downloaded from http://vba-m.com/ (locale folder near the .exe), but the change is that the language folders are directly near the .exe, and that the website is not up-to-date and we have to download this new translations.zip from here:
https://github.com/visualboyadvance-m/visualboyadvance-m/releases/download/v2.1.1/translations.zip
Thx.
