### ISSUE TITLE
Gameboy bugs in  VisualBoyAdvance-M v2.1.1

### ISSUE THREAD

**Issue by benderscruffy** [visualboyadvance-m/visualboyadvance-m#382]
using VisualBoyAdvance-M v2.1.1 with bios

Speedy Gonzales (USA, Europe) 
during gameplay the HUD down the bottom is corrupt
![speedy](https://user-images.githubusercontent.com/2696404/53675211-4846b100-3ccf-11e9-976e-aedb84e3f889.PNG)

Altered Space - A 3-D Alien Adventure (Europe)
during the intro the screen doesnt scroll down far enough
![altered](https://user-images.githubusercontent.com/2696404/53675222-67ddd980-3ccf-11e9-8ba2-fb2e2bbe96ef.PNG)

Versatility by The New Image demo
all the graphics are messed up
http://www.pouet.net/prod.php?which=1795
![versatility](https://user-images.githubusercontent.com/2696404/53675665-98c00d80-3cd3-11e9-867f-4c6ab385a75c.PNG)

Buster Bros. (USA)
After pressing A at the title screen, the countdown should be started at 9 but starts at 8

Killer Instinct (USA, Europe) (SGB Enhanced)
when you press start you come up as player 2 instead of player one
![killer](https://user-images.githubusercontent.com/2696404/53679891-2fa9bb80-3d0e-11e9-85d1-dcc5b0800bb7.PNG)

Heracles no Eikou - Ugokidashita Kamigami (Japan)
cannot save 
![heracles](https://user-images.githubusercontent.com/2696404/53680039-5a950f00-3d10-11e9-82e1-d50df41b99d6.PNG)

Donkey Kong (Japan, USA) (SGB Enhanced) missing the voice of the woman as seen in this video
https://youtu.be/t2iicAjF9xI?t=121

**Comment by Squall-Leonhart** [comment]
Can you try one of these nightlies
https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354#issuecomment-457876139

if they work, the issue specifically comes back to a change made to gbgfx.cpp on Feb 2.

**Comment by Squall-Leonhart** [comment]
Donkey Kong voice is working as expected of what we emulate (we don't emulate the SGB APU)
