### ISSUE TITLE
Weird Sticky Keys Issue

### ISSUE THREAD

**Issue by sorin255** [visualboyadvance-m/visualboyadvance-m#390]
### Expected behavior
When movement keys are released, that key's input will stop being read.

### Actual behavior
When a movement key is pressed, often after being held for a bit, movement in that direction will continue until the key is pressed again.

### Steps to reproduce the behavior
First noticed in Fire Red. Tried changing keys to see if it was just an issue with my directional keys but it was the same experience. Made sure autofire and turbo were cleared and turned off.
Tested in other games: Sonic Advance, then Donkey Kong Land (GB) and was having the same issues there.
Didn't seem to be having the issue with my joypad.

### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game): Pokmeon Fire Red (GBA), Sonic Advance (GBA), Donkey Kong Land (GB)

Which games, if any, are NOT affected by the issue (please state if GBA or GB game): none that I can tell

Include screenshots of ROM Information (File > ROM Information):

### Option details

Video driver (simple, opengl): OpenGL

Sound driver (directsound, xaudio, openal, SDL): OpenAL

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Linux (Ubuntu 18.04)

If using Linux, specify if using xorg or Wayland: xorg

Version of code (pre-built binary version, or commit ref, or just "master"):

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it: xbox one controller 2017 firmware, just default xpad driver

**Comment by rkitover** [comment]
Which keys did you map for movement? arrows?

**Comment by sorin255** [comment]
Arrows initially and then WASD when replicating the issue.

**Comment by rkitover** [comment]
Thanks, I'll see if I can reproduce this.

**Comment by shibatan** [comment]
Wanted to chime in that I'm experiencing this (also in Fire Red) but exclusively while using Throttle.

**Comment by rkitover** [comment]
Please try latest nightly.

**Comment by denisfa** [comment]
@sorin255 @shibatan We had a very similar issue reported (#142) and I believe they are the same problem. The fix has been merged, so it will be available on version `2.1.4`.
