### ISSUE TITLE
Painful building issue under CentOS 7.6

### ISSUE THREAD

**Issue by chenjaq** [visualboyadvance-m/visualboyadvance-m#395]
### Expected behavior
installation successfully pass the make process under Centos7.6.

### Actual behavior
The make process was interrupted by multiple errors taking places  at the wxvbam.cpp file. 

### Steps to reproduce the behavior
1、Finished pre-install as the last comment mentions of reported issue#297.
2、And then did the following with gcc-c++compiler installed:
2.1mkdir build && cd build
2.2cmake3 -DENABLE=NO ..
2.3make -j`nproc`

### Crash bugs
the crash during make process is cause by the both the wxGTK3 and wxGTK-2.8 package is used and mixing up during the compiling. 

### Build details
By following the installation steps from the last comment of reported issue#297, it first told to install wxGTK3, then install wxGTK(this will lead to actually install wxGTK-2.8). During the cmake process, it will take the lower version which is wxGTK2.0 instead of wxGTK3. All relevent matter will take wxGTK2.0 to compile their source code, which will give you the painful compiling issue of all wxvbam.cpp coversion(ie. wxString) issue. If cmake was ran without wxGTK-2.8 installed,  the makefile process cannot detect wxrc becase of the install path issue of wxGTK3.

#297

**Comment by rkitover** [comment]
I will take a look.

**Comment by denisfa** [comment]
> By following the installation steps from the last comment of reported issue#297, it first told to install wxGTK3, then install wxGTK(this will lead to actually install wxGTK-2.8). During the cmake process, it will take the lower version which is wxGTK2.0 instead of wxGTK3. All relevent matter will take wxGTK2.0 to compile their source code, which will give you the painful compiling issue of all wxvbam.cpp coversion(ie. wxString) issue. If cmake was ran without wxGTK-2.8 installed, the makefile process cannot detect wxrc becase of the install path issue of wxGTK3.

I can confirm this. The following script works:
```
## RHEL/CentOS 7 64-Bit ##
yum -y groupinstall "Development Tools"
yum -y install libpng-devel SDL2-devel zlib-devel mesa-libGL-devel wget cmake
# https://www.tecmint.com/how-to-enable-epel-repository-for-rhel-centos-6-5/
wget http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
rpm -ivh epel-release-latest-7.noarch.rpm
yum -y install wxGTK3-devel wxGTK3
# GIT
git clone https://github.com/visualboyadvance-m/visualboyadvance-m.git
cd visualboyadvance-m && mkdir -p build && cd build
cmake .. -DENABLE_LINK=OFF -DWXRC='/bin/wxrc-3.0' -DwxWidgets_CONFIG_EXECUTABLE='/bin/wx-config-3.0'
make -j`nproc`
```

Both `wx-config` and `wxrc` names are reserved for the stable version. For centOS it is **2.8**.

**Comment by rkitover** [comment]
@denisfa thanks for the script!

I am actually looking into why it doesn't build for the centos version of 2.8, which is a unicode build, and once I fix this I will also make any necessary cmake and installdeps adjustments. Actually I'll make a branch for this now with what I have, it's centos-fixes. That has mostly working installdeps support.
