### ISSUE TITLE
Analog Stick on GameCube controller triggering in-game movement even though it is in resting position

### ISSUE THREAD

**Issue by anLizard** [visualboyadvance-m/visualboyadvance-m#397]
Demonstration: 
https://gfycat.com/MetallicRapidHen
https://gfycat.com/SingleMessyDolphin

The GameCube controller does not show this behavior in other applications. I tested this with four different GC controllers on all four ports.
Other kinds of controllers do not have this issue in VBA-M (Xbox One S, 8Bitdo SF30 Pro).

### Expected behavior
After letting go of the GameCube controller's analog stick, the in-game character should stop moving.

### Actual behavior
After letting go of the analog stick, the in-game character keeps moving in the direction the stick was tilted in before.

### Steps to reproduce the behavior
Configure the GameCube controller's analog stick in VBA-M to be used for Up, down, left, right.
Tilt the stick in one direction while playing, then let go.

### ROM details
Which games are affected by the issue (please state if GBA or GB game):
Tested with Pokemon Ruby, and the GBA BIOS linked to Dolphin running Four Swords Adventures locally.

Include screenshots of ROM Information (File > ROM Information):
https://imgur.com/a/BUO1EQw

### Option details
Video driver (simple, opengl): OpenGL
Sound driver (directsound, xaudio, openal, SDL): SDL

### Build details
Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 10 Pro 64-Bit 1803

### Hardware details:
GameCube Controller (DOL-003), connected to the PC using the Mayflash GC adapter in PC mode. I did not install any additional drivers.

**Comment by rkitover** [comment]
This is on 2.1.1 right?

**Comment by anLizard** [comment]
Yeah, 2.1.1 Windows 64-bit

**Comment by anLizard** [comment]
After some more playing around, I found out that the issue is not present on 2.1

**Comment by rkitover** [comment]
fixed in v2.1.2
