### ISSUE TITLE
Last window size isn't remembered, top of GBA screen cut off

### ISSUE THREAD

**Issue by anLizard** [visualboyadvance-m/visualboyadvance-m#406]
### Expected behavior
Emulator remembers window size from last time it was launched.
![image](https://user-images.githubusercontent.com/48686356/55685496-4bc8fa00-5957-11e9-9a28-51c423f79ba9.png)

### Actual behavior
Emulator always starts with same window size, regardless of previous size and the top of the GBA screen is cut off.
![image](https://user-images.githubusercontent.com/48686356/55685488-33f17600-5957-11e9-81f4-b6de79b28407.png)
Resizing window solves it until emulator is closed again.

### Steps to reproduce the behavior
Launch any ROM without changing window size

If you are using a BIOS file, please say which one.

### Option details
Video driver (simple, opengl):
opengl

Sound driver (directsound, xaudio, openal, SDL):
sdl

### Build details
Operating System (Windows, Mac, Linux (state distribution), etc.):
Window 10 Pro 64-bit 1803

### Config file
https://privatebin.net/?0754d5cfe01a7ff5#3/eqNRrFDtCt1oTHaXZIJ4sLrNSYQPXMzoGXy7UUmbA=

**Comment by retro-wertz** [comment]
mine does as well...

until you resize window then it updates...

**Comment by rkitover** [comment]
@denisfa looks like we have more work to do on this one

**Comment by denisfa** [comment]
Yeah, can confirm both. One of them is an issue with the position `(0,0)` being a weird point for the app. The other one was new to me, though. I will working on a solution.

**Comment by rkitover** [comment]
@anLizard hey, could you please test the latest release and see if you still have any geometry/position issues

**Comment by anLizard** [comment]
> 
> 
> @anLizard hey, could you please test the latest release and see if you still have any geometry/position issues

Seems fixed on new release, although I get black bars. 
![image](https://user-images.githubusercontent.com/48686356/56356943-842fca00-61da-11e9-8885-01d2305024e3.png)

**Comment by rkitover** [comment]
Yeah the black bars are because of the "keep aspect ratio" option, you can stretch the window to minimize their appearance.
