### ISSUE TITLE
windows XP compatibility

### ISSUE THREAD

**Issue by rkitover** [visualboyadvance-m/visualboyadvance-m#407]
Some users on reddit are reporting incompatibility with XP, it may be possible to tweak the mingw build scripts to support it.

**Comment by rkitover** [comment]
This is the error:

![](https://i.ibb.co/zNk9fWG/err.jpg)

**Comment by denisfa** [comment]
@rkitover Was this working before? If it was, I believe this is related to the compilation warning fixes. Probably somewhere there is an initialized `std::string` with `NULL` or `nullptr`.

**Comment by rkitover** [comment]
No idea if and when this was working before, someone reported it on reddit, but I don't think we should change our code for this.

**Comment by denisfa** [comment]
Well, I believe XP is no longer supported by MS since 2010... So, what will you check exactly?

**Comment by rkitover** [comment]
There is a way to set the windows API version with mingw with a define, I believe the current default is vista.

**Comment by Squall-Leonhart** [comment]
Visual studio needs a compatibility toolchain to retain XP compatibility.

**Comment by denisfa** [comment]
@rkitover Before I forget about this, the error is [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/src/Util.cpp#L78). This variable does not exist for `winXP`; all the API actually changes after `winXP`. There is a better way to get the equivalent of this variable, I have a test code ready with this. We can do this as a workaround:

```
char *appdata = getenv("LOCALAPPDATA");
std::string app_data(appdata ? appdata : getenv("APPDATA"));
```

**Comment by rkitover** [comment]
I think now that I know more about this, we can just forget about this.

It's not even possible to build the toolchain for this project on mingw targetting XP, a lot of things need the Vista API or higher. Some things now need the Windows 7 API.

So I will just close this as WONTFIX.

**Comment by denisfa** [comment]
@rkitover Just to be sure that this is known... If you use the fix suggested and compile for `i686` using minGW, it works out of the box for Windows XP. That is how I tested it.

I agree with dropping support because XP is very old.

**Comment by rkitover** [comment]
@denisfa oh it actually works on XP? That's very interesting, the later APIs in the libraries must not then be in the codepaths that we use. I might take a look at this again then.

**Comment by ZachBacon** [comment]
I think it's partly because mingw-w64 crt has been focusing on platforms other than i686 more, most recently someone started updating the crt for i686, so I'm not entirely sure how long it'll work.

**Comment by rkitover** [comment]
Ok I added a fallback to `APPDATA` if `LOCALAPPDATA` is not set, if this works for any poor soul still running XP, then excellent.
