### ISSUE TITLE
cmake: add compiler check for ASAN

### ISSUE THREAD

**Issue by Alkaris** [visualboyadvance-m/visualboyadvance-m#409]
I need to compile VisualBoyAdvance-M with Network Link, because it's not enabled for some reason in the official build of 2.1.1, however going to compile it complains that the compiler can't find SFML or SSP (gcc-4.8) and GTK (gtk-2.0/gtk-3.0) even though they exist, dev packages and all.

```
/usr/include/SFML
[...]
/usr/share/SFML
/usr/share/SFML/cmake
/usr/share/SFML/cmake/Modules
/usr/share/SFML/cmake/Modules/FindSFML.cmake
/usr/include/gtk-2.0
[...]
/usr/include/gtk-3.0
```

```
$ cmake ..
Could NOT find SFML (missing:  SFML_NETWORK_LIBRARY SFML_SYSTEM_LIBRARY)
CMake Warning at CMakeLists.txt:232 (message):
  SFML not found, LINK will be disabled


-- Found gcc-ar: /usr/bin/gcc-ar
-- Found gcc-nm: /usr/bin/gcc-nm
-- Found gcc-ranlib: /usr/bin/gcc-ranlib
-- Could NOT find SSP (missing: SSP_LIBRARY) 
CMake Error at src/wx/CMakeLists.txt:538 (message):
  Could not find gtk


-- Configuring incomplete, errors occurred!
```

Looks to me that it's not looking in the right places to find them or using the wrong syntax in the code to search for them, the proper directory is `/usr/include/` is where it's suppose to search for the libraries it needs for compiling, and SSP is has since been included in GCC since 4.1. The error message for "Could not find gtk" is too vague of a message, what are you expecting? libgtk-2.0(-dev)? gtk-3.0(-dev)?

[CMakeOutput.log](https://gist.github.com/Alkaris/c46f6ede5ea281cfac6b4e20dfd83db4#file-cmakeoutput-log)
[CMakeError.log](https://gist.github.com/Alkaris/2f47cda1db096e55c48b496babe488ea#file-cmakeerror-log)

```
Linux Mint 19.1 4.15.0-46-generic #49-Ubuntu x86_64 GNU/Linux
```

**Comment by retro-wertz** [comment]
you can run *installdeps* to get dependencies

**Comment by Alkaris** [comment]
@retro-wertz I've already run that, makes no difference.

**Comment by rkitover** [comment]
check your environment variables, do you have things like `LDFLAGS` set? I'm fairly sure there should be no issues on mint as there are no issues on ubuntu.

**Comment by denisfa** [comment]
@Alkaris Could you provide some more info about your build? I am trying to reproduce this error, but without any success. I did a new install on a virtual machine using this [MATE ISO x64].(https://www.linuxmint.com/download.php)

After the install, I executed:
```
$ sudo apt install git
$ git clone https://github.com/visualboyadvance-m/visualboyadvance-m.git
$ cd visualboyadvance-m
$ ./installdeps
$ mkdir -p build && cd build
$ cmake .. -DENABLE_LINK=ON && make -j`nproc`
```

I believe the `ENABLE_LINK` option was changed very recently to default `OFF` due to issues when building on some platforms.

Also, do you have any type of custom setup for these tools? Overriding some binaries or anything?

**Comment by rkitover** [comment]
I see you enabled ASAN and your compiler does not support it, this is why cmake fails all of its tests.

**Comment by rkitover** [comment]
I need to do a proper compiler check for ASAN, and it should not be enabled in release mode.

**Comment by Alkaris** [comment]
Okay so I did a fresh git clone and it managed to compile properly this time, however, when I go to run it I now end up with a segfault.

```
$ ./visualboyadvance-m 
libpng warning: Application jmp_buf size changed
Segmentation fault (core dumped)
```

**Comment by rkitover** [comment]
@Alkaris that is a separate issue, please show all the steps you used to compile, and don't turn on any options you don't need.

**Comment by Alkaris** [comment]
Might be a separate issue, but it's still related.

all I did was run
```
cmake .. -DENABLE_LINK=ON && make -j`nproc`
```
after doing a clean clone download.

**Comment by rkitover** [comment]
That is strange and I don't know what can cause that, the issue seems to be in `libpng`, some things I'd suggest:

Do a:

```bash
apt -y update
apt -y upgrade
```

Run this command on the binary:

```bash
ldd visualboyadvance-m
```

look for any strange paths, especially to the `libpng.so`.
