### ISSUE TITLE
cannot load ROMs with unicode characters

### ISSUE THREAD

**Issue by simperen** [visualboyadvance-m/visualboyadvance-m#410]
Unable to open the Zip format compression package with Chinese name,Prompt message:XXXX.zip is not a valid Rom file.

if the Zip package is English name，no error will be reported.
But，The same chinese ZIP package can run normally on 2.1.1.

**Comment by simperen** [comment]
![1111](https://user-images.githubusercontent.com/26716558/55887205-af655880-5bdf-11e9-8755-44e7950db3e2.png)

**Comment by denisfa** [comment]
@simperen Thanks for reporting! We will see what is happening.

Some more information, for debugging purposes. I tested on a `Windows 7 x64` virtual machine:

1. the `2.1.1` did not work for me when using a chinese ZIP. The ROM was a Pokemon game, and I only changed the zip name. I did two runs: one before installing the chinese language pack and one after.

2. Same error appeared to me on `2.1.2`; so it kept this behaviour.

When running on Linux x64 (my host), the chinese ZIP worked perfectly. I did not need to set locale or anything similar.

**Comment by mudlord** [comment]
My guess is that somewhere Wx is messing up with UTF16. And on Linux everything is plain UTF8 so everything there is just fine.

**Comment by rkitover** [comment]
That is indeed the problem, but it's a bit more complicated.

On Windows wx handles `UTF16` just fine, and `wxString` can be internally represented by `wchar_t` or `char` as necessary and this is transparent to the user.

The problem arises when the user wants to pass a filename to a function taking a `const char*` as we are doing with various core and utility functions, which may in turn call other OS or runtime functions.

This will not be simple to fix.

**Comment by rkitover** [comment]
And of course on windows if you want to open a unicode filename, you have to use functions such as `_wfopen()` and not the regular `fopen()` etc..

Right now I'm thinking of implementing perhaps some clever solution involving macros and the preprocessor and/or C++ function overloading.

**Comment by mudlord** [comment]
With einweggerat I have to constantly convert between UTF16/ANSI/UTF8.

I made a small class to convert between the 3 using C++ strings and the Windows string conversion functions. 

Maybe something similar could be done?

**Comment by rkitover** [comment]
Thank you, I may need some of those.

**Comment by denisfa** [comment]
Fixed in #446.
