### ISSUE TITLE
add hotkeys for 10 save states

### ISSUE THREAD

**Issue by SLaks** [visualboyadvance-m/visualboyadvance-m#411]
### Expected behavior

Load / Save State submenus in Key Shortcuts dialog should have entries for `1` through `10`

### Actual behavior

![image](https://user-images.githubusercontent.com/313894/55905706-896c9380-5ba0-11e9-9c5c-8543aa6951c4.png)

On Windows 10

**Comment by RunisDauphin** [comment]
It does not matter which version of Windows you use: it is still present (in 2.1.3) in Windows 8.1 since 2.0.x, when vba-m.com looked completely different.
