### ISSUE TITLE
Add Auto-hold keys, VBA-RR style

### ISSUE THREAD

**Issue by RunisDauphin** [visualboyadvance-m/visualboyadvance-m#414]
Have autofire keys for all buttons and autohold keys like VBA-RR has. Autohold keys invert the behaviour of the keys: if you selected Autohold B, while you press the B button is unpressed and when you do not press the B button, B button is pressed. If you get tired of autohold or it is not necessary for that part, with the correspondant key the behaviour is returned to normal.

**Comment by retro-wertz** [comment]
from my understanding, this would mean pressing and holding the button will only activate the the button one frame, then activated again once released? so if this was super mario holding B wont make him run fast?

is this a hardware behavior and what the use-case for this...

**Comment by rkitover** [comment]
How should the autohold for a button be turned off?

**Comment by RunisDauphin** [comment]
In VBA-RR, to turn off the auto-hold is by a specific key.

When you open VBA-RR and you go to Options -> Input, you find an Auto-Fire section and an Auto-Hold section. You can set a hotkey to every Auto-Fire Button and Auto-Hold Button in Options -> Input -> Customize All Commands...

The Auto-Fire buttons you know already how they work (and I like them as they are). The Auto-Hold Buttons have a toggle (the Auto-Hold Button command) and from now the behaviour of the button is inverted. If you press a second time, it gets back to normal.

Here is an example: Imagine I run in Megaman Battle Network games (made by B button, assigned in my case to S key), but I feel so lazy that I want to run without pressing any key (Star Force style). What I do is press Auto-Hold Key for B (assigned to W in my case) and Lan / Netto or Megaman / Rockman will run whatever I do (even while pressing Fast-Forward). And, in combat, I can charge my weapon, then press B button (which makes the buster shoot because I release the button) and immediately start charging again (because I press the B button again).

In Retro-Wertz's example, that would be:
If I press the Auto-Hold B, I would shoot a fireball (if I can) and run continuously until I press Auto-Hold B. If I want to shoot fireballs, I could simply press the B button (while Auto-Hold B is active) and still run with no much problem.

This is the latest version I could find of VBA-RR:
emucr.com/2019/02/vba-rerecording-git-20190207.html
I do not think this link is violating any law in the Union Européene, so please keep it.

I would give you my configuration files of VBA-M 2.1.2 / 2.1.3 and VBA-RR, but apparently is not supported by Github. If I can send them to you, tell me and I will give them to you.

Thanks for your attention, M. Kitover and Retro-Wertz, and I hope this could get implemented: once you try it, there is no going back.

**Comment by ZachBacon** [comment]
We rather take sources directly from the projects website not emucr.

**Comment by rkitover** [comment]
Yeah thanks for the detailed description, it doesn't sound difficult to implement.

**Comment by RunisDauphin** [comment]
Much welcome. I gave that direction because I had troubles to find that exactly fork everywhere else. I do not know if the original source code is still accessible somewhere.

Thanks, and I hope the project could progress well. If you can, could you put an option to show the input? That is, if active the option, the emulator would show which console button I am pressing. It is not a big deal for normal input, but it is a huge deal for Auto-Fire and Auto-Hold still active. In VBA-RR is under Options -> Head-Up Display -> Input, and works similar to the one present in DeSmuME.

Thanks for your attention, M. Kitover, Retro-Wertz and Bacon.

P.S.: Sorry for the typo when I wrote "Union Européenne".

**Comment by trlkly** [comment]
Another use case is just to enable being able to press a bunch of keys at once on a keyboard where that only allows a limited number of keys held at a time. If you could toggle the key down and key up, then you could press them separately. 

Currently, my workaround is just to assign multiple keys to the same button, but that's a bit annoying if you have more than one button combination you need to cover. (I've assigned F1 to A, B, START, SELECT, L, and R, so that I can easily do the in-game reset method, which sometimes is different than a soft-reset, like in Link's Awakening, where it is the only way to save without dying.

**Comment by rkitover** [comment]
@trlkly I'm not sure I understand fully, you mean we should disambiguate separate key binds when multiple keys are pressed together? If so, please open a separate enhancement request, thank you!

**Comment by denisfa** [comment]
@RunisDauphin Several of the issues you opened are now coded/fixed. Check some of them on our next release (it should be soon).
