### ISSUE TITLE
Add a hotkey for changing sizes, such as mGBA and previous versions of VBA do

### ISSUE THREAD

**Issue by RunisDauphin** [visualboyadvance-m/visualboyadvance-m#415]
Have a hotkey for changing window size (for example, if want the window 4x the real size, I can press key "4" and it automatically changes, but if I want it later 2x the real size, simply I press "2" then and it reverts back).

### Actual behavior

You have to change it manually in Options -> Video -> Configure -> Zoom -> Default Magnification. Also, for some reason, there are like 40 pixels beneath the "game screen" (my vbam.ini file says window is 741 pixels tall) that are black.

**Comment by rkitover** [comment]
What are the default hotkeys in mGBA and previous versions of VBA?

**Comment by RunisDauphin** [comment]
In mGBA version 0.7.1, there is no default hotkey to adjust sizes, but you can assign them in Tools -> Settings -> Shortcuts -> Audio/Video -> Frame Size, and there you can give shortcut keys to sizes from 1x to 6x.

Thanks for your attention, M. Kitover.

**Comment by rkitover** [comment]
Ok, so, what are the default hotkeys you would like for this? Perhaps ctrl-1 through ctrl-9 or some such? But people wanted those buttons for save states. We could use ctrl+shift or some such.

**Comment by RunisDauphin** [comment]
It could be: I do not mean it NEEDS to have a default hotkey, just have a hotkey (that can be empty by default) to make that thing. I think mGBA or even the Visual Boy Advance 1.8.0's Beta 3 do it just right.

In Visual Boy Advance 1.8.0 Beta 3, there are four options (named in x1 to x4 in Options -> Video) who have no default hotkey, but can be assigned in Tools -> Customize -> OptionsVideoXn (which n is all numbers between 1 and 4).

I hope I could have helped you with this work.

Thanks for your attention, M. Kitover.
