### ISSUE TITLE
Clear button on Input Configuration works weird

### ISSUE THREAD

**Issue by RunisDauphin** [visualboyadvance-m/visualboyadvance-m#416]
I expect it should clean only the button configuration you are in.

### Actual behavior

It cleans all the buttons, and there is no button to eliminate only one button.
The only way I can do it is by manually change them in vbam.ini and search for the wanted command.

**Comment by rkitover** [comment]
you can press backspace to delete a button

**Comment by rkitover** [comment]
I could add a button next to each box to clear it, and rename the bottom clear button "reset".

**Comment by RunisDauphin** [comment]
That would be great. By now, this is the only emulator I found that does this kind of things.

Thanks for your attention, M. Kitover.
