### ISSUE TITLE
config settings for hotkeys get overwritten

### ISSUE THREAD

**Issue by RunisDauphin** [visualboyadvance-m/visualboyadvance-m#417]
### Expected behavior
vbam.ini file should stay the same way as it was kept before moved or actualised.

### Actual behavior
vbam.ini file changes some options to the default values or varies things.
For example, when updated, it has two lines of Reset=TAB in the file (one between "Save=CTRL+S" and "JoypadAutofireA=D" and the other between "CLOSE=SHIFT+TAB" and "ToggleSound=SHIFT+0"), giving me the "Entry 'Reset' appears more than once in group '/Keyboard'" error warning.
Another example is the fact that some of the default hotkeys I pulled off return to the file. For example, I always establish F as Auto-Fire B: when actualised, Auto-Fire B can be activated with F AND Alt+2.

### Steps to reproduce the behavior
Take an old version of VBA-M and actualise it to a newer one.

**Comment by rkitover** [comment]
Can you please describe which versions of VBA/VBA-M you were testing and which settings got reset.

**Comment by RunisDauphin** [comment]
As for now, I tried 2.1.0 to 2.1.1 and 2.1.1 to 2.1.2. I will check in the next days what happens to 2.1.3 version.

Thanks for your attention, M. Kitover

**Comment by RunisDauphin** [comment]
I tried this morning to actualise versions and it still has this problem. Going from 2.1.2 to 2.1.3 causes this problem to.

The things got reset are that the default hotkeys return no matter what I do. For example, for the Auto-Fire keys, I assign:
-/ Auto-Fire A: D
-/ Auto-Fire B: F
-/ Auto-Fire L: C
-/ Auto-Fire R: V
After I update it gets like this:
-/ Auto-Fire A: D or ALT+1
-/ Auto-Fire B: F or ALT+2
-/ Auto-Fire L: C or ALT+3
-/ Auto-Fire R: V or ALT+4

And that with EVERY default hotkey. The ones I pulled off return AGAIN.

I hope you can solve this problem, specially since I had three new versions of your emulator in the last two months (and the ones are yet to come).

Thanks for your attention, M. Kitover.

**Comment by denisfa** [comment]
I did some testing. My tests were from `2.1.2` to `2.1.3` on `Windows 10 x64` (virtual machine). I set `Auto-Fire A` to `D`and `Auto-Fire B` to `F` on `2.1.2`. Nothing else was set since I wanted a simple case of this issue. When I open the config on `2.1.3`, nothing changed. `Auto-Fire A` to `D`and `Auto-Fire B` to `F`.

@RunisDauphin, could you provide some information on this so I can have a better idea about this problem? If you don't mind:

1. What OS are you running and what language/locale.
2. How did you set `Auto-Fire L` and `Auto-Fire R`? We do not have this on the GUI (which we should add, since we have for `Auto-Fire A` and `Auto-Fire B`).
3. Can you upload your `vbam.ini` with the strange messages?

I see  `AutoA=D` instead of `JoypadAutofireA=D` on `2.1.3`.

One thing I noticed is that the auto-fire are hardcoded to `ALT+1, ALT+2, ALT+3, ALT+4`. This ignores whatever is set as an alias. This should not be on `Options` > `Input` > `Autofire`. Maybe only on `Options` > `Input` > `Configure`. Although I see the need to alert users the autofire for whatever is on.

I will be waiting feedback.

**Comment by RunisDauphin** [comment]
Hiya, I am back in the middle of exam season.

About the assignation of the auto-fire buttons, I did not set them in input configuration, rather on hotkey configuration (a.k.a. Options -> Key Shortcuts...). The problem is not in the input configuration, but on the hotkeys. As I have explained, when I actualise the VBA-M version, those hotkeys get overwritten with the default ones.

Here is another example of hotkeys that I have:
My configuration:
-/Load recent ROM x (1<=x<=10): (Nothing)
-/Load state -> About (should be Load Recent State 1): Nothing
-/Save state -> About (should be Save Recent State 1): Nothing
After I update:
-/Load recent ROM x (1<=x<=10): CTRL+Fx (1<=x<=10)
-/Load state -> About (should be Load Recent State 1): F1 (This one does not appear because I moved it to Help -> About, but the rest of them do).
-/Save state -> About (should be Save Recent State 1): SHIFT+F1

If you feel curious, to alter those Autofire Keys, you just need to go, in Options -> Key Shortcuts, to Options -> Input -> Autofire -> Button (Button is the real button on the device). This was (and is) the only way to configure the Autofire / Autohold keys in any other branch of VBA (and that is how I discovered it).

And now that we are on it, could you solve that error that copies the Help stuff onto Load / Save State on Recent States? As far as I am aware, this was referenced before in another issue.

Just to end, my Specs:
-/ Operative Systeme: Windows 8.1 x64, updated up today.
-/ Processor: Intel Celeron N2840 @ 2,16 GHz.
-/ RAM: 4 GB (3,88 GB usable).
-/ Graphic Card: By defaut.

The vbam.ini file has been cleaned of most of the defaut keys (that means no recent stuff, no CTRL+W to turn off game, no CTRL+Q to close, no CTRL+P to pause, no CTRL+R to Reset, no CTRL+N to Next Frame, no autofire defaut keys, etc...).

[vbam.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/3219766/vbam.zip)

Hope this gets a better understanding of the problem, and gets solved soon.

Runis Dauphin

**Comment by denisfa** [comment]
@RunisDauphin Thank you very much for all this info! I will see what I can do!

Good luck on your exams!

**Comment by RunisDauphin** [comment]
So I keep trying to study, that is what I am trying to pass those exams. That is why I have not written anything in about a month.

By the way, if the configuration file has all those hotkeys readded, that means the problem is somewhere in the track of the route, would not it?

Maybe I am getting out of the track. Going back to work.

Runis Dauphin

**Comment by denisfa** [comment]
Fixed in #439.
