### ISSUE TITLE
Diagonal movement from vertical to horizontal axis doesn't work

### ISSUE THREAD

**Issue by autofire372** [visualboyadvance-m/visualboyadvance-m#42]
Attempting to go directly from a vertical movement to a horizontal one (i.e. going from Up to Up+Right) doesn't work correctly, as the horizontal input doesn't register.

**Comment by autofire372** [comment]
Whoops, just noticed the proper issue tracker.

**Comment by DoctorWho11** [comment]
This is the proper issue tracker now. Source forge issue tracking is shit to be honest

**Comment by autofire372** [comment]
No kidding.

**Comment by DoctorWho11** [comment]
Working on a script to try and export the existing issues from there to here. And then shutting down the sf.net project page once and for all. Anyways thanks for the report. Will look into it asap.

**Comment by rkitover** [comment]
Is this with keyboard or joystick? Which interface? (Wx, GTK, MFC or SDL)

**Comment by autofire372** [comment]
Joystick on Wx.

**Comment by rkitover** [comment]
And of course I forgot to ask, which OS and which type of joystick?

And is this the analog stick or the directional pad?

**Comment by autofire372** [comment]
Xbox One pad on Linux, and the issue is with the controller's d-pad.

**Comment by rkitover** [comment]
Ok thank you, we will try to look at this.

**Comment by rkitover** [comment]
Works fine for me just scrolling the cursor on the map in advance wars, which game are you trying this with?

**Comment by autofire372** [comment]
Tried with Pokemon Blue and with Pokemon Fire Red; both exhibit this incorrect behavior.

**Comment by DoctorWho11** [comment]
I'll try it out when I get home. I have an Xbox one controller. Last I tried using the xbone controller on Linux it was playing Metroid and it was fine for me.

**Comment by autofire372** [comment]
For the record, I just tested, and this issue happens on Windows too.

**Comment by rkitover** [comment]
@autofire372 does #53 (in master) fix your issue?

**Comment by autofire372** [comment]
I can't tell, since master is segfaulting on launch on my end.

**Comment by autofire372** [comment]
After re-fetching the source, I rebuilt the program, and this issue has been resolved; issue #46 is still present, though.
