### ISSUE TITLE
Emulator responds to "up" input with "A" button press

### ISSUE THREAD

**Issue by JetLag413** [visualboyadvance-m/visualboyadvance-m#425]
### Expected behavior
I have W set as my "UP" key, so pressing W should make my cursor go up in menus, make my character go up, etc.

### Actual behavior
Game responds as if I'm pressing the "A" button. 

### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
Pokemon Red rescue team is the only one I've tried

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

Include screenshots of ROM Information (File > ROM Information):

If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 10
If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by rkitover** [comment]
This definitely works, have you tried on another computer?

**Comment by rkitover** [comment]
Also have you checked all 4 player input configurations?

**Comment by Sand-Sand** [comment]
go to options > input > configure > special 

Once there remove Autofire A + Autofire B so that they're both blank.

Fixed for me.

**Comment by denisfa** [comment]
If I understand this correctly, then this means the default option for autofire was "W", and it was set like this when the user @JetLag413 set "UP" as "W". Therefore the issue reported here.

Can I confirm this with you, @Sand-Sand? I believe this should be enough for me to close this.

**Comment by denisfa** [comment]
@rkitover The default buttons are set for our Windows downloads, right? This should explain what happened here.

**Comment by rkitover** [comment]
@denisfa the default buttons are hard-coded, and we really need to redo them, see also #362.

See `defkeys` in `opts.cpp`.

If you want to redo them to something more sane, and perhaps remove some of the unnecessary defaults please go ahead.

**Comment by denisfa** [comment]
The default buttons have been reworked. This should be fixed, at least for now.
