### ISSUE TITLE
Win32: Build fails on Visual Studio

### ISSUE THREAD

**Issue by autofire372** [visualboyadvance-m/visualboyadvance-m#43]
This project currently cannot build on Visual Studio, as hundreds of errors kill compilation.

**Comment by DoctorWho11** [comment]
The visual studio solution is going to be dropped. We use cmake now.

**Comment by rkitover** [comment]
And by the way, cmake has Visual Studio generators, see the `-G` option.

**Comment by DoctorWho11** [comment]
Labeling as won't fix, also glad you used github for the report. :)

**Comment by rkitover** [comment]
There has recently been some work on making the Visual Studio cmake generator work for the project:

https://github.com/visualboyadvance-m/visualboyadvance-m/pull/70

edorax described the process, and at some point we will get this more automated.
