### ISSUE TITLE
VBA-M creates folder in appdata anyway

### ISSUE THREAD

**Issue by quroe** [visualboyadvance-m/visualboyadvance-m#430]
### Expected behavior
If there is ini file in exe's directory,VBA-M doesn't create empty folder.
### Actual behavior
VBA-M creates folder in appdata.
### Steps to reproduce the behavior
1.Unzip "visualboyadvance-m-Win-64bit.zip" to any directory.
2.Create "vbam.ini" file in same directory.
3.Launch "visualboyadvance-m.exe" and exit.
4."visualboyadvance-m" folder created in "%USERPROFILE%\AppData\Local".
### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 8.1 64bit

Version of code (pre-built binary version, or commit ref, or just "master"):
VisualBoyAdvance-M 2.1.3 64bit

**Comment by denisfa** [comment]
@rkitover I might need the tutorial about how to generate one of the nightlies for Windows. This is a really simple fix, but I would like to test it myself. The tutorial using mingw gets me a binary that forces me to copy a bunch of dll's to the current dir, which is not the case for the nightly (I kinda want to know what is being done).

**Comment by rkitover** [comment]
Sure, I will explain on the chat page in about half an hour.

**Comment by denisfa** [comment]
Fixed in https://github.com/visualboyadvance-m/visualboyadvance-m/commit/bf6f2d4ac276dd21c6a837ec3795d7a03d3d0bdd. It will be available on version `2.1.4`.
