### ISSUE TITLE
moving to the right in menus

### ISSUE THREAD

**Issue by zoeysaTrap** [visualboyadvance-m/visualboyadvance-m#434]
### Please fill out this form:
in menus it moves to the right non stop
### Expected behavior
not to
### Actual behavior
oddly moves to right with out stopping
### Steps to reproduce the behavior
nc
### Crash bugs
none
If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
gbas fe7 cv:hod
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
not sure only have the two
Include screenshots of ROM Information (File > ROM Information):

If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
windows
If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by denisfa** [comment]
@zoeysaTrap We have had a very similar issue regarding something like this that was fixed not so long ago. I believe it is the same issue and it is fixed already. What windows version are you using? I can generate a exe with the fix so we can check if it is indeed fixed.

**Comment by denisfa** [comment]
@zoeysaTrap I have a build for Windows that you can try to confirm if this issue is already fixed. Use the one that matches your system (x64 or x32 bits):  [visualboyadvance-m.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/3252047/visualboyadvance-m.zip) 

If there are any problems, please let  me know.

**Comment by rkitover** [comment]
Please let us know if that build fixes your issue.

**Comment by zoeysaTrap** [comment]
sorry was away for a bit found a fix in the button mapping got to special
and delete the mappings

**Comment by zoeysaTrap** [comment]
sorry was away for a bit found a fix in the button mapping go to special and delete the mappings

**Comment by rkitover** [comment]
We should remove all unnecessary default mappings.

**Comment by denisfa** [comment]
Fixed in #439.
