### ISSUE TITLE
Key Maps stay empty and cannot be set

### ISSUE THREAD

**Issue by simsemax** [visualboyadvance-m/visualboyadvance-m#437]
### Expected behavior

Defined Key Mapping works while playing and is saved when VBA is restarted.

### Actual behavior

Manually configured key maps stay empty, even default mappings are not saved.
The first time I opened VBA everything worked fine, but the second and following times this keeps happening.

### Steps to reproduce the behavior
Start VBA and configure the keys maps in the input menu, save them but in the game they won't work. If you open up the input menu again, you will see why: the definitions of Up, Down, Left, Right, ABLR, Select and Start are empty except for the special ones, which are always (MotionUp=KP_UP, MotionDown=KP_DOWN, MotionLeft=KP_LEFT, MotionRight=KP_RIGHT, MotionIn=KP_PAGEUP, MotionOut=KP_PAGEDOWN, AutoA=W, AutoB=Q, Speed=SPACE).
Due to the fact that I use a laptop with no keypad, I can only use AutoA, AutoB and Speed.
Configs in vbam.ini can be reset manually but if I open VBA again, vbam.ini gets initially reset and overwritten with the key maps described above and the same problem occurs.

### Crash bugs

no crashes occurred.

### ROM details

Only tested "Legend of Zelda, The - The Minish Cap (Europe) (En,Fr,De,Es,It).gba" so far but this problem occurs even if no rom is loaded.

### Option details

Video driver: OpenGL

Sound driver: SDL

### Build details
Operating System : Mac OS X 10.10.5

Version of code (pre-built binary version, or commit ref, or just "master"): I tried the VBA versions 2.1.3, 2.1.2 and 2.1.1

### Hardware details:
Computer: MacBookPro9,2, Intel Core i7, 2,9 GHz, 16 GB RAM, Intel HD Graphics 4000 (1024GB VRAM)

Joystick: Gravis Gamepad Pro USB Model #4211, don't know the driver, Plug'n'Play just worked fine.

**Comment by denisfa** [comment]
@simsemax Thanks for the report. I believe this is similar to another open issue. Could you provide what language are you using on your Mac? We have a translation issue currently reported with french.

**Comment by simsemax** [comment]
Hi @denisfa,
thanks for the reply! My Mac OS runs in german and so does VBA. I have found the threads #110 and #126 after I posted this but I haven't figured out yet how to change the VBA language to english on my mac. I suppose the first time I ran VBA it was in English and everything worked.

**Comment by denisfa** [comment]
@simsemax At the moment, vbam uses the locale to set its language. So only if you change yours to english, it will use the english texts. This is not necessary, though. I think it is not a translation issue after thinking for a while, so I am going to investigate something else. When this is fixed, we will update you here.

**Comment by simsemax** [comment]
@denisfa I tried and deleted the languages in the vbam.appContent/Resources folder except for the english one and now the game will remember the key maps I configured. So I beg to differ good sir ;) I think this is an issue related to languages.

**Comment by denisfa** [comment]
@simsemax Thanks for the extra info. I will take a better look at this.

**Comment by denisfa** [comment]
@simsemax How did the buttons for input appeared? They don't save, but how were they write? Like `Joy1-Hat0W`, `Joy1-Button5` or something else? Right before you press OK after you configure them.

The translation issue we know did not break all buttons; only the axes related ones. The other issue here is that our special buttons had a overwriting bug, like our key shortcuts. This last part should be fixed soon.

**Comment by simsemax** [comment]
I only configured the Gamepad buttons but no keyboard buttons. I will attach a screenshot.
![Screenshot 2019-06-15 um 10 27 52](https://user-images.githubusercontent.com/51508716/59549069-75566100-8f58-11e9-8e7f-2a811fe047b7.png)

**Comment by denisfa** [comment]
@simsemax Thank you. It is indeed another translation problem. The special buttons is another issue, but I believe it should be fixed soon.

**Comment by rkitover** [comment]
@simsemax try doing something like this:

```bash
LANG=C open visualboyadvance-m.app
```

then set your key maps, then it should work when you restart it in german again.
