### ISSUE TITLE
Not being able to use SHIFT+F1 to F9

### ISSUE THREAD

**Issue by UchihaFabio** [visualboyadvance-m/visualboyadvance-m#438]
I press the command but nothing happens. I am not that good on not dying at hard games so i would love to be able to use it.
if i do manually (going to settings and saving) it works but not by the command.

I cannot either load or save with the comand

**Comment by denisfa** [comment]
@UchihaFabio Use the template. We need it to better trace what can be done. For example, I am on Linux and it works as intended.

The default is F1 to F9 to load, and SHIFT+F1 to SHIFT+F9 to save it.

**Comment by UchihaFabio** [comment]
Sorry...... I am using on Windows 10 19H1 x64

**Comment by denisfa** [comment]
@UchihaFabio Thanks, that should help.

Do you have any type of special input configuration? Like using `SHIFT` for something? I am testing this on a virtual machine; it seems to be working. In case you can test this, check [these instructions](https://github.com/visualboyadvance-m/visualboyadvance-m#note-for-windows-users).

Also, what version of `visualboyadvance-m` are you using? We have the latest (not official nor nightly, just with some bug fixes) here: https://github.com/visualboyadvance-m/visualboyadvance-m/files/3252047/visualboyadvance-m.zip

Use the one with x64 in its name.

**Comment by UchihaFabio** [comment]
no i dont have a special imput uding SHIFT. i am going to test your link

**Comment by UchihaFabio** [comment]
> 
> 
> @UchihaFabio Thanks, that should help.
> 
> Do you have any type of special input configuration? Like using `SHIFT` for something? I am testing this on a virtual machine; it seems to be working. In case you can test this, check [these instructions](https://github.com/visualboyadvance-m/visualboyadvance-m#note-for-windows-users).
> 
> Also, what version of `visualboyadvance-m` are you using? We have the latest (not official nor nightly, just with some bug fixes) here: https://github.com/visualboyadvance-m/visualboyadvance-m/files/3252047/visualboyadvance-m.zip
> 
> Use the one with x64 in its name.

This version you gave me worked like a charm the save feature. Thanks
