### ISSUE TITLE
Win32, minGW: "The application was unable to start correctly"

### ISSUE THREAD

**Issue by autofire372** [visualboyadvance-m/visualboyadvance-m#44]
After figuring out how to set up minGW and MSYS2, I finally successfully built WxWidgets VBA-M for Windows...and found that the resulting executable refuses to start, spewing forth the following error: 

"The application was unable to start correctly (0xc000007b). Click OK to close the application."

**Comment by rkitover** [comment]
You compiled it in either the MINGW32 or MINGW64 shell right? not the msys shell?

**Comment by rkitover** [comment]
If you built for 64bit try building for 32bit or vice-versa.

**Comment by DoctorWho11** [comment]
Sounds like he's missing the proper runtimes. Needs libstdc++ libwinpthreads libgcc dll's with the executable.

**Comment by rkitover** [comment]
Oh right.

Instead of launching the .exe from explorer, try just running it in the terminal e.g.:

```bash
./visualboyadvance-m
```

that will have the `PATH` set up correctly and everything.

**Comment by DoctorWho11** [comment]
I'm also working on a custom msys2 repo where we are going to provide fully static libraries and debug libraries too

**Comment by autofire372** [comment]
It appears this only compiles properly as 32 bit at the moment.

**Comment by DoctorWho11** [comment]
It builds properly for 64bit windows just fine. As long as you don't enable lto.
