### ISSUE TITLE
Frame skip on 0

### ISSUE THREAD

**Issue by Gumbag** [visualboyadvance-m/visualboyadvance-m#440]
Even the number of frames to skip is at 0, it looks like it's skip, giving a few pauses.

**Comment by Gumbag** [comment]
I was playing in an updated version

**Comment by denisfa** [comment]
@Gumbag So did the latest version solve the issue for you? So we can close this.

**Comment by Gumbag** [comment]
@denisfa yes, I was going to delete, but I did not find where it excluded :/

**Comment by denisfa** [comment]
@Gumbag It is ok. We don't delete issues, only close them.
