### ISSUE TITLE
Emulator does not read rom

### ISSUE THREAD

**Issue by Gumbag** [visualboyadvance-m/visualboyadvance-m#441]
### Expected behavior
Open the game when you select the rom

### Actual behavior
It says that it is not possible to read the rom, even if it is in the format .gba, .gbc or .gb and neither the place where it is

### Steps to reproduce the behavior
Open the emulator and select a rom

### ROM details
All GBA, GBC and GB games in any format

### Build details
Windows 8

Version 2.1.3

Edit:
This occurs in the default language (I do not know if translating yet the error occurred because I could not translate)

It seems that the bug happens after you change version

In version 1.8.0 and 2.1.0, I selected a folder, now in 2.1.3 it does not read the folder any more, only if it changes the game or the folder of the place

![Sem título](https://user-images.githubusercontent.com/51837985/59544730-0989df00-8eeb-11e9-86da-1ff1e9af1960.png)

![Sem título 1](https://user-images.githubusercontent.com/51837985/59544846-3d193900-8eec-11e9-9b97-e02e78e2d693.png)

**Comment by denisfa** [comment]
@Gumbag This is way too vague. We need more information. Copy and paste the error message if you can, please. What language are you using?

I might need more answers, so if you can five more info, please do.

**Comment by Gumbag** [comment]
> @Gumbag This is way too vague. We need more information. Copy and paste the error message if you can, please. What language are you using?
> 
> I might need more answers, so if you can five more info, please do.

I already edited the problem

**Comment by denisfa** [comment]
@Gumbag We have an open issue where we don't deal with unicode files well on Windows. This means that if there is a `ç`, `á`or any other non-english char, it will result in an error when opening the game. There is the possibility that this might be the cause here as well. 

> This occurs in the default language (I do not know if translating yet the error occurred because I could not translate)

`vbam` uses the current locale to set its language. If you use english, then it should be english. There are missing translations, that's why I would like to confirm the language you are using.

> It seems that the bug happens after you change version
> In version 1.8.0 and 2.1.0, I selected a folder, now in 2.1.3 it does not read the folder any more, only if it changes the game or the folder of the place

I will take a look.

**Comment by Gumbag** [comment]
@denisfa My folder has an i with accent, ie "í", but the other versions of the emulator, other emulators and the computer itself has always read the folder with that letter with accent.

**Comment by denisfa** [comment]
@Gumbag This became an issue for vbam starting from version `2.1.1`. It has been fixed, though, and it will be available for the next release.

**Comment by Squall-Leonhart** [comment]
open a new issue, after trying to fix it yourself by changing the file name, pathing, etc.
