### ISSUE TITLE
Vba-m won't open with wii u pro controller connected

### ISSUE THREAD

**Issue by Birutath** [visualboyadvance-m/visualboyadvance-m#444]
### Expected behavior
To open normaly and recognize the controller as a xbox 360 one

### Actual behavior
Won't open, and insted gives a pop up that reads "unhandled Standard exception of type "st20bad_array_new_lenght" with message std::bad_array_new_lenght"; terminating the application"

### Steps to reproduce the behavior
Use a wii u pro controller with wiinUsoft app, and try to open vba-m

### Build details

Operating System: Windows 10 pro 64 bit

Version of code: 2.1.3

**Comment by Squall-Leonhart** [comment]
Get a real xbox 360 controller, bluetooth pads are odd spec wise.

**Comment by Birutath** [comment]
What i think is strange is that, i don't have this problem with anything else. All my pc games and emulators run normally, only vba-m won't run with my controller

**Comment by denisfa** [comment]
@Birutath Thanks for the report. This is a little tough to debug because I believe we don't have someone who owns this controller... We can take a look, but it won't be high priority.

**Comment by ZachBacon** [comment]
My guess is that SDL2 isn't picking up on that properly. May need to add a special case for that.

**Comment by rkitover** [comment]
The error should be fixed, as for the joystick you might look into SDL2 settings.
