### ISSUE TITLE
VBA-M Crashes When Using BIOS

### ISSUE THREAD

**Issue by AceTrainerDJ** [visualboyadvance-m/visualboyadvance-m#447]
### Expected behavior
1. VBA-M boots using BIOS rom
2. Screen says something akin to "look at TV screen"
3. Dolphin detects VBA-M
4. Animal Island made available in Animal Crossing
### Actual behavior
1. Emulator boots BIOS rom
2. Emulator freezes and crashes part way through boot process
3. Dolphin obviously doesn't detect 
### Steps to reproduce the behavior
1. Set directory in Boot ROM for a BIOS file 
2. Select "use BIOS file" under Options > Gameboy Advance
3. Try booting the BIOS file via the same way you would boot a GBA rom
4. Emulator gets part way through the boot but then freezes and crashes

### ROM details

I'm using a BIOS file which from my understanding appears to be a collection compiled into one? The original file name is [BIOS] Game Boy Advance (World) (TS2).gba

### Option details

Video driver (simple, opengl): Doesn't seem to matter. I've tried both

Sound driver (directsound, xaudio, openal, SDL): Doesn't seem to matter

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Windows 10

Version of code (pre-built binary version, or commit ref, or just "master"): Unfamiliar with this info

I provided the most info I thought was vital but if more is needed I can certainly try to acquire it, I just want to be able to do things on GCN games that require a GBA to do.

**Comment by denisfa** [comment]
@AceTrainerDJ Sorry for the delay. Finally I had a chance to look at this.

> Version of code (pre-built binary version, or commit ref, or just "master"): Unfamiliar with this info

On main menu: `Help` > `About`. Should be the entire second line. It is the version of vbam you are running.

> 3. Try booting the BIOS file via the same way you would boot a GBA rom
> 4. Emulator gets part way through the boot but then freezes and crashes

Did this BIOS file work with `vbam` before? I would suggest trying with another BIOS, if you have available.

> Animal Island made available in Animal Crossing

I am not familiar with this game, so it is a little bit difficult to debug this. I would need to quickly be able to check the functionality. At the moment, I know `Legend of Zelda, The - Four Swords Adventures` is working with the current release. So I have an idea that at least something from the linking part is working.

**Comment by retro-wertz** [comment]
no one should be using random bios file, especially for link purposes (link is problematic already to begin with, i can only test it with Zelda game + Dolphin on linux, never had success running this on windows)...

**Comment by denisfa** [comment]
@retro-wertz what are the known issues of link? There are some open issues, but they feel very random. I know very little about windows, though, so that might be where this is coming from.
