### ISSUE TITLE
audio loop when clicking outside of vba's screen borders

### ISSUE THREAD

**Issue by stefgina** [visualboyadvance-m/visualboyadvance-m#45]
Hello, i don't really know if anyone else mentioned that on the old bugtracker but there's an issue when you click the cursor outside of the vba's window boarders while you playing any ROM. The issue causes VBA to pause the current video frame (which is logical) and the audio to stuck in a loop of approximately 0.5 sec's which is repeating constantly until you move the cursor back in and click it. 

Tested while no other program was running in the backround.

OS : Windows 10 pro
Processor : Intel Core i7 (3.4hz both)
System Type : 64bit os, x64 based processor 

Thank You.

**Comment by rkitover** [comment]
I've noticed this too, at least with the DirectSound audio driver, I'll try to take a look.

**Comment by stefgina** [comment]
I think it's happening inside the DirectSound::pause() or reset() functions.. (visualboyadvance-m/src/win32/DirectSound.cpp). It seems like when in pause state it's looping through pausing,reseting and resuming secondary sound buffer. 

ps. will never stop appreciate well written code, gj.

**Comment by rkitover** [comment]
Would you like to try sending us a PR? It's very easy to build on msys2 and the `./installdeps-msys2` script will install everything you need.

**Comment by stefgina** [comment]
Sure. Tried building for 64bit and 32bit. Both of them spammed these errors at the end of the last 
(make -j10) command in mingw64 and mingw32.

[
/Desktop/visualboyadvance-m-master/src/wx/xaudio2.cpp:12:21: fatal error: XAudio2.h: No such file or directory
 #include <XAudio2.h>
                     ^
compilation terminated.
make[2]: *** [src/wx/CMakeFiles/visualboyadvance-m.dir/build.make:495: src/wx/CM      akeFiles/visualboyadvance-m.dir/xaudio2.cpp.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:220: src/wx/CMakeFiles/visualboyadvance-m.dir      /all] Error 2
make: *** [Makefile:150: all] Error 2
]

Ended up with a bin2c.exe on both occasions which runned like this : 

[
/* generated from resource data: do not edit */
const unsigned char resource_data[] = {
]

**Comment by DoctorWho11** [comment]
you need to run git submodule update --init --recursive for xaudio2 stuff to compile.

**Comment by stefgina** [comment]
I had this error everytime i tried to git submodule update. (tried from many dir's)

$ git submodule update --init --recursive
': not a valid identifierline 89: export: `dashless
fatal: Not a git repository (or any of the parent directories): .git

**Comment by rkitover** [comment]
@stefgina 

Yeah the build works only from a git clone.

To do a PR on github, you want to fork the repository, commit to your fork, then create the Pull Request.

After you click the fork button, you can clone your fork like so:

git clone git@github.com:stefgina/visualboyadvance-m.git

from there you can run the git submodule command and build.

**Comment by rkitover** [comment]
As far as build issues go, I believe we have everything documented and working properly now.

As for the issue itself, it should be relatively simple to fix and I will try to do so soon.

**Comment by rkitover** [comment]
This is fixed in master in f10e2e99.
