### ISSUE TITLE
VBA-M doesn't load  

### ISSUE THREAD

**Issue by AyanamiRei1** [visualboyadvance-m/visualboyadvance-m#451]
First I'm using Windows 10 Pro 64-bit 1809

Alright for the issue I'm trying to load it and all I'm getting is this error no idea why.

![image](https://user-images.githubusercontent.com/25233407/60071183-299e7700-9711-11e9-98c5-1ed4e4a29b63.png)

Cheers for the help.

**Comment by ZachBacon** [comment]
Please keep the standard issue template, it has questions there that are relevant such as are you using a release or nightly.

**Comment by AyanamiRei1** [comment]
Expected behavior
For it to work.

Actual behavior
Crashes while trying to open it.

Steps to reproduce the behaviour

Just trying to open the program causes this error.
![image](https://user-images.githubusercontent.com/25233407/60076663-0d560680-9720-11e9-81b9-b6cc487503e7.png)

Build details
 Latest Stable.

**Comment by ZachBacon** [comment]
Give this a try https://github.com/visualboyadvance-m/visualboyadvance-m/files/3219928/visualboyadvance-m-Win-32bit.zip
At some point I'll see about doing a new nightly based on current changes. But this should be newer than the stable release.

**Comment by AyanamiRei1** [comment]
Still the same problem.

![image](https://user-images.githubusercontent.com/25233407/60077358-acc7c900-9721-11e9-899d-d906c50fad96.png)

**Comment by ZachBacon** [comment]
So on all my windows based systems it does run, so there's something on your system that is causing a memory allocation exception within vba-m, or I should say that's my best guess on the matter. @rkitover what do you think?

**Comment by rkitover** [comment]
I think I fixed this, try this nightly:

https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354#issuecomment-505387781

**Comment by AyanamiRei1** [comment]
Same issue boss.

![image](https://user-images.githubusercontent.com/25233407/60120392-96992780-9778-11e9-94b4-340b5a1e0537.png)

And this is with the Nightly.

**Comment by ZachBacon** [comment]
Just out of curiosity, go to %USERPROFILE%\AppData\Local\visualboyadvance-m and remove (or backup) the ini, if there is one there and see if that will do anything.

**Comment by denisfa** [comment]
@AyanamiRei1 Are you using a controller? We had an issue not so long ago that it was related to using a `wii u pro` controller with wiinUsoft app. It was the same error message and behaviour you describe here.

**Comment by NoDuff** [comment]
I have the exact same issue with 2.1.2 and 2.1.3, but versions 2.1.1 and older work fine.

Deleting the config folder does not help.

After reading denisfa's post I remembered that I had a MayFlash Dolphin Sensor Bar connected to my computer. When I unplugged the sensor bar, the errors went away and now VBA-M loads.

Is this error potentially fixable? Or will I have to leave the affected device unplugged to run VBA-M?

**Comment by denisfa** [comment]
@NoDuff It really depends on the issue itself... We don't have the controller/hardware available for testing, so we would need to keep asking users to test whatever possible solution we have... I believe that the easiest path is to ignore devices, but I would not be able to test it.

> I have the exact same issue with 2.1.2 and 2.1.3, but versions 2.1.1 and older work fine.

I need to ask: does `2.1.1` loads and knows about the device or just ignore it?

**Comment by NoDuff** [comment]
I would go with it ignores it. The sensor bar is pretty much custom made for the Dolphin emulator and I have never used it for anything else.  I even forget it is still plugged in sitting on my monitor most of the time.

I loaded up 2.1.1 and while it didn't crash. I wasn't able to bind any controller keys or use the Wii Remote to play games. (while my XB360 controller worked just fine)

**Comment by rkitover** [comment]
@denisfa see line 68 in sdljoy.cpp, this should be fixed, I have no idea how it still happens.

**Comment by terralilly85** [comment]
Not sure if this should be a different thread, but I'm seeing the same error message. I have a WiiU Pro Controller running on WiinUSoft (latest version). If I disable Bluetooth completely, VBA-M will launch with no issues. If I have the controller connected and cloned to as an XInput device, VBA-M fails to launch. Is there some way I can get you any logs of the crash?

**Comment by rkitover** [comment]
Thank you for confirming the bug still exists.

If someone with dev experience can give us a backtrace, it would be highly appreciated.

**Comment by rkitover** [comment]
@terralilly85 @AyanamiRei1 @NoDuff 

I realized what I was doing wrong, can you please try this build:

https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354#issuecomment-510661713

**Comment by terralilly85** [comment]
Posted this there accidently:

@rkitover Same error on launch, however this time load was instant. On previous builds application load would take several minutes.

![image](https://user-images.githubusercontent.com/52293448/61087755-8d5cbb80-a404-11e9-92c9-510ff99c44d6.png)

**Comment by NoDuff** [comment]
Also continues to give the same error for me, and still takes about 20 seconds for the error to pop up (same as the release builds)

**Comment by rkitover** [comment]
I actually posted the wrong build.

**Comment by rkitover** [comment]
@terralilly85 @AyanamiRei1 @NoDuff 

Sorry about that, I thought my script was making the `.zip` but it turns out I was uploading an old `.zip`.

Anyway, these are the right binaries:

https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354#issuecomment-510661713

**Comment by NoDuff** [comment]
The 64bit build ran fine, no error at all. Looks like you squashed the bug.
VBA-M does still take around 20s to show initially show the window, which is a bit odd.

For some reason BitDefender flags the 32bit version as a virus: Atc4.Detection
A quick Google seems so show this as a common false positive.

**Comment by terralilly85** [comment]
I can also confirm that the x64 build squashed the bug. Load time seemed normal to me.

**Comment by rkitover** [comment]
Thank you very much for testing! We should be doing a new release soon which will have this change.
