### ISSUE TITLE
Multiple bindings for Keyboard shortcuts doesn't work as expected

### ISSUE THREAD

**Issue by jasonsparc** [visualboyadvance-m/visualboyadvance-m#454]
### Expected behavior
Ability to set more than one key bindings to a command (under **Options > Key Shortcuts**), and should also be saved to the `vbam.ini` file.

### Actual behavior
Only the last key binding is remembered upon closing the emulator. The `vbam.ini` file only records the last key shortcut set.

Another weird behavior: assigning additional key bindings to the *Emulation > Pause* command, would make the default key bindings (`CTRL+P` and `PAUSE`) not working anymore, even though they weren't removed. Also, assigning one more additional key binding to the *Emulation > Pause* command (for a total of 4 key shortcuts to the same command) will cause all previous key bindings to not work.

### Steps to reproduce the behavior
Go to **Options > Key Shortcuts** and assign two or more key bindings to any command.

### Option details

Video driver (simple, opengl):
opengl

Sound driver (directsound, xaudio, openal, SDL):
SDL

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 10

Version of code (pre-built binary version, or commit ref, or just "master"):
2.1.3

**Comment by denisfa** [comment]
@jasonsparc This is very similar to another issue already fixed. It will be available for our next release. Check [here](https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354#issuecomment-505387781) for our nightly download options.

**Comment by denisfa** [comment]
> Another weird behavior: assigning additional key bindings to the Emulation > Pause command, would make the default key bindings (CTRL+P and PAUSE) not working anymore, even though they weren't removed. Also, assigning one more additional key binding to the Emulation > Pause command (for a total of 4 key shortcuts to the same command) will cause all previous key bindings to not work.

I will check this. This is a different issue from the key shortcuts.

**Comment by denisfa** [comment]
Alright, all of this has been tackled in #455. It is fixed.
