### ISSUE TITLE
wxvbam segfaults when audio settings are changed during emulation

### ISSUE THREAD

**Issue by autofire372** [visualboyadvance-m/visualboyadvance-m#46]
Opening VBA-M's audio settings during emulation, changing anything, and then hitting OK causes the program to segfault on both Windows and Linux.

**Comment by rkitover** [comment]
The initialization/deinitialization code for all the sound drivers needs to be updated for this to work correctly.

**Comment by retro-wertz** [comment]
this has been fixed in latest commit, together with sound enhancement fixes...
