### ISSUE TITLE
[Input Bind] Missing or empty default key binds on a clean or new config

### ISSUE THREAD

**Issue by retro-wertz** [visualboyadvance-m/visualboyadvance-m#463]
### Please fill out this form:
[Input Bind] Missing or empty default key binds on a clean or new config

### Expected behavior
a default input binding should be set, most preferably for gamepad (additional analog as dpad) and keyboard binds.

### Actual behavior
there is no default key binds, gamepad nor keyboard

### Steps to reproduce the behavior
remove or delete vbam.ini, run vba-m

### Crash bugs

not a crash bug

### ROM details

Which games are affected by the issue (please state if GBA or GB game): all

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

Include screenshots of ROM Information (File > ROM Information): not required

If you are using a BIOS file, please say which one: not required

### Option details

Video driver (simple, opengl): gl

Sound driver (directsound, xaudio, openal, SDL): sdl-alsa

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): im using arch btw!

If using Linux, specify if using xorg or Wayland: xorg

Version of code (pre-built binary version, or commit ref, or just "master"): master

**Comment by retro-wertz** [comment]
this should be reopened. there is still no default input bind set, keyboard or gamepad, when vbam.ini already exists in path even without the [Joypad/1] / [Joypad/2]. so meaning that non existing entries (at least for key/joy binds) are not filled with default values.

sample 1 (success story)
delete vbam.ini
run visualboyadvance-m
default binds are set...

sample 2
create vbam.ini (can be empty or at least does not have [Joypad/(1/2)] )
run visualboyadvance-m
see option > input > configure. this should still have no binds whatsoever.

**Comment by rkitover** [comment]
@retro-wertz thank you for testing!

Whether or not we should fix this depends on this, was the empty config file created with a release version or from git? Because as far as I know the problem has only existed in master for a few weeks between a couple of @denisfa's commits.

I will reopen this and let him decide how to handle this.

**Comment by denisfa** [comment]
> Whether or not we should fix this depends on this, was the empty config file created with a release version or from git?

The file is not empty; rather just some options not set (as in option=""). The input was supposed to be set as well, but there was a bug in one of the `if`'s when setting it.

Yeah, I do agree with him. I think we can do something more smart for this, although I need to think better about how to do it. The sample 2 gave me some good ideas; I want to check how some other default options are handled first. I will keep this open for now.
