### ISSUE TITLE
Fullscreen doesn't work

### ISSUE THREAD

**Issue by FreskoYouTube** [visualboyadvance-m/visualboyadvance-m#464]
### Expected behavior
Going to fullscreen by pressing alt+enter or going out fullscreen by pressing alt+enter.
### Actual behavior
Nothing happens
### ROM details
Which games are affected by the issue (please state if GBA or GB game):
Kirby's Dream Land (USA, Europe).gb,Mario Kart - Super Circuit (Europe).gba,Kirby - Nightmare in Dream Land (USA).gba and Super Mario Land 2 Dx (a Rom Hack).
### Option details
Video driver (simple, opengl):
OpenGL
Sound driver (directsound, xaudio, openal, SDL):
SDL
### Build details
Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 10
Version of code (pre-built binary version, or commit ref, or just "master"):
2.1.0
### Hardware details:
CPU:
AMD Athlon || X3 450
Memory:
DDR3
GPU:
AMD Radeon R7 200 Series

**Comment by denisfa** [comment]
@FreskoYouTube There was an issue with key shortcuts that was fixed not so long ago. It will be available on the next release.  So I will mark this as fixed.
