### ISSUE TITLE
Visual Studio build failure

### ISSUE THREAD

**Issue by Jamiras** [visualboyadvance-m/visualboyadvance-m#465]
### Expected behavior
Following instructions in README would result in a successful build

### Actual behavior
Error about `int8_t` being doubly defined, which can be fixed by updating `dependencies` submodule to `master`. Then this error occurs:
```
"E:\Source\VBAM\vsbuild\ALL_BUILD.vcxproj" (default target) (1) ->
 "E:\Source\VBAM\vsbuild\src\wx\visualboyadvance-m.vcxproj" (default target) (5) ->
 (Link target) ->
   keyedit.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall wxUniCharRef::~wxUniCharRef(void)" (__imp_??1wxUniCharRef@@QAE@XZ) [E:\Source\VBAM\vsbuild\src\wx\visualboyadvance-m.vcxproj]
   wxvbam.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall wxUniCharRef::~wxUniCharRef(void)" (__imp_??1wxUniCharRef@@QAE@XZ) [E:\Source\VBAM\vsbuild\src\wx\visualboyadvance-m.vcxproj]
   viewers.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall wxUniCharRef::~wxUniCharRef(void)" (__imp_??1wxUniCharRef@@QAE@XZ) [E:\Source\VBAM\vsbuild\src\wx\visualboyadvance-m.vcxproj]
   opts.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall wxUniCharRef::~wxUniCharRef(void)" (__imp_??1wxUniCharRef@@QAE@XZ) [E:\Source\VBAM\vsbuild\src\wx\visualboyadvance-m.vcxproj]
   sys.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall wxUniCharRef::~wxUniCharRef(void)" (__imp_??1wxUniCharRef@@QAE@XZ) [E:\Source\VBAM\vsbuild\src\wx\visualboyadvance-m.vcxproj]
   E:\Source\VBAM\vsbuild\Debug\visualboyadvance-m.exe : fatal error LNK1120: 1 unresolved externals [E:\Source\VBAM\vsbuild\src\wx\visualboyadvance-m.vcxproj]
```

### Steps to reproduce the behavior
* Fresh clone, submodule init/update
* Open `VS2017 Native Tools Command Prompt` (tried with both x86 and x64)
* Follow steps in README:
> mkdir vsbuild
> cd vsbuild
> cmake .. -DVCPKG_TARGET_TRIPLET=x64-windows
> msbuild /m .\ALL_BUILD.vcxproj

### Crash bugs

n/a

### ROM details

n/a

### Option details

n/a

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Windows 10

If using Linux, specify if using xorg or Wayland: n/a

Version of code (pre-built binary version, or commit ref, or just "master"): master

### Hardware details:

n/a

### Other

For what it's worth, I did notice the following warning in the `cmake` output for x86:
```
Could NOT find SFML (missing:  SFML_NETWORK_LIBRARY SFML_SYSTEM_LIBRARY)
CMake Warning at CMakeLists.txt:261 (message):
  SFML not found, LINK will be disabled
```
But it looks like it downloaded and built it:
```
Starting package 5/6: sfml:x86-windows
Package sfml:x86-windows is already installed
Elapsed time for package sfml:x86-windows: 9.482 us
```
The x64 build found it just fine:
```
-- Found SFML 2.5.1 in E:/Source/vcpkg/installed/x64-windows/include
```
There are files in `E:/Source/vcpkg/installed/x86-windows/include`.

**Comment by ZachBacon** [comment]
Run the solution file in the IDE, there's a known issue where the msbuild will error out, but the IDE itself will compile.

**Comment by Jamiras** [comment]
I get the same errors in the IDE:
![image](https://user-images.githubusercontent.com/32680403/60853258-7aee4200-a1b8-11e9-95d3-c8011b03520c.png)

However, if I switch the IDE to `Release`, it does succeed.

Which led me to try this, which also succeeds.
```
msbuild /m ALL_BUILD.vcxproj -p:Configuration=Release
```

For thoroughness, I also tried this:
```
cmake .. -DVCPKG_TARGET_TRIPLET=x64-windows -DCMAKE_BUILD_TYPE=Debug
msbuild /m ALL_BUILD.vcxproj
```

Which fails with:
```
CMake Error at src/wx/CMakeLists.txt:122 (file):
  file COPY cannot find
  "E:/Source/vcpkg/installed/x64-windows/debug/bin/SDL2.dll".
```
The file is actually `SDL2d.dll`. Copying `SDL2d.dll` to `SDL2.dll` (and the pdb and lib) allows cmake to complete and msbuild also completes.

My issue has been solved. Thanks.

Feel free to close this, or leave it open as a tracker for updating the README and/or the Debug build process.

**Comment by ZachBacon** [comment]
That's actually good information to have, @rkitover Gonna tag you in this since I'm sure you'd appreciate the report on this.

**Comment by rkitover** [comment]
@Jamiras thank you very much for figuring this out, I will update the readme and fix the SDL2 thing!

**Comment by rkitover** [comment]
Finally got around to updating the `README.md`.

**Comment by orbea** [comment]
@rkitover This issue is fixed now?

**Comment by rkitover** [comment]
I'm keeping this open to track Visual Studio build improvements, there is still a lot to do.
