### ISSUE TITLE
Update libretro memory map for GB

### ISSUE THREAD

**Issue by rzumer** [visualboyadvance-m/visualboyadvance-m#466]
### Background
Memory info from the emulator is passed through the libretro API via https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/src/libretro/libretro.cpp#L287 and https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/src/libretro/libretro.cpp#L1465 for achievement support.

### Issue
The reference memory map has changed recently, and the changes can be seen [here](https://github.com/RetroAchievements/RAIntegration/pull/366). This change was necessary due to limitations in the memory mapping scheme used in RetroArch, and to allow achievements to make use of the GBC banked RAM more easily while unbanked.

I am not familiar with the memory management in VBA-M, so if updating the memory map in `libretro.cpp` is not too difficult and someone with the knowledge is willing to do it, that would be appreciated.

Please refer to the PRs linked in [this one](https://github.com/RetroAchievements/RAIntegration/pull/366) for Gearboy, SameBoy and gambatte-libretro for examples.

**Comment by retro-wertz** [comment]
i opened this issue on the libretro forum in reply to the test you did for Harry Potter. As i posted there, the recent or the first update i was able to make it work. but the last one or final one, i cant get that achievement anymore in harry potter, even with corrected maps.

here was the screenshot when that achievement was working, using the initial memory mapping you did:
https://user-images.githubusercontent.com/23315382/56094446-10a26a00-5f07-11e9-8e01-5e7394158adf.png

**Comment by rzumer** [comment]
Your comment is irrelevant to this issue.

**Comment by retro-wertz** [comment]
not again...

**Comment by rzumer** [comment]
@retro-wertz Sorry, your comment was not clear and I thought it was related to https://github.com/libretro/RetroArch/issues/8582.

The achievement trigger code was not updated following the second memory map change. It was updated today. So if you have changes ready to accommodate the updated memory map I advise trying again.

If it does not work, then it is due to https://github.com/libretro/RetroArch/issues/8582.

**Comment by retro-wertz** [comment]
as stated, cant do anything without fixing in retroarch first. i dont even understand that the initial test case (which is still available as suggested test case in Libretro) still exists despite it being taken down already, the mapping is easy to do, and as stated I made it work despite them having problems making it work in some cores (aside from sameboy which had incorrect memory size to begin with) and as stated in the screenshots both in the libretro page and here, which got ignored anyways, the said test achievement worked on my end.

**Comment by rzumer** [comment]
@retro-wertz You have been commenting on issues and PRs I opened on various projects for a few months now, and you seem to frequently jump to (incorrect) conclusions without understanding what I am actually doing or what issues I am raising, as well as changing the subject away from said issues and PRs.

I would appreciate if you would refrain from commenting on my issues or PRs in the future. Your comments raise confusion and do not help resolve problems.

I invite maintainers and other contributors interested in updating the memory map to raise any questions with this issue in case there is anything unclear. I may send in a PR myself if it will be reviewed by someone other than @retro-wertz.

**Comment by retro-wertz** [comment]
question. adding this said memory map (which btw you never made it worked that time, hence i posted the screenshot of it working on my end coz i understand how to add the memmaps on the core at least), will the core be able to access the banked gbc rams without updating RetroArch. And i am a collaborator, specifically on the Libretro port. Don't go in here and spread you distrust for whatever reasons with regards to libretro and or any of the people working on it.

**Comment by rzumer** [comment]
This can be considered solved after changes made in https://github.com/libretro/gambatte-libretro/pull/138 are reproduced here.
