### ISSUE TITLE
vbam-sdl does not load config with -c flag, will only load from inside directory

### ISSUE THREAD

**Issue by DillonCC97** [visualboyadvance-m/visualboyadvance-m#469]
### Expected behavior
Setting flag -c or --config=FILE should read the given configuration file

### Actual behavior
Default config always loads even when setting config flag
Custom config will only load if vbam is run from inside a directory with a vbam.ini

### Steps to reproduce the behavior
`vbam -c $HOME/.config/gvbam/vbam.ini [game]`
Opens game with default config. Controls, filters etc. all the same

`vbam --config=$HOME/.config/gvbam/vbam.ini [game]`
Opens game with default config. Controls, filters etc. all the same

`cd $HOME/.config/gvbam/ && vbam [game]`
Opens game with `$HOME/.config/gvbam/vbam.ini` as config. Controls and filters all change properly.

### ROM details

Which games are affected by the issue (please state if GBA or GB game): Both GBA and GB are affected

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

Include screenshots of ROM Information (File > ROM Information): not sure how to do this with vbam-sdl, but the same behavior happens with all ROMs I've tried.

### Option details

Video driver (simple, opengl): Opengl

Sound driver (directsound, xaudio, openal, SDL): ALSA

vbam.ini
```
[preferences]
Joy0_Left=0061
Joy0_Right=0064
Joy0_Up=0077
Joy0_Down=0073
Joy0_A=006C
Joy0_B=006B
Joy0_L=0071
Joy0_R=0065
Joy0_Start=010F
Joy0_Select=0008
Joy0_Speed=0020
Joy0_Capture=0125
Joy0_AutoA=0078
Joy0_AutoB=0076
Motion_Left=0104
Motion_Right=0106
Motion_Up=0108
Motion_Down=0102
openGL=1
openGLscale=1
frameSkip=0
gbFrameSkip=0
fullScreen=0
useBios=0
biosFile=none
gbBiosFile=none
skipBios=0
filter=0
disableStatus=0
borderOn=0
borderAutomatic=0
emulatorType=0
colorOption=0
saveDir=$HOME/games/gb/saves
captureDir=$HOME/games/gb/sc
batteryDir=$HOME/games/gb/batt
captureFormat=0
soundQuality=1
soundStereo=0
soundEcho=0
soundSurround=0
declicking=1
saveType=0
flashSize=0
soundVolume=70
ifbType=0
showSpeed=1
showSpeedTransparent=1
autoFrameSkip=0
throttle=100
pauseWhenInactive=0
agbPrint=0
rtcEnabled=0
soundEnable=30f
rewindTimer=0
saveKeysSwitch=2
```

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Arch Linux

If using Linux, specify if using xorg or Wayland: xorg

Version of code (pre-built binary version, or commit ref, or just "master"): vbam-sdl 2.1.3-1 from Arch Community repository

### Hardware details:

If relevant, the joystick you are using and the drivers you are using for it: All controls are on keyboard

**Comment by denisfa** [comment]
@DillonCC97 Thanks for the detailed report. I can confirm this issue and I will start working on it soon.

**Comment by denisfa** [comment]
@DillonCC97 It has been fixed and it will be available on our next release. If you have any other issues/ideas for enhancements for the SDL port, please feel free to open another issue.
