### ISSUE TITLE
Error to start the program

### ISSUE THREAD

**Issue by EtianAM** [visualboyadvance-m/visualboyadvance-m#470]
### Expected behavior
The program starts and is normally displayed
### Actual behavior
The program doesn't start, instead it just displays a window that says:
> Unhandled standard exception of type
"St20bad_array_new_length" with message
"std::bad_array_new_leght"; terminating the application.
### Steps to reproduce the behavior
Only starts the program and this appers
### Crash bugs
I can not send this information, because y do not know how I can do that...
### Build details
OS: Windows x86
Version: 2.1.2 and newest (The version 2.1.1 and oldest is totaly functional)

**Comment by rkitover** [comment]
Use the latest nightly.
