### ISSUE TITLE
MSU1 Support 

### ISSUE THREAD

**Issue by DeathWrench** [visualboyadvance-m/visualboyadvance-m#473]
I've been using some MSU1 for snes9x and it would be really cool to enhance the GBA audio by doing the same thing. I know you guys have lives and it might not become a thing for a long time, but it would be a really cool feature to have nonetheless.

**Comment by ZachBacon** [comment]
Not really going to happen, it's specific to the SNES.

**Comment by DeathWrench** [comment]
Dang
