### ISSUE TITLE
release v2.1.3 (from Releases "visualboyadvance-m-Win-64bit.zip") crashing.

### ISSUE THREAD

**Issue by Kzitold** [visualboyadvance-m/visualboyadvance-m#478]
### Expected behavior
The exe not crashing

### Actual behavior
[The exe crashing with an error dialog.](https://www.dropbox.com/s/pcc1odwhbbku84d/Screenshot%202019-07-27%2016.46.29.png?dl=0)

### Steps to reproduce the behavior
Freshly extracted exe using WinRAR
Just the exe. No other files extracted.

### Build details
[Here's a copy of the receipt.](https://www.dropbox.com/s/u42sv8zi180jtqa/pcreceipt.png?dl=0)
Windows 10

**Comment by ZachBacon** [comment]
For the time being use the latest build from here https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354 the issue has been fixed
