### ISSUE TITLE
Maybe a giant oversight but how do I start it...

### ISSUE THREAD

**Issue by smellyonionman** [visualboyadvance-m/visualboyadvance-m#480]
### Expected behavior
Produce a command to run the emulator

### Actual behavior
Successfully compiled with no way to run the game

### Steps to reproduce the behavior
Compile on Ubuntu 19.04 and be a total noob about it
### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Ubuntu 19.04

If using Linux, specify if using xorg or Wayland: XOrg

Version of code (pre-built binary version, or commit ref, or just "master"): master clone

Basically, I compiled according to the steps produced by ./installdeps.  I followed the wiki steps exactly throughout.  The instructions produced were:

`Done! To build do:

mkdir -p build && cd build
cmake .. 
make -j3`

I received no errors, except for some warnings about GBA_Link.  But no errors.
This actually went much more smoothly than it did in May, when I had to reconfigure packages for libicu63.  This time the steps worked perfectly.

But no .desktop file was generated, and the following commands don't do anything:
`vbam`, `vba-m`, `visualboyadvance-m`, `visualboyadvancem`, and I can't think of anything else :)

Am I really dumb or did something actually go wrong this time?

**Comment by ZachBacon** [comment]
you didn't install it, and if you want to run it in the build directory you need to run it in terminal as ./visualboyadvance-m or just double click on the executable

**Comment by smellyonionman** [comment]
I actually just noticed that file in the build directory.
I seem to be forgetting Linux faster than I am learning it :D  I had it installed last time, apparently.
Thanks for the tip Mr. Bacon.
