### ISSUE TITLE
Two words not translated into Brazilian Portuguese (pt_BR)

### ISSUE THREAD

**Issue by Gumbag** [visualboyadvance-m/visualboyadvance-m#483]
### Expected behavior
Putting the translation, the emulator (less a few words, because there is no direct translation) would be translated

### Actual behavior
Only two words are not translated, which are Open (GBA) and Quit
Open=Abrir
Quit=Sair

### Steps to reproduce the behavior
Put the translation in Brazilian Portuguese

![Sem título](https://user-images.githubusercontent.com/51837985/62567229-2a264380-b861-11e9-879f-bb098da25db1.png)

**Comment by ZachBacon** [comment]
Not really a bug, more like an incomplete translation. 

If you're able, could you submit this to https://www.transifex.com/bgk/vba-m

**Comment by Gumbag** [comment]
> Not really a bug, more like an incomplete translation.
> 
> If you're able, could you submit this to https://www.transifex.com/bgk/vba-m

I didn't know where to report this

**Comment by ZachBacon** [comment]
That's fine, I wasn't being critical or anything.

**Comment by Gumbag** [comment]
Ok

**Comment by cyberdyne-sys** [comment]
Gumball seems to be right i guess, since these aren't just untranlated, but rather hardcoded strings. This issue is present in the hungarian localization too, with several more hardcoded strings anyways.
A few examples:

![vba-m_hardc-str_01](https://user-images.githubusercontent.com/38621070/62630548-7049d880-b92f-11e9-8a77-00dae255e62e.jpg)
![vba-m_hardc-str_02](https://user-images.githubusercontent.com/38621070/62630569-793aaa00-b92f-11e9-9388-b5354df9a929.jpg)
![vba-m_hardc-str_03](https://user-images.githubusercontent.com/38621070/62630579-7f308b00-b92f-11e9-832c-29032eb9b09b.jpg)
![vba-m_hardc-str_04](https://user-images.githubusercontent.com/38621070/62630588-85bf0280-b92f-11e9-9875-ae10ec62a003.jpg)

**Comment by RunisDauphin** [comment]
I know I have asked this in a previous issue, and now that it seems to work, I would like to know: how do you make now translations make effect in your emulator? I would like to try M. Kitover's work on the Spanish and French translations.

Thanks for the info.

Runis Dauphin.

P.D.: I had troubles getting my account unflagged. I have no idea what happened, how and who (and I do not care as long as it does not repeat), but about two months ago I managed to get it unflagged.

**Comment by Gumbag** [comment]
@RunisDauphin download the translation and put it in the folder where the emulator is.

**Comment by RunisDauphin** [comment]
Thank you, I will try as soon as I get to my store unit. I will answer as soon as I manage to make it work.

**Comment by YALouis** [comment]
> @RunisDauphin download the translation and put it in the folder where the emulator is.
![Uploading image.png…]()

I download the translation and attempt to put it any where I thought it should be, however that doesn't work. :(  Would you please tell me how should  me deal with this .mo or .po files.Thanks!

**Comment by YALouis** [comment]
![image](https://user-images.githubusercontent.com/35215030/63618445-ac16ba80-c61e-11e9-98db-2da60c785dba.png)

**Comment by ZachBacon** [comment]
so the po is an uncompiled translation, so off hand that won't work, you need the .mo file which should go in the locale folder of the same name. so if it's zh_CN.mo then it goes into locale/zh_CN/zh_CN.mo

**Comment by rkitover** [comment]
I have the newest `translations.zip` in the nightly thread.

**Comment by YALouis** [comment]
> so the po is an uncompiled translation, so off hand that won't work, you need the .mo file which should go in the locale folder of the same name. so if it's zh_CN.mo then it goes into locale/zh_CN/zh_CN.mo
> 
> It's also dependant on system language too, so if your OS is english, but you want zh_CN, you need to set your OS as that language.

I download the locale.7z from http://www.vba-m.com/ and unzip it ,but there is only 'zh_TW' in it. I created 'zh_CN' myself ,and put some .mo files in it(can be seen in the photos),but it still not works.My OS should be chinese  simplified.


![image](https://user-images.githubusercontent.com/35215030/63629740-9321ff80-c646-11e9-9bd7-9d963cbb9614.png)
![image](https://user-images.githubusercontent.com/35215030/63629747-a339df00-c646-11e9-8459-0cdc3ea13d08.png)

**Comment by ZachBacon** [comment]
get it from here https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354 webpage for vba-m.com is out of date. I still need to redesign the site.

**Comment by denisfa** [comment]
@Gumbag Eu traduzi o que faltava na GUI. Vai estar disponível na próxima versão. Se encontrar algum erro de tradução, é só reportar novamente.

@cyberdyne-sys Thanks for reporting. I believe everything should be translatable now. If there is something you want translated ASAP, I would recommend updating [our transifex](https://www.transifex.com/bgk/vba-m/) directly (only if you want and have time and will. Any type of supporting is kindly appreciated)

**Comment by cyberdyne-sys** [comment]
@denisfa Thank you for your efforts. I guess, there are still some issues with "Cancel" and "OK" buttons, just like with the About dialog. I'll review the whole localized GUI as soon as the new compiled pot file appears. Also thank you for the invitation into the translation team, but i'm already the only maintainer of this language.

**Comment by denisfa** [comment]
@cyberdyne-sys Some of these will still be missing because we need the translation. I did all the pt-BR translation, and all buttons from the screenshots are translated. We should get for all languages eventually, though. Out of curiosity, what is the translation of "Ok" to hungarian?

**Comment by cyberdyne-sys** [comment]
@denisfa Though, OK can be used in almost every country of the world, just like in Hungary, but in more sophisticated translations it could sound like "rendben", or sometimes - according to the current context - "kész" too.

**Comment by RunisDauphin** [comment]
By the way, I am trying the newest developpement version (Windows 32-bit) and I still can not make translation of the emulator lines.

Trying with the es_ES and fr_FR translations, on a Windows 7, Windows 8.1 and Windows 10, all x64 and all with Spanish (Spain) as their S.O. language.

Is it having the language file in the same file as the executable? Is it having the LC_MESSAGES file in the same file as the executable? Is it having the wxvbam.mo file in the same file as the executable?
None of this has worked.

The previous help comment has not helped me (sorry :( ) but I still keep trying.

**Comment by cyberdyne-sys** [comment]
@denisfa After updating the mo file and the binary with the latest nightly, i made a quick check on the GUI and found the followings to be translating, besides "Cancel" and "OK":

![vba-m_00001](https://user-images.githubusercontent.com/38621070/64891689-ed751580-d672-11e9-95ad-c4e296ddc810.jpg)
![vba-m_00002](https://user-images.githubusercontent.com/38621070/64891691-ee0dac00-d672-11e9-8154-54f353ad451d.jpg)
![vba-m_00003](https://user-images.githubusercontent.com/38621070/64891692-ee0dac00-d672-11e9-9ab7-487173318cc9.jpg)
![vba-m_00004](https://user-images.githubusercontent.com/38621070/64891693-ee0dac00-d672-11e9-9365-9b938a749163.jpg)
![vba-m_00005](https://user-images.githubusercontent.com/38621070/64891695-eea64280-d672-11e9-8aeb-17cc8bd97a8e.jpg)
![vba-m_00006](https://user-images.githubusercontent.com/38621070/64891696-eea64280-d672-11e9-90e1-915175737941.jpg)
![vba-m_00007](https://user-images.githubusercontent.com/38621070/64891697-eea64280-d672-11e9-9a00-0388559b2214.jpg)
![vba-m_00008](https://user-images.githubusercontent.com/38621070/64891698-ef3ed900-d672-11e9-9dc0-a5401214aaef.jpg)
![vba-m_00009](https://user-images.githubusercontent.com/38621070/64891699-efd76f80-d672-11e9-8ea0-98b0132827ed.jpg)
![vba-m_000010](https://user-images.githubusercontent.com/38621070/64891700-efd76f80-d672-11e9-8b44-a672b6ce5e22.jpg)
![vba-m_000011](https://user-images.githubusercontent.com/38621070/64891703-efd76f80-d672-11e9-84a2-709680ddb645.jpg)

**Comment by ZachBacon** [comment]
Some of those, actually probably needs the gettext files from wxwidgets themselves. @rkitover besides vba-m's translations, we should look at getting wxwidgets translations included
