### ISSUE TITLE
.sav files corrupted for non-US region ROMs

### ISSUE THREAD

**Issue by Gumbag** [visualboyadvance-m/visualboyadvance-m#484]
### Expected behavior
Open game and play normally

### Actual behavior
The game says the data is corrupted and you can't play

### Steps to reproduce the behavior
Open game and see if data is corrupted

### Crash bugs
Just can't play

### ROM details
Zelda A Link To The Past & Four Swords, both normal rom and hack rom

**Comment by ZachBacon** [comment]
what version of vba-m are you using? one of the nightlies? Release build? You left out some important information. If you could provide them please, we can better diagnose your issue.

**Comment by Gumbag** [comment]
I'm using version 2.1.3, when I was using 1.8.0, it didn't happen, I tried to create a .sav file to see if I could, but it wasn't

Original:
![Sem título 1](https://user-images.githubusercontent.com/51837985/62640890-e3942000-b918-11e9-90ed-a5574a0fd184.png)

Hack:
![Sem título](https://user-images.githubusercontent.com/51837985/62640961-07effc80-b919-11e9-9cf8-956fcfa020dd.png)

**Comment by ZachBacon** [comment]
Can you try this build? https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354#issuecomment-513351748

**Comment by retro-wertz** [comment]
send me or post you savefile. ill test.

**Comment by Gumbag** [comment]
When I try to create, it prevents saying that the file cannot be created

![Sem título 2](https://user-images.githubusercontent.com/51837985/62643892-5accb280-b91f-11e9-91a5-291fd81162ab.png)

**Comment by ZachBacon** [comment]
You aren't using a nightly, the latest build should be versioned 2.1.3-2fcad3f8, again please try the nightly.

**Comment by Gumbag** [comment]
I used this version and gave the same error

![Sem título 3](https://user-images.githubusercontent.com/51837985/62644691-09252780-b921-11e9-9f58-36459aa69767.png)

**Comment by Gumbag** [comment]
I could not create a file in 2.1.3-2fcad3f8

**Comment by denisfa** [comment]
@Gumbag Você consegue criar algum arquivo no diretório onde você está tentando criar o arquivo de save? O pessoal acha que é um problema de permissão de diretório. Se você mudar o jogo da pasta para uma em que você consegue criar arquivos, isso acontece (tipo sua área de trabalho)? Se sim, você chegou a usar uma pasta dedicada para arquivos de save? Isso está no arquivo de configuração `vbam.ini`.

**Comment by Gumbag** [comment]
@denisfa eu já criei uma pasta para saves, mas o problema continua, tentei criar um arquivo .sav e importar e não funcionou, um outro jogo, o Pokémon Emerald não cria um arquivo .sav, mas dá para salvar o jogo mesmo assim, o problema acontece independente da pasta em que o jogo estava, e parece que meu emulador não criar um arquivo vbam.ini, não sei o meu computador Windows 8.1 não cria o arquivo

**Comment by denisfa** [comment]
@Gumbag Cria um arquivo vazio no bloco de notas com nome `vbam.ini` (você tem que abrir o bloco de notas, e na hora de salvar adicionar o `.ini` -- verifica se o tipo é "arquivo de configuração" ao invés de "Documento de texto") no mesmo diretório onde está o executável `2.1.3-2fcad3f8` (tem que ser onde está o `.exe`). Apenas cria, abre o programa e fecha. Depois, verifica se o arquivo `vbam.ini` continua vazio. Ele não deveria estar mais vazio (1). Se este for caso, move o jogo para esta pasta e tenta criar um arquivo de save novamente (2).

Faz isso para o `Zelda A Link To The Past & Four Swords` versão não hack. Eu acho que sei qual é o problema, mas não quero falar para você fazer coisa muito complicada sem motivo.

**Comment by denisfa** [comment]
@Gumbag  (2) tenta, pelo emulador, criar um arquivo de save. Não é para você tentar criar um arquivo `.sav` vazio na pasta e tentar importar*

**Comment by Gumbag** [comment]
@denisfa eu já tentei com o jogo rodando, mas não funcionou, só consegui fazendo de outro jeito, entrei em outro emulador, rodei o jogo e peguei o arquivo .sav e deu certo.

**Comment by denisfa** [comment]
@Gumbag Eu queria entender o porquê do `vbam.ini` não ser criado. Esta pode ser a causa do problema. Você tentou com o meu procedimento? Se você estiver com um arquivo `vbam.ini` na mesma pasta do executável, ele usa este arquivo ao invés do padrão.

Só para confirmar, quando você pressiona "Windows + R", digita "%localappdata%" e confirma com Enter, você visualiza uma pasta `visualboyadvance-m`? É onde deveria estar o arquivo.

O importante mesmo é você conseguir usar o emulador para jogar o que quiser, é que é chato encerrar este problema sem uma explicação melhor do que uma gambiarra. Mesmo assim, se quiser encerrar por aqui, manda uma mensagem de "ok, meu problema foi resolvido" ou alguma coisa parecida e eu investigo mais depois. Seu `windows  8.1` é 32 ou 64 bit?

**Comment by Gumbag** [comment]
@denisfa vi e o arquivo está nesta pasta, o emulador só não estava criando na pasta onde esta ele, e eu tinha tentado com o seu procedimento, mas não deu certo, e meu windows é 64 bits.
Esse problema, também vi em um emulador de celular, que os dados estão corrompidos.

**Comment by denisfa** [comment]
@Gumbag Se eu entendi direito, existem dois problemas então:

1. Você não consegue criar arquivos `.sav` com os jogos na versão nova;
2. Você não conseguiu importar um arquivo `sav` de uma versão antiga para uma nova;

Quando você fala que criou uma pasta para saves, o que isso significa? Você colocou todos os saves lá ou no emulador você apontou que os saves deveriam ficar nesta pasta?

Existe algum motivo para você não enviar o arquivo `vbam.ini`? Alguma informação pessoal ou similar? Você pode colar o texto do arquivo como um comentário aqui. Várias das minhas dúvidas passam por este arquivo.

> o Pokémon Emerald não cria um arquivo .sav, mas dá para salvar o jogo mesmo assim

Ele não cria um `.sav` no diretório do jogo ou naquela pasta de saves que você criou?

**Comment by retro-wertz** [comment]
you should check if other gba game saves fine. in any case this could be path issue or language (assuming your locale)

game works fine on my end (screenshot even taken from the stable 2.1.3 release) :
![Screenshot_2019-08-08_00-58-00](https://user-images.githubusercontent.com/23315382/62817781-9f01c200-bb6e-11e9-94c0-6366c43fd975.png)

**Comment by Gumbag** [comment]
@retro-wertz I think it must be really region, I just downloaded the USA version and it worked, I took the other .sav to see and it worked, I was using the European version.

@denisfa eu fiz uma pasta para saves para não ficar meio "poluída" a pasta do emulador e fiz o emulador mandar os saves para lá, acabei de ver também e o pokémon está criando um save, acho que o problema esta na região do jogo, em que o zelda está na versão europeia.

vbam.ini:
[Display]
Bilinear=0
Filter=none
FilterPlugin=
IFB=none
KeepOnTop=0
MaxThreads=1
RenderMethod=opengl
Scale=3
Stretch=1
[GB]
BiosFile=
GBCBiosFile=
GBCROMDir=C:\\1Nintendo\\visualboyadvance-m-Win-64bit\\GBC
PrintAutoPage=1
PrintScreenCap=0
ROMDir=C:\\1Nintendo\\visualboyadvance-m-Win-64bit\\GB
Palette0=7FFF,56B5,318C,0000,7FFF,56B5,318C,0000
Palette1=7FFF,56B5,318C,0000,7FFF,56B5,318C,0000
Palette2=7FFF,56B5,318C,0000,7FFF,56B5,318C,0000
[GBA]
BiosFile=
LinkAuto=0
LinkFast=0
LinkHost=127.0.0.1
LinkProto=0
LinkTimeout=1
LinkType=0
ROMDir=C:\\1Nintendo\\visualboyadvance-m-Win-64bit\\GBA
[General]
AutoLoadLastState=1
BatteryDir=C:\\1Nintendo\\visualboyadvance-m-Win-64bit\\Save
FreezeRecent=0
OnlineUpdates=daily
RecordingDir=
RewindInterval=0
ScreenshotDir=
StateDir=C:\\1Nintendo\\visualboyadvance-m-Win-64bit\\Save
StatusBar=0
[Joypad]
AutofireThrottle=1
Default=1
[Joypad/1]
Up=CIMA
Down=BAIXO
Left=ESQUERDA
Right=DIREITA
A=Z
B=X
L=A
R=S
Select=BACK
Start=ENTER
MotionUp=
MotionDown=
MotionLeft=
MotionRight=
MotionIn=
MotionOut=
AutoA=
AutoB=
Speed=SPACE
Capture=
GS=
[Joypad/2]
Up=
Down=
Left=
Right=
A=
B=
L=
R=
Select=
Start=
MotionUp=
MotionDown=
MotionLeft=
MotionRight=
MotionIn=
MotionOut=
AutoA=
AutoB=
Speed=
Capture=
GS=
[Joypad/3]
Up=
Down=
Left=
Right=
A=
B=
L=
R=
Select=
Start=
MotionUp=
MotionDown=
MotionLeft=
MotionRight=
MotionIn=
MotionOut=
AutoA=
AutoB=
Speed=
Capture=
GS=
[Joypad/4]
Up=
Down=
Left=
Right=
A=
B=
L=
R=
Select=
Start=
MotionUp=
MotionDown=
MotionLeft=
MotionRight=
MotionIn=
MotionOut=
AutoA=
AutoB=
Speed=
Capture=
GS=
[Sound]
AudioAPI=sdl
AudioDevice=
Buffers=10
Enable=783
GBAFiltering=50
GBAInterpolation=1
GBDeclicking=1
GBEcho=20
GBEnableEffects=0
GBStereo=15
GBSurround=0
Quality=44
Volume=100
[geometry]
fullScreen=0
windowHeight=744
windowWidth=1378
windowX=104
windowY=104
[preferences]
LinkNumPlayers=2
agbPrint=0
autoFrameSkip=0
autoPatch=1
autoSaveCheatList=1
borderAutomatic=0
borderOn=0
captureFormat=0
cheatsEnabled=0
disableStatus=0
emulatorType=1
flashSize=0
frameSkip=0
fsColorDepth=32
fsFrequency=60
fsHeight=600
fsWidth=800
gbPaletteOption=0
gbPrinter=0
gdbBreakOnLoad=0
gdbPort=55555
maxScale=0
pauseWhenInactive=1
rtcEnabled=1
saveType=0
showSpeed=0
showSpeedTransparent=1
skipBios=0
skipSaveGameBattery=0
skipSaveGameCheats=0
speedupFrameSkip=9
speedupThrottle=0
throttle=100
useBiosGB=0
useBiosGBA=0
useBiosGBC=0
vsync=0
[Keyboard]
NOOP=CTRL+O
OPEN=CTRL+A
OpenGB=CTRL+B
OpenGBC=CTRL+C
[Recent]
file1=C:\\1Nintendo\\visualboyadvance-m-Win-64bit\\GBA\\Pokemon Esmeralda (BR).gba
file2=C:\\Users\\Perim\\Desktop\\Legend of Zelda, The - A Link To The Past Four Swords (U) [!].zip
file3=C:\\1Nintendo\\visualboyadvance-m-Win-64bit\\GBC\\The Legend of Zelda - Link's Awakening (T-BR).gbc
file4=C:\\1Nintendo\\visualboyadvance-m-Win-64bit\\GBA\\The Legend Of Zelda- A Link To The Past & Four Swords (BR).gba
file5=
file6=
file7=
file8=
file9=
file10=

**Comment by ZachBacon** [comment]
Next time, just drag the file into the comment box, it'll upload the file.

**Comment by rkitover** [comment]
So what I gathered from this is that for ROMs that are non-US region the `.sav` file might get screwed either upon reading or writing.

**Comment by Gumbag** [comment]
Acabei de ver e parace que só o zelda não está criando um save, e outras rons europeias criam arquivos .sav e não dizem que os dados estão corrompidos.

**Comment by retro-wertz** [comment]
using the EU rom, which has different languages is not also a problem saving games. what i said above is the language or locale of vbam itself since it has been a known problem...

**Comment by Gumbag** [comment]
quando vi o problema, tudo no game overrides estava em default, e mesmo colocando o save type em automatic, ainda continuou o problema, tentei colocar outros idiomas, como o espanhol da Espanha e o francês da França, e não traduziu para eu ver se o problema resolvia

**Comment by rkitover** [comment]
If you guys could narrow down the exact cause, so that we know what to fix, it would be highly appreciated.

**Comment by denisfa** [comment]
@rkitover I did some research here and I found out the issue is the save type. The hack uses `SRAM`, while the original is `EEPROM`. If you override to save for the Hack, then the original stops saving and vice versa.

I have a solution ready, just doing some refactoring and I will create a pr.

**Comment by Squall-Leonhart** [comment]
The proper workaround would have been to tell the user his pirated gba rom isn't welcome here and to dump his own legit copy + implementing automatic trimming for wrong saves.

**Comment by rkitover** [comment]
@Squall-Leonhart how would you suggest we implement automatic trimming?

**Comment by Squall-Leonhart** [comment]
In the case of Eeprom saves, there is no additional data throughout the file, everything is in the first 256-8192b, this goes for SRAM patched roms too (which default to 32KB)

The code already has dialogs set up to do things like throw a warning that the size is wrong and that saving will be disabled (ie, trying to load an old 256b final fantasy legends save, when the game is actually 512b)

Instead of automatically disabling the battery (or trying to load  but corrupting), the dialog could report the file size doesn't match the detected size / type of backup memory and offer to trim only if the existing size exceeds that detected.

I think it is far less likely that we'll come across artificially short save files at this point,  Skid_au has the battery code priorities pretty well done with his last changes back before the move from sourceforge,  coming across files larger than they should be are the most likely issue to come across.

**Comment by Squall-Leonhart** [comment]
Another way to go about it is clamp the battery read size to the detected size, so even if the file was 1MB in size (no game can save a 1MB flash on gba) it'd read only the amount of bytes that are possible for that type.

this would require backing out the change that made the .sav file size override the detected size and changing the save read code, but I suspect it could completely break some of the more significant rom hacks available.

**Comment by inukaze** [comment]
Just change manually Save Type to SRAM to fix it

**Comment by Squall-Leonhart** [comment]
no.

**Comment by inukaze** [comment]
Ok i now the thing with this Zelda ROM is : 

1 - Open the rom, choose language, and see the error
![001](https://user-images.githubusercontent.com/1647332/147710869-d5ef5ae2-0654-4918-8c62-3aa0bb6d3e6c.png)

2 - If you try to create a save game, get another error the file cannot be create
![002](https://user-images.githubusercontent.com/1647332/147710906-8aab2364-e8b5-49ad-aff6-530d72d073d1.png)

> no.
@Squall-Leonhart : Try by this way
3 - Open the "VisualBoyAdvance Overrides" file

Add the follow (for international rom) [Sorry i forgot i had this to my file around 2014]

```
# The Legend Of Zelda : A Link To The Past / Four Swords
[AZLP]
mirroringEnabled=1
flashSize=016384
```
![003](https://user-images.githubusercontent.com/1647332/147710980-33bb4eaf-58dd-4071-8a80-31db1294429d.png)

2 - Change the Save Type to SRAM
![004](https://user-images.githubusercontent.com/1647332/147710993-2aae77fe-d2f0-405a-94a7-1718553b2d6a.png)

![005](https://user-images.githubusercontent.com/1647332/147711005-36b22e98-2909-4805-a4df-ae4b8ae9a542.png)

3 - Reset & Try again (in my case is fixed)
![006](https://user-images.githubusercontent.com/1647332/147711038-78915b5c-e635-49da-8434-9c81b715b7ef.png)
![007](https://user-images.githubusercontent.com/1647332/147711050-e45de300-064f-4855-8a9f-b9a31c53a4c1.png)

**Comment by Squall-Leonhart** [comment]
patched roms are not our problem, use a clean copy that uses the intended save type.

**Comment by inukaze** [comment]
the opinion of another people not my problem, anyone can try this solution(s) and determine by itself if solve the save capability or not. 

to whom it may concern, the rom(s) info i had use is the follow : 
1) The First, i use "SRAM" save type [EEPROM_V122 (64Kbit) (Patched) by Cezar Group]

Internal Title : GBAZELDA
CRC32 : C72F6AE3
Game code : AZLP
Maker Code : 01
Maker Name : Nintendo
Main unit code : 00
Device type : 00
ROM version : 00
CRC : 7f (7f)
MD5 : 623bd6af417ed48b5dbbfd19e78a80d9
SHA1 : 2675b9510f6dcdbfc24b9f9bb35b4191cae33910

2) The Second, i use "EEPROM" save type for make it work [i not had idea if this is the clean rom]

Internal Title : GBAZELDA
CRC32 : 5A164321
Game code : AZLP
Maker Code : 01
Maker Name : Nintendo
Main unit code : 00
Device type : 00
ROM version : 00
CRC : 7f (7f)
MD5 : 9edf4f6e19d901d470aa1117cb0372b3
SHA1 : 3bb7f97ada7d60d8d334b271084effd1db853b32

![vbam](https://user-images.githubusercontent.com/1647332/147720158-c84c2476-35c5-462b-a0c3-87cdae586607.png)

in both case need the override for works.

**Comment by Squall-Leonhart** [comment]
overrides are not required for eeprom clean saves.
