### ISSUE TITLE
Emulator can not connect control Xbox 360

### ISSUE THREAD

**Issue by Gumbag** [visualboyadvance-m/visualboyadvance-m#485]
### Expected behavior
When connecting the control, could change the controls

### Actual behavior
After you change the buttons, when you exit setup, the button menu is blank.

### Steps to reproduce the behavior
Connect the Xbox 360 controller to the computer, change the buttons, after switching press ok

### Hardware details:
Xbox 360 Wireless Control with Receiver

**Comment by ZachBacon** [comment]
I can not confirm this bug, Input works as expected on both my wireless Xbox 360 Controller and Xbox One Controller. I'm beginning to think your issue is that you're running from a read only location, same with your other issues.

**Comment by denisfa** [comment]
@Gumbag Thanks for the report. Could you provide a screenshot of the input menu configuration before you press `Ok` but after setting the input? 

Also, could you report the version you are running, please?

**Comment by denisfa** [comment]
@Gumbag Oi! Eu acho que você é brasileiro por causa do problema # 483, então se quiser pode mandar mensagem em português mesmo para mim. Nós estamos com dificuldades em reproduzir alguns dos problemas que você reportou; se você puder, dê mais detalhes. Faz upload do seu arquivo de configuração `vbam.ini`, por favor. Pode nos ajudar a resolver isto.

**Comment by Gumbag** [comment]
![Sem título](https://user-images.githubusercontent.com/51837985/62815866-40e4c880-baf5-11e9-815d-a662201abbf5.png)

![Sem título 1](https://user-images.githubusercontent.com/51837985/62815871-493d0380-baf5-11e9-9755-6cd70573714a.png)

**Comment by denisfa** [comment]
@Gumbag Nós estamos com um problema de tradução para mapear o controle. O programa não reconhece nenhuma tradução dos controles (exemplos: `Controle1-Hat0N` e `Controle1-Botão5`). Como ele não reconhece, ele apaga a configuração no `Ok`.

Isso não é apenas para português, é para qualquer idioma que não seja inglês americano. Nós já resolvemos isso, mas vai estar disponível apenas na nossa próxima versão (`2.1.7`); deve sair em breve. Se você quiser, podemos gerar um executável temporário para isso. A tradução não vai estar completa, mas pelo menos você vai poder mapear o controle.

Uma solução temporária é você usar inglês na configuração e depois **não** abrir mais a tela de mapeamento (pura gambiarra que funciona).

**Comment by Gumbag** [comment]
Ok

**Comment by denisfa** [comment]
@ZachBacon It is a translation issue. It is a duplicate of #110 for `pt_BR`. We already fixed this in #458. Just waiting for the user feedback.

**Comment by ZachBacon** [comment]
@denisfa Alright, once we get your changes settled, 2.1.4 will be marked. We still need to do those before doing a 2.1.7 ;)

**Comment by rkitover** [comment]
@Gumbag please try latest nightly.
