### ISSUE TITLE
VBA-m stutter

### ISSUE THREAD

**Issue by HiImBrala** [visualboyadvance-m/visualboyadvance-m#488]
### Expected behavior
Game should run in normal speed
### Actual behavior
Game is smooth then slows down back to normal
### Steps to reproduce the behavior
Play any game

**Comment by denisfa** [comment]
@HiImBrala Sorry about the delay here, but could you provide more information? Fill the information on the issue template, please. This helps us to reproduce this behaviour and fix it.

**Comment by ZachBacon** [comment]
It's been 11 days, I'm closing this. If @HiImBrala wants to comment and provide more information, at that point I will reopen then.
