### ISSUE TITLE
Suggestion: Update build process to wxWidgets based on GTK3 for linux

### ISSUE THREAD

**Issue by XXXBold** [visualboyadvance-m/visualboyadvance-m#489]
I'm referring to the PPA for Ubuntu: https://code.launchpad.net/~sergio-br2/+archive/ubuntu/vbam-trunk

The build process should be updated to use wxWidgets based on GTK3 instead of GTK2.
Reason is GTK2 is deprecated and a lot of distros will try to avoid it on the future.

Are there any regressions or other reasons why GTK2 is still used?

**Comment by ZachBacon** [comment]
That's an issue to bring up to the maintainer of that ppa, we do however already allow vba-m to compile against wxwidgets that itself is compiled against gtk3.
