### ISSUE TITLE
Clicking 16-bit in the Cheat Search Section Crashes the Emulator

### ISSUE THREAD

**Issue by DeadSkullzJr** [visualboyadvance-m/visualboyadvance-m#495]
**Expected behavior**
Allow me to click 16-bit in the data size options of the Cheat Search section so making 16-bit searches are possible.

**Actual behavior**
Clicking 16-bit completely crashes the emulator, thus making it impossible to make 16-bit searches.

**Steps to reproduce the behavior**
Open up any game, click Tools->Cheats->Find Cheats->Click 16-bit in the data size section.

**Crash bugs**
I don't have the proper environment to debug and provide this.

**ROM details**

**Which games are affected by the issue (please state if GBA or GB game):**
All GBA games seem to be hit, however here is a couple to test with:

  File: Castlevania - Aria of Sorrow (USA).gba
CRC-32: 35536183
   MD4: 880fbf333b3b9330389f4e338642612c
   MD5: e7470df4d241f73060d14437011b90ce
 SHA-1: abd71fe01ebb201bcc133074db1dd8c5253776c7

Verified Dump Information:
[https://datomatic.no-intro.org/?page=show_record&s=23&n=0983](url)

  File: Metroid - Zero Mission (USA).gba
CRC-32: 5c61a844
   MD4: efc1f8fcd3afd9d17d2cd7d991ecba26
   MD5: ebbce58109988b6da61ebb06c7a432d5
 SHA-1: 5de8536afe1f0078ee6fe1089f890e8c7aa0a6e8

Verified Dump Information:
[https://datomatic.no-intro.org/?page=show_record&s=23&n=1351](url)

Didn't test with Game Boy or Game Boy Color games.

**Which games, if any, are NOT affected by the issue (please state if GBA or GB game):**
None.

**Include screenshots of ROM Information (File > ROM Information):**
Castlevania - Aria of Sorrow
[https://i.postimg.cc/FzTzVPg0/Castlevania.png](url)

Metroid - Zero Mission
[https://i.postimg.cc/bwtYZYMx/Metroid.png](url)

**Option details**

**Video driver (simple, opengl):**
OpenGL

**Sound driver (directsound, xaudio, openal, SDL):**
XAudio2

**Build details**

**Operating System (Windows, Mac, Linux (state distribution), etc.):**
Windows 10 Pro (Version 1809 OS Build 17763.678)

**Version of code (pre-built binary version, or commit ref, or just "master"):**
Commit: 1401573 (2.1.3 release)
[https://github.com/visualboyadvance-m/visualboyadvance-m/commit/1401573f5225a22bd70bcceeb54e267a37b677e0](url)
Most specifically the 64-bit version for Windows.

**Hardware details:**
CPU: Intel(R) Core(TM) i7-7700k CPU @ 4.20 GHz (Clocked at 5.00 GHz)
GPU: ASUS ROG Strix GTX 1060 OC (6GB)
RAM: 16.0 GB (DDR4)

As a side note, I did scan through the issues section to see if anyone had the same problem, seems I am the only one that noticed it.

**Comment by ZachBacon** [comment]
Have you tried one of the nightly builds? https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354#issuecomment-522354350 try that and if it still exists we'll look into it further.

**Comment by DeadSkullzJr** [comment]
> 
> 
> Have you tried one of the nightly builds? [#354 (comment)](https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354#issuecomment-522354350) try that and if it still exists we'll look into it further.

Tested, clicking on 16-bit works on this build, but one of the other issues I encountered on the 2.1.3 release build is still present on this nightly build. Might as well tell what's still broken, apparently making any byte edits in the Memory Viewer still causes some weird issues, the bytes you change tend to change on their own when making edits to bytes next or near that byte(s). Obviously we both know what's supposed to happen when you mess with bytes in the viewer, whatever byte you type in should stay in that location, surrounding bytes when changed shouldn't be messing with the byte you edited. If you want me to make a separate page though for this issue I will do so.

**Comment by ZachBacon** [comment]
No that's fine. I'm about to head to bed myself, but I do thank you for reporting back on the issue. We'll have a look when someone is available on the team.

**Comment by DeadSkullzJr** [comment]
Thanks, sleep well, and good luck!

**Comment by rkitover** [comment]
Memory viewer is completely broken, see #486
