### ISSUE TITLE
crash immediately when setting check updates weekly

### ISSUE THREAD

**Issue by shinecurve** [visualboyadvance-m/visualboyadvance-m#499]
when click OK button in General settings with check for updates weekly, application crash immediately.

system: Windows 10 1903 x64 simp_chinese
vba-m version: visualboyadvance-m 2.1.3 64bit

**Comment by denisfa** [comment]
@shinecurve Thanks for the report. The check for updates was behaving weirdly, so it should be fixed by next release. I will keep this open to investigate some related stuff.

**Comment by ZachBacon** [comment]
@denisfa technically it should be disabled, however, I've been tempted to reimplement the update checker to something along the lines of winsparkle. But for now it should be technically disabled to ensure this doesn't happen again.

**Comment by denisfa** [comment]
@ZachBacon Yeah, it does nothing at all. I would say to just to `ENABLE_ONLINEUPDATES=Off` by default. I don't know what is good or bad on Windows world, but for linux, especially with this package being in official repos, we could turn if off. No idea about mac as well.

**Comment by ZachBacon** [comment]
@denisfa I'll have to agree there. Or I would say, make it a platform condition since on linux we don't really need it.
