### ISSUE TITLE
The Default Shortcuts can not be deleted from Key Shortcuts

### ISSUE THREAD

**Issue by RunisDauphin** [visualboyadvance-m/visualboyadvance-m#502]
### Expected behavior
Every deleted shortcut key remains deleted until Factory Reset (like Développement Version 19/08/2019 does).

### Actual behavior
The deleted keys will come back next time you open VBA-M Développement Version 12/09/2019.

### Steps to reproduce the behavior
Delete any set of defaut keys from Options -> Key Shortcuts, close VBA-M.exe and re-open it.

### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game): Emulator thing.

Which games, if any, are NOT affected by the issue (please state if GBA or GB game): Emulator thing.

Include screenshots of ROM Information (File > ROM Information): Does not proceed.

If you are using a BIOS file, please say which one.
Does not proceed.

### Option details

Video driver (simple, opengl): I do not think this is necessary.

Sound driver (directsound, xaudio, openal, SDL): I do not think this is necessary.

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Windows 10 (This is not my base computer and I can not find which version is).

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"): 2.1.3 D.V., released 12/09/2019 by Rafael Kitover, for Windows.

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it: Keyboard.

Possible Solution: I found a line in the ini called "MMX", who has the keys I just deleted, but next time I open it, those keys are back. Line "NOOP" (who was present in the previous Développement Version, and was the responsable for this improvement) causes an error because the emulator does not know what it is.

P.D.: Thanks for the Auto Hold Keys, they are really useful.

**Comment by denisfa** [comment]
@RunisDauphin Thanks for the report. I can confirm a part of this bug. I am testing this on WIndows 10, but there are some discrepancies:

1. The key indeed stops working. It is not rebooted on next startup. I may need more information here.

2. Replacing `MMX` by `NOOP` did not cause any errors for me.

I will investigate more about this.

**Comment by denisfa** [comment]
More information about this. On `guiinit.cpp` we do a lot of things like:
```
#ifndef MMX

	    if (cmdtab[i].cmd_id == XRCID("MMX"))
	    {
		if (mi)
		    mi->GetMenu()->Remove(mi);
                cmdtab[i].cmd_id = XRCID("NOOP"); // THIS
                cmdtab[i].mi = NULL;
                continue;
	    }
#endif
```

to deactivate commands because they were disabled on compilation time. `MMX` happens to be the last, both on `cmd_id` and code scope. If you remove this part, then you get the previous to last. Eg:
`DebugGDBBreak=CTRL+F1` when you remove this shortcut on config file.

**Comment by denisfa** [comment]
Another update: I have a solution ready. Just checking some code stuff first.

**Comment by RunisDauphin** [comment]
Still makes this weird bug in VBA-M 2.1.4. I have just tried and the keys come back. Is it related with that bug that make the configuration file appear in that corner in C: and load from there?

Runis Dauphin
