### ISSUE TITLE
Emulator running slow on low specs.

### ISSUE THREAD

**Issue by RunisDauphin** [visualboyadvance-m/visualboyadvance-m#503]
Hi, I am Runis Dauphin from Rebelles Unis:

I have troubles with the video settings since version 2.0.0. This emulator runs slow on the computers I try it and I can not apply even the simplest filters I use in any other Game Boy Advance emulator (any old version of VBA or VBA-RR run flawlessly with a hq2x filter, but they do not have anything better than that, and mGBA has its problems with the 2xBR and 3xBR shaders, so I use Pixelate instead). Up until version 2.1.0, it was unplayable in my computers because it never went above 90% of speed.

My point is, Which are the specifications in my computer to have better video options than "Pixelated Image" by default (I like the HQx or High Quality and the xBRZ or Scale by Rules, Zenju version, the most)? I may have a low spec set of computers, that is why I want to know.

Thanks in advance.

Runis Dauphin

P.D.: Now that we are on, Are Kega Fusion plugins still compatible or have they been dropped in compatibility again?

**Comment by denisfa** [comment]
@RunisDauphin What video settings do you use? `OpenGL` or `Simple`? The emulator should not be resource expensive...

What specs are we talking here?

> P.D.: Now that we are on, Are Kega Fusion plugins still compatible or have they been dropped in compatibility again?

Different issue.

**Comment by RunisDauphin** [comment]
I usually use OpenGL because it is what most of the emulators use as their video coder.

And with specs I speak about PC Processor Power (and Clock Speed) and Graphic Card (because my integrated one in the laptop sucks).

Basically those two things.

**Comment by denisfa** [comment]
@RunisDauphin Give me more information, please. What kind of CPU (core i3 etc)? What type of graphic card (`GTX 750` etc)? What FPS do you get? What is the resolution when using the filters (1600x900, 4k etc)?

When you run into this issues, do you know if it is actually taking all CPU resources (all cores 100% or very close)?

> I have troubles with the video settings since version 2.0.0

I can't think of anything that could lead to this. Any ideas @rkitover ?

**Comment by RunisDauphin** [comment]
I will answer to that tomorrow, because now I am with my Windows 7 and not the laptop (Windows 8.1).

The Windows 7 computer has the following specs:
Windows 7 Service Pack 1 x64
Procesador Intel Core TM2 Quad CPU Q8300 @ 2,5 GHz
4 GB RAM (3,75 GB usable)

For the sake of comparison, I will be checking the x86 Windows version, with Puyo Puyo Fever (Japan), in Free Battle Mode, Arle (me) versus Popoi (computer):
Normal: Between 92% (55 fps) and 96% (57 fps).
HQ2x: Between 72% (42 fps) and 78% (46 fps)
2xBRZ: Between 31% (18 fps) and 35% (21 fps) (to be fair, my laptop struggles with xBRZ filters as well, but way less).

Cores: How do I check that on Windows 7 or 8.1? I know how to check the disk or the processor, from the Task Administrator on Windows 8.1.

This is my actual configuration file (who can be used for Issue 502 if necessary). It has no filter loaded now.
[vbam.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/3611261/vbam.zip)

The Windows 10 computers I use in the university for test purposes work flawlessly at least with hq2x filters (I have not checked beyond that).

Thanks for your help.

Runis Dauphin

**Comment by rkitover** [comment]
Please use the latest nightly for testing. Also try xbrz6, that is the nicest filter.

We will definitely look for opportunities to optimize.

**Comment by RunisDauphin** [comment]
I would like, but, as I tell, every filter that I tried to improve the image (basically HQx and xBRZ) makes the emulator go slow (and xBRZ filters make go every emulator that supports them slow in my computers when activated, even the all mighty Kega Fusion, who runs in basically everything with Windows).

I do not see how I am going try the 6xBRZ filter, who looks all nice you want (and, in fact, it does: I like it like there is no other thing on the world) when the 2xBRZ filter makes the emulator run below 25% of its speed in my Windows 7 computer and Windows 8.1 laptop.

The only solution I find (at least for me) is getting a better computer, but it has a problem: "All my problems would get solved if I had more money/income".

So do not get me wrong, I do not try to offend anyone in here, I just say that that does not work for me, at least with these conditions.

Runis Dauphin

**Comment by LuismaSP89** [comment]
In my case "windows 11, gtx970, i7 4790k, 16GB DDR3. The Vba-M runs fine "I'm using 2.1.4 version since there's the latest version, and the current WIP builds have a problem with washed color in the games" but the emulator runs fine with my specs at 1080p using 6xbrz, if I change the resolution in the windows 11 settings and select 2560x1440 the vba-m has a very low framerate. I don't know the reason, since other more demanding emulators with 3D graphics are running fine at 4k with my specs.

**Comment by Squall-Leonhart** [comment]
the 4790k is not a cpu that can run xbrz at 6x. at 1440p.

**Comment by Squall-Leonhart** [comment]
uncheck LCD Filter for the washed out issue, it simulates how the device looks on a real device under strong light.

**Comment by LuismaSP89** [comment]
Thanks for the LCD filter tip, I don't know why this is enabled by default, because the games look darker and a bit washed, but just my opinion.

In the other side the nightly builds run worse than the stable 2.1.4, my computer can handle 6xbrz with golden sun at 1080p with 2.1.4 stable, but with nightly builds, even the 2xbrz destroys the framerate and the sound becomes very choppy, disabling the xbrz filter solves the problem. Is there any new implementation of the xbrz filter on the nightly builds that causes this massive performance drop?

**Comment by Squall-Leonhart** [comment]
you may have downloaded the 64bit version,

32bit has an assembly optimised core which requires less cpu power compared to the x64 version which relies only on compiler optimisations.

**Comment by LuismaSP89** [comment]
I was already using the x64 version of the 2.1.4 stable and runs fine with 1080p and 6xbrz. Anyway I downloaded the x86 nightly version and the result is the same as the x64 nightly, huge performance drop when using xbrz compared to the 2.1.4 stable build.

**Comment by Squall-Leonhart** [comment]
thats entirely inverse results to my tests.

**Comment by LuismaSP89** [comment]
The thing is that something has been changed in the xbrz implementation for the nightly builds, otherwise it makes no sense this huge performance loss. If for you is the opposite maybe depends of the hardware... I don't see any other explanation. We'll see if there is people with the same case when the 2.1.5 is released.

**Comment by Squall-Leonhart** [comment]
nothing has been changed with the filters.

**Comment by Squall-Leonhart** [comment]
rkit is going to introduce the asm optimisation into the 64bit binary, i doubt it'll change all that much though.

**Comment by LuismaSP89** [comment]
Then this is nonsense. Anyway, after the 2.1.5 launch, we'll see the people's feedback.

**Comment by Squall-Leonhart** [comment]
can you join us on irc,

https://web.libera.chat/
channel #vba-m
