### ISSUE TITLE
Emulation is too fast

### ISSUE THREAD

**Issue by Mystro256** [visualboyadvance-m/visualboyadvance-m#51]
I was previously using a personal build based on SVN snapshots but moved to this git version recently. I'm using Fedora (Linux) and I seem to get abnormally really fast emulation speeds, almost as if I was constantly holding down the speed key. Hitting the speed key seems to make things go even faster. It seems like the frame limiter is messed up and games run from 500% to 1000% the normal speed and about 1500% with the speed key hit. I can't reproduce this with OpenGL with WX, but this is always reproducible with GTK, WX+Simple, or WX+Cairo.

I'm going to try to do a git bisect to figure out what happened, but if anyone can point me in the right direction, that may help.

**Comment by Mystro256** [comment]
Found it, it's caused by ef62b1977516a8ea145e9795a434396762d10ce1

I'm thinking it's due to SDL backend not syncing with the audio? I haven't looked too into it. I'll work around the issue for now.

**Comment by DoctorWho11** [comment]
Sorry for the delay. Have you tried with another audio backend like openal?

**Comment by Mystro256** [comment]
I'll check and get back to you

**Comment by DoctorWho11** [comment]
I'll be awaiting.

**Comment by Mystro256** [comment]
Sorry for the delay, I can reproduce this with both SDL and openal.
Manually reverting ef62b19 removes the issue from both as well.

**Comment by DoctorWho11** [comment]
I can't reproduce this issue on my linux setup. But I'll keep trying, even if I have to setup a fedora machine just to see.

**Comment by ichigo-0** [comment]
I'm on debian testing (though I only update occasionally), and have this too with master and Beta-3. However, the version tagged v2.0.0 (1eb768...) seems to work fine.

(In order to compile that version, I had to use newer versions of src/sdl/expr-lex.cpp, expr.cpp, and expr.ypp; or needed at least one of those.)

**Comment by rkitover** [comment]
@ichigo-0 is this with all ROMs you tried or only specific ones? Which ROMs do you use?

**Comment by rkitover** [comment]
@ichigo-0 ah yeah, there is the "throttle" option in vbam.ini, the default setting is `100`.

**Comment by rkitover** [comment]
@Mystro256 and can you also try making sure `throttle=100` is set in your `vbam.ini` and try master?

Either that, or move `~/.vbam` out of the way while testing.

**Comment by ichigo-0** [comment]
While I can't confirm what I had in my vbam.ini file initially, setting throttle=0 seems to give me the previous (too fast) behavior, while setting it back to 100 returns to normal speeds. So that probably was the issue.

**Comment by Mystro256** [comment]
Looks like ```throttle=0``` produces the issue. After a quite look, 0 is default, so if 0 implies no fps limit, I wouldn't say this is a sane default. Perhaps 0 was supposed to imply 100%? Or perhaps it was this default never updated after ef62b19? If so, do you think there's a sane migration method for distros?

From src/common/ConfigManager.cpp:
```c
throttle = ReadPref("throttle", 0);
```

From src/wx/opts.cpp:
```c
INTOPT("preferences/throttle", "", wxTRANSLATE("Throttle game speed, even when accelerated (0-1000%, 0 = disabled)"), throttle, 0, 1000),
```

**Comment by rkitover** [comment]
@Mystro256 @DoctorWho11 

Somehow when I reinitialize the config, I get `throttle=100` generally. How this happens I'm not exactly sure yet, but it looks like `ThrottleCtrl_t` in `guiinit.cpp` is broken, and when you go to the "General" options the throttle value is fixed at `100` and `100%` no matter what you try to change it to. This needs to be fixed of course. Most likely this is due to slightly different behavior of Wx 3.x.

But `throttle=100` and `throttle=0` are supposed to be equivalent, with `0` meaning disabled, and `100` meaning 100% speed, so this needs to be fixed as well.

**Comment by Mystro256** [comment]
A workaround for this bug could be to check if throttle=0, and if so, change it to 100? Similar how you switch from OpenGL to simple render for Wayland.

**Comment by rkitover** [comment]
@Mystro256 I will do that as a last resort, but I would prefer to fix it properly, I'll work on this today.

**Comment by Mystro256** [comment]
Sounds good. I committed the workaround to my git just to push to the official fedora package for now.

**Comment by rkitover** [comment]
@Mystro256 great! How does this work? Will there be a package in dnf in f26 or is there already a package in f25?

**Comment by Mystro256** [comment]
At the moment, there is already a _visualboyadvance-m_ package in Fedora 24/25/26, albeit with some workarounds and patches to get things working smoothly.

Since the git has some cleaner fixes, last night I took a snapshot of git, included the workaround for this issue, and build it for 24/25/26. F26 should land within a day or two, while f24/f25 has to go through the updates channel, which may take up to a week or two before it hits Fedora users.

**Comment by rkitover** [comment]
@Mystro256 thank you very much for taking such good care of the package! Having a working package for a major linux dist definitely helps the project visibility, not to mention help people play Advance Wars and their silly pokemon games.

I'll try to properly resolve the throttle issues soon, I think this bug may have something to do with the SDL sound driver not working on linux and mac as well.

**Comment by Mystro256** [comment]
Haha, no problem, thanks for the dev help! I'll be sure to pass more fixes along if I get more bug reports from the Fedora userbase.

Back on this issue, as I said above, this issue also happens on openal. As well, I noticed this workaround already exists in _xaudio2.cpp_ (see the ```XAudio2_Output::setThrottle``` function), although I didn't really look into it beyond that (I don't own a Windows device). If this is necessary for xaudio, I would guess this maybe an issue with the common code, not SDL specifically.

**Comment by rkitover** [comment]
@Mystro256 so I took a look at this tonight, and it seems like the throttle functionality is not even really implemented beyond some hacks in the sound drivers. Also I couldn't reproduce the throttle controls being broken in the general config again, and I don't remember where I saw that last.

Can you please try the `throttle-fix` branch and see if that fixes everything, more or less? It's like, 3 minor changes to the sound drivers where throttle is checked is all.

Then we can close this.

Btw we're making some progress with someone making debian/ubuntu packages as well.

**Comment by Mystro256** [comment]
Seems to solve the original issue, but the throttle setting doesn't really do anything valuable, although it didn't really work before either.

Basically:
Prior to change, Throttle=0 gives 1000% speed, Throttle>0 gives 100% speed
After change, Throttle<=100 gives 100% speed, Throttle>100 gives 1000% speed

Also I'm thinking you made a coding mistake because you put:
```(throttle == 0 || throttle <= 100)```
and the first conditional would be redundant. I would assume you meant ```throttle == 100```, unless you were just hacking things until it worked.

**Comment by rkitover** [comment]
@Mystro256 Yes you're right, at first I had:

```cxx
if (throttle == 0 || throttle == 100) { ... }
```

so I forgot to remove the first condition when I changed it to `<= 100`.

I think throttle is implemented better in the xaudio driver, although I'm not really sure, and it really shouldn't be the sound drivers controlling game speed anyway.

**Comment by Mystro256** [comment]
Ok, so I've looked into it. The purpose of three code blocks
```c
if (!speedup && throttle && !gba_joybus_active) { ... }
```
appears to be just a wait for synchronization with the sound driver before continuing, so basically just an audio sync.

xaudio.cpp seems to implement the throttle by just using ```SetFrequencyRatio``` to change speed at which the music will play (see the code below). E.g. if the throttle is 50, the sound will play half as fast and audio sync will cause the game to play half as fast. Obviously a hacky solution, as you put it, the sound driver shouldn't be controlling the game speed, but I would leave it as-is until the throttle mechanism is re-implemented correctly (someone should slap a big ```//TODO``` on there).

```c
void XAudio2_Output::setThrottle(unsigned short throttle)
{
    if (!initialized || failed)
        return;

    if (throttle == 0)
        throttle = 100;

    HRESULT hr = sVoice->SetFrequencyRatio((float)throttle / 100.0f);
    assert(hr == S_OK);
}
```

The correct solution for the purpose of closing this issue seems to be to just to remove ```throttle``` condition from the three blocks, since throttle is always going to be non-zero for xaudio (i.e. ```throttle``` always evaluate to true anyway because throttle of 0 is always changed to 100 in the above code), and throttle doesn't work for SDL and openal anyway, so it should be ignored for now.

I can make a PR if you don't quite follow what I'm saying.

**Comment by rkitover** [comment]
I think I'm happy with my solution in 1665f2f of checking if throttle is <= 100 for the time being unless you have any objections.

**Comment by Mystro256** [comment]
Well from just looking at the code, I would think that 1665f2f would break xaudio's throttle code for throttle values > 100. As I said before, as the code currently stands in master, ```throttle``` in xaudio will always evaluate to true, so having it in there in the first place seems misleading as it does nothing. If anything, I would personally advise just removing ```throttle``` altogether from that line of code to avoid future confusion.

As for the other two, it would just mean any throttle <=100 would run at 100% speed, while any throttle value >100 would run full speed without waiting for audio sync (about 1000% in my tests).

**Comment by rkitover** [comment]
@Mystro256 I will test throttle with xaudio tonight.

**Comment by rkitover** [comment]
@Mystro256 I had a chance to test things and throttle works perfectly for xaudio now, with any value below 100 or above 100, you were right about removing the throttle condition (but not because it's always 100, it's the parameter variable in that function, but because since the rate is set there is no reason to drop frames.)

Please take a look at 93538e3c.

As far as having throttle work for e.g. openal, that's probably not a  high priority right now, I don't think many people actually need this.

**Comment by Mystro256** [comment]
That's basically what I want trying to say needs to be done, but I think it got a little misconstrued. I would have done a pull request myself but I didn't have time to make a commit and I haven't been home since testing it. Either way, looks good to me.

**Comment by rkitover** [comment]
@Mystro256 it's all good, discussing how best to implement something always leads to better results.

I was thinking if the xaudio driver can do pretty much perfect throttle control with one API call I might be able to find something similar for openal and dsound and maybe SDL too, I will look some more.

**Comment by Mystro256** [comment]
I looked into SDL, I have a working fix for this issue, see b09ce6d. Please let me know if you want me to make a pull request. Just a few trivial coding errors.

Unfortunately, it seems like SDL's throttle is very hacky, so it doesn't work 100% on all setups (it uses a very messing method of resampling audio). This fix should at least fix cases of 0 or 100 (i.e. full speed throttle).

The solution you have above (93538e3) should work for openal and dsound until it can be properly implemented. I was looking into openal, but I'll post a pull request if I can figure out how to do this.

**Comment by Mystro256** [comment]
You know what. I think I understand what the issue was, looks like this was my fault.

This issue was fixed by b02d948dc102ee3cb48d476794ef4b1ef63feb48 but this commit was missing on my local git for some reason. Looks like throttle of 0 was supposed to mean "no fps limit", not an alias for 100%.

Without the fix, my configuration was incorrectly defaulting to 0, when it should have been defaulting to 100. Although with that said, I still found a mistake in SDL, I'll make a PR for that.

Closing this issue as this isn't actually a bug.

**Comment by rkitover** [comment]
@Mystro256 great, so I did actually fix one thing, making the throttle setting take effect on `LoadGame()` and I committed this to master in 441e6c9e.

**Comment by Mystro256** [comment]
Good! Also see my PR #92, it fixes throttle for SDL.

Openal and dsound do not have a working throttle, but those seem like lower priority.
