### ISSUE TITLE
Building Libretro target appears broken, tested on ARCH=arm & x86_64

### ISSUE THREAD

**Issue by Ntemis** [visualboyadvance-m/visualboyadvance-m#510]
### Expected behavior
To be able to launch a game
### Actual behavior
Goes back to emulation station 

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
tested only gba games

### Build details
https://github.com/batocera-linux/batocera.linux/blob/master/package/batocera/emulators/retroarch/libretro/libretro-vba-m/libretro-vba-m.mk
Operating System (Windows, Mac, Linux (state distribution), etc.):
Batocera/Buildroot Linux system
If using Linux, specify if using xorg or Wayland:
Libretro API
Version of code (pre-built binary version, or commit ref, or just "master"):
Tested latest stable+master with same issue.
Libretro as target is broken, can you please verify.
Thanks

**Comment by ZachBacon** [comment]
Fill out the details, of the platform you are compiling on etc by editing your post. These details are important. Because it could be a bug with your compiler setup potentially.

**Comment by Ntemis** [comment]
@ZachBacon Done

**Comment by orbea** [comment]
It builds here on x86_64 linux, please share build logs.

To build the libretro target all you need is.
```
cd src/libretro
make
```

**Comment by Ntemis** [comment]
I didn't say it doesn't build. The binary produced doesn't work.

Στις Δευ, 30 Σεπ 2019, 16:31 ο χρήστης orbea <notifications@github.com>
έγραψε:

**Comment by ZachBacon** [comment]
Wikipedia page is largely incorrect and we don't control the information on that. The libretro core now supports GB and GBC emulation. But builds at least for 64bit works for me, haven't tested aarch64 myself yet.

**Comment by orbea** [comment]
Sorry I misunderstood, but the binary works here too with both gba and gb games. Can you provide some verbose logs and better explain how it fails?

**Comment by ZachBacon** [comment]
@Ntemis sorry took me a little time to setup an aarch64 chroot, however before I do a few compile tests, I must ask you the platform. One that in my original reply I asked you to fill out. One that's very important.

The arm device you're testing on. What is it? a raspberry pi? bananapi? details like this are very important.

**Comment by Ntemis** [comment]
Tested on Tinkerboard&MiQi (RK3288) Cortex-A17, also tested on X86_64(pc)
I have an image ready for X86_64 if you care to burn with etcher and test i can link it asap.
Let me know

**Comment by ZachBacon** [comment]
Nah, I only care at the moment is the aarch64, since x86_64 my distro can deal with that no issue

**Comment by Ntemis** [comment]
You can boot and test from usb no need to burn or alter your distro or hdd

**Comment by ZachBacon** [comment]
@Ntemis You missed the point. a generic compile of libretro against 64bit compilers would be all that I need. It's the 64bit arm stuff I'm testing against. I generated a binary using qemu-user-mode emulation via an archlinuxarm image I generated myself. But that was based off of the raspberry pi 3 64bit arm tarball. Now that I know what board you're using I can properly find an image and test it against that.

**Comment by Ntemis** [comment]
All boards are treated as arch=aarch32/arm for arm dynarec compatibility reasons since we are a retro gaming distro

**Comment by Ntemis** [comment]
https://www.androidfilehost.com/?fid=1899786940962600530

**Comment by ZachBacon** [comment]
As I've mentioned. I have no need for x86_64 images.

**Comment by negativeExponent** [comment]
why would you want specifically the libretro core if you are gonna use emulation station anyways? i believe that ES supports standalone version and if so, then an sdl version would work. there is also RAVBA if you want if for the retroachievements.

**Comment by ZachBacon** [comment]
We test against retroarch, not against emulation station

**Comment by Ntemis** [comment]
Am closing this down, and please keep up the good work.
It was a binary naming issue
it was trying to launch /usr/lib/libretro/vba-m_libretro.so
but the correct is /usr/lib/libretro/vbam_libretro.so.
Sorry for the noise. :)
