### ISSUE TITLE
.sav files mades using vba-m do not load

### ISSUE THREAD

**Issue by Compani0n** [visualboyadvance-m/visualboyadvance-m#511]
### Expected behavior
I should be able to load .sav files on all the different roms of pokémon red I have 
### Actual behavior
I doesnt load even though a .sav file is created

**Comment by denisfa** [comment]
@Compani0n Thanks for the report, but please fill the issue template. It helps us to reproduce and isolate the bug behaviour. If you can, please upload the sav file that you want to use on vbam.

Did you try to import the `sav` file using the gui? Did you try to start link or something else than default configuration?

**Comment by denisfa** [comment]
@Compani0n Just re-read your issue and I think I have an idea. Check this notice #324. I believe this should be your case.

**Comment by Compani0n** [comment]
Oh yeah it's working actually ! Thanks for the help, i'm very new to the whole github process.
I was just wondering why it wasnt by default. Do you have any idea ?

**Comment by denisfa** [comment]
@Compani0n In a nutshell, sometimes a game has customized save options and we need to override the defaults with that game parameters. We do that already for some, but it is an ever growing list of exceptions. If we fail to detect a game as one of these, them we use the default options, and hence cannot save/play properly.

Anyway, if you have any issues/questions, please report again. We will be gladly to help!

**Comment by Compani0n** [comment]
Thanks :)

**Comment by rkitover** [comment]
@denisfa We should probably add the most common of the hacked roms to our overrides list, this is a common complaint.
