### ISSUE TITLE
Releases gone?

### ISSUE THREAD

**Issue by TheDoctor40** [visualboyadvance-m/visualboyadvance-m#512]
In the readme it says you can find Windows and Mac builds on the releases tab. The only thing I can see though is all different versions of the source code, uploaded 2 days ago, but no build releases. I can't find an official download anymore execpt for the nightly builds, but I'd rather just run a stable build. I used to just be able to download the executable. Where have they gone?

**Comment by rkitover** [comment]
You need to click the assets arrow.

**Comment by TheDoctor40** [comment]
Yeah I saw that, but that only contains the source code. There is no longer an executable you can download and I am not able to build the code on windows myself. When I google around a bit I can find references to pre-built files, but these links now return "Not found".

Example link: https://github.com/visualboyadvance-m/visualboyadvance-m/releases/download/v2.1.0/visualboyadvance-m-Windows-64bit.zip

**Comment by rkitover** [comment]
Yeah it looks like the releases got screwed up when I rewrote all the tags, sorry.

I'll just post a new release.

**Comment by rkitover** [comment]
windows binaries posted, I'll post mac binaries in a couple of minutes

**Comment by rkitover** [comment]
mac binaries posted.

Looks like I just had to republish some of the old releases for them to re-appear, some are gone but those aren't important.

As a bonus, you have a shiny new release.
