### ISSUE TITLE
VBA-M doesn't let me type any number in any preference window

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [visualboyadvance-m/visualboyadvance-m#516]
I was trying to configure the cable link in server-client mode when I noticed I couldn't fill forms like timeout or server IP.

The emulator captured automatically the key 1-6 and resize the window despite not having focus and being paused, so I couldn't write those number.

A possible workaround would be disabling those shortcuts, but it's not a normal behavior and should be fixed.
### Steps to reproduce the behavior
Option->Link->Configure (type 123456 numbers)

This happens in the recent VBA-M 2.1.4 released yesterday, with any rom I tested.

**Comment by rkitover** [comment]
@denisfa can you take a look please?

**Comment by denisfa** [comment]
@rkitover Of course! I believe I know what is happening. Should be fixed soon.

**Comment by ZachBacon** [comment]
@denisfa Much appreciation man.
