### ISSUE TITLE
Error when opening tile viewer

### ISSUE THREAD

**Issue by poesdelal** [visualboyadvance-m/visualboyadvance-m#517]
2.1.4 
Win10 x64

Open tile viewer for every rom show this error:

XRC error: 136: vertical alignment flag "wxALIGN_BOTTOM" has no effect inside a vertical box sizer, remove it and consider inserting a spacer instead

Sometimes error number is 120 and sometimes program just crashes.

**Comment by poesdelal** [comment]
OAM viewer have this issue too.

**Comment by ZachBacon** [comment]
The memory viewer still has issues, that's already been confirmed for a while. The current memory viewer fix was more for scrolling.

Currently though we are going to redesign a lot of the common dialogs, try and have a central location for certain things, like video settings etc, So hopefully the xrc error you're experiencing we can get fixed rather soon.

**Comment by negativeExponent** [comment]
Memory viewer is different from Tile/Oam viewer or other viewers. I myself can get crash in some of these viewers as well.

**Comment by Tenome** [comment]
Same issue.
