### ISSUE TITLE
VBA-M 2.1.4 does not open

### ISSUE THREAD

**Issue by RunisDauphin** [visualboyadvance-m/visualboyadvance-m#518]
### Expected behavior
Programme opens.

### Actual behavior
Programme does not open and gives error.

### Steps to reproduce the behavior
Double click on the exe file (no matter if it is 32 bits or 64 bits).

### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.
![VBA-M 2 1 4 Error](https://user-images.githubusercontent.com/49384468/66185103-99ac8980-e67e-11e9-9001-7a6ff1980723.png)

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game): Does not open.

Which games, if any, are NOT affected by the issue (please state if GBA or GB game): Does not open.

Include screenshots of ROM Information (File > ROM Information):
![VBA-M 2 1 4 Error](https://user-images.githubusercontent.com/49384468/66185103-99ac8980-e67e-11e9-9001-7a6ff1980723.png)

If you are using a BIOS file, please say which one: Does not open.

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Windows 8.1 x64, up to date as of 01/10/2019 (I am actualising it right now). I tried in my other computer with Windows 7 x64 and it opened with no probleme.

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

### Hardware details:
Intel Celeron CPU N2840 @ 2,16 GHz
4GB RAM (3,88 GB Usable)

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by rkitover** [comment]
Well this is strange, I thought I fixed that bug.

Can you try with your joystick unplugged?

**Comment by RunisDauphin** [comment]
I had (and I have) no joystick plugged.

I have just run Ccleaner to clean up the register and miraculously opened up again.

I have no idea of what just happened.

Runis Dauphin

**Comment by RunisDauphin** [comment]
Sorry, again. The probleme was caused by version 2.1.3 (which I swear I think I changed it). I will try again in a few minutes.

**Comment by RunisDauphin** [comment]
Version 2.1.4 opened now just fine. Maybe it was affected by the error of the Register too.
