### ISSUE TITLE
Cheat List does not work as it should

### ISSUE THREAD

**Issue by RunisDauphin** [visualboyadvance-m/visualboyadvance-m#519]
### Expected behavior
You click on Add Cheat and emulator lets you input a code.

### Actual behavior
You click on Add Cheat and emulator crashes.

### Steps to reproduce the behavior
Click Add Cheat on Cheat List.

### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game): It happened to me with Megaman Battle Network (USA), but I think it is a thing of the emulator.

Which games, if any, are NOT affected by the issue (please state if GBA or GB game): Not sure.

Include screenshots of ROM Information (File > ROM Information):

If you are using a BIOS file, please say which one: GBA BIOS

### Option details

Video driver (simple, opengl): OpenGL

Sound driver (directsound, xaudio, openal, SDL): Direct Sound

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Windows 7 and Windows 8.1, up to date as of 01/10/2019.

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"): VBA-M 2.1.3 (Dev version of 12/09/2019) and VBA-M 2.1.4.

### Hardware details:
Detailed in issues 502 and 518.

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:
Wii U GCN USB Adapter
m4sv.com/page/wii-u-gcn-usb-driver

**Comment by negativeExponent** [comment]
the question is what format and cheat codes were added? some requires a master code before you can use any cheat. i just tested now with MMBN2 and adding CB cheats and enabling them worked.

**Comment by RunisDauphin** [comment]
I can not input any code. When I try to hit "Add Cheat" button, the emulator freezes for a few seconds (4 to 5 seconds) and then Windows says "VBA-M has stopped working" and all the stuff Windows says whenever a programme crashes.

The thing I am trying right now is to create a clt file with either Visual Boy Advance 1.8.0 Link or Visual Boy Advance - ReRecording and then export it to VBA-M.

I already have the codes (and I know there are several formats), but, if I can not even open the Add Cheat screen, I think it does not matter how are they.

Runis Dauphin

**Comment by RunisDauphin** [comment]
By the way, Negative Exponent, did you use any kind of BIOS file that is not conflicting with the emulator? Maybe my BIOS file must be disable while I do such kind of things (now it is active for sure).
By the second way, Negative Exponent, which version of Megaman Battle Network 2 are you using? I know it was released in three regions, plus two versions for Console Virtuelle.

Thanks for your help, and I hope this error does not get triggered again, because when triggered, it triggers me too.
Runis Dauphin

**Comment by negativeExponent** [comment]
im using US version of games when i mention any (unless the game itself is never imported). with or without BIOS does not affect when just adding cheats. Im on linux, so it probably works here better than on the Windows version since you said it crashes by just starting to add input.

**Comment by Squall-Leonhart** [comment]
Closing as fixed
