### ISSUE TITLE
GBA: force feedback(rumble) does not work

### ISSUE THREAD

**Issue by negativeExponent** [visualboyadvance-m/visualboyadvance-m#522]
### Expected behavior
controller rumble should work with games that supports it

### Actual behavior

no rumble

### Steps to reproduce the behavior
load drill dozer, or wario twisted
force feedback should just work
(tested on linux with xbox 360 controller)

### ROM details

Which games are affected by the issue (please state if GBA or GB game): gba

Operating System (Windows, Mac, Linux (state distribution), etc.): linux - arch

Version of code (pre-built binary version, or commit ref, or just "master"): master

**Comment by rkitover** [comment]
@negativeExponent I've implemented this in master, can you please check if it is working adequately for you.

**Comment by rkitover** [comment]
@negativeExponent I changed it to always enable rumble regardless of rtc option based on your feedback, and also increased rumble time just in case.

Is the rumble stronger in libretro/mgba? I couldn't run Drill Dozer in mgba, but I'm going to try to test some other things.
