### ISSUE TITLE
Running GB games on GBC mode causes missing sprites

### ISSUE THREAD

**Issue by negativeExponent** [visualboyadvance-m/visualboyadvance-m#539]
### Expected behavior

sprites should appear in color (compared to running it in GB mode)

### Actual behavior

some games have missing sprites

### Steps to reproduce the behavior
this problem is more noticeable in Chikyuu Kaihou Gun ZAS (Japan) since entire ship and enemy is missing/

* load vbam
* make sure emulated gb system is set to Game Boy Color
* load and start Chikyuu Kaihou Gun ZAS (Japan)
* start game and you won't see ship/enemies

- a few other games like bomber man has missing elements like cursor at main selection screen etc.

### Crash bugs

N/A

### ROM details

Which games are affected by the issue (please state if GBA or GB game): GB

Which games, if any, are NOT affected by the issue (please state if GBA or GB game): Chikyuu Kaihou Gun ZAS (Japan) is the best case for test

Include screenshots of ROM Information (File > ROM Information):

If you are using a BIOS file, please say which one. with or without bios does not matter

### Option details

Video driver (simple, opengl): gl

Sound driver (directsound, xaudio, openal, SDL): sdl

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): linux

If using Linux, specify if using xorg or Wayland: xorg

Version of code (pre-built binary version, or commit ref, or just "master"): master

**Comment by RunisDauphin** [comment]
Have you realised what you have written in "Which games are NOT affected by the issue?"

**Comment by Squall-Leonhart** [comment]
Turn on interframe blending, and don't run this old DMG game in forced CGB mode.

**Comment by negativeExponent** [comment]
im confused. why is this closed? are you proposing a fix? or is it that this is NOT suppose to work in gbc mode? i never said anything about sprites flickering or ghosting which can be fixed by using motionblur. the sprites are missing at all. what settings are you using on that vbam 2.1.1 of yours coz without doing anything else with gfx code, sprites are not appearing on my game:

![image](https://user-images.githubusercontent.com/54053706/66607757-8736d080-ebe7-11e9-89b7-22c16f74c7f2.png)

i expect it to be this:
![image](https://user-images.githubusercontent.com/54053706/66607853-b9e0c900-ebe7-11e9-8e48-5bbce88b70b6.png)

**Comment by Squall-Leonhart** [comment]
its closed because its not a bug,

This game runs in DMG backwards compatibility on a real CGB (The equivalent of VBAM Auto select)
When you force the GBC type in the emulator, it runs with the emulated characteristics of the CGB LCD.

the bug that supports the layer of the ships and projectiles is not supported by the CGB LCD, therefore you must run the game with autoselect or Gameboy type, and then use Interframe blending to stop the flickering.

**Comment by negativeExponent** [comment]
again. i am not talking about flickering or ghosting here.

**Comment by Squall-Leonhart** [comment]
the bug that supports the layer of the ships and projectiles is not supported by the CGB LCD, because it explicitly VBlanks before updating the picture, this was an intentional design change because the "Bug" is what caused the blurry behavior of DMG games on the original Gameboy.

**Comment by negativeExponent** [comment]
i dont know why this is even considered "solved" when nothing is being changed and this issue is not something that happended just now. its not even related to whatever gb "bug" you are refering to which causes some gb games to fail in gbc mode (its not a hard fix to be honest-or at least a workaround). mGBA, know to be accurate dont have this problems (and im talking about "missing" sprites here, not flickering) and so are gbc-compatible emu running this game (or issue related to it) are you then implying then that mgba has this wrong while vbam is now suppose to be following hardware accurately? in any case since the core does not seen much update for years, i doubt any attempt at updating compatibility is not a priority (hence closing or applying quick-whatever work fixes to issues like this)

**Comment by Squall-Leonhart** [comment]
You're forcing the Emulator to run the Game on incompatible hardware.

No fix is coming because the cause is user error, you chose to force the game to boot in CGB mode, the Auto, DMG and SGB types all run the game correctly.
