### ISSUE TITLE
v2.1.4 How to set the language? ?

### ISSUE THREAD

**Issue by Kumiri** [visualboyadvance-m/visualboyadvance-m#544]
Officially provided “Language Locale files”
Locale.7z — “Language abbreviation” — LC_MESSAGES — wxvbam.mo
How to use "wxvbam.mo"？

**Comment by rkitover** [comment]
Currently we do not have a way to set the language from the UI.

If you unzip the `translations.zip` into the same directory as the executable, it will run in the Windows system language using the appropriate translation files.

**Comment by Kumiri** [comment]
Oh, I see. Thank you for your answer.
