### ISSUE TITLE
games slow down for no literal reason

### ISSUE THREAD

**Issue by logicminimal** [visualboyadvance-m/visualboyadvance-m#545]
### Please fill out this form:
games play very slow even though it says 60 fps in the latest version

### Expected behavior
for it to run lagless

### Actual behavior
it gets fps drops, even in super mario bros 3. a 1 mb game..
it randomly gets fps drops and therefore slows down when i generate new horizontal lines ( basically just play the game ) i have tried every pixel filter simple opengl and stuff but none semt to do anything

### Steps to reproduce the behavior
i dont know as  i dont have any experience in development
### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details
super mario advance 4 super mario bros 3
super mario world gba
the yoshi supermario game
Which games are affected by the issue (please state if GBA or GB game):
all of these that i have mentioned early
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
gba pokemon roms i guess
Include screenshots of ROM Information (File > ROM Information):

If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl):
opengl
Sound driver (directsound, xaudio, openal, SDL):
idk
### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
win 10 32 bit
If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

### Hardware details:
@e5200 dual core pentium 2.50 ghz
3 gb ddr2 667   mhz ram
geforce 210
If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by rkitover** [comment]
Does it start normally and then slow down the longer you play, or does it start slow from the very beginning?

**Comment by supremayro420** [comment]
> 
> 
> Does it start normally and then slow down the longer you play, or does it start slow from the very beginning?

no, it slows down when i move to the right. and that generated chunk has a sprite in it.
not like it plays in %50 of the speed. more like it skips a lot of frames and makes it laggy instead of slow

**Comment by denisfa** [comment]
@supremayro420 Could you try running again with a clean configuration file? Also, how is the sound while playing with lagging? Is it normal or also stutters?

**Comment by supremayro420** [comment]
> 
> 
> @supremayro420 Could you try running again with a clean configuration file? Also, how is the sound while playing with lagging? Is it normal or also stutters?

there is nothing wrong with the sound. what's wrong is the game doesnt feel like 60/30 fps. fps counter tells that fps is stable 60. all awhile it doesnt feel like 60 at all. i've tried everything i could find from internet like changing renderer to opengl

**Comment by supremayro420** [comment]
> 
> 
> @supremayro420 Could you try running again with a clean configuration file? Also, how is the sound while playing with lagging? Is it normal or also stutters?

ooh and actually turns out it isnt like lag. but more like throttle yet i have throttle  on 0% it throttles when new sprites load

**Comment by denisfa** [comment]
> there is nothing wrong with the sound. what's wrong is the game doesnt feel like 60/30 fps. fps counter tells that fps is stable 60. all awhile it doesnt feel like 60 at all. i've tried everything i could find from internet like changing renderer to opengl

> ooh and actually turns out it isnt like lag. but more like throttle yet i have throttle on 0% it throttles when new sprites load

@supremayro420 Thank you! I will take a look at possible causes. Last question: did it happen on previous versions of vbam as well? If you are willing to do so, try recording the gameplay for some seconds and  then watch the recording. Check if they match. Upload the recording here as well if you see something suspicious.

**Comment by logicminimal** [comment]
this issue is 2 years old at this point. closed

**Comment by Squall-Leonhart** [comment]
this issue was always caused by not having mirroring enabled, i don't know how you have a configuration where this is the case because the inbuild game database includes the necessary settings for all of the classic nes series.

**Comment by logicminimal** [comment]
> this issue was always caused by not having mirroring enabled, i don't know how you have a configuration where this is the case because the inbuild game database includes the necessary settings for all of the classic nes series.

i really dont remember what exactly caused me to write this issue
