### ISSUE TITLE
Build fails on Ubuntu Bionic 32bit

### ISSUE THREAD

**Issue by Ntemis** [visualboyadvance-m/visualboyadvance-m#554]
Scanning dependencies of target visualboyadvance-m
[ 90%] Building CXX object src/wx/CMakeFiles/visualboyadvance-m.dir/wxvbam.cpp.o
[ 90%] Building CXX object src/wx/CMakeFiles/visualboyadvance-m.dir/guiinit.cpp.o
[ 91%] Building CXX object src/wx/CMakeFiles/visualboyadvance-m.dir/viewers.cpp.o
[ 91%] Building CXX object src/wx/CMakeFiles/visualboyadvance-m.dir/gfxviewers.cpp.o
[ 92%] Building CXX object src/wx/CMakeFiles/visualboyadvance-m.dir/cmdevents.cpp.o
[ 92%] Building CXX object src/wx/CMakeFiles/visualboyadvance-m.dir/opts.cpp.o
[ 93%] Building CXX object src/wx/CMakeFiles/visualboyadvance-m.dir/sys.cpp.o
[ 93%] Building CXX object src/wx/CMakeFiles/visualboyadvance-m.dir/panel.cpp.o
In file included from /usr/include/wx-3.0/wx/meta/movable.h:13:0,
                 from /usr/include/wx-3.0/wx/vector.h:32,
                 from /usr/include/wx-3.0/wx/list.h:34,
                 from /usr/include/wx-3.0/wx/gdicmn.h:19,
                 from /usr/include/wx-3.0/wx/gtk/cursor.h:13,
                 from /usr/include/wx-3.0/wx/cursor.h:48,
                 from /usr/include/wx-3.0/wx/dc.h:21,
                 from /usr/include/wx-3.0/wx/dcmemory.h:14,
                 from /usr/include/wx-3.0/wx/dcbuffer.h:14,
                 from /home/demetris/Desktop/visualboyadvance-m/src/wx/panel.cpp:5:
/usr/include/wx-3.0/wx/meta/pod.h:76:23: fatal error: template instantiation depth exceeds maximum of 900 instantiating ‘wxIsPod<wxXmlResourceHandler*>::value’, possibly from virtual table generation (use -ftemplate-depth= to increase the maximum)
     static const bool value = true;
                       ^~~~~
compilation terminated.
src/wx/CMakeFiles/visualboyadvance-m.dir/build.make:292: recipe for target 'src/wx/CMakeFiles/visualboyadvance-m.dir/panel.cpp.o' failed
make[2]: *** [src/wx/CMakeFiles/visualboyadvance-m.dir/panel.cpp.o] Error 1
CMakeFiles/Makefile2:423: recipe for target 'src/wx/CMakeFiles/visualboyadvance-m.dir/all' failed
make[1]: *** [src/wx/CMakeFiles/visualboyadvance-m.dir/all] Error 2
Makefile:151: recipe for target 'all' failed

**Comment by rkitover** [comment]
I just built it fine on bionic, though not 32 bit, I doubt that makes a difference.

Make sure your environment is clean, no `CXXFLAGS`/`CPPFLAGS`/`LDFLAGS` etc..

**Comment by Ntemis** [comment]
I updated the gcc via ppa and it builds fine now
