### ISSUE TITLE
BUG with Filters

### ISSUE THREAD

**Issue by Resue** [visualboyadvance-m/visualboyadvance-m#561]
Black line appeared when applied filters.

Version: 2.1.4

See the picture:
![bug](https://user-images.githubusercontent.com/57211862/68266044-d6f2a580-0088-11ea-843a-23e51fe7bb0e.png)

**Comment by rkitover** [comment]
@denisfa hey I think you made some changes to filter calculations previously, any ideas here?

**Comment by thatonegoyim** [comment]
i notice a very transparent grayish bar similar to that one using filters #1 #6 #7 when cycling through filters using ctrl + g or the menu. so its not just bi-linear filter. just wanted to add to what they posted

**Comment by denisfa** [comment]
@rkitover Yes, I know why. It is from [this scope](https://github.com/visualboyadvance-m/visualboyadvance-m/pull/494/files#r318804621). The black line is our top border.
