### ISSUE TITLE
[patch] CMake fails when OpenAL is absent

### ISSUE THREAD

**Issue by witcher-bayonetta** [visualboyadvance-m/visualboyadvance-m#563]
Version: visualboyadvance-m v2.1.4
Environment: Gentoo Linux with wxWidgets, without OpenAL

If you try to build vbam with wxWidgets in an environment where OpenAL is not installed, cmake fails. (We will soon see the error message.)

I attached a fix at the bottom. Though it works for me, it's a quick-n-dirty guess, because I don't know CMake. It simply adds

`unset(OPENAL\_LIBRARY CACHE)`

to src/wx/CMakeLists.txt when OpenAL is not found.

The build log looks like this:
- - - - -
> [...]
> -- Found gcc-ranlib: /usr/x86\_64-pc-linux-gnu/gcc-bin/7.3.0/x86\_64-pc-linux-gnu-gcc-ranlib
> -- Could NOT find OpenAL (missing: OPENAL\_LIBRARY OPENAL\_INCLUDE\_DIR)
> -- Found X11: /usr/include
> -- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
> [...]
> -- Looking for \_\_WXGTK3\_\_ - found
> -- Checking for module 'gtk+-3.0'
> --   Found gtk+-3.0, version 3.22.15
> -- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1")
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
> Please set them or make sure they are set and tested correctly in the CMake files:
> OPENAL\_LIBRARY (ADVANCED)
>     linked by target "visualboyadvance-m" in directory /tmp/portage/portage/games-emulation/vbam-2.1.4/work/visualboyadvance-m-2.1.4/src/wx
- - - - -
Thank you very much for developing vbam. I'm so happy that hotkeys work now reliably in Linux. Best regards.

The patch:

<pre>diff --git a/src/wx/CMakeLists.txt b/src/wx/CMakeLists.txt
index ba52363d..1d96d47e 100644
--- a/src/wx/CMakeLists.txt
+++ b/src/wx/CMakeLists.txt
@@ -48,4 +48,5 @@ if(ENABLE_OPENAL)
 	endif()
 else()
     add_definitions(-DNO_OAL)
+    unset(OPENAL_LIBRARY CACHE)
 endif()

 if(APPLE)</pre>

**Comment by ZachBacon** [comment]
Please submit this as a pull request and not as a patch.

**Comment by denisfa** [comment]
@ZachBacon does our CI try different compilation options? Or is it something like "enable everything and see if it fails"?

**Comment by orbea** [comment]
@denisfa It would be trivial to add this support to travis.

I suspect there is a better way to refactor to OpenAL `find_package` checks to avoid this issue, but I haven't looked too closely yet.

**Comment by rkitover** [comment]
To add this to travis we need to add flags to installdeps to skip dependencies like openal and ffmpeg.

**Comment by rkitover** [comment]
This is fixed now and tested for on travis.
