### ISSUE TITLE
installdeps: Obsolete debian package reference

### ISSUE THREAD

**Issue by ObscenityIB** [visualboyadvance-m/visualboyadvance-m#564]
### Expected behavior
`./installdeps` succeeds
### Actual behavior
`E: Package 'libwxgtk3.0-dev' has no installation candidate`
### Steps to reproduce the behavior
pull bd7f38ece783abd10358ca05c2f9b9a66173414c 
`./installdeps`
### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Linux (Debian/Ubuntu)
If using Linux, specify if using xorg or Wayland:
both
Version of code (pre-built binary version, or commit ref, or just "master"):
bd7f38ece783abd10358ca05c2f9b9a66173414c

## Solution

use `libwxgtk3.0-gtk3-dev` over `libwxgtk3.0-dev`

**Comment by rkitover** [comment]
which ubuntu is this?

Run this:

```bash
lsb_release -a
```

**Comment by ObscenityIB** [comment]
@rkitover 

```
No LSB modules are available.
Distributor ID:	Kali
Description:	Kali GNU/Linux Rolling
Release:	2019.4
Codename:	kali-rolling
```
Yeah its my everyday distro, because it has all I need.

PS. Last succesful build was eaa744cc and is still currently installed.

**Comment by ObscenityIB** [comment]
My solution got rid of the warning but there's still an error later on, oddly with gtk2 instead of the gtk3 that was just replaced.

```
In file included from /usr/include/gtk-2.0/gdk/gdkscreen.h:32,
                 from /usr/include/gtk-2.0/gdk/gdkapplaunchcontext.h:31,
                 from /usr/include/gtk-2.0/gdk/gdk.h:32,
                 from /usr/include/gtk-2.0/gdk/gdkprivate.h:30,
                 from /usr/include/gtk-2.0/gdk/gdkx.h:30,
                 from /home/obscenity/DEV/git/visualboyadvance-m/src/wx/panel.cpp:1330:
/usr/include/gtk-2.0/gdk/gdktypes.h:114:39: error: conflicting declaration ‘typedef struct _GdkDrawable GdkWindow’
  114 | typedef struct _GdkDrawable           GdkWindow;
      |                                       ^~~~~~~~~
```

**Comment by rkitover** [comment]
This should be fixed in master, please re-run `./installdeps` and let me know if you have any further issues.

**Comment by ObscenityIB** [comment]
@rkitover yep works great, the other gtk2 error also cleared itself up when I purged and reinstalled it.
