### ISSUE TITLE
Accept gamepad input in hotkey assignment [Feature Request] [Enhancement]

### ISSUE THREAD

**Issue by mcabel** [visualboyadvance-m/visualboyadvance-m#569]
### Expected behavior

It would be really useful to assign gamepad/joystick buttons to hotkeys and auto-fire.
This way, one could have savestates, Toggle fast forward, and other useful functionality pretty accessible.

 ### Steps to reproduce the behavior
Options > KeyShortcuts
 
### ROM details
N/A

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 8.1
 

Version of code (pre-built binary version, or commit ref, or just "master"):
2.1.3
### Hardware details:

If relevant, the joystick you are using and the drivers you are using for it:
PS4 gamepad with Steam Drivers

**Comment by rkitover** [comment]
This is already implemented in master (available in the nightly.) Go to `Options -> Key Shortcuts` and you can assign joystick events to UI actions when you are in the shortcut field.

Does this do what you want?

If you need other, specific UI bindings to be available in that configuration dialog, please file a separate issue for each one.

**Comment by tdeeb** [comment]
Hi @rkitover, I tried master and it works perfectly! Thank you!
