### ISSUE TITLE
Adding Portable Mode

### ISSUE THREAD

**Issue by Papermanzero** [visualboyadvance-m/visualboyadvance-m#57]
### Expected behavior
Visualboyadvance-M shall create a settings file within its install folder (for all settings).
No registry entries or roaming data folder shall be created. The only folder which shall be used is the install folder.

### Actual behavior
Visualboyadvance-M stores the settings to a place which is "unknown" for the user.

### Steps to reproduce the behavior
Start VBA-M configure something. Change the path from the vba-m.exe and verify if the settings remain.

### Build details
Latest Beta 3 from the releases. Windows 10

**Comment by DoctorWho11** [comment]
It already has portable mode, just by default uses appdata folder, just move the config to exe level and it will be in portable mode.

**Comment by Papermanzero** [comment]
I see. This is great. :-)
It is just a proposal but to make it more user-friendly why not adding an option or a text file to indicate the portable mode (like dolphin)

**Comment by DoctorWho11** [comment]
Well in due time. Right now we are rather busy with some other work, but I'll add it as a 2.0 final target to do list.
