### ISSUE TITLE
Allow multiple assignments for each gamepad button [Enhancement][Feature Request]

### ISSUE THREAD

**Issue by mcabel** [visualboyadvance-m/visualboyadvance-m#570]
### Expected behavior
Have the ability to assign multiple gamepad/joystick buttons to a single game button.
Examples:
+Assigning BOTH dpad and left joystick to movement.
+Have "A" button on Circle, triangle and R2
+ Map movement to Dpad. Also map "up" from the emulator to up from the second joystick, individually. (can use up in mapped dpad and second joystick)
+and so on...
-as an example PPSSPP emulator can assign any number of keys to any button.

### Actual behavior
Current mapping is 1:1

**Comment by ZachBacon** [comment]
You just duplicated the same issue... Only one please.

**Comment by mcabel** [comment]
@ZachBacon it's a different issue ^^;

**Comment by ZachBacon** [comment]
@mcabel it's input related, then append your last issue since it's essentially the same topic

**Comment by mcabel** [comment]
I can append if you want to keep it that way, but one would deal with the hotkeys modules while the other would deal with basic input modules. Wouldn't it be cleaner to keep them separate?
I'll do as you advise @ZachBacon

**Comment by ZachBacon** [comment]
@mcabel never mind.

**Comment by mcabel** [comment]
I realized this is NOT an issue. The current version does this. For some reason it did not work the first time I tried. My apologies.
