### ISSUE TITLE
ubuntu How to set the language?

### ISSUE THREAD

**Issue by lgczszs** [visualboyadvance-m/visualboyadvance-m#574]

**Comment by ZachBacon** [comment]
@lgczszs Assuming the translations are properly installed, it should follow your operating systems set language

**Comment by lgczszs** [comment]
I compiled the code, how to change the language from the source code

**Comment by ZachBacon** [comment]
My answer is shown above.

**Comment by lgczszs** [comment]
How to install translation correctly

**Comment by ZachBacon** [comment]
How about asking the Ubuntu forums for that. We aren't an operating system support forum.

**Comment by lgczszs** [comment]
This is because the compilation tutorial does not say how to compile the language

**Comment by ZachBacon** [comment]
Translations are automatically compiled and installed upon make install. And if you install into /usr then what I said still stands.

**Comment by lgczszs** [comment]
It's fixed after executing make install ,thank you
