### ISSUE TITLE
Very laggy ROM, any game

### ISSUE THREAD

**Issue by JPValejo** [visualboyadvance-m/visualboyadvance-m#576]
### Expected behavior
game to run smoothly

### Actual behavior
varry laggy game, both video and sound.

### Steps to reproduce the behavior
open any game... i dont know whats wrong with my setup. is an old laptop, but should run.

### Crash bugs

didn't crashed at any time.

### ROM details
![image](https://user-images.githubusercontent.com/58639338/70380020-a6b25700-1913-11ea-86cc-b7d01c4d2522.png)
![image](https://user-images.githubusercontent.com/58639338/70380028-b762cd00-1913-11ea-8cb6-3d6a23fdfd50.png)
both this game are afected.
tried other pokemon game and all do the same thing

(If you are using a BIOS file, please say which one.)<< don't know what this means.

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows 7.):

Version of code (VBA-M 2.1.4"):

### Hardware details:

Intel i5-M30
![image](https://user-images.githubusercontent.com/58639338/70380055-1aecfa80-1914-11ea-97fd-3463a24e3357.png)

**Comment by JPValejo** [comment]
Just un update>>> I just tried the VBA-M-WX and didn't had any problem... any idea what could be?

**Comment by ZachBacon** [comment]
We only support the wxwidgets frontend now. A lot of our effort went into polishing that up. That's all I can say.

**Comment by denisfa** [comment]
@JPValejo We are always trying to optimize. 

> Just un update>>> I just tried the VBA-M-WX and didn't had any problem... any idea what could be?

Did you have a special config for VBA-M-WX? Did you try the same config with the latest VBA-M? This is very unlikely, but I just want a simple confirmation.
