### ISSUE TITLE
Compiler warning: tautological comparison

### ISSUE THREAD

**Issue by wjmelements** [visualboyadvance-m/visualboyadvance-m#578]
During make -j
```
~/projects/visualboyadvance-m/src/gba/ereader.cpp:459:23: warning: comparison of unsigned expression >= 0 is always true [-Wtautological-compare]
        if ((reg[0].I >= 0) && (reg[0].I <= 0x10)) {
             ~~~~~~~~ ^  ~
1 warning generated.
```
This might be causing another issue.

**Comment by denisfa** [comment]
@wjmelements Sorry for the delay, but could you explain about what other issue this may cause? We know about some warnings, but we are not aware of bugs due to it. Also, please provide some more details (compiler and version).
