### ISSUE TITLE
Issues compiling in Ubuntu.

### ISSUE THREAD

**Issue by pqnhan** [visualboyadvance-m/visualboyadvance-m#58]
I tried to compile the source code on ubuntu x86_64 but get error:
[ 84%] Linking CXX executable ../../visualboyadvance-m
/usr/bin/ld: cannot find -lgtk-x11-2.0
/usr/bin/ld: cannot find -lgdk-x11-2.0
/usr/bin/ld: cannot find -lpangocairo-1.0
/usr/bin/ld: cannot find -lcairo
/usr/bin/ld: cannot find -lgdk_pixbuf-2.0
/usr/bin/ld: cannot find -lpangoft2-1.0
/usr/bin/ld: cannot find -lpango-1.0
/usr/bin/ld: cannot find -lfontconfig
/usr/bin/ld: cannot find -lfreetype
collect2: error: ld returned 1 exit status
src/wx/CMakeFiles/visualboyadvance-m.dir/build.make:554: recipe for target 'visualboyadvance-m' failed.
make[2]: *** [visualboyadvance-m] Error 1
CMakeFiles/Makefile2:219: recipe for target 'src/wx/CMakeFiles/visualboyadvance-m.dir/all' failed
make[1]: *** [src/wx/CMakeFiles/visualboyadvance-m.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

What can i do to fix it? Thanks.

**Comment by sergiobenrocha2** [comment]
You're missing the dependences

```
libavcodec-dev libavformat-dev libavutil-dev libcairo2-dev libgl1-mesa-dev libgtkglextmm-x11-1.2-dev libgtkmm-2.4-dev liblircclient-dev libopenal-dev libpng-dev libsdl1.2-dev libsfml-dev libswscale-dev libwxbase3.0-dev libwxgtk3.0-dev zip zlib1g-dev
```

**Comment by rkitover** [comment]
@pqnhan Can you try master again? What version of Ubuntu is this?
