### ISSUE TITLE
Turbo mode gets stuck after saving the file while having it on.

### ISSUE THREAD

**Issue by CoolFer3** [visualboyadvance-m/visualboyadvance-m#581]
### Expected behavior:
Turbo mode is supposed to disable when you press the hotkey that you chose for it.

### Actual behavior
When i try to press the hotkey to disable turbo mode, it does nothing and it stays fast. i think this happens because i saved the file while having turbo mode enabled

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
Pokemon Emerald (GBA)

### Build details

Version of code (pre-built binary version, or commit ref, or just "master"): 2.1.4

**Comment by CoolFer3** [comment]
im sorry if there is not enough information but this is the first time im using this emulator.

**Comment by denisfa** [comment]
@CoolFer3 Thanks for the report. But there is at least one important thing missing: the vbam version you are using. Go on `Help` > `About`. It should be the second line.

Is this a issue with the hotkey only? When the game is running, if you use the menu option, does it work (removes the turbo)?

**Comment by CoolFer3** [comment]
no, the issua is still there when i try to disable turbo mode from the menu

**Comment by CoolFer3** [comment]
and im using the version 2.1.4

**Comment by Pikachuisgood** [comment]
very easy : just do help--> factory reset

**Comment by denisfa** [comment]
@CoolFer3 This looks very weird... I was thinking about a toggling issue, but it seems very different.

If you can, please upload your save file `.sav` and your config `vbam.ini` for us to check.

@Pikachuisgood Have you had this issue before? Can you give us more information about your case, please?

**Comment by Pikachuisgood** [comment]
yeah i had this issues before and it work for me 
this was exactly like him

**Comment by denisfa** [comment]
@Pikachuisgood Thank you! That confirms this is a config issue. Although I still would like to see the config file while this issue is happening, to be 100% sure.

@CoolFer3 Check the solution above from @Pikachuisgood. Before that, please upload your configuration file so I can check and close this.

**Comment by CoolFer3** [comment]
it doesn't let me upload my save file

**Comment by CoolFer3** [comment]
@Pikachuisgood thank you very much for the advice :) it worked and my game is fixed.
also thank you denisfa for trying to help me with my issue, i like that you guys really care about your emulator and i appriciate your work!

**Comment by Pikachuisgood** [comment]
no problem buddy ;)

**Comment by Pikachuisgood** [comment]
i make an account just for fixing ur problem

**Comment by ZachBacon** [comment]
If this is resolved, I'm closing this.
