### ISSUE TITLE
Input latency increased by 1 frame since last rework

### ISSUE THREAD

**Issue by negativeExponent** [visualboyadvance-m/visualboyadvance-m#582]
### Expected behavior

same input latency by frames

### Actual behavior

increased by 1 frame

### Steps to reproduce the behavior

Super Mario Advance 4 - Super Mario Bros. 3 (USA) is a good game for the test.
- start the game in world 1
- pause game.
- press and hold the "jump" button
- press "next frame" hotkey (ctrl+N default)
- Mario jumps on the 3rd press

compared to before joystick rework, Mario jumps on the 2nd times ctrl+N is pressed

### Crash bugs
[N/A]

### ROM details

Which games are affected by the issue (please state if GBA or GB game): all

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

Include screenshots of ROM Information (File > ROM Information):

If you are using a BIOS file, please say which one. [n/a]

### Option details

Video driver (simple, opengl): gp

Sound driver (directsound, xaudio, openal, SDL): sdl

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): arch

If using Linux, specify if using xorg or Wayland: xorg

Version of code (pre-built binary version, or commit ref, or just "master"): master

**Comment by ZachBacon** [comment]
most likely it's due to the input rework that @rkitover put into, trying to get device polling for hot plug support. Thanks for the report

**Comment by rkitover** [comment]
@negativeExponent I might have set the poll frequency too high, can you please try changing `POLL_TIME_MS` in `src/wx/widgets/wx/sdljoy.h` to `50` or even `100`.

**Comment by rkitover** [comment]
Never mind what I said earlier, I realized what it is, should be fixed in master. Please reopen if that is not the case.

**Comment by negativeExponent** [comment]
no difference. put polling before emuMain

**Comment by rkitover** [comment]
Sorry should have tested this, does it work now?

**Comment by negativeExponent** [comment]
> Sorry should have tested this, does it work now?

yeah, not it has better response.

**Comment by rkitover** [comment]
Awesome, thank you very much for testing!
