### ISSUE TITLE
Loading save causes music to stop playing temporarily in Aria of Sorrow

### ISSUE THREAD

**Issue by KirbyFan102** [visualboyadvance-m/visualboyadvance-m#591]
Just noticed this odd bug in version 2.1.4 while loading a save in Aria of Sorrow. I started the game and loaded a save in the middle of a level. The game had no music, until I ran into another room, at which point the music started back up from the beginning. However, this bug was nowhere to be found in Dragon Ball Z: Buu's Fury or Boktai 2, which were the other games I tested. Both game loaded the music normally, without errors.

**Comment by negativeExponent** [comment]
upload the related savefile and do not skip template

**Comment by denisfa** [comment]
@KirbyFan102 On your other report, you used `VBA-M version 1.8.0.0`. Can you confirm this happens only on `2.1.4`? Also, please upload your savefile so we can check.

**Comment by KirbyFan102** [comment]
NEVERMIND, I figured it out. the save state in question was just after I had beaten the first boss. The lack of music was caused by that. I didn't remember because I hadn't played the game for a week, Since I still had the previous problem I talked about in my mind, I assumed it was a problem with VBA instead of the game. Goddamn it. I'm sorry for wasting your time.

**Comment by denisfa** [comment]
@KirbyFan102 Don't worry about this. Just keep reporting what you think is a bug and we will check case by case! But please use the template next time, like you did a couple of times.

**Comment by KirbyFan102** [comment]
Sure thing. I'll try to be more careful in the future.
