### ISSUE TITLE
Multiplayer won't work over internet:Emulator can't accept Public IP

### ISSUE THREAD

**Issue by HiImBrala** [visualboyadvance-m/visualboyadvance-m#594]
### Expected behavior
The emulator would connect to host device if host Port Forwarded
### Actual behavior
The emulator DOES NOT connect to host
### Steps to reproduce the behavior
Simply try to play LAN 
### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
Every game
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

Include screenshots of ROM Information (File > ROM Information):

If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl):
Direct3D
Sound driver (directsound, xaudio, openal, SDL):
DirectSound
### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows
If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by ZachBacon** [comment]
At the moment link is broken and while it's on the list to be fixed, it isn't exactly on the top of the Todo list just yet.

**Comment by HiImBrala** [comment]
> At the moment link is broken and while it's on the list to be fixed, it isn't exactly on the top of the Todo list just yet.

when will the fix be done.if i may ask?Really want to play some GBA games with friend

**Comment by denisfa** [comment]
@HiImBrala What games are you trying to play? GBA games using `Cable` should work. But you have to use the latest nightly available [here](https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354#issuecomment-568932350).

**Comment by HiImBrala** [comment]
> @HiImBrala What games are you trying to play? GBA games using `Cable` should work. But you have to use the latest nightly available [here](https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354#issuecomment-568932350).

it connects normally using 192.168.x.x. >Local IP.But using Public IP 28.79.40.51 DOESN'T work

**Comment by rkitover** [comment]
@HilmBrala we don't have any kind of upnp support, you have to make a port forward from your router for that to work.

**Comment by HiImBrala** [comment]
> @HilmBrala we don't have any kind of upnp support, you have to make a port forward from your router for that to work.

i did

**Comment by HiImBrala** [comment]
> @HilmBrala we don't have any kind of upnp support, you have to make a port forward from your router for that to work.

thing is.port 5738 DOESNT WORK .every other does.At least add back option to choose port ourselves.One that link 1.8 has

**Comment by rkitover** [comment]
@HiImBrala oh sure, that's very easy to do. I'll do it now.

**Comment by rkitover** [comment]
@HiImBrala actually before I do all the gui and options wiring for this, give me a different port you would like to try and I'll make a build for you.

**Comment by rkitover** [comment]
I tried connecting to a port forward over 5738 on my network to the external IP, and I linked advance wars fine. Just FYI. I'll add something to configure the port though.

**Comment by rkitover** [comment]
Also, I just noticed this and edited one of your previous comments, never post your home network IP publicly, that's a very bad idea.

**Comment by rkitover** [comment]
Anyway, I'll have a build with the configurable port feature in a few days at most, waiting for that to be merged.

@denisfa I think we need to implement some kind of cross-platform UPNP like apps like qbittorrent do, there should be something handy for that.

**Comment by rkitover** [comment]
Try this build which has a port setting: https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354#issuecomment-582162781

**Comment by HiImBrala** [comment]
thanks :)
