### ISSUE TITLE
Purple text freezing issue fire red squirrels rom with ultra violet.

### ISSUE THREAD

**Issue by prestonpirateking** [visualboyadvance-m/visualboyadvance-m#597]
### Expected behavior
Pokemon game does not freeze or change text color to purple
### Actual behavior
Pokemon freezes when I go up in my tm case, and the text changes color
### Steps to reproduce the behavior
Not sure. I changed a few settings according to this video:https://www.youtube.com/watch?v=xwwggrT6CKI
### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
Pokemon fire red squirrels rom, with ultra violet rom (GBA I think)
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

Include screenshots of ROM Information (File > ROM Information):

If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 10
![helpmepurp](https://user-images.githubusercontent.com/10253665/73126415-1f32ad00-3f80-11ea-8733-e345a7486fae.PNG)

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by denisfa** [comment]
@prestonpirateking Thank you for the report. Could you retry with our latest version? Is is available [here](https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354#issuecomment-568932350).

Some options will have changed place, though. But I believe they should all be there.
