### ISSUE TITLE
VBA-M crashing when adding cheats

### ISSUE THREAD

**Issue by SkilledTheGamer** [visualboyadvance-m/visualboyadvance-m#598]
### Expected behavior
Be able to click the add new cheats button without the program crashing
### Actual behavior
Clicking the add new cheats button crashes VBA-M
### Steps to reproduce the behavior
Open VBA-M, loading a game, click list cheats (assuming cheats was enabled), click the add new cheats button.
### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace: (don't really know how on windows, since the crash bug logging tutorial is only for linux)

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game): Pokemon Emerald

Which games, if any, are NOT affected by the issue (please state if GBA or GB game): none

Include screenshots of ROM Information (File > ROM Information): 
![gdsa](https://user-images.githubusercontent.com/36399055/73350644-026be180-42c0-11ea-8e45-a07e17b3d417.PNG)

If you are using a BIOS file, please say which one: GBA BIOS

### Option details

Video driver (simple, opengl): OpenGL

Sound driver (directsound, xaudio, openal, SDL): DirectSound

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Windows 7

Version of code (pre-built binary version, or commit ref, or just "master"): [v2.1.4](https://github.com/visualboyadvance-m/visualboyadvance-m/releases/tag/v2.1.4)

**Comment by ZachBacon** [comment]
Can you provide the cheats you used?

**Comment by RunisDauphin** [comment]
Hi, I am Runis Dauphin from Rebelles Unis:

I already have talked this in Issue 519: Cheat List does not work as it should. According to Negative Exponent, probleme is not present in Linux, but I know it is still present on Windows. I checked back then with Megaman Battle Network games (US version).

Hope that extra info helps.

Runis Dauphin

**Comment by denisfa** [comment]
@SkilledTheGamer @RunisDauphin Could you retry with the version available [here](https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354#issuecomment-568932350)?

I did an initial test using `Windows 10 x64` and it seemed to work.

**Comment by RunisDauphin** [comment]
Tried on the VBA-M 2.1.4, 01/01/2020 developpement version with Megaman Battle Network 1 (US) with Must Be On and Full Sack Cheats (for Codebreaker): It works flawlessly (but only tried on Windows 10; later I will try on Windows 7 and Windows 8.1).

If someone wants to try, here you have the cheats:
971181CD4EE1
3FFA80599274
27FB8522914B

1A8A02793170
5CF3E8878C1A
3DA7B225D550
1CF3A926949A
1EA7B227D570
1CF3A926949A
3DA3A2A59D50
1CF3A926949A

By the way, contrary to other emulators, I can not find if this emulator saves a cheat list (.cht, .clt) or if it makes an "on the fly" cheat list and then deletes it when you exit (as VBA-RR lets do, which I highly recommande if you change emulator constantly among VBA-RR and others).

Thanks for the info, and feel free to close Issue 519. Probleme is solved.

Runis Dauphin

P.D.: Skilled the Gamer, are you sure you are using the correct cheats (I do not mean now, evidently; I mean after you try to open the add cheat sourcil)?

**Comment by denisfa** [comment]
> By the way, contrary to other emulators, I can not find if this emulator saves a cheat list (.cht, .clt) or if it makes an "on the fly" cheat list and then deletes it when you exit (as VBA-RR lets do, which I highly recommande if you change emulator constantly among VBA-RR and others).

You answered yourself... It is "on the fly" and then deletes it when you exit. You can save to a file, though. If you think this is not good, as it should be saved automatically to a file, then open another issue with this request.

**Comment by SkilledTheGamer** [comment]
I have tried the older version [here](https://github.com/visualboyadvance-m/visualboyadvance-m/releases/tag/v2.1.3) and it works flawlessly. Cheats? yeah sure:
[1986 - Pokemon Emerald (U)(TrashMan)(plez change it to clt).txt](https://github.com/visualboyadvance-m/visualboyadvance-m/files/4133208/1986.-.Pokemon.Emerald.U.TrashMan.plez.change.it.to.clt.txt)
if you're too lazy, heres it: 83005E18 270F, 82005274 0001, 82005274 0044.
also they r correct cheats

**Comment by SkilledTheGamer** [comment]
my timezone is different from you guys (GMT+7) so i might not answer when you guys ask, cuz i am sleeping

**Comment by ZachBacon** [comment]
@SkilledTheGamer I don't think you answered @denisfa's question. Have you tried one of the nightlies. All you stated was that you tried an older version.

**Comment by SkilledTheGamer** [comment]
ohk

**Comment by SkilledTheGamer** [comment]
@ZachBacon @denisfa sorry but it seems like, i can't download it. its giving me a html 500 error.

**Comment by ZachBacon** [comment]
@SkilledTheGamer We literally linked it to you earlier

**Comment by ZachBacon** [comment]
It's also a pinned topic on the issues page.

**Comment by ZachBacon** [comment]
https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354#issuecomment-568932350

**Comment by SkilledTheGamer** [comment]
suprisingly it worked @ZachBacon
