### ISSUE TITLE
commenting on PR disabled?

### ISSUE THREAD

**Issue by negativeExponent** [visualboyadvance-m/visualboyadvance-m#616]
![image](https://user-images.githubusercontent.com/54053706/74853518-ff24bc80-5378-11ea-856f-73b5c5d0498e.png)
this repo now dev only since we cant comment on PRs and stuff! ?

**Comment by ZachBacon** [comment]
@negativeExponent I literally tried checking the permissions, I couldn't find anything. @rkitover did you change something?

**Comment by rkitover** [comment]
Nope, we did nothing, @negativeExponent I think you should contact github support, this is some kind of bug.

I don't think github even has any such setting.

**Comment by ZachBacon** [comment]
I saw no such setting on my end, and I went through, there's nothing that forbids commenting on pull requests save if it's a private repository in which this repo/organization is not.

**Comment by rkitover** [comment]
I mean, this may be related to my particular situation, but it's certainly nothing that I did or asked anyone to do.

**Comment by ZachBacon** [comment]
I'm more inclined to think this maybe a GitHub related but. Seems really weird.

**Comment by rkitover** [comment]
Let us know what github says.

**Comment by rkitover** [comment]
I contacted github support about this.

**Comment by negativeExponent** [comment]
this can be close. i have been requested to enable F2A on libretro (which i dont want to since i care less about security nor remembering gazillion passwords/keys) and that seems to resolve i have here in this repo.

**Comment by negativeExponent** [comment]
thanks for blocking me again. if you guys dont want corrections, then do you stuff correctly.

**Comment by ZachBacon** [comment]
@negativeExponent no one blocked you period, this seems legit a GitHub issue

**Comment by negativeExponent** [comment]
https://help.github.com/en/github/building-a-strong-community/blocking-a-user-from-your-personal-account
> After you've blocked a user, they cannot:
>    Send you any notifications, including by @mentioning your username
>    Comment on issues or pull requests that you've created

![unknown](https://user-images.githubusercontent.com/54053706/75930396-7ac05680-5ead-11ea-9892-98b2b61a0352.png)

**Comment by ZachBacon** [comment]
Really? That's really odd, lemme talk with denisfa.

**Comment by rkitover** [comment]
I do see that comment in that PR.

**Comment by rkitover** [comment]
@denisfa can you please check if you blocked @negativeExponent by accident?

**Comment by denisfa** [comment]
You should be good now. Sorry about this!
