### ISSUE TITLE
Can't turn off fullscreen visualboyadvance-m 2.0.2 emulator

### ISSUE THREAD

**Issue by ricsirogi** [visualboyadvance-m/visualboyadvance-m#617]
### Expected behavior
       After turning on the fullscrean on the visualboyadvance-m 2.0.2 emulator i can close it with f11 
        or other key shortcuts

### Actual behavior
        I can't turn off the fullscreen even the key shortcuts are not working!

### Steps to reproduce the behavior
       - start the emulator
       - turn on fullscreen
       - and you can't use anything, u just play, without the chanse of saving, becouse the in-game 
          save is a .sav file, and the vba can't read it, even if i tried the file - import - battery

 file
![there is no menu bar](https://user-images.githubusercontent.com/61251735/74874812-954ce880-5361-11ea-9157-ddfb4ef0e55a.JPG)

As you see, there is no menu bar! so i can't save the game, and if i save ingame, ( as i sad before ) 
the emulator can't read it, whatever i do. Even if i name it the same name as the rom!

PS:sorry for the bad grammar :(

**Comment by ZachBacon** [comment]
You're using an outdated version

https://github.com/visualboyadvance-m/visualboyadvance-m/releases/tag/v2.1.4

**Comment by ricsirogi** [comment]
Thanks a lot, i will try it tomorrow!

Zach Bacon <notifications@github.com> ezt írta (időpont: 2020. febr. 19.,
Sze 22:27):
