### ISSUE TITLE
Framerate Issues

### ISSUE THREAD

**Issue by buffaloburrow** [visualboyadvance-m/visualboyadvance-m#618]
### **Expected behavior**

Game runs at 60 frames per second.

### Actual behavior

Game runs normally, but after a window of about 30 to 60 seconds, there is a noticeable drop in framerate that can only be addressed by tabbing out of the emulator, then switching back to it. 
This will only stall it for that amount of time.

### Steps to reproduce the behavior

None that I'm aware of.

### ROM details

All GBA games I've tested are affected, I'm not sure if GB games are. ![Untitled](https://user-images.githubusercontent.com/61395046/75122588-136d0000-567e-11ea-8787-f61a518cf461.png)

### Option details

Display: OpenGL

Audio: SDL

### Build details

Windows 10 64-bit

### Hardware details:

Graphics card: GTX 750
Processor: Core i3-4130T CPU @ 2.90Hz (4 CPUs)

**Comment by denisfa** [comment]
@buffaloburrow Thank you for the report. But we need some more information:

- What version were you using (latest, 2.1.4 or nightly)?
- Does the framerate drop affect the audio? Or both audio and video are affected?
- Any type of special configuration? Like throttle,turbo or some other setting?

**Comment by buffaloburrow** [comment]
Thank you for the reply, I'm using the latest release, audio is NOT affected, and no other setting has been tinkered with that I'm aware of.

**Comment by ZachBacon** [comment]
@buffaloburrow have you tried the simple renderer yet?

**Comment by buffaloburrow** [comment]
@ZachBacon Certainly, I have. It turned out it puts a significant dent on the framerate and is far worse than OpenGL. No clue why. I have also tried other emulators but so far this has been the only one to even hint at a stable framerate. Frustrating.

**Comment by buffaloburrow** [comment]
What's staggering to me is this shouldn't even be a problem, my hardware is more than capable of handling this kind of emulation. Such a bizarre issue. This doesn't happen with other emulators either, just GBA ones. Super Mario World for example runs smooth like butter without any issues.

**Comment by denisfa** [comment]
@buffaloburrow Sorry if this looks intrusive, but could you test an experimental build for this? It is on the attached file. I have an idea about what is happening, but cannot reproduce it on my end.

[visualboyadvance-m.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/4243010/visualboyadvance-m.zip)

> What's staggering to me is this shouldn't even be a problem, my hardware is more than capable of handling this kind of emulation. Such a bizarre issue. This doesn't happen with other emulators either, just GBA ones. Super Mario World for example runs incredibly smoothly even in the default settings.

Which ones did you try? Were they all OpenGL based?

**Comment by buffaloburrow** [comment]
@denisfa Whether the other emulators are OpenGL based I couldn't tell you, but I can namedrop the other emulators I do use. The one I use most outside this one is snes9x, and as I pointed out it runs well and without issue. I'll keep you posted on the experimental build.

**Comment by ZachBacon** [comment]
@rkitover @denisfa I think we should look at revamping the video drivers making that one of the priorities

**Comment by buffaloburrow** [comment]
@denisfa Here is what I've noticed: It seems that the "grace period" where the emulator runs without issue has been extended dramatically in this build, it's not just 30 to 60 seconds anymore, it's around 3  minutes minimum, a massive improvement. Choppiness does happen, but the emulator can recover and put the frames back together very quickly and enter another grace period. Tabbing out of the emulator still works for some reason, but now the problem is infrequent enough where gameplay is enjoyable.

**Comment by denisfa** [comment]
@buffaloburrow Thank you very much for testing this. I can't do something better than this very quickly, so I hope this is good enough for now. We will try to tackle this more properly ASAP. If we include a nightly build for it, we will tag you here for updates.

@ZachBacon This is mainly an Windows issue. I think we need to bring back Direct X {9,10,11} output module. Let's move this discussion to either dev chat or a mega-thread issue.

**Comment by buffaloburrow** [comment]
By the way what is this? It pops up when I close the emulator. Annoying.
![Untitled](https://user-images.githubusercontent.com/61395046/75129778-71fba380-56a9-11ea-8a71-023e70e13196.png)

**Comment by denisfa** [comment]
It is an wip auto-update feature. Sorry about this. Here is a link without it. 

[visualboyadvance-m.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/4243146/visualboyadvance-m.zip)

Same stuff, but with the option disabled.

**Comment by buffaloburrow** [comment]
gotcha. I will keep tabs on this Issue. Let me know when the framerate problem is rectified.

**Comment by ZachBacon** [comment]
> 
> 
> @buffaloburrow Thank you very much for testing this. I can't do something better than this very quickly, so I hope this is good enough for now. We will try to tackle this more properly ASAP. If we include a nightly build for it, we will tag you here for updates.
> 
> @ZachBacon This is mainly an Windows issue. I think we need to bring back Direct X {9,10,11} output module. Let's move this discussion to either dev chat or a mega-thread issue.

Eventually the message board will be back soon though. Having some sql conversion issues in trying to migrate away from mybb to phpBB, mainly because there's more of a rich extensions that we can make use of certain things like markdown etc, The conversion plugin is set for an older version of phpBB and for a slightly older myBB so it's literally trying to adapt the conversion plugin to convert the proper tables. Not a lot of fun and sifting through various version changes, I'm almost tempted to just do it by hand :/

**Comment by buffaloburrow** [comment]
Short update: Choppiness does not go away like I described. Seems like I have to "refresh" the screen, either by tabbing out, entering full screen or some other method. I have not come across a solution still. My drivers are up to date, too. I have not had to deal with an issue this annoying in forever. Is there any way at all I could bind a key to refreshing the screen so it goes away? Honestly, if I could just do that I wouldn't mind it very much.

**Comment by rkitover** [comment]
@buffaloburrow what you are describing is very strange.

Is there another Windows computer you can try the emulator on?

It sounds like something specific to your configuration.

**Comment by buffaloburrow** [comment]
@rkitover Unfortunately I do not have access to another machine. As to whether this is specific to my configuration, let me say this: This is a fresh Windows 10 installation. I do not recall having this issue on Windows 7, so maybe that has something to do with it? All I know is I have never had to deal with something like this.

**Comment by rkitover** [comment]
Do you have latest nvidia drivers?

**Comment by buffaloburrow** [comment]
@rkitover Yes I have triple-checked at this point. There are no driver updates and DirectX is up to date.

**Comment by rkitover** [comment]
Do you have any kind of remote desktop, screen sharing or screen recording software enabled?

**Comment by ZachBacon** [comment]
Also directx doesn't really matter since vba-m doesn't support directx, currently that is.

**Comment by Squall-Leonhart** [comment]
is this a case where the GPU falls back to low power clocks and the emulator chokes from the reduced video memory bandwidth?

**Comment by vetlern** [comment]
Hello, ran into identical issues lately when playing Metroid Zero Mission. Doesn't seem to be fruitful to open an additional topic when I can just give a second computer to test the same problems with.

Just like him, i'm running it on windows, similar settings, and just like he mentions, the framerate drop went from "after 30-60 seconds" to "after 3 minutes" after downloading the nightly build for VBA, but with a better processor and graphics card, neither of which should have any sort of issue running the emulators.

Any new advice/suggestions/questions I can try to answer about our issue to have it solved?

**Comment by Kabutak** [comment]
Having a similar issue on my end. I noticed that at the time the drops start, my gpu/cpu utilization seems to drop as well. Though when I looked at it with GPU-Z there was nothing useful there and it seemed stable throughout. Runs buttery smooth otherwise, and utilizes a very small amount of my gpu and cpu, so the specs aren't the issue. I'm gonna poke around some more and see if I can find a solution, but for now I may just play on my laptop, which doesn't have the issue last I checked.
![snapshot](https://user-images.githubusercontent.com/22622424/132068090-ffd65221-b513-45c0-b8bb-1a0b4a0d404f.gif)
[GPU-Z Sensor Log.txt](https://github.com/visualboyadvance-m/visualboyadvance-m/files/7108630/GPU-Z.Sensor.Log.txt)

**Comment by TurboCasual** [comment]
Greetings!

I can confirm to have the exact same issue described by the users above. Vanilla settings. FPS constantly drops down to low 40s-30s not affecting audio but game speed.

My specs are as followed. Slightly dated but still capable.

GTX 1060 6GB
i7 6700k
32GB Ram 3000mhz
Windows 10
Latest nvidia drivers as of today.

I use frame skipping (playing at 30 FPS) which results in a stable 30 FPS. Still enjoyable but not optimal.

I use many other emulators like Snes 9x, nestopia UE, Project64, ePSXe as well as more demanding emulators like desmume, PPSSPP, Dolphin, PCSX2 and RPCS3 without any software related issues. I mostly use OpenGL or Vulkan if given the option.

I noticed that i VisualBoy Advance-M is the only emulator that didn't let me use the nvidia overlay out of the box and i had to manually enable it in the nvidia control panel which didn't solve the issue but maybe this information might help identify the issue.

Maybe something hardware related ...? Seems like other people with semi decent hardware encounter this issue.

Looking forward to future releases :)

**Comment by Squall-Leonhart** [comment]
more than likely using 64bit builds with x4+ filters, have not been able to identify a cause or problem otherwise.

**Comment by vetlern** [comment]
> op is using a laptop cpu, so the power profile is a factor there, its probably using a vendor optimized profile and falling back to inadequate clock frequency.
> 
> xbrz above 2x times is a no go in the opengl or simple renderers pending the addition of multithreading or using the gpu to perform it as a shader
> 
> above 3x is pushing it, this applies to both the 32bit and 64bit builds as we have no ASM implementation of xbrz the lack of assembly for 64bit builds rules out the HQx4 filter there, but its fine in 32bit builds, with maybe a rare drop to 58fps depending on cpu age.


I'm using a desktop with a GTX 1080, and have been using no filters until you mentioned them. I'd actually thank you for talking about xbrz, and I'm actually using the 6x right now, and it seems to be working perfectly fine- insofar as I still have the same issues I had with no filter whatsoever, but to counteract that, I've actually discovered a filter I don't hate. Thanks!

still can't figure out why i'm getting slowdowns though as that obviously wasn't the issue. It seems however that if I don't have any slowdown at the moment but trigger the VBA's menu bar, it introduces slowdown. This also purges the slowdown when the menubar fades- the slowdown is triggered by the menu bar (also by natural play without involving the menu bar) and then cleared by it thereafter.

**Comment by PolygonSlayer** [comment]
Having the same issue when trying this emulator. Was going to try and use it for link up games, but for some reason even running one copy of the emulator the games runs at around 60% speed no matter what. I can get normal speed for a short period (few seconds) if I activate the menu and then go back to the game it runs fine for a short "burst".
I use other emulators and got no issues so not sure what it wrong.

Did anyone figure out what the problem?

PC specs:
Interl Core i9-11900K 3.5GHz
32gb RAM
RTX 3080 Ti

**Comment by Squall-Leonhart** [comment]
use another emulator for linking, there are numerous known issues and nobody to work on them.

**Comment by samuelemaus** [comment]
I've been experiencing this for years at this point on multiple computers with Nvidia GPUs and on several builds of VBA-M.  What's absolutely bizarre about this is that the FPS indicator on the bottom menu shows 60 fps, but the game is visibly running at closer to 30.  The only thing that "fixes" it is to pause emulation and unpause it, but this only works for a few seconds at most.

**Comment by Squall-Leonhart** [comment]
This has never been reproducible, and seems only attributable to misconfigured laptop cpu's that are throttling aggressively.

**Comment by samuelemaus** [comment]
> This has never been reproducible, and seems only attributable to misconfigured laptop cpu's that are throttling aggressively.

I have only ever experienced this on desktop Intel CPUs and Nvidia GPUs with no power management settings to speak of.

**Comment by Squall-Leonhart** [comment]
Then you're experiencing accurate behavior, games that also slowed down on the hardware.

**Comment by Kabutak** [comment]
It is worth noting that in my case, the issue has persisted through three different Nvidia GPUs and two AMD CPUs. However, I have also been able to replicate the issue with the game Iratus: Lord of the Dead, wherein the game will show similar choppiness resolved by alt+tab after any major loading segment (such as entering a battle).

This makes a strong case towards it being a system specific issue and nothing to do with the application itself. Definitely annoying, but likely impossible to solve on the software side since it isn't isolated. If I ever find a cause, I'll update for people who find this issue in the future, but chances are I'll just ignore it and hope it goes away next PC build.

**Comment by samuelemaus** [comment]
> Then you're experiencing accurate behavior, games that also slowed down on the hardware.

That’s just… not true.  It is unambiguously not running correctly and it is certainly not accurate behavior.  It happens on literally every game (GB, GBC, and GBA) and is completely unrelated to what is happening in game.  I acknowledge that this is clearly behavior that only happens on certain systems (albeit two of mine in a row apparently), but VBA-M is the only emulator I’ve ever used that does this, and I use a great many.

**Comment by Squall-Leonhart** [comment]
Get me a HWInfo trace starting from idle, starting the game and running it until the issue manifests.
