### ISSUE TITLE
Final Fantasy Crystal Chronicles Multiplayer Inputs Stuttering

### ISSUE THREAD

**Issue by SenerioIX** [visualboyadvance-m/visualboyadvance-m#630]
That's an old one and maybe it's been addressed before with no result but here goes anyway.

### Expected behavior
No stuttering for a player when their map is opened.

### Actual behavior
The player experiences stutter when their map is opened.

### Steps to reproduce the behavior
You need to setup links between Dolphin and VBAs to get into multiplayer (at least 2 players).
When going in a map, the UI will become available on the VBAs.
Set it to the map and you should notice stutter in the movement, like the game is constantly eating inputs.

Not having the map displayed gets rid of the issue, but at the cost of a feature.

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
Final Fantasy Crystal Chronicles - GameCube

BIOS : 
GBA

### Build details

OS: 
Windows 10

Version:
Latest : 2.1.4 (same issue since at least 2.0.0)

**Comment by ZachBacon** [comment]
Can you try this build https://github.com/visualboyadvance-m/visualboyadvance-m/issues/354#issuecomment-582162781 and then tell me if it's still an ongoing issue, mainly since this build has some link changes.

**Comment by SenerioIX** [comment]
Same thing. I'd say it's a very specific emulator to game problem. Not only is it only with this game, but it's also only when a player has a map opened. And it's not that it's affecting the whole emulation. It's really just eating inputs from that player alone.

And on a side note, that build also made my GameCube controller not work anymore.

**Comment by rkitover** [comment]
Can you please open a separate issue for the gamecube controller? I need to fix this before next release then.

**Comment by SenerioIX** [comment]
> Can you please open a separate issue for the gamecube controller? I need to fix this before next release then.

There you go https://github.com/visualboyadvance-m/visualboyadvance-m/issues/631

**Comment by johnbateman** [comment]
Are there any workarounds for this or a version of vba-m I can try where this isn't present?

**Comment by SenerioIX** [comment]
> Not having the map displayed gets rid of the issue, but at the cost of a feature.

**Comment by Pop000100** [comment]
Is there any thing I could do to help the Developers resolve this issue without actually providing coding assistance. my C++ is not very good.
