### ISSUE TITLE
[enhancement] set server ip for linking

### ISSUE THREAD

**Issue by robertlinke** [visualboyadvance-m/visualboyadvance-m#632]
Expected behavior
in `options>link>start network link>server` field the ability to adjust the ip address for which i want to run the server
### Actual behavior
the ip field grays out the moment i switch from client to server mode
### Steps to reproduce the behavior
`options>link>start network link` en then server, and the IP setting grays out.

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): WIN10 1909

### Extra Comment

also no option for it in vbam.ini

**Comment by rkitover** [comment]
Here's a build for you with the feature enabled:

[visualboyadvance-m-Win-64bit-bind-ip.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/4334965/visualboyadvance-m-Win-64bit-bind-ip.zip)

**Comment by robertlinke** [comment]
you sir are awesome!
