### ISSUE TITLE
No way to start this thing

### ISSUE THREAD

**Issue by Venkx** [visualboyadvance-m/visualboyadvance-m#636]
### Please fill out this form:
Ok
### Expected behavior
.exe file
### Actual behavior
no .exe file
### Steps to reproduce the behavior
search for a .exe file
### Crash bugs

If this is a crash bug, and you have the time and inclination, please provide a
symblic backtrace.

Instructions for doing so are
[here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
every single game, since the emulator is not able to be started
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

Include screenshots of ROM Information (File > ROM Information):

If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

### Hardware details:

If your joystick or gamepad isn't working in Linux, please try to troubleshoot
using the information on this page:
https://wiki.archlinux.org/index.php/Gamepad **BEFORE** filing an issue. We use
SDL for joystick support, any problems will generally be an issue with SDL and
**NOT** the emulator.

If relevant, the joystick you are using and the drivers you are using for it:

**Comment by denisfa** [comment]
@Venkx The latest release is available [here](https://github.com/visualboyadvance-m/visualboyadvance-m/releases/tag/v2.1.4).

You may also consider our nightlies builds, which are available [here](http://win.vba-m.com/nightly/).

Just download and extract the zip file.

**Comment by Venkx** [comment]
ok now I found it. but I was on the releases tab before, maybe you should consider hiding all the changes, while scrolling the page I couldn't make out the files at the bottom, but it works now

**Comment by ZachBacon** [comment]
@Venkx the changes are also for distro maintainers to know what's new when they pull in the source to compile for linux distributions. In future release information will also be mirrored at https://vba-m.com and at https://board.vba-m.com/viewforum.php?f=22
