### ISSUE TITLE
No Sound When Playing

### ISSUE THREAD

**Issue by TheBrowndragon** [visualboyadvance-m/visualboyadvance-m#640]
So I've been trying to play a Pokémon Ultra Violet and there has been no sound. I looked in the settings and I tried almost everything In the audio settings but nothing is working.

**Comment by denisfa** [comment]
@TheBrowndragon I have some questions:

1. Is this the title screen?
![Screenshot_2020-03-30_18-58-07](https://user-images.githubusercontent.com/11354751/77965922-76266c80-72b8-11ea-9182-baef2f60d625.png)

2. Windows, MacOS or Linux? 64 or 32 bit?

3. For confirmation, did you ever try `Help` > `Factory Reset` before playing the game?

4. What version of vbam did you try? `Help` > `About` (should be second line)

5. Is this only for this pokemon game or other games as well?

**Comment by TheBrowndragon** [comment]
1. This is my screen. Sorry that it's not the title screen don't know if that matters though.
![Pokemon Ultra Violet](https://user-images.githubusercontent.com/62910981/78328945-21426900-75cc-11ea-8cb3-9aebcc559b14.PNG)

2. I am Using Windows 10 64 bit.

3. When I press help it says Report Bugs, VBA-M Support Forum, Translations and About

4. 2.0.1

5. Yes it also happens for other games

**Comment by ZachBacon** [comment]
You're using an extremely old version @TheBrowndragon if you look, you'll see the releases link and news is updated at https://vba-m.com we also have nightlies you can test at https://win.vba-m.com/nightly/

**Comment by TheBrowndragon** [comment]
Thanks! It is working now!

**Comment by ZachBacon** [comment]
Alright, glad it is fixed for you, if you notice any issues, feel free to open more posts.
