### ISSUE TITLE
 Zelda Four Swords can't link

### ISSUE THREAD

**Issue by Nathanrico04** [visualboyadvance-m/visualboyadvance-m#641]
I spent 1 hour trying, but every time I try to link, it stays on this screen for a long time, and nothing happens
detail: we are using hamachi
![image](https://user-images.githubusercontent.com/60151869/78452985-3f0fdc80-7665-11ea-95ea-f13fd1c5ec1b.png)

### Steps to reproduce the behavior
Well, I tried it on an older version, and it worked, but it ran at 6%, I soon found out that there were newer versions, only it appears to be on this screen, and it doesn't come out of it, not that it's frozen, I can go back and enter again and go back to that, but there is no "A" to continue

**Platform:** Gameboy Advance link (GBA)

### Option details

Video driver (simple, opengl):
![image](https://user-images.githubusercontent.com/60151869/78453158-4e435a00-7666-11ea-8ac8-7d640737869c.png)

Sound driver (directsound, xaudio, openal, SDL):
![image](https://user-images.githubusercontent.com/60151869/78453166-57ccc200-7666-11ea-9c6b-8504aeb8504f.png)

### Build details

Windows 10 64bits

Version of code (pre-built binary version, or commit ref, or just "master"):
VisualBoyAdvance-M 2.1.4
### Hardware details:
AMD Ryzen 3 2200g
8,00GB

**Comment by SoulStriker27** [comment]
Also using DS4windows causes inputs on 1 controller to act as 2 separate controllers. The previous version didn't do this (SVN947)

**Comment by v1993** [comment]
It's not "dolphin link" issue. Four Swords are run by linking VBA-M instances together with no Dolphin involved.

**Comment by AlexN64gamer** [comment]
Somebody know if this game is working properly now? with the last stable release? thanks in advance

**Comment by Squall-Leonhart** [comment]
this game has always been link capable, its just a matter of the right timeout settings.
