### ISSUE TITLE
Can't stream VBA-M on Discord

### ISSUE THREAD

**Issue by subarashi-06** [visualboyadvance-m/visualboyadvance-m#643]
When I try to stream my VBA-M window on Discord (I'm playing Pokemon Crystal Clear) the screen whites out. The game still functions underneath the white screen, and resetting it keeps the white screen. I need to reload the ROM file in order to see the game again.

**Comment by rkitover** [comment]
Try changing video output from OpenGL to Simple.

**Comment by ApteryxWarrior** [comment]
I have the same problem. How do I change the video output?

**Comment by rkitover** [comment]
`Options -> Video -> Configure -> Output Module`

**Comment by rkitover** [comment]
Please also let me know if this fixes your issue.

**Comment by ApteryxWarrior** [comment]
Just tried it, and it works! Thanks for the help. I'm sure other people with find this issue.

**Comment by Danice123** [comment]
I don't think this is an adequate resolution to this issue. Simple rendering has a significant impact on gameplay smoothness. This really deserves a full fix.

**Comment by hug0b** [comment]
I have the same issue, btw https://github.com/visualboyadvance-m/visualboyadvance-m/issues/767 is identical

**Comment by Squall-Leonhart** [comment]
It looks like this is actually Discords fault, but I believe its possible to fix from our end based on a similar issue and a fix introduced for eduke32.

**Comment by Squall-Leonhart** [comment]
Based on eduke32's method, this has been fixed in https://github.com/visualboyadvance-m/visualboyadvance-m/compare/discord-fix and will be merged to master after some testing.

Try this
[visualboyadvance-m.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/11964207/visualboyadvance-m.zip)
