### ISSUE TITLE
Program not opening. idle in process list, no window.

### ISSUE THREAD

**Issue by plaguewolf** [visualboyadvance-m/visualboyadvance-m#645]
downloaded latest release version (2.1.4) attempted to run but while i can find the process in the task manager no window opens and the program is just idling.

### Expected behavior
Working?

### Actual behavior
Not working. no error message, no obvious log files created, no indication as to whats happening.

### Steps to reproduce the behavior
download latest release, drop in empty folder, double click exe, observe as nothing seems to happen.

### ROM details
N/A, the program doesnt even open, didnt get this far

### Option details
N/A, the program doesnt even open, didnt get this far

Windows 10 latest release as of post (not early access stuff, whatever windows calls it)
pre-built release directly from github, x64 version of 2.1.4

not sure what exactly is going on here, since i had an earlier version of this running like 2 months ago (version 2.0.0 i think)

**Comment by Drakon1590** [comment]
Maybe you should try to use nightly build.

[https://win.vba-m.com/nightly/](url)

**Comment by ZachBacon** [comment]
Another thing to look at is the settings located in %APPDATA%/visualboyadvance-m, basically move the ini out of that directory and then try launching it with fresh settings.

**Comment by rkitover** [comment]
Try turning off your anti-virus/anti-malware realtime protection.

**Comment by rkitover** [comment]
Check that your OpenGL is working properly too.

You can also try editing the config file in `%USERPROFILE%\AppData\Local\visualboyadvance-m\vbam.ini` and changing `RenderMethod` to `simple`.

**Comment by plaguewolf** [comment]
Okay, I've tried the suggestions listed here and the same thing is happening. heres what ive done:

Working from a fresh temporary directory to test things
Downloaded latest release version. failed.
tried deleting %APPDATA% and running release version. failed.
downloaded nightly. failed
deleted %APPDATA% and running nightly version. failed.
 changed RenderMethod to simple for both release and nightly. both failed.

currently downloading the official NVidia drivers to see if windows 10 derped opengl somehow. /shrugs

**Comment by rkitover** [comment]
By the way, is there an entry in the taskbar when you launch the executable?

Would you be willing to download the `-debug` version of the nightly and running it in visual studio? You can just open the `.exe` directly in visual studio and run it in the debugger.

**Comment by plaguewolf** [comment]
hmm, updating nvidia drivers seems to have fixed it. so im thinking that windows update must have changed my video drivers in the last month or so.

its either that or the restart after updating drivers fixed it. dunno.
going to close issue.
