### ISSUE TITLE
Audio Delay

### ISSUE THREAD

**Issue by Vivit-R** [visualboyadvance-m/visualboyadvance-m#647]
### Expected behavior
Game audio is synchronized with the emulation.

### Actual behavior
Audio lags up to half a second behind the emulation. If the emulation is paused after an event happens onscreen but before the event's sound effect plays in the delayed audio, the sound effect does not play until the emulation is resumed.

### Steps to reproduce the behavior
Open a ROM and begin emulation.

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
Metroid: Zero Mission (GBA)
Mega Man Battle Network (GBA)
Mega Man Battle Network 2 (GBA)
Pokemon Blue (GB)

Include screenshots of ROM Information (File > ROM Information):

```
Game title: mzm
Internal title: ZEROMISSIONE
Scene Release: -
Release Number: -
CRC32: 5C61A844
Game code: BMXE
Maker code: 01
Maker name: Nintendo
Main unit code: 00
Device type: 00
ROM version: 00
CRC: 1d (1d)
```

```
Game title: mmbn
Internal title: MEGAMAN_BN
Scene Release: -
Release Number: -
CRC32: 1D347971
Game code: AREE
Maker code: 08
Maker name: Capcom
Main unit code: 00
Device type: 00
ROM Version: 00
CRC: e7 (e7)
```

```
Game title: mmbn2
Internal title: MEGAMAN_EXE2
Scene Release: -
Release Number: -
CRC32: 6D961F82
Game code: AE2E
Maker code: 08
Maker name: Capcom
Main unit code: 00
Device type: 00
ROM version: 00
CRC: 83 (83)
```

```
Game title: POKEMON BLUE
Maker code: 01
Maker name: Nintendo
Unit code: 03
Cartridge type: 13 (ROM+MBC3+RAM+BATT)
ROM version: 00
CRC: d3 (d3)
Color: 00
ROM size: 05 (1M)
RAM size: 03 (32K)
Dest. code: 01
License code: 33
Checksum: 9d0a (9d0a)
```

### Option details

Video driver (simple, opengl):
Happens with both.

Sound driver (directsound, xaudio, openal, SDL):
Happens with both openal and SDL.

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Linux

If using Linux, specify if using xorg or Wayland:
xorg

Version of code (pre-built binary version, or commit ref, or just "master"):
commit 8e3978b314bfac0aee89e26174e0ad2d2f6fe1fc

**Comment by rkitover** [comment]
Can confirm there is an audio delay with master compared to mgba.

**Comment by wisetrap11** [comment]
Audio delay is also occurring on Rhythm Tengoku (GBA). I know this thread is a few months old but this seems like relevant enough information to add.
![image](https://user-images.githubusercontent.com/67494522/85914520-a96f8d80-b80c-11ea-875e-91d8421f4c6e.png)

**Comment by N-Harmonik** [comment]
Ditto except I use Windows.

**Comment by rkitover** [comment]
@N-Harmonik that's interesting thanks, I will see if I can track this down.
