### ISSUE TITLE
Pokemon RS can't communicate with dolphin's Colosseum bonus disk

### ISSUE THREAD

**Issue by Liger0** [visualboyadvance-m/visualboyadvance-m#648]
### Expected behavior
The VBA M acts like it isn't connected to dolphin, while dolphin connects to it.

### Actual behavior
It should work correctly. 6 years ago I transferred Jirachi from the Colosseum bonus disk to Pokemon Sapphire just fine, while now it doesn't connect at all with the correct settings.
I tried to use the same VBA as before but it doesn't seem to work and crashes each few seconds, while the latest stable release and nighly work fine except from the connection.

https://www.youtube.com/watch?v=LvG4bO6klt4

### Steps to reproduce the behavior

Setup the today's builds of Dolphin and nightly VBA-m (I tried  stable ones of both too with no difference), configure dolphin correctly and configure the VBA-M like I show in the video, also trying high timeouts like 10000. 
Also use gba bios.

### ROM details
Pokemon Sapphire USA, Pokemon colosseum bonus disk

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Windows 10 1909

**Comment by briansrls** [comment]
Hello, I just tested this locally with the latest dolphin nightly build (12436) and the latest VBA-M build.

The first time I tried, I got the transmission error you described.  Then, without closing dolphin and retrying the process, I proceeded through the gamecube dialogue once more and reset the GBA when appropriate.  This time, it worked.  

I was very careful to follow these instructions:  https://forums.dolphin-emu.org/Thread-gamecube-gba-link-cable-emulation-guide

Could you try what I described and see if it solves your issue?

![image](https://user-images.githubusercontent.com/11205878/90054585-ec88a180-dc90-11ea-9cab-1b10369bf124.png)

**Comment by briansrls** [comment]
@rkitover I think we can close this issue.
