### ISSUE TITLE
GB: MBC30 or MBC3 with 4MB support

### ISSUE THREAD

**Issue by roytam1** [visualboyadvance-m/visualboyadvance-m#652]
### Expected behavior
All blocks should have a tick.

### Actual behavior
blocks starting from block 7F get a F(ail) mark.
![image](https://user-images.githubusercontent.com/1192577/80007601-0abb6d80-84f9-11ea-8584-f58612f3190a.png)

### Steps to reproduce the behavior
-Load ROM
-Start emulation

### Crash bugs

it doesn't crash emulator.

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
https://github.com/EricKirschenmann/MBC3-Tester-gb

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

Include screenshots of ROM Information (File > ROM Information):
![image](https://user-images.githubusercontent.com/1192577/80007234-908ae900-84f8-11ea-8d2e-39e86558a970.png)

If you are using a BIOS file, please say which one.
Not using BIOS ROM.

### Option details

Video driver (simple, opengl):
simple

Sound driver (directsound, xaudio, openal, SDL):
SDL

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Win7 SP1 x64

If using Linux, specify if using xorg or Wayland:
Nil.

Version of code (pre-built binary version, or commit ref, or just "master"):
2.1.4-eecde424

cross-reference:
https://github.com/mgba-emu/mgba/issues/1713

**Comment by roytam1** [comment]
for hackfixing this issue, changing from `0x7f` to `0xff` will make `mbctest.gb` pass the test.
https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/src/gb/gbMemory.cpp#L365

**Comment by rkitover** [comment]
@roytam1 According to this informal spec I found:

https://gist.github.com/drhelius/3745961

MBC3 rom bank select actually is supposed to accept values up to `0x7f`, if you are sure that this is wrong then we should fix it, but please give me a technical explanation, I am actually clueless about the hardware emulation and we need to be very careful about things like this and document everything properly.

**Comment by roytam1** [comment]
> MBC3 rom bank select actually is supposed to accept values up to `0x7f`

because it is actually MBC30, but with MBC3 in ROM type byte.

**Comment by rkitover** [comment]
@roytam1 as I admitted, I'm clueless about these things, thank you for the info.

What in your opinion is the best way to distinguish this MBC30 variant, would rom size be sufficient?

**Comment by roytam1** [comment]
> would rom size be sufficient?

yeah it should work.

**Comment by FredrIQ** [comment]
MBC30 cartridges should be possible to distinguish by the rom and sram sizes, yes. E.g. Japanese Crystal uses a MBC30, but (as per above) identifies as a MBC3 with added SRAM, since MBC30 don't have their own MBC identifier but uses the same as MBC3.

**Comment by rkitover** [comment]
Any hints where I can find the right crystal rom, the one I tried was a 2M rom size, please email me at rkitover@gmail.com.

**Comment by roytam1** [comment]
> Any hints where I can find the right crystal rom, the one I tried was a 2M rom size, please email me at [rkitover@gmail.com](mailto:rkitover@gmail.com).

retail cart of Pokemon Crystal JP is 2MB in size, and there are custom projects make use of MBC30 with 4MB ROM with success.

**Comment by roytam1** [comment]
and by the way, there is also a project make use of normal MBC3 and 4MB ROM. https://shop.insidegadgets.com/product/gameboy-4mb-32kb-fram-mbc3-with-rtc-flash-cart/
