### ISSUE TITLE
PS2 joypad key configuration isn't saved.

### ISSUE THREAD

**Issue by Ufeldraku** [visualboyadvance-m/visualboyadvance-m#66]
### Expected behavior
Joypad keys should be saved.
### Actual behavior
They are deleted, thus, I can't use my joypad
### Steps to reproduce the behavior
Open VBAM-M [WX/GTK] under linux.
Click settings, then input, then configure.
Try to put your joypad keys.
Save.
### Build details

Operating System (Windows, Mac, Linux, etc.):
Linux, Arch Linux.
Interface (wx, SDL, default is wx):
wx
Version of code (pre-built binary version, or commit ref, or just "master"):
commit 1eb768578bc0c4fa17396f573a4b37a652f12acd
Any other relevant build information:
Got from arch repos.
If this is e.g. a joystick or video issue, then the relevant hardware information:

**Comment by rkitover** [comment]
@Ufeldraku does the joystick work for that session after you configure the keys and only not work when you relaunch the emulator? Or does it not let you set the joystick keys at all?

Did you check that settings are getting saved properly into `~/.vbam/vbam.conf` and that permissions on that directory and file is correct?

**Comment by Ufeldraku** [comment]
Nope, it doesnt let me save the keys. It only accepts the keyboard.

On Feb 12, 2017 11:43 AM, "Rafael Kitover" <notifications@github.com> wrote:

@Ufeldraku <https://github.com/Ufeldraku> does the joystick work for that
session after you configure the keys and only not work when you relaunch
the emulator? Or does it not let you set the joystick keys at all?

Did you check that settings are getting saved properly into
~/.vbam/vbam.conf and that permissions on that directory and file is
correct?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/visualboyadvance-m/visualboyadvance-m/issues/66#issuecomment-279230675>,
or mute the thread

**Comment by rkitover** [comment]
Can you check that your gamepad works with both `jstest` from the `joyutils` package and `sdl2-jstest-git` as described here:

https://wiki.archlinux.org/index.php/Gamepad

Also, we use SDL for joystick input, perhaps try this (or another SDL game):

https://wiki.archlinux.org/index.php/Gamepad#Joystick_not_working_in_FNA.2FSDL_based_games

**Comment by Erim24** [comment]
I am experiencing the same..
And if i specify the keys by their english names (e.g. Joy1-button1) in the vbam.config file it works until I change anything in the settings.
But if I try to set them via the user interface the configuration of the keys is deleted as soon as I press "OK" in the dialog
