### ISSUE TITLE
Playing on 2pcs LAN does not work | v2.14

### ISSUE THREAD

**Issue by MBWebTechMariusz** [visualboyadvance-m/visualboyadvance-m#665]
### Expected behavior
When linked with another VBA-M on the same LAN, you can play with them.

### Actual behavior
Connection works, but the game still doesn't recognize any connections.

### Steps to reproduce the behavior

1. Start a server on pc1 (192.168.0.149)
2. Connect to the server on pc2
3. Try to play a game

### ROM details

All roms which I've tested; easily reproducible on:
![image](https://user-images.githubusercontent.com/37508162/81843891-90f22f00-954e-11ea-85ce-0ac0e91d4b3b.png)
Kirby & the Amazing Mirror [Europe]

### Option details

Video driver (simple, opengl): opengl

Sound driver (directsound, xaudio, openal, SDL): SDL

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Windows 10 on both pcs

Version of code (pre-built binary version, or commit ref, or just "master"): .exe 2.14 from here: https://github.com/visualboyadvance-m/visualboyadvance-m/releases/tag/v2.1.4

### Further remarks

- Link timeout on server is set to 2000
- Server and client can ping each other
- The connection seems established, because I can't connect again; but in the game, nothing happens

**Comment by rkitover** [comment]
Please try cable link type with the latest nightly.

**Comment by MBWebTechMariusz** [comment]
@rkitover cool - some GBA-Games actually worked with that, really cool!

I still can't connect Pokémon Blue:
![image](https://user-images.githubusercontent.com/37508162/81870806-ecd0ae00-9576-11ea-8fe5-c659dd71ce21.png)
It's a GB-Game, is there another issue?

ROM: Pokemon - Blaue Edition (Germany) (SGB Enhanced)

**Comment by rkitover** [comment]
Yes, GB link is horribly broken at this time. GBA cable link should usually work fine.
