### ISSUE TITLE
issue with .sav

### ISSUE THREAD

**Issue by Mhanna112** [visualboyadvance-m/visualboyadvance-m#668]
**Expected behavior**
When I import my FFVI battery file or boot up the game, I expect my game to have my most recent save.
**Actual behavior**
The game doesn't have the "Load Game" option. Emu seemingly isn't detecting my .sav file.
**ROM details**
VisualBoyAdvance-M 2.1.4.
**Which games are affected by the issue (please state if GBA or GB game):**
Final Fantasy VI Advance (Restored) - GBA game.
**Build details**
Using a Dell Latitude E6540. 
**Operating System (Windows, Mac, Linux (state distribution), etc.):**
Windows 10.

**Comment by denisfa** [comment]
@Mhanna112 Were you able to solve your issue? What happened? If you can, please upload your `sav` file as a zip attached here.
