### ISSUE TITLE
Emulator completely locks up when clicking menus in GB/GBC

### ISSUE THREAD

**Issue by vmrosetta** [visualboyadvance-m/visualboyadvance-m#67]
### Expected behavior
It doesn't freeze
### Actual behavior
The emulator freezes and I am unable to click on anything on my computer. Must enter tty and use kill -9 (SIGINT doesn't work)
### Steps to reproduce the behavior
Open a GB/GBC game and click menus
### Build details

Operating System (Windows, Mac, Linux, etc.): Linux (Arch Linux)

Interface (wx, SDL, default is wx): wx

Version of code (pre-built binary version, or commit ref, or just "master"): master

Any other relevant build information: laptop with AMD Radeon graphics

If this is e.g. a joystick or video issue, then the relevant hardware information:

**Comment by DoctorWho11** [comment]
Have you tested a release tarball yet?

**Comment by DoctorWho11** [comment]
I ask because master is a moving target at the moment.

**Comment by rastephens426** [comment]
I've tried the latest releases in the Arch Linux repos (2.0.0b2) as well.

**Comment by Jesin** [comment]
Do you have a commit ref?

**Comment by rastephens426** [comment]
The Arch repos have commit 1eb768578bc0c4fa17396f573a4b37a652f12acd

**Comment by rkitover** [comment]
@rastephens426 is this only an issue for GB/GBC? When you use a GBA ROM this does not happen?

**Comment by rastephens426** [comment]
It is indeed only happening with GB/GBC

**Comment by rkitover** [comment]
Thanks, will try to take a look sometime soon.

**Comment by sboukortt** [comment]
I can reproduce the issue on a desktop machine with NVIDIA graphics. It also happens when closing the window or pressing Escape. `SIGINT` and `SIGTERM` are not enough to stop VBA-M, `SIGABRT` is.
