### ISSUE TITLE
Is there a way to transfer saves from no$gba to vba?

### ISSUE THREAD

**Issue by dagwimweaper** [visualboyadvance-m/visualboyadvance-m#672]
### Expected behavior
When importing battery file from no$gba i expect it to load my save along with it
### Actual behavior
it loads a blank game
### Steps to reproduce the behavior
1. change no$gba.ini to make saves in raw format
2.save game 
3. import save into vba

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
pokemon leafgreen

### Option details

Video driver (simple, opengl): intel

Sound driver (directsound, xaudio, openal, SDL): intel

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): windows 8

Is there a way to import battery files/saves from no$gba to vba? I read another thread on here where someone removed a header using a hex editor but i have absolutely no idea how to do that. No$gba is outdated and buggy so i want to change to vba m.
 
edit: heres my save file: https://drive.google.com/file/d/1Ur8ozvVa2bXkmDqS64tn12Q_FMhKE_0w/view?usp=sharing

and heres a screenshot of rom info:
![Capture](https://user-images.githubusercontent.com/65793320/82718783-a532dc00-9c72-11ea-877d-49d02316f8e3.PNG)

**Comment by denisfa** [comment]
@dagwimweaper Please edit your issue and upload your save file. Also, add a screenshot of `File` > `Rom information` so we can 100% sure about what version of pokemon leafgreen this is.

**Comment by Liger0** [comment]
After opening the rom and the battery (import File->battery), do Options->GBA->Configure->Save type->Detect now->OK. Then restart the emulator and try again. importing the battery.

**Comment by dagwimweaper** [comment]
> @dagwimweaper Please edit your issue and upload your save file. Also, add a screenshot of `File` > `Rom information` so we can 100% sure about what version of pokemon leafgreen this is.

Sorry, the information is there now.

**Comment by dagwimweaper** [comment]
> After opening the rom and the battery (import File->battery), do Options->GBA->Configure->Save type->Detect now->OK. Then restart the emulator and try again. importing the battery.

this didnt work, but thank you for the suggestion!

**Comment by denisfa** [comment]
@dagwimweaper Here you go. Tell me if it works.

[Pokemon - Leaf Green Version (U) (V1.1).sav.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/4670978/Pokemon.-.Leaf.Green.Version.U.V1.1.sav.zip)

Also, as far as importing saves from `no$gba`, you need to locate the file `NO$GBA.INI` and change the line:

`SAV/SNA File Format == Compressed (good/lz)`
to
`SAV/SNA File Format == Raw`

Open the game, save it and close `no$gba`. The new file should be usable automatically by vbam.

**Comment by dagwimweaper** [comment]
> @dagwimweaper Here you go. Tell me if it works.
> 
> [Pokemon - Leaf Green Version (U) (V1.1).sav.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/4670978/Pokemon.-.Leaf.Green.Version.U.V1.1.sav.zip)
> 
> Also, as far as importing saves from `no$gba`, you need to locate the file `NO$GBA.INI` and change the line:
> 
> `SAV/SNA File Format == Compressed (good/lz)`
> to
> `SAV/SNA File Format == Raw`
> 
> Open the game, save it and close `no$gba`. The new file should be usable automatically by vbam.

It worked now! I tried that before but apparently it didnt work because I didn't capitalize the R in raw. I feel like an idiot lol

**Comment by rkitover** [comment]
@denisfa I suppose we should detect this compressed format and decompress it if this is not difficult to do.

**Comment by Squall-Leonhart** [comment]
nocash eeprom savs are always 128KB, and byte flipped compared to ours.
