### ISSUE TITLE
Mouse disappears in link

### ISSUE THREAD

**Issue by Liger0** [visualboyadvance-m/visualboyadvance-m#675]
Expected behavior
Mouse cursor doesn't disappear 

### Actual behavior
When there are 2 emulator instances and random clicks are done, the cursor keeps disappearing on either screens

### Steps to reproduce the behavior

Stock configs (apart inputs that have WASD I don't accept)
Link in cable, click multiple times on both screens on the program title bar and the screen to trigger it. 
Clicking then on the windows bar, it appears again in that instance.

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Win10 x64

Version of code (pre-built binary version, or commit ref, or just "master"): 2.1.4

**Comment by denisfa** [comment]
@Liger0 This is intentional. The mouse cursor is supposed to disappear if stays on top of the vbam screen for some time (with a loaded game, of course). We could make this an option on the config file, but this is definitely not a bug.

**Comment by Liger0** [comment]
It happens instantly, not after a bit of time, and that only makes sense if you don't move the mouse, not trying to figure where it is, imo.

**Comment by rkitover** [comment]
@Liger0 can you please try the nightly, I believe I changed some code related to the mouse cursor hiding/unhiding recently.

**Comment by Liger0** [comment]
The mouse works fine with the nightly, it doesn't disappear.
The problem now the menu bar keeps appearing and disappearing each 2-3 seconds, making the game screen move continuously and thus making it impossible to play.

**Comment by rkitover** [comment]
The menubar hiding is a new feature, it is supposed to disappear when the mouse is inactive.

Are you moving the mouse while playing?

Are you using the keyboard or gamepad to play?

**Comment by rkitover** [comment]
I forgot to mention, you can turn off the menubar hiding by going to Options -> UI Settings.

**Comment by Liger0** [comment]
I am using the keyboard.
 Anyway, I don't think it randomly reappearing each 3 seconds is a good thing, with the mouse moving or not. Maybe the delay could be improved or the mouse should be gived a minimal range of movement, or making this option off by default. 
This becomes worse when multiple instances are open and connected and you have to move the mouse. Maybe the feature could automatically turn off in this case?
This behaviour causes a weird "sensation" like when the screen flashes very fast.
It's not a big problem for me but I believe it could be if anyone suffers of photosensitive epilepsy.

**Comment by rkitover** [comment]
The random reappearing does not happen for me, or other people who have tried this feature, with link as well. A guy I work with who does dolphin link stuff says it works fine for him and his users.

I would need to figure out why it happens for you. The minimal range of movement thing is a good idea, and I can try to implement it to see if it will fix your problem.

Are you using a laptop with a trackpad by any chance? And if so, is it possible that the trackpad is registering these mouse movements accidentally? Anything else that could be registering mouse movements erroneously?

**Comment by Liger0** [comment]
It seems to be working fine today, I can't say what was. Probably the mouse shaking a little bit due to high DPI.
