### ISSUE TITLE
Cannot complete build on Mac

### ISSUE THREAD

**Issue by acidcake** [visualboyadvance-m/visualboyadvance-m#676]
# Expected behavior
Build successfully.

#### Hangs at step 204/205 (and has yet to timeout on both macs I'm testing this on).
> [204/205] Linking CXX executable visua....app/Contents/MacOS/visualboyadvance-m

### Steps to reproduce the behavior
Following the procedure to generate a build in the ~/src/vis... directory, and having doctored and cleaned up homebrew so that there would be no issues before installing dependencies, I am able to clone the repo, install them, create a build directory and run cmake. I cannot, however, get past the final steps of running `ninja`

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):  MAC

Version of code (pre-built binary version, or commit ref, or just "master"): master

**Comment by rkitover** [comment]
In release mode it copies and links all dylibs to the app bundle, this can take a while, but it should not hang, I will look into it.

In the meantime, pass `-DCMAKE_BUILD_TYPE=Debug` to cmake.

**Comment by acidcake** [comment]
This created the application, but the process generated a bunch of warnings. Most of these are _unused parameter_/_function_ warnings, and I'm assuming there's some shifting around in the logic currently going on bts that's more or less harmless. Some pragmas ignored as well.

The part that's iffy is again the 204th step.

> [204/204] Linking CXX executable visualboyadvance-m.app/Contents/MacOS/visualboyadvance-m
> ld: warning: text-based stub file /System/Library/Frameworks//IOKit.framework/IOKit.tbd and library file /System/Library/Frameworks//IOKit.framework/IOKit are out of sync. Falling back to library file for linking.

A bunch of these. I won't bother counting or passing standard output into a counting function, but they're all the same.

### Of note is that my terminal actually spelled out the whole directory this time, whereas before, it actually printed to the console
> visua....app/Contents/MacOS/visualboyadvance-m
### That could indicate a formatting error in the directory name?

And a minor update: I let this guy run for 5 hours. It was still on step 204.

**Comment by rkitover** [comment]
The warnings are because the codebase is shit, and we just turn them off in release mode. They need to be fixed of course, when that will happen I don't know.

What version of macOS are you building on by the way?

The linking warnings can most likely be ignored.

The dylibs linking I will definitely look at and either fix or remove if I can reproduce the problem.

If you want to build in release mode without the dylibs, just remove the `third_party_libs_tool` step in `src/wx/CMakeLists.txt`.

I should also add a cmake option to turn that off.

**Comment by acidcake** [comment]
I'm actually just a bit outdated. **High Sierra (10.13.6)**. I'm afraid updating will cause so many things to break in Catalina. I've heard horror stories, so I'll lay off for now. If you think that's an issue let me know.

Otherwise, thank you for the frankness and information. I'm shit when it comes to solving linker issues myself, and if I have to implement a linker on a mac, it usually ends up breaking somewhere. 

I'll create a separate build using your suggestion. It'll probably be good enough for my purposes.

**Comment by rkitover** [comment]
I should mention that we do our release binaries differently, using the `tools/osx/builder` script.

This will build all deps and make a static binary, that does not require bundling any dylibs.

If you want to try it, it will take much longer to build, maybe about an hour or so depending on your hardware, but next time you use it it will not rebuild any deps since they are already built.

**Comment by acidcake** [comment]
Thanks, Rafael. This is good info to have. Let me give it a go. Not that it'll solve this problem. I didn't realize that this wasn't a release build. And going to the tags, I didn't realize that the current release didn't support 32-bit Macs until the literal day I tried it (~3-4 days ago). 

Of course I could just be interpreting this wrong.

Let me know if you have a commit for me to try on my mac. I can pull the repo and build anew. JIC you don't have a machine to test it out on.

**Comment by rkitover** [comment]
32 bit macs really aren't worth supporting, any macs still in actual use, even if they are running a 32 bit OS, can run 64 bit binaries.

**Comment by rkitover** [comment]
I made a high sierra vm, but I could not reproduce the problem.

If you could tar up your `/usr/local` and post it for me on dropbox or some such, I would be able to debug whatever the linking issue is.

I am guessing it's something to do with a recursive symlink to a dylib, or something like that, but if I could reproduce the issue it would be much easier to fix.

**Comment by acidcake** [comment]
Shared a Drive link via email. If it's something on my end and not a problem native to this repo, then don't feel obligated to troubleshoot for me. Otherwise, I'm happy to help.

**Comment by rkitover** [comment]
I used your local tree and it ran through fine for me.

I think I know what the problem is, the link script can use sudo in some cases, and it's hanging on the password prompt.

Try enabling passwordless sudo, by doing this as root:

```bash
sudo su -
cd /etc/sudoers.d
echo 'user ALL = (ALL) NOPASSWD: ALL' > user
```

where **user** is your normal mac user.

**Comment by rkitover** [comment]
Also a note that your brew installation is out of sync, you probably need to run `brew upgrade`.
