### ISSUE TITLE
Crash when writing PNG capture

### ISSUE THREAD

**Issue by pfhore-github** [visualboyadvance-m/visualboyadvance-m#680]
# Expected behavior
save PNG screen capture imge.

### Actual behavior
VBA-m crashed.

### Steps to reproduce the behavior
1. open any ROM.
2. Select "Screen capture..."
3. write any file name & click 

### ROM details

Which games are affected by the issue (please state if GBA or GB game): Any (both GB/GBA)

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

Include screenshots of ROM Information (File > ROM Information):

If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl):
opengl

Sound driver (directsound, xaudio, openal, SDL):
SDL

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows

Version of code (pre-built binary version, or commit ref, or just "master"):
d8da9389

**Comment by rkitover** [comment]
Nightly has been rebuilt with the fix.

Thank you for your report!
