### ISSUE TITLE
Odd Audio

### ISSUE THREAD

**Issue by Louispaz** [visualboyadvance-m/visualboyadvance-m#682]
While I was playing a modded version of Pokemon Emerald, odd audio began to play and I'm unsure what caused it. I decided to close the game and open it again, but it was still playing. The audio just sounded like some tractor driving around. I have no idea how to remove it from the game and I wish I could show you the audio of whats playing, but the file pasting doesn't support MP3 files. I just hope you can help me with this..

**Comment by ZachBacon** [comment]
Please use the template that was given, we need to know config specifics such as sound driver etc

**Comment by Louispaz** [comment]
I tried everything, but nothing was working. I just decided to do a new game and start all over

**Comment by ZachBacon** [comment]
That doesn't help at all. We need specific INFORMATION such as what audio driver you're using within vba-m etc. Information like that helps diagnose your issue and have a better chance of helping you with your issue.

**Comment by ZachBacon** [comment]
Closing this due to lack of detail from original poster, if he provides more details then it can be reopened.
