### ISSUE TITLE
Graphic glitches in FF4-Advance

### ISSUE THREAD

**Issue by slacknk** [visualboyadvance-m/visualboyadvance-m#684]
Sometimes when i playing game `Final Fantasy IV Advance`  i'am getting graphic glitches,  game don't go to crash and glitches don't stop gaming process, they are refreshing and go away after any actions and changes made. Glitches AFTER or inside  dialogs and in gaming messages from objects. Intro, Clips and Battles  are without these glitches.
* This is not Crash bugs

This bug happens in window and fullscreen mode RA. Trying other jRPG/Action-RPG: Classic NES Series - Legend of Zelda (UE) [!] - works fine w/o glitches.
* GBA w/o BIOS:  `Final Fantasy IV Advance (UA) [!]`, maybe other game, maybe. 
```
$ retroarch -L FULL_PATH/to/vbam_libretro.so "Final Fantasy IV Advance (UA) [!].gba"
```
[![](https://i.postimg.cc/TKHRXzXH/vbam-git20200318-b21880ea-2-1-4-64-200612-090555.png)](https://i.postimg.cc/Dz7m1hpF/vbam-git20200318-b21880ea-2-1-4-64-200612-090555.png) [![](https://i.postimg.cc/Yj1qmD1h/vbam-git20200318-b21880ea-2-1-4-64-200612-090532.png)](https://i.postimg.cc/9Xk4Kv0t/vbam-git20200318-b21880ea-2-1-4-64-200612-090532.png) [![](https://i.postimg.cc/WDFsp5Np/vbam-git20200318-b21880ea-2-1-4-64-200612-090544.png)](https://i.postimg.cc/8CwcHYxv/vbam-git20200318-b21880ea-2-1-4-64-200612-090544.png) 

### Build details
* Linux: Slackware64-14.2
* Xorg: 1.18.3
* RetroArch-1.8.8-x86_64

Tried libretro core of vba-m from this code repository and from libretro project:

* 2.1.3_git20200310.[29dffc01](https://github.com/libretro/vbam-libretro/tree/29dffc01)_libretro
  * [![](https://i.postimg.cc/cKHrR7dP/vbam-git20200310-29dffc01-2-1-3-64lr-200611-083311.png)](https://i.postimg.cc/9fPZj1KX/vbam-git20200310-29dffc01-2-1-3-64lr-200611-083311.png) [![](https://i.postimg.cc/jWFCZW52/vbam-git20200310-29dffc01-2-1-3-64lr-200612-080139.png)](https://i.postimg.cc/26zvjhNQ/vbam-git20200310-29dffc01-2-1-3-64lr-200612-080139.png) [![](https://i.postimg.cc/r0Rsb80J/vbam-git20200310-29dffc01-2-1-3-64lr-200611-084524.png)](https://i.postimg.cc/Y9bFv0tJ/vbam-git20200310-29dffc01-2-1-3-64lr-200611-084524.png)

* 2.1.4_git20200318.https://github.com/visualboyadvance-m/visualboyadvance-m/commit/b21880ea
  * [![](https://i.postimg.cc/4mPfWK2G/vbam-git20200318-b21880ea-2-1-4-64-200612-092150.png)](https://i.postimg.cc/K8S1vBn1/vbam-git20200318-b21880ea-2-1-4-64-200612-092150.png) [![](https://i.postimg.cc/ppRVQQZk/vbam-git20200318-b21880ea-2-1-4-64-200612-092216.png)](https://i.postimg.cc/L6ZqpNZd/vbam-git20200318-b21880ea-2-1-4-64-200612-092216.png) [![](https://i.postimg.cc/DSz2H2RX/vbam-git20200318-b21880ea-2-1-4-64-200612-092222.png)](https://i.postimg.cc/CxGzZ5Nm/vbam-git20200318-b21880ea-2-1-4-64-200612-092222.png)

* 2.1.4_git20200607.https://github.com/visualboyadvance-m/visualboyadvance-m/commit/0c5ee99
  * [![](https://i.postimg.cc/1fmnR1L9/vbam-git20200607-0c5ee99-2-1-4-64-200612-051944.png)](https://i.postimg.cc/vH9WzQh6/vbam-git20200607-0c5ee99-2-1-4-64-200612-051944.png) [![](https://i.postimg.cc/nXMX7YFg/vbam-git20200607-0c5ee99-2-1-4-64-200612-053951.png)](https://i.postimg.cc/pLJzwqgW/vbam-git20200607-0c5ee99-2-1-4-64-200612-053951.png) [![](https://i.postimg.cc/SJgXJthc/vbam-git20200607-0c5ee99-2-1-4-64-200612-054342.png)](https://i.postimg.cc/cLSfkVkk/vbam-git20200607-0c5ee99-2-1-4-64-200612-054342.png)

### Option details
`retroarch-core-options.cfg`:
```
vbam_allowcolorizerhack = "disabled"
vbam_astick_deadzone = "15"
vbam_forceRTCenable = "disabled"
vbam_gbcoloroption = "disabled"
vbam_gbHardware = "gba"
vbam_gyro_sensitivity = "100"
vbam_layer_1 = "enabled"
vbam_layer_2 = "enabled"
vbam_layer_3 = "enabled"
vbam_layer_4 = "enabled"
vbam_layer_5 = "enabled"
vbam_layer_6 = "enabled"
vbam_layer_7 = "enabled"
vbam_layer_8 = "enabled"
vbam_palettes = "black and white"
vbam_show_advanced_options = "enabled"
vbam_showborders = "disabled"
vbam_solarsensor = "0"
vbam_sound_1 = "enabled"
vbam_sound_2 = "enabled"
vbam_sound_3 = "enabled"
vbam_sound_4 = "enabled"
vbam_sound_5 = "enabled"
vbam_sound_6 = "enabled"
vbam_soundfiltering = "0"
vbam_soundinterpolation = "disabled"
vbam_swap_astick = "disabled"
vbam_tilt_sensitivity = "100"
vbam_turbodelay = "3"
vbam_turboenable = "enabled"
vbam_usebios = "disabled"
```
`retroarch.cfg`:
```
video_adaptive_vsync = "false"
video_allow_rotate = "true"
video_aspect_ratio = "-1.000000"
video_aspect_ratio_auto = "false"
video_black_frame_insertion = "false"
video_context_driver = ""
video_crop_overscan = "false"
video_ctx_scaling = "false"
video_disable_composition = "false"
video_driver = "glcore"
video_filter = ""
video_filter_dir = "/usr/lib64/retroarch/filters/video"
video_font_enable = "true"
video_font_path = ""
video_font_size = "32.000000"
video_force_aspect = "true"
video_force_srgb_disable = "false"
video_frame_delay = "0"
video_fullscreen = "false"
video_fullscreen_x = "0"
video_fullscreen_y = "0"
video_gpu_record = "false"
video_gpu_screenshot = "true"
video_hard_sync = "false"
video_hard_sync_frames = "0"
video_layout_directory = "~/.config/retroarch/layouts"
video_layout_enable = "false"
video_layout_path = ""
video_layout_selected_view = "0"
video_max_swapchain_images = "3"
video_message_color = "ffff00"
video_message_pos_x = "0.050000"
video_message_pos_y = "0.050000"
video_monitor_index = "0"
video_msg_bgcolor_blue = "0"
video_msg_bgcolor_enable = "false"
video_msg_bgcolor_green = "0"
video_msg_bgcolor_opacity = "1.000000"
video_msg_bgcolor_red = "0"
video_post_filter_record = "false"
video_record_config = ""
video_record_quality = "4"
video_record_scale_factor = "1"
video_record_threads = "2"
video_refresh_rate = "60.000000"
video_rotation = "0"
video_scale = "4.000000"
video_scale_integer = "false"
video_shader_delay = "0"
video_shader_dir = "~/.config/retroarch/shaders"
video_shader_enable = "false"
video_shader_watch_files = "false"
video_shared_context = "true"
video_smooth = "false"
video_swap_interval = "1"
video_threaded = "false"
video_vsync = "true"
video_window_opacity = "100"
video_window_save_positions = "false"
video_window_show_decorations = "true"
video_windowed_fullscreen = "true"
video_windowed_position_height = "720"
video_windowed_position_width = "1280"
video_windowed_position_x = "0"
video_windowed_position_y = "0"
```

**Comment by rkitover** [comment]
Can you please see if you can reproduce the glitch using the regular emulator GUI, so we can see if this issue is specific to the libretro interface.

**Comment by slacknk** [comment]
Too, vba-m_2.1.4:
[![](https://i.postimg.cc/Jy6TQHFG/vbam-v2-1-4-200616-102251.png)](https://i.postimg.cc/1tPLspcc/vbam-v2-1-4-200616-102251.png) [![](https://i.postimg.cc/68hbymLV/vbam-v2-1-4-200616-102232.png)](https://i.postimg.cc/RZkkbrWY/vbam-v2-1-4-200616-102232.png) [![](https://i.postimg.cc/wtTfJQ0C/vbam-v2-1-4-Final-Fantasy-IV-Advance-UA-03.png)](https://i.postimg.cc/zfT9sdWG/vbam-v2-1-4-Final-Fantasy-IV-Advance-UA-03.png)
```
[Display]
Bilinear=0
Filter=none
FilterPlugin=
IFB=none
KeepOnTop=0
MaxThreads=1
RenderMethod=opengl
Scale=4
Stretch=1
```
My idea, maybe: 
* Speed Up / rewind
* BIOS, because with him on release version vba-m (regular emulator GUI) I couldn't reproduce error

(But, maybe help, I'm tried other emulator [mgba-libretro](https://github.com/libretro/mgba) w/o BIOS, with this ROM, with Speed Up - works fine w/o this glitches.)

**Comment by rkitover** [comment]
Great, thank you.

**Comment by negativeExponent** [comment]
can you consistently recreate this issue? if so, upload the savefile (either vbam or libretro savefile will do)
ive played with the (USA) version of this game past where you kill all summoners in the village but no issue so far.

**Comment by Squall-Leonhart** [comment]
Working as intended, these are present on hardware.
