### ISSUE TITLE
I cant even find how to enable Super Game Boy SGB mode, let alone use it...

### ISSUE THREAD

**Issue by ambipie** [visualboyadvance-m/visualboyadvance-m#685]
### Expected behavior
I expected it to be labeled.

### Actual behavior
I wouldn't know where to start.

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
Any SGB enabled/enhanced games.

Version of code (pre-built binary version, or commit ref, or just "master"):
It seems to be fully updated, as far as I could discern. I cant find the version at this time.

**Comment by RokkumanX** [comment]
![image](https://user-images.githubusercontent.com/50436544/85029231-5ba7b500-b17c-11ea-839a-0d0f9144a20e.png)

![image](https://user-images.githubusercontent.com/50436544/85029517-a7f2f500-b17c-11ea-80c0-71ec8bb293a4.png)

![image](https://user-images.githubusercontent.com/50436544/85029997-39fafd80-b17d-11ea-8d9e-3b3be2c32da6.png)

**Comment by RokkumanX** [comment]
Good luck! 
Personally I don't even use VBA-M anymore but found this option pretty much immediately.

**Comment by rkitover** [comment]
What is the border editor? You can assign keys to GBA buttons in the input configuration.
