### ISSUE TITLE
Misbehaving arrow keys

### ISSUE THREAD

**Issue by EpicWink** [visualboyadvance-m/visualboyadvance-m#689]
About a year ago (or maybe a little more), there was a bug (in Linux I think) where the emulator would intermittently not register my arrow key release. This was fixed in an input refactor back then (I think near or at the same time the input latency on Linux was significantly improved).

It now seems to have cropped up since the recent input refactor. In addition, some of my inputs seem to be dropped. My most recent successful commit tested is 0c5ee99 (although there could have been newer that I haven't tested).

### ROM details
* Title: Tetris DX (GBC)
* Maker: 01 Nintendo
* Unit: 03
* Cartridge: 03
* Version 00

### Option details
Video: OpenGL, xBRZ 6x filter, no blending
Sound: SDL, 2-frame buffer

### Build details
OS: Ubuntu 19.10
Graphics: Xorg, Nvidia 435.21, GLX 1.4, OpenGL 4.6.0, ES 3.2
Build: 3a2b97f (current master)

<details>
<summary>cmake -L (click to expand)</summary>

```
-- Found SFML 2.5.1 in /usr/include
-- Could NOT find FFmpeg (missing: AVCODEC_LIBRARIES AVCODEC_INCLUDE_DIRS AVFORMAT_LIBRARIES AVFORMAT_INCLUDE_DIRS SWSCALE_LIBRARIES SWSCALE_INCLUDE_DIRS AVUTIL_LIBRARIES AVUTIL_INCLUDE_DIRS SWRESAMPLE_LIBRARIES SWRESAMPLE_INCLUDE_DIRS) 
-- Found gcc-ar: /usr/bin/gcc-ar
-- Found gcc-nm: /usr/bin/gcc-nm
-- Found gcc-ranlib: /usr/bin/gcc-ranlib
-- Configuring done
-- Generating done
-- Build files have been written to: ~/src/visualboyadvance-m/build
-- Cache values
CCACHE_FOUND:FILEPATH=/usr/bin/ccache
CMAKE_BUILD_TYPE:STRING=Release
CMAKE_INSTALL_PREFIX:PATH=/usr/local
ENABLE_ASAN:BOOL=OFF
ENABLE_ASM:BOOL=OFF
ENABLE_ASM_CORE:BOOL=OFF
ENABLE_ASM_SCALERS:BOOL=OFF
ENABLE_DEBUGGER:BOOL=OFF
ENABLE_FAUDIO:BOOL=OFF
ENABLE_FFMPEG:BOOL=ON
ENABLE_GBA_LOGGING:BOOL=ON
ENABLE_LINK:BOOL=OFF
ENABLE_LIRC:BOOL=OFF
ENABLE_LTO:BOOL=ON
ENABLE_NLS:BOOL=OFF
ENABLE_ONLINEUPDATES:BOOL=OFF
ENABLE_OPENAL:BOOL=OFF
ENABLE_SDL:BOOL=OFF
ENABLE_SSP:BOOL=OFF
ENABLE_WX:BOOL=ON
GCC_AR:FILEPATH=/usr/bin/gcc-ar
GCC_NM:FILEPATH=/usr/bin/gcc-nm
GCC_RANLIB:FILEPATH=/usr/bin/gcc-ranlib
GETTEXT_MSGFMT_EXECUTABLE:FILEPATH=/usr/bin/msgfmt
GETTEXT_MSGMERGE_EXECUTABLE:FILEPATH=/usr/bin/msgmerge
GPG_PROGRAM:FILEPATH=/usr/bin/gpg
HTTPS:BOOL=ON
MSGINIT:FILEPATH=/usr/bin/msginit
REVISION:STRING=3a2b97fd
SDL2MAIN_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libSDL2main.a
SDL2_DEFINITIONS:STRING=-D_REENTRANT
SDL2_EXTRA_LIBS:STRING=
SDL2_INCLUDE_DIR:PATH=/usr/include/SDL2
SDL2_LIBRARY:STRING=/usr/lib/x86_64-linux-gnu/libSDL2main.a;/usr/lib/x86_64-linux-gnu/libSDL2.so;-lpthread
SDL2_LINKER_FLAGS:STRING=
SFML_INCLUDE_DIR:PATH=/usr/include
UPSTREAM_RELEASE:BOOL=OFF
VBAM_STATIC:BOOL=OFF
VERSION:STRING=2.1.4
VERSION_RELEASE:STRING=0
WX_CONFIG_H:PATH=/usr/include/wx-3.0
XGETTEXT:FILEPATH=/usr/bin/xgettext
ZIP_PROGRAM:FILEPATH=/usr/bin/zip
ZIP_SUFFIX:BOOL=OFF
exe:FILEPATH=/usr/bin/wx-config
pkgcfg_lib_FFMPEG_LIB_libavcodec_avcodec:FILEPATH=/usr/lib/x86_64-linux-gnu/libavcodec.so
pkgcfg_lib_FFMPEG_LIB_libavformat_avformat:FILEPATH=/usr/lib/x86_64-linux-gnu/libavformat.so
pkgcfg_lib_FFMPEG_LIB_libavutil_avutil:FILEPATH=/usr/lib/x86_64-linux-gnu/libavutil.so
pkgcfg_lib_FFMPEG_LIB_libswresample_swresample:FILEPATH=/usr/lib/x86_64-linux-gnu/libswresample.so
pkgcfg_lib_FFMPEG_LIB_libswscale_swscale:FILEPATH=/usr/lib/x86_64-linux-gnu/libswscale.so
pkgcfg_lib_FFMPEG_avcodec:FILEPATH=/usr/lib/x86_64-linux-gnu/libavcodec.so
pkgcfg_lib_FFMPEG_avformat:FILEPATH=/usr/lib/x86_64-linux-gnu/libavformat.so
pkgcfg_lib_FFMPEG_avutil:FILEPATH=/usr/lib/x86_64-linux-gnu/libavutil.so
pkgcfg_lib_FFMPEG_swresample:FILEPATH=/usr/lib/x86_64-linux-gnu/libswresample.so
pkgcfg_lib_FFMPEG_swscale:FILEPATH=/usr/lib/x86_64-linux-gnu/libswscale.so
pkgcfg_lib_GTK2_atk-1.0:FILEPATH=/usr/lib/x86_64-linux-gnu/libatk-1.0.so
pkgcfg_lib_GTK2_cairo:FILEPATH=/usr/lib/x86_64-linux-gnu/libcairo.so
pkgcfg_lib_GTK2_fontconfig:FILEPATH=/usr/lib/x86_64-linux-gnu/libfontconfig.so
pkgcfg_lib_GTK2_freetype:FILEPATH=/usr/lib/x86_64-linux-gnu/libfreetype.so
pkgcfg_lib_GTK2_gdk-x11-2.0:FILEPATH=/usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so
pkgcfg_lib_GTK2_gdk_pixbuf-2.0:FILEPATH=/usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so
pkgcfg_lib_GTK2_gio-2.0:FILEPATH=/usr/lib/x86_64-linux-gnu/libgio-2.0.so
pkgcfg_lib_GTK2_glib-2.0:FILEPATH=/usr/lib/x86_64-linux-gnu/libglib-2.0.so
pkgcfg_lib_GTK2_gobject-2.0:FILEPATH=/usr/lib/x86_64-linux-gnu/libgobject-2.0.so
pkgcfg_lib_GTK2_gtk-x11-2.0:FILEPATH=/usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so
pkgcfg_lib_GTK2_pango-1.0:FILEPATH=/usr/lib/x86_64-linux-gnu/libpango-1.0.so
pkgcfg_lib_GTK2_pangocairo-1.0:FILEPATH=/usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so
pkgcfg_lib_GTK2_pangoft2-1.0:FILEPATH=/usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so
wxWidgets_USE_DEBUG:BOOL=OFF
wxWidgets_USE_UNICODE:BOOL=ON
wxWidgets_wxrc_EXECUTABLE:FILEPATH=/usr/bin/wxrc
```
</details>

**Comment by denisfa** [comment]
@EpicWink Thank you for this report. There were some open questions after I finished the input refactor, but I couldn't confirm anything with my testing.

> where the emulator wouldn't register my arrow key release.

Is there a minimal test case here? I am also on Linux, but could only get something similar when I press and hold a key, then open a menu with mouse. If I release the key while browsing menus, it would not get registered for the game.

> In addition, some of my inputs seem to be dropped.

Also arrow keys? Or other? I had to do some follow-up to deal with special keys, such as `BACKSPACE`, `ENTER`, `CTRL` and `ALT`.

**Comment by EpicWink** [comment]
> Is there a minimal test case here?

Is difficult to find one, as the problem is intermittent. However is feels like the same issue from a year ago, so if there was a test case for that, perhaps that could be reused. Regardless, I think first steps for me is to on down the exact commit which introduced the issue (I suspect my username doesn't rely on you follow-up commit)

> but could only get something similar when I press and hold a key, then open a menu with mouse

I'm not touching the mouse when I get the issues

> Also arrow keys? Or other?

Hard to test on Tetris as it only card about key down for the other actions. I'll things the direction actions and report back

**Comment by rkitover** [comment]
@denisfa this may be because we removed `wxGetKeyState()`, which as I recall you added some months ago to fix spurious keyboard events, we may want to reintroduce it with some checks (disable for unicode keys and wayland.)

I think this is the most likely cause, I can do a PR for this if you like.

**Comment by EpicWink** [comment]
I can confirm that the issue is not present in d379a076, but is present in de933301. In addition, re-mapping the direction buttons to other keys (I tried "IJKL") didn't solve the issue.

I see your follow-up: in de933301, the backspace and enter didn't work, but in the follow-up 91a6b53e they worked again

**Comment by denisfa** [comment]
@EpicWink Thanks for taking your time here! The issue for me is that I cannot replicate using my setup. The issues for the older input refactor were really easy to force and I did check my test cases for that matter. As a last attempt here, could you please upload your `vbam.ini`? I want to see all config so I can compare with mine.

> @denisfa this may be because we removed wxGetKeyState(), which as I recall you added some months ago to fix spurious keyboard events, we may want to reintroduce it with some checks (disable for unicode keys and wayland.)

@rkitover  Were you able to force this?  I don't think this function play a role here, but then again I cannot replicate this issue.

**Comment by rkitover** [comment]
> > @denisfa this may be because we removed wxGetKeyState(), which as I recall you added some months ago to fix spurious keyboard events, we may want to reintroduce it with some checks (disable for unicode keys and wayland.)

> @rkitover  Were you able to force this?  I don't think this function play a role here, but then again I cannot replicate this issue.

To refresh your memory, look at commit b0ec8469, this is where you introduced this function.

The function was only necessary because of bugs in the system and/or system libraries. If we were not getting spurious keyboard events, it would not be necessary in the first place.

My theory is that @EpicWink has this bug on her system, while you do not. Perhaps because of different Ubuntu versions, or different distro versions entirely, or whatever.

In any event, we can still use this function, all we have to do is check that the key is not unicode and we are not running under wayland.

I'll probably post a commit for this later today.

**Comment by rkitover** [comment]
@EpicWink Hi, can you please try the `key-state` branch, I believe it will fix this issue, for reasons I described above.

**Comment by EpicWink** [comment]
@rkitover The `key-state` branch works perfectly, thanks
