### ISSUE TITLE
Cannot toggle fullscreen (visualboyadvance-M 2.1.4)

### ISSUE THREAD

**Issue by gabba-wabba** [visualboyadvance-m/visualboyadvance-m#691]
### Expected behavior
Toggle on/off fullscreen when pressing the F11 key.
### Actual behavior
F11 key does not do anything, cannot toggle off fullscreen even when using the Esc key if fullscreen has been activated using the hotbar.

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Windows 10

**Comment by rkitover** [comment]
Try `ALT+ENTER`, you can also modify the bindings for this in `Options -> Key Shortcuts`.

Also please try nightly.

**Comment by gabba-wabba** [comment]
`ALT+ENTER` worked, thanks for the help! I'll also check nightly out.
