### ISSUE TITLE
DS4Windows Compatiblity

### ISSUE THREAD

**Issue by SoulStriker27** [visualboyadvance-m/visualboyadvance-m#703]
# Expected behavior
Configuring controller settings should only be from 1 input device

### Actual behavior
Controller configurations end up setting 2 buttons at once  (joy1 - button 11, joy3 - button 11)  when 1 button on 1 controller is pressed.
![Capture](https://user-images.githubusercontent.com/46726808/87615980-964c3100-c6d9-11ea-8a5d-bc131997da5c.PNG)

### Steps to reproduce the behavior

I haven't fully figured it out, ds4 makes an HID compliant device on the computer so ps4 controllers work as xbox 360 controllers. This might be the issue and visual boy might be getting data from both at the same time.
![Capture11](https://user-images.githubusercontent.com/46726808/87616174-196d8700-c6da-11ea-85b6-4fc2e5fc25d4.PNG)

### ROM details

Which games are affected by the issue (please state if GBA or GB game): 
Link to the Past/Four Swords - GBA

Include screenshots of ROM Information (File > ROM Information):
![Capture](https://user-images.githubusercontent.com/46726808/87614059-ab729100-c6d4-11ea-8dba-2b37bb8b056d.PNG)

If you are using a BIOS file, please say which one: 
GBA Bios

### Option details

Video driver (simple, opengl): 
opengl

Sound driver (directsound, xaudio, openal, SDL):
SDL

**Comment by rkitover** [comment]
Would it be possible to test what happens with DS4windows disabled?

**Comment by Squall-Leonhart** [comment]
Use HID-Hide to mask the original device, otherwise you're mapping  both the DS4 and virtualized Xbox device at the same time.
