### ISSUE TITLE
More Speed Issues

### ISSUE THREAD

**Issue by Castaf1ore** [visualboyadvance-m/visualboyadvance-m#704]
### Expected behavior
Regular speed at 100% without turbo.
### Actual behavior
Extreme speed at 785% - 800% without turbo. Changing throttle did not help, in fact, it only made it worse when I increased throttle (from the default 100) it pushed it up to 1200%-1500%. Lowering throttle had no affect on the speed stuck at 800%. Interestingly, the audio is also silent. Configuring the audio to anything other than SDL increased the speed to 1500%, and trying to change it back kept the speed up permanent until the program was closed. Checked the audio toggle and it was on, checked audio output on my computer and it should have been the speakers. So the problem may be related to audio.
### Steps to reproduce the behavior
I opened up the VBA today on 7/24/2020. This bug did not happen prior and I did not open the program for the past 7 days. Not sure if this is caused by an update or external interference. For reference, I was in a discord call when I booted the program up, but disconnecting from discord and trying to reopen VBA did not solve the problem.

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
I only have an FE-8 (The Sacred Stones) Custom ROM on my computer that I play, it's Fire Emblem Vision Quest https://feuniverse.us/t/fe8-complete-fire-emblem-vision-quest-v1-18-22-jul-20-full-hack-release/3815
The game ran fine prior over multiple sessions.
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
None that I know since I don't have any other ROMs on this computer, though I can download another ROM and test if need be.
Include screenshots of ROM Information (File > ROM Information):
![2020-07-24 (2)](https://user-images.githubusercontent.com/68762760/88446872-a495fd80-cdfb-11ea-9648-a6865daa5314.png)
If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl):
Started on OpenGL, but occurs on both drivers.
Sound driver (directsound, xaudio, openal, SDL):
Started on SDL, but occurs on all drivers.
### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 10 Home
If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):
Not entirely sure what this means, it's version 2.1.4 if that helps?

Sorry if I did this wrong it's my first time writing a post.

**Comment by rkitover** [comment]
Try going to `Help -> Factory Reset`.

**Comment by rkitover** [comment]
And then restart the program.

**Comment by keego123** [comment]
same thing tho i dont know much about this i just got this and im figuring every

**Comment by keego123** [comment]
> same thing tho i dont know much about this i just got this and im figuring every out as i go can any one please help me

fixed it

**Comment by Squall-Leonhart** [comment]
I'm closing this because theres no replication.
