### ISSUE TITLE
error del link del vba-m

### ISSUE THREAD

**Issue by infernoblack** [visualboyadvance-m/visualboyadvance-m#717]
quiero conectarme al link del emulador con un amigo pero senos crashea no nos deja poner ni el server ni el client  que hago

**Comment by infernoblack** [comment]
For those who speak English I put the translation: I want to connect to the link of the emulator with a friend but crashea does not let us put neither the server nor the client that I do

**Comment by rkitover** [comment]
Make sure you are using the nightly and this is a GBA game, GB link is known broken, and GBA link also has some issues with some games.
