### ISSUE TITLE
ffmpeg sound recording only captures right channel

### ISSUE THREAD

**Issue by LAC48** [visualboyadvance-m/visualboyadvance-m#723]
When you record video or sound that is in stereo and then play the saved file it only plays the audio of the right channel.
I tried different sound settings and the same thing keeps happening.

[Example.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/5111759/Example.zip)

**Comment by rkitover** [comment]
Latest nightly has the fix. Thank you for reporting this!
