### ISSUE TITLE
Clarification on CPULoop

### ISSUE THREAD

**Issue by ammrat13** [visualboyadvance-m/visualboyadvance-m#725]
I was looking for clarification on what exactly the `void CPULoop(int ticks)` method in `src/gba/GBA.cpp` does. I would expect that it advances execution by `ticks` instructions. However, it also seems to be doing other stuff with timers, interrupts, SWI, IRQ, and something with `has_frames`, all of which seem to extend how long the CPU is simulated for. I haven't looked too deep into the code, but I'd still like to understand what exactly is going on. Does it guarantee that execution is advanced by exactly `ticks` instructions, and what does all the other logic do in that case?

For context, I'd like to use VBA-M to simulate GBA games headlessly. Ideally, I'd be able to step through tick by tick and see the state of the processor and of RAM at any given point. How might I go about doing this?

### Build details
Version of code (pre-built binary version, or commit ref, or just "master"): `master`

**Comment by rkitover** [comment]
This is the main entry point into the emulator core, it is called by `gbaEmulate(int ticks)` in a loop until frames are produced one level above which is mapped to `emusys->emuMain(int ticks)` by `struct EmulatedSystem` in `src/common/System.h`. This is what we call from the wxWidgets GUI to do one emulation cycle.

`int ticks` is a fixed number set to `300000` in `struct EmulatedSystem GBASystem {}` in `GBA.cpp`.

If you want to see what the best way to control the emulator core without the GUI is, look at the libretro interface in `src/libretro`.

Hope that helps!

**Comment by briansrls** [comment]
Hi @ammrat13 , I'm a little late to this, but I have also been reading this area of code a bit lately.  I found a function in viewers.cpp that looks like this:

```
    void Next(wxCommandEvent& ev)
    {
	(void)ev; // unused params
        CPULoop(1);
        GotoPC();
    }
```

So, like you mentioned, looks like it will advance by 1 ticks.  This function is located in our Debugger viewer class.  

It looks like this viewer has some idea of what you want to do already:

![image](https://user-images.githubusercontent.com/11205878/91811340-386d9d00-ebe4-11ea-8aa6-ec95246ff439.png)

It can step through, tick by tick (via the Next button), and displays some registers, I guess.  Hopefully this section of code and viewer is helpful to you, you can find it in Tools->Disassemble while playing a game.
