### ISSUE TITLE
Input configuration is doubled when 2 controllers are connected

### ISSUE THREAD

**Issue by Steelskin** [visualboyadvance-m/visualboyadvance-m#726]
### Expected behavior

1. Connect 2 XInput controllers on Windows
2. Open Input configuration panel
3. Input one button on one controller.
4. Only one input shows up in the input configuration panel

### Actual behavior

The input configuration panel shows 2 input at the same time. In fact, after configuring, both controllers work as input.

### Steps to reproduce the behavior

See above.

### ROM details
N/A

### Option details

Video driver (simple, opengl): opengl

Sound driver (directsound, xaudio, openal, SDL): SDL

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Windows
Version of code (pre-built binary version, or commit ref, or just "master"): ToT. The issue does not reproduce in v2.1.4.

Any XInput joystick. I tested with 8bitdo controllers in bluetooth and Xbox One controllers with an Xbox One dongle on 2 different machines.

### Additional info

Since the issue does not reproduce in the latest stable build, I am going to try to bisect the issue.

**Comment by briansrls** [comment]
Hi @Steelskin , I am currently rewriting the joystick code to better handle situations like this.  I was not able to repro your issue in my branch, do you want to give it a try?

https://github.com/briansrls/visualboyadvance-m/pull/1  (it's in my fork)

**Comment by Steelskin** [comment]
I am going to try your branch. In the meantime, I have managed to pinpoint the issue to these 2 commits:
* Starting at 02520fb63e97160ef6d46053d744e9085d3e1cf1, only one controller input is accepted.
* Starting at 0577f8afc24b4afba946cbfba683c6b77a11300d, the issue I described starts happening.

**Comment by rkitover** [comment]
@Steelskin thanks, I'm going to do some more work on the joystick code soon, I will try this configuration.

**Comment by Steelskin** [comment]
@rkitover I tested your branch. I can confirm that some of the issues go away with it. Double input is gone but another issue has appeared. I am testing with 2 controllers connected. One is an SF30 Pro, the second is an FC30 Pro.

The SF30 Pro inputs work fine, they appear as `joy0-buttonX`. However, the POV buttons in the FC30 Pro do not register in the UI. Oddly enough the other buttons on that controller show up as `joy65535-buttonX` but they work fine in-game.

I'm happy to give you more detailed information for that controller if you can point me where to look.

**Comment by briansrls** [comment]
@Steelskin thanks for testing.  It looks like you are running issues with the player_index changes I made, the joy65535 looks like an underflow (we use player index -1 to indicate an invalid player index).  I'll look into it to see if I can find any bugs.

Just as a test, could you try the FC30 as a standalone controller (only controller attached), if this works I will play around more with having multiple controllers attached.

**Comment by Steelskin** [comment]
The issue was that the FC30 Pro was connected as DInput and not as XInput, I can confirm everything works great with a build from your branch, otherwise!

**Comment by briansrls** [comment]
Ah ok, I don't actually know much about DirectInput, how are you able to switch between the two?  Maybe I could try testing and see what behavior is like.  I read somewhere that ps4 controllers are using directinput, so I will try that first.

**Comment by briansrls** [comment]
Actually, I was able to reproduce some buggy behavior by having both a ps4 controller and xbox one controller plugged in.  Seems like SDL is not having the behavior I expected, I will try to fix it now.

**Comment by rkitover** [comment]
@briansrls Before you spend too much time on that branch of yours, I should tell you that there is no way I am going to use any of that, I am going to do my own refactor. I appreciate your help debugging all of this, but that code is extremely bad.

**Comment by Steelskin** [comment]
8bitdo controllers offer different modes to connect. I usually just use XInput when connecting to a Windows machine but I must have accidentally set that one for DInput. The issue was that the D-Pad appears as an axis in this mode, which I am guessing it being filtered out by VBA-M.

**Comment by rkitover** [comment]
It may be a hat, and I dropped hat support because modern controllers send button events for hats too, but I can re-add some kind of fallback code for hats.

**Comment by briansrls** [comment]
Hi @rkitover, can you please clarify what you meant by "extremely bad"?

**Comment by Steelskin** [comment]
I was trying to diagnose the issue and it seems to stem from the code behind the `if (do_poll)` block in `sdljoy.cpp`. I am not certain why this block is present in the first place. Is it to get events we may have missed from SDL? It appears that reading events from SDL is enough to proceed and this leads to some "ghost" events from the other controller - maybe an underlying bug in SDL?

I tried removing this block and everything seems to work as expected. I also removed some other code that no longer seemed to have any use and cleaned up gamepad initialization in https://github.com/Steelskin/visualboyadvance-m/tree/multi-gc

I am really not certain this is doing the right thing but everything seems to be working properly so far, at least on the only platform I tested on, Windows. Perhaps some of the code I removed is used on other platforms?

**Comment by rkitover** [comment]
@Steelskin some notes on your code:

- The polling is necessary because SDL does not always handle reconnects of the controller, when I was testing reconnecting my 360 controller, it stopped sending events, while polling still worked. See: https://bugzilla.libsdl.org/show_bug.cgi?id=4886

- The joystick IDs we use for the game are not the same as the SDL joystick IDs, and we only want to open the joysticks that are mapped in the config. That is, if the system has 2 joysticks, and only joystick 1 is in the config, we only open joystick 1, leaving other joystick devices for other apps. While for the input configuration dialog and the accel configuration dialog, we open all system joysticks because we don't know which ones the user wants to configure.

- The timer is necessary when a game is not running or the input or accel config dialog is open. When a game is running, polling is handled in `OnIdle`.

**Comment by Steelskin** [comment]
Thanks for the explanation!

* I see. It does look like the plug/unplug events are not sent properly. I'll try to dig deeper into this.

* I do not believe that is correct. VBA-M does not end up with exclusive access to the gamepad. I just tried this and I can still input being received from other apps. Maybe this is true on other platforms than Windows?

* Okay that makes sense but I believe there is bug related to the use of `jpoll`. AFAICT, it is always active as `IsJoyPollTimerRunning()` was always returning true. This is what prompted me to delete the code. Maybe this and the fact that the joystick IDs are not the same are the root cause of our "double input" bug?

**Comment by rkitover** [comment]
> I do not believe that is correct. VBA-M does not end up with exclusive access to the gamepad. I just tried this and I can still input being received from other apps. Maybe this is true on other platforms than Windows?

Regardless, we do not want to keep any joysticks open that are not configured for input and be receiving events for them.

> AFAICT, it is always active as IsJoyPollTimerRunning() was always returning true.

This was caused by my merging denisfa's background input PR, for some reason he deleted the code that stops the timer, I just put it back in in def5d3e4.

> Maybe this and the fact that the joystick IDs are not the same are the root cause of our "double input" bug?

Polling any number of times would not cause any problems, as SDL events are processed and removed when they come in, and our own wx events are only generated on state changes.

As for the joystick IDs not matching the SDL joystick IDs, that was the issue @briansrls found and was exploring in his branch. I will address this very soon hopefully, I was just taking care of some project related emergencies like the CI being on the fritz again.
