### ISSUE TITLE
Billinear filter does not toggle until you open/close the video plugin menu

### ISSUE THREAD

**Issue by briansrls** [visualboyadvance-m/visualboyadvance-m#727]
### Expected behavior
Bilinear filter should immediately take effect when toggled through the menu.

### Actual behavior
Bilinear filter does not seem to take effect until the video plugin menu opens.  Also, bilinear filter doesn't seem to work with the "Simple" video driver?

### Steps to reproduce the behavior
Toggle bilinear filter.

Video driver (simple, opengl):
opengl

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows

Version of code (pre-built binary version, or commit ref, or just "master"):
master

**Comment by briansrls** [comment]
Probably need to reload something when this option is set, I will look into it.

**Comment by rkitover** [comment]
bilinear filter is only implemented for the OpenGL video driver.

Does toggling the option work with the OpenGL driver currently in effect?

We may want to change the UI for this.

**Comment by briansrls** [comment]
I realized that after you toggle the option in dropdown menu, you then have to go to open the video plugin menu, and then simply hit OK for it to take effect (without changing anything).

If the filter isn't implemented for all video plugins, I think the option should only be present on a plugin to plugin basis in the video plugin menu.

**Comment by rkitover** [comment]
I agree, we should just move it to a checkbox in the video config dialog for OpenGL.

**Comment by negativeExponent** [comment]
(cont from https://github.com/visualboyadvance-m/visualboyadvance-m/pull/736)

basically, its missing a re-init when **Video > Bilinear filter** is changed.

find this, **EVT_HANDLER(Bilinear, "Use bilinear filter with 3d renderer")**

change code to this:
```
EVT_HANDLER(Bilinear, "Use bilinear filter with 3d renderer")
{
    bool curopt = gopts.bilinear;
    GetMenuOptionBool("Bilinear", gopts.bilinear);

    // Prevent reinitializing if there is no change
    if ((curopt != gopts.bilinear) && panel->panel) {
        panel->panel->Destroy();
        panel->panel = nullptr;
    }

    update_opts();
}
```

this will only reinitialized when the value is changed.

**Comment by briansrls** [comment]
Hi @negativeExponent , you're right that this would fix the issue.

However, @rkitover and I discussed moving this option to the video->configure->opengl menu instead.  What do you think about that idea?

**Comment by negativeExponent** [comment]
move it, hide it what ever is needed for the option to be still relevant. I hate option boxes though for common stuff.

removing a feature, does not solve the original issue.

**Comment by briansrls** [comment]
Hi @negativeExponent , I previously thought it was a redundant menu option, but you explained it was not and now I understand.  We should not remove the menu option because it is a separate feature to the texture filtering present in the openGl menu.

I understand the preference for a config option to be more convenient.  If it stays where it is now, I would suggest naming it something else like "Bilinear filter (OpenGL)".  The other option which is to move it to the OpenGL menu.

**Comment by rkitover** [comment]
@briansrls Let's take it one step at a time, test @negativeExponent's fix and open a PR. We need to do a lot of UI cleanup anyway, we can do that as the next step.

**Comment by briansrls** [comment]
Alright, I will save the UI cleanup for another time.  I will fix the basic issue first.
