### ISSUE TITLE
Inconsistent behavior for "Pause when inactive"

### ISSUE THREAD

**Issue by briansrls** [visualboyadvance-m/visualboyadvance-m#730]
### Expected behavior
This is more of a question, I'm not sure what expected behavior should be.  I think windows behavior is buggy, but let's see.

### Actual behavior
On windows, regardless of when "Pause when inactive" is checked/unchecked, the emulator always pauses when the **drop down** menu is opened. The game resumes after you open say the video plugin configuration dialogue, with pause when inactive checked (that's correct).

On Ubuntu, when "Pause when inactive" is checked, Ubuntu never pauses when a dropdown is opened.  However, it does pause when the menu is opened, I'm ok with this.
When it's unchecked, the game never pauses, even when a dialogue is opened.  I think this makes sense too.

I think the inconsistency comes with the Windows drop down menu always pausing the game.  It probably should never pause the game, like on Linux. 

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows/Ubuntu

If using Linux, specify if using xorg or Wayland:
xorg

Version of code (pre-built binary version, or commit ref, or just "master"):
40741580

**Comment by rkitover** [comment]
We are tracking this here:

https://github.com/visualboyadvance-m/visualboyadvance-m/issues/83
