### ISSUE TITLE
SSL Certificate for vba-m.com expired fifteen days ago.

### ISSUE THREAD

**Issue by Asday** [visualboyadvance-m/visualboyadvance-m#733]
Wasn't sure whether to put this here or [website](https://github.com/visualboyadvance-m/website) but seeing as that repo is completely blank, here made more sense.

**Comment by ZachBacon** [comment]
It's fine, seems the auto-renew script I setup with certbot didn't evoke properly. I'll fix that tomorrow.

**Comment by ZachBacon** [comment]
renewed the certs manually, but I definitely need to fix the autorenewal script for systemd.

**Comment by Asday** [comment]
Ballin', cheers for the speedy response.

It looks like [uptimerobot](https://uptimerobot.com/) offer SSL checks in the free tier which might help in future.

Also also, if you're behind nginx, I've hit that issue before.  The cert renewed just fine, but I forgot and/or didn't know that I needed to run `nginx -s reload` to load the new certs.  That's now tacked onto the end of the cronjob.

**Comment by ZachBacon** [comment]
> Ballin', cheers for the speedy response.
> 
> It looks like [uptimerobot](https://uptimerobot.com/) offer SSL checks in the free tier which might help in future.
> 
> Also also, if you're behind nginx, I've hit that issue before.  The cert renewed just fine, but I forgot and/or didn't know that I needed to run `nginx -s reload` to load the new certs.  That's now tacked onto the end of the cronjob.

I'm using a systemd timer script, but chances are I just need to append the nginx reload portion to it. But even though certbot said it didn't need to be renewed, I figured I may as well as force the renewal to be safe.

**Comment by Asday** [comment]
Aye just sounds exactly like a missing `nginx -s reload`.

Catch you on the streets my dude.

**Comment by rkitover** [comment]
I do something like this from cron:

```bash
systemctl stop nginx
certbot renew
systemctl start nginx
```

**Comment by Asday** [comment]
@rkitover consider my solution instead.  It doesn't kill every site served by that `nginx` instance while it works.

If you're hell-bent on stopping `nginx` for some reason, at least change the order to this:

```
certbot renew
systemctl restart nginx
```

**Comment by rkitover** [comment]
I had problems with certbot trying to do a live test on port 80 and dying because nginx owns that port, might be my version of certbot or how I have it configured or something.

**Comment by Asday** [comment]
That's how you configured it - it sounds like you have set up certbot to run its own webserver to serve the ACME challenge files, which makes sense for situations in which you don't have a webserver, for instance if you want an SSL certificate for a game server, or your web server isn't ready _yet_.  It's a stop-gap solution.

As you have a working webserver, you'll want to tell certbot to put the ACME challenge files somewhere _your_ webserver can serve them and not run its own webserver.

Here is an excerpt from one of my `nginx.conf`s which acts as a reverse proxy, but also serves ACME challenge files:

```
server {
	listen 443 ssl http2;
	listen [::]:443 ssl http2;
	server_name "emby.righttobeoffensive.com";

	ssl_certificate      /usr/local/etc/letsencrypt/live/emby.righttobeoffensive.com/fullchain.pem;
	ssl_certificate_key  /usr/local/etc/letsencrypt/live/emby.righttobeoffensive.com/privkey.pem;

	include ssl_params;
	include hsts_params;

	location /.well-known/ {
		root /srv/emby.righttobeoffensive.com/public;
	}

	location / {
		<...>
	}
}
```

To tell certbot to not run its own webserver, use the switch `--webroot` when obtaining a certificate.  For existing certificates, you can edit the renewal configuration [as described here](https://stackoverflow.com/a/39904344/1149933).

**Comment by rkitover** [comment]
Nice, thank you very much for the detailed explanation!

**Comment by rkitover** [comment]
I am actually planning to completely rebuild the server soon, just have been dealing with various emergencies like the CI constantly breaking.

**Comment by Asday** [comment]
It was my pleasure.  If you find yourself with a couple spare bucks, throw them LetsEncrypt's way.  God knows they need 'em.
