### ISSUE TITLE
My audio and game are speeding up without throttle or turbo on

### ISSUE THREAD

**Issue by gayhomoman** [visualboyadvance-m/visualboyadvance-m#735]
Expected behavior 100% Speed sound and gameplay

Actual behavior 200/300% speed sound and gameplay without turbo or toggle on

Steps to reproduce the behavior I have no clue other than the fact i think i pressed turbo mode a bunch of times

ROM details

Which games are affected by the issue (please state if GBA or GB game): Every game i load into vba

Include screenshots of ROM Information (File > ROM Information):
![2020-09-01 22_21_01-1636 - Pokemon Fire Red (U)(Squirrels) (patched) (2) - VisualBoyAdvance-M 2 1 4](https://user-images.githubusercontent.com/70595985/91907322-8a282d00-eca1-11ea-87df-2e1b356818fa.png)

If you are using a BIOS file, please say which one.

Option details

Video driver (simple, opengl): OpenGL

Sound driver (directsound, xaudio, openal, SDL): SDL

Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):Windows 10

**Comment by gayhomoman** [comment]
This is happening on Pokemon roms if that helps at all

**Comment by briansrls** [comment]
Hello, please follow the basic Issue template.  It was presented to you when you first made the issue, and you can find it here:

https://raw.githubusercontent.com/visualboyadvance-m/visualboyadvance-m/master/.github/ISSUE_TEMPLATE.md

Please edit your original post and fill in the details found in this template, it will help us out a lot.

**Comment by gayhomoman** [comment]
> Hello, please follow the basic Issue template. It was presented to you when you first made the issue, and you can find it here:
> 
> https://raw.githubusercontent.com/visualboyadvance-m/visualboyadvance-m/master/.github/ISSUE_TEMPLATE.md
> 
> Please edit your original post and fill in the details found in this template, it will help us out a lot.
 
Done

**Comment by briansrls** [comment]
Thanks, could you first try 

```
About->Factory Reset
```

It will reset your emulator to default settings.  Then, restart the emulator.

**Comment by gayhomoman** [comment]
Thanks so much!!! it worked first try

**Comment by briansrls** [comment]
That's good, please be mindful of if/when it happens again.  If it does, try to note the steps you took to reproduce the issue, and we will try to fix it.

**Comment by SearPigeon95** [comment]
Excuse me, so I saw this post, and I have the same problem. I couldn't find no factory reset button on my emulator.

**Comment by ZachBacon** [comment]
> Excuse me, so I saw this post, and I have the same problem. I couldn't find no factory reset button on my emulator.

Then you're using an older version that's not supported anymore
