### ISSUE TITLE
Key gets stuck when pressed down.

### ISSUE THREAD

**Issue by OnlineOliver** [visualboyadvance-m/visualboyadvance-m#739]
### ROM details

Which games are affected by the issue (please state if GBA or GB game): Every GBA and GB game
Which games, if any, are NOT affected by the issue (please state if GBA or GB game): none
Include screenshots of ROM Information (File > ROM Information):

If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Windows

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

**Comment by rkitover** [comment]
Have you tried a nightly?

**Comment by rkitover** [comment]
Also is this on the keyboard or with a joystick? What version of vbam is this?
