### ISSUE TITLE
Pause while inactive is not working.

### ISSUE THREAD

**Issue by GiladPellaeon** [visualboyadvance-m/visualboyadvance-m#743]
### Expected behavior
Expected GBA to accept inputs while not the main selected item.
### Actual behavior
Does not.
### Steps to reproduce the behavior
Boot Crystal Chronicles, cannot use two GBAs at the same time despite different keybindings.
### ROM details
gba_bios.bin
### Build details
Latest
Windows 10

**Comment by rkitover** [comment]
Try the nightly please.

**Comment by rkitover** [comment]
Sorry, the nightly server was down, try again.
