### ISSUE TITLE
VBA-M Steam Editon?

### ISSUE THREAD

**Issue by Kein** [visualboyadvance-m/visualboyadvance-m#744]
Apparently someone added VBA-M on Steam (along with bunch of other emus):
https://steamdb.info/app/1227455/history/
 ¯\\\_(ツ)\_/¯

**Comment by ZachBacon** [comment]
Well that's not supported by us at all.

**Comment by ZachBacon** [comment]
the only supported version on steam we have is when retroarch launches, I gave explicit permission to use the libretro core of vba-m as free dlc for it. So it could be related to that.

**Comment by Kein** [comment]
Ah yes, this is retroarch:
https://steamdb.info/app/1118310/dlc/
