### ISSUE TITLE
Improve wxSDLJoy handling of controllers.

### ISSUE THREAD

**Issue by Steelskin** [visualboyadvance-m/visualboyadvance-m#745]
Following #742, there is still room for improvements in the way `wxSDLJoy` handles controllers, especially reconnects.
Currently, we do not have a good way to ensure a reconnected joystick is going to be the same as the previous one. In addition, usage of `wxSDLJoyEvent` could be improved by abstracting what is referred to as the `player_index`. The latter should really be treated as an abstract key that refers to a joystick. The tricky part is matching that key back to a joystick in a future session or in case of a reconnect.

High-level summary of things that were discussed on PR #742:
* Keep a map of joystick keys to active joysticks. Or more simply a vector of joysticks where the index corresponds to a joystick key if we simply use an integer.
* Make use of the `*PlayerIndex` API in SDL. This is going to require updating SDL, maybe linking statically against it on all platforms to avoid weird conditional blocks.
* Abstract the `player_index` value in `wxSDLJoyEvent` into a `wxSDLJoyKey`. This is going to require refactoring of all the classes that use it.

Select quotes:
@briansrls said
> This is correct. I would actually argue we should not use the SDL joystick index at all past the initially connection. I don't think storing them is valuable to us.
>
>For example, in my implementation I was thinking the player_index should be managed as follows:
> We have a maximum of N players (say, 4 players). We have a simple boolean array of length 4:
>
> [false, false, false, false]
>
> This indicates to us if we have any players active on that player_index. Now, we connect the first controller, it has SDL index 0, instance ID 1. We assign it to player_index 0 using SDL_GameControllerSetPlayerIndex.
> 
> [true, false, false, false]
>
> Now, we accept another controller connection. Our second player is SDL index 1, instance ID 2. We look at our map, and determine that player_index 1 is available. We set this controller to player_index 1 using SDL_GameControllerSetPlayerIndex.
>
> [true, true, false, false]
> 
> Now, say player 1 disconnects. Sure, the SDL indexes will be sliding around. Player 2's SDL index will slide from index 1 to index 0, like you described. However, it will still have player_index 1. This should be the source of truth, along with its instance ID.
>
> After player 1 disconnects, we clear that hole in our table:
>
> [false, true, false, false]
>
> Now, whatever controller connects next, will get player_index 0, and fill the hole we created.
> 
> [true, true, false, false]
>
> So, my idea is to ditch SDL index immediately, set a self determined player index via SDL_GameControllerSetPlayerIndex and SDL_GameControllerGetPlayerIndex to avoid sliding controllers. This is basically a very rudimentary controller port system, like on a console. The only downside to this is that we have no concept of tracking controllers through disconnects, so technically if both player 2 and player 1 disconnect, they could swap depending on the order they reconnect in.

@rkitover said
> One thing you may not have known, is that the SDL API wiki is not up to date, if you click on the header files there is more stuff there.
> 
> Now to @briansrls's point that we should use `player_index`, we can probably do that.
> 
> This is the API for `player_index`:
> 
> ```c
> extern DECLSPEC SDL_GameController *SDLCALL SDL_GameControllerFromPlayerIndex(int player_index);
> extern DECLSPEC int SDLCALL SDL_GameControllerGetPlayerIndex(SDL_GameController *gamecontroller);
> extern DECLSPEC void SDLCALL SDL_GameControllerSetPlayerIndex(SDL_GameController *gamecontroller, int player_index);
> 
> extern DECLSPEC int SDLCALL SDL_JoystickGetDevicePlayerIndex(int device_index);
> extern DECLSPEC SDL_Joystick *SDLCALL SDL_JoystickFromPlayerIndex(int player_index);
> extern DECLSPEC int SDLCALL SDL_JoystickGetPlayerIndex(SDL_Joystick * joystick);
> extern DECLSPEC void SDLCALL SDL_JoystickSetPlayerIndex(SDL_Joystick * joystick, int player_index);
> ```
> 
> I'm not sure what version of SDL is required for this, but we may be able to fall back to using `device_index+1` on older versions.
> 
> Here's my proposal for the design:
> 
> * On connect events, call `SDL_JoystickGetDevicePlayerIndex(int device_index)`, if it's `-1`, check what is the first available index in the set, and if it matches a requested index from the GUI call `SDL_JoystickSetPlayerIndex()` with the new index.
> * The `requested_sdl_indexes_` map would become `requested_player_indexes_`. We wouldn't use the `device_index` at all, except for getting the `player_index`.
> * `RemapControllers()` would no longer be necessary, since we would be managing the `player_index` through the API.

@rkitover said
> @briansrls described exactly the design I was thinking of above for `player_index`, except we can't limit the map to 4 controllers because during input configuration or accel configuration we have to accept input from all available controllers, and we store the `player_index` in the config for one of the 4 logical GBA controllers.
> 
> I think we're on the same page here.

@briansrls said
> Maybe this even could all be done internally? For example, to avoid issues with compatibility, we could just store a private variable called "virtual_player_index".
> 
> We never call SetPlayerIndex, or GetPlayerIndex, and just ignore index and player_index. We only deal with instance_id and virtual_player_index.
>
> We then instead of maintaining a bool array, we maintain an array like:
>
> vector<wxSDLJoy*> player_index_array, where the index corresponds to our virtual_player_index. We can set the values to NULL or to a valid SDLJoy object depending on who owns that index.
>
> I guess I'm even questioning the need to mess with the SDL api. I think we need a reliable way to preserve our ordering internally, and to map that ordering to instance IDs. I think we can do that even without the API.
>
> This thought is mostly out of my desperation to avoid the handling of different versions of the API. Maybe it won't matter.

**Comment by Steelskin** [comment]
I have spent some time over the past few days looking into this. I believe we would be better off with a much larger refactor changing the way we handle keyboard input, joystick events and accelerators and game keys. I believe we can handle all of this in a uniform manner. First, a few notes on what I have noticed in the codebase:
* It seems we do not actually make use of `wxAcceleratorEntry`, other than as a holder type since handling of accelerators is apparently buggy in wxWidgets. Handling of accelerator input is performed in `MainFrame::FilterEvent()` in `wxvbam.cpp`. In here, we use the `GetCommand()` to initialize a `wxCommandEvent` and send it to the wxWidgets event handler, which will eventually call the event handler. If I understand the code correctly, the code in `MainFrame::FilterEvent()` will filter the event so it is not sent to any other handler if it corresponds to an accelerator.
  * The returned values in `MainFrame::FilterEvent()` are incorrect, per the [`wxEventFilter::FilterEven()` documentation](https://docs.wxwidgets.org/3.0/classwx_event_filter.html#ae9aee87e6c6c7ff3df84e46a2e3b2c6a). I'll submit a PR to fix this.
  * This parses through the entire accelerators list, which is O(n) with a worst case scenario of n. With a map of "user control" to "command", we could lower this to O(log(n)).
* Game keys are handled in `panel.cpp` in the logic that starts from one of these handlers: `OnKeyDown()`, `OnKeyUp()` and `OnSDLJoy()`, corresponding to keyboard press down, keyboard press up and joystick event, respectively. This then goes through several steps:
  * The values from each of these handlers are then converted to a series of numbers:
    * `joy` corresponds to the joystick number, of `player_index`. Set to 0 for keyboard.
    * `key` corresponds to the key for a keyboard event or the `control_index` for a joystick event.
    * `mod` corresponds to a modifier key for a keyboard event (ctrl, alt...) or a "special" value depending on the control type for joysticks, this conversion is handled in `wxJoyKeyTextCtrl::DigitalButton()` for joysticks.
    * `down` a boolean value set to true when the event correponds to a key or button down press.
  * All of this boils down to converting the event into something that can be handled in a uniform manner with an on/off toggle. There is some special logic in the joystick handling to "unpress" the other end of the axis or the other directions of a HAT 
  * Once this conversion is done, the event is processed in `process_key_press()` in `panel.cpp`. The wxWidget frontend keeps track of all of the currently pressed keys in a global `keys_pressed` vector. This vector is parsed to figure if the currently pressed key is already registered as being pressed. The index for the corresponding key in the `keys_pressed` vector is stored in `kpno`. This is set to `keys_pressed.size()` if the event corresponds to a new key being pressed.
  * The next step is gathering the corresponding game keys being pressed for this event. This is done in `game_keys_pressed()` in `panel.cpp`. The `game_keys` vector is populated with the corresponding game keys being pressed - a user control event can be assigned to multiple game keys. This is O(n) for the total number of key bindings (4 players x 21 keys per player x bindings per key).
    * Note: The user game keys bindings are stored in the global `gopts.joykey_bindings` vector.
  * Double-down or double-release are ignored and this function returns early here.
  * `keys_pressed` is updated (O(1) on insertion, O(n) on deletion)
  * Finally, the state of the emulator keys is updated. This is tracked in the global `joypress` vector, which has 4 bit masks (one per player) corresponding to the state of the currently pressed game keys - one bit per key. Here, we differentiate 2 cases:
    * The key is pressed (`down` is true). The `joypress` value for that game key is updated (O(1))
    * The key is released (`down` is false). In this case, the release must only be registered if no other binding for the current game key is being pressed. For instance, if the emulated game key for the A button is mapped to keyboard keys Z and X, if the players presses both Z and X, the release must only be registered when both Z and X are released. In practice, this is done by parsing all of the bindings associated with the current game key and checking the state of `keys_pressed` again, at which point we are in O(n^2).
* Last part, user configuration and conversion from and to string for a given "user control". This is largely handled in the `wxJoyKeyTextCtrl` and `wxKeyTextCtrl` classes, which derived classes from `wxTextCtrl` that convert a joystick or keyboard input into a localized string, which is also used in the ini configuration. This class also has a number of static methods to handled conversion from the ini file in other parts of the codebase.
  * It seems `wxKeyTextCtrl` is never used directly and could probably be removed in favor of a single `wxUserTextCtrl` class.

With that out of the way, here is a high-level overview of how I believe we could refactor things so we can make things faster and easier to parse:
* Move the "ghost events" for joystick handling in `wxSDLJoy`. Let's go one step further and change the `wxSDLJoyEvent` class so it is directly usable with no further conversions in the rest of the codebase. It is awkward to go through an extra step before the event can be properly processed.
* Abstract `player_index` into a `wxJoystick` class that is a fancy wrapper for an integer. This should also take care of converting between a `wxJoystick` and a string like `"Joy1"`.
  * `wxJoystick` should implement comparison operators so it can be used as a key.
* Add a common user control class for both joystick and keyboard events, `wxUserControl`.
  * `wxUserControl` should be POD keeping track of what we currently use as key, mod and joy. It does not keep track of the "pressed" status. Note that key, mod and joy should not be accessible as part of the API and that users should rely on comparison with other `wxUserControl`.
  * `wxUserControl` should implement comparison operators so it can be used as a key for maps and quick access (O(log(n)) in a set.
  * `wxUserControl` can be converted to and from string and can have a `wxJoystick` if the control corresponds to a joystick control. This allows easy tracking of active joysticks.
  * Proposed API:
```c++
class wxUserControl {
public:
    // The device type for a user control.
    enum class Device {
        Invalid = 0,
        Keyboard,
        Joystick,
        Last = Joystick
    };

    // Invalid wxUserControl, used for comparison.
    static wxUserControl Invalid();

    // Build from an OnKeyDown() event.
    static wxUserControl FromKeyDown(const wxKeyEvent& event);

    // Build from an OnKeyUp() event.
    static wxUserControl FromKeyUp(const wxKeyEvent& event);

    // Constructor from a wxSDLJoyEvent, sets |pressed|.
    static wxUserControl FromJoyEvent(const wxSDLJoyEvent& event, bool* pressed);

    // Constructor from a configuration string. Returns wxUserControl::Invalid() on failure to parse.
    static wxUserControl FromString(const wxString& string);

    // Converts to a configuration string. Computed on first call, and cached for further calls.
    wxString ToString();

    Device device();

    // Returns wxJoystick::Invalid() if device() is not Device::Joystick.
    wxJoystick GetJoystick();
[...]
};
```
* Accelerators tracking:
  * Keep a map of `wxUserControl` to `command`.
  * Keep the handling in `MainFrame::FilterEvent()`, the logic becomes O(log(n)).
* Game keys tracking:
  * Add a `wxGameControl` class. This will correspond to a single control in the emulated gamepad. (e.g. "player 1 button A"). This implements comparison operators for use in a set.
  * Keep a map of `wxUserControl` to a set of `wxGameControl`. This is the user configuration, replacing `gopts.joykey_bindings`.
  * Keep the list of currently pressed `wxUserControl` as a set. Lookup, insertion and deletion are now all O(log(n)).

This is quite a bit of work so I propose doing it in multiple steps in order to move slow and break nothing:
* Add `wxJoystick` and convert all call sites. This class can give access to the underlying `player_index()` for the duration of the transition.
* Add `wxUserControl` as described above.
* Convert all event handlers one by one. This can be done in parallel since there are multiple use cases.
* At the same time, we can also modify `wxSDLJoyEvent` so its API is more in line with how events are used, generating "ghost" key-up events as needed for hats and axis changes.
* Remove all of the transitional stuff.

With all this, we completely side-step the issue of handling `player_index` since it is abstracted in the `wxJoystick` class, which we can always modify later to better "tag" a unique controller.

**Comment by nrkramer** [comment]
FYI: http://forums.libsdl.org/viewtopic.php?p=20126

It might be feasible to correlate Gamepads to a unique identifier provided by the operating system instead, which would eliminate the "sliding controller" issue (which is really just SDL allocating controller devices on a stack).

**Comment by Steelskin** [comment]
I consider this done as it is. Input handling has been entirely refactored.
