### ISSUE TITLE
aaaaaaaaaaaaa

### ISSUE THREAD

**Issue by w2ef3hghdg** [visualboyadvance-m/visualboyadvance-m#749]
### ROM details

Which games are affected by the issue (please state if GBA or GB game):

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

Include screenshots of ROM Information (File > ROM Information):

If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

**Comment by ZachBacon** [comment]
If you can't describe your issue with visualboyadvance-m, I'm going to have to close this issue until you edit your issue with the relevant data.
