### ISSUE TITLE
missing sound channels when doing a quick save with the shift+ F1 key or chaging the volume settings in Game Boy Advance

### ISSUE THREAD

**Issue by Cibomatto2002** [visualboyadvance-m/visualboyadvance-m#75]
### Expected behavior
No sound bug
### Actual behavior
Sound bug when changing volume in Game Boy Advance

### Steps to reproduce the behavior
change the volume in the sound settings

### Build details
VisualBoyAdvance-M-WX-2.0.0-beta2

Operating System (Windows, Mac, Linux, etc.):
Windows 10 64 bit

Interface (wx, SDL, default is wx):
WX

Version of code (pre-built binary version, or commit ref, or just "master"):
Master

Any other relevant build information:
No

If this is e.g. a joystick or video issue, then the relevant hardware information:

Here's a video I made of how it sounds.

https://www.youtube.com/watch?v=k1YBahl3PqA&feature=youtu.be

**Comment by Cibomatto2002** [comment]
Just got the latest visualboyadvance-m-x86_64-Release-and-Debug.7z with the Keyboard fixes and the bug is still there.

**Comment by Cibomatto2002** [comment]
Playing around with the emulator somemore and to here the sound bug just do a save with the shift+F1 key then Reload the save you will here the sound bug.

**Comment by rkitover** [comment]
@Cibomatto2002 I looked at your youtube video, and I don't understand I'm sorry, can you please describe what you mean by "sound bug". What is actually wrong with the sound and what is it supposed to sound like.

**Comment by Cibomatto2002** [comment]
It sounds like some of the channels are not playing. Here is another bug i found if you load the game with the F1 key it will distorted graphics and will not load correct. here is a video of it.

https://www.youtube.com/watch?v=EEX8v6sPXRU

I will upload my quick save file maybe it will help you.
[Castlevania - Harmony of Dissonance (USA)-01.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/809725/Castlevania.-.Harmony.of.Dissonance.USA.-01.zip)

**Comment by rkitover** [comment]
Ok, so missing channels, may be related to #91.

**Comment by Cibomatto2002** [comment]
They only miss when loading a quick save in some games the quick save then reload with quick load will lock up same games. it's not related to #91.

**Comment by retro-wertz** [comment]
this should be fixed in latest commit, reopen if its still the same issue.
