### ISSUE TITLE
missing version numbers on macOS in 2.1.6

### ISSUE THREAD

**Issue by core-code** [visualboyadvance-m/visualboyadvance-m#750]
i've downloaded version '2.1.4' but when selecting it in the Finder, no version number is displayed

the CFBundleVersion and CFBundleShortVersionString entries in the Info.plist file are missing

**Comment by briansrls** [comment]
Hello,

Could you please leave some more details?  Are you using macOS?  It sounds like in Finder there is a column for displaying the version number, we used to display something, and recently it stopped displaying the version?  Could you also show us where you downloaded it from?

**Comment by core-code** [comment]
> Could you please leave some more details?

sure

>  Are you using macOS? 

yes, as the title of the bug report says

> It sounds like in Finder there is a column for displaying the version number,

yes, the Finder can display version numbers of apps in its Get Info, Quick Look and Column View displays

> we used to display something, and recently it stopped displaying the version

no it is not a regression. all macOS apps are supposed to have version numbers though

> Could you also show us where you downloaded it from?

i've downloaded it from https://github.com/visualboyadvance-m/visualboyadvance-m/releases/download/v2.1.4/visualboyadvance-m-Mac-64bit.zip

**Comment by core-code** [comment]
here are screenshots illustrating how it doesn't have version numbers and other apps have them



<img width="251" alt="Screenshot 2020-09-14 at 12 58 52" src="https://user-images.githubusercontent.com/1261954/93078115-34cd2200-f68a-11ea-91f2-d36ccf10d789.png">
<img width="265" alt="Screenshot 2020-09-14 at 12 58 15" src="https://user-images.githubusercontent.com/1261954/93078117-37c81280-f68a-11ea-8c8f-f5353f4f7e83.png">

**Comment by core-code** [comment]
the problems stems from these entries in your Info.plist file:

```
	<key>CFBundleShortVersionString</key>
	<string></string>
	<key>CFBundleVersion</key>
	<string></string>
```


these aren't supposed to be empty but supposed to contain '2.1.4'

**Comment by rkitover** [comment]
Thank you this will be fixed.

**Comment by rkitover** [comment]
Apparently we are already writing `CFBundleVersion` since denisfa's Sparkle changes, I also added `CFBundleShortVersionString` just now.

**Comment by core-code** [comment]
thanks!

**Comment by core-code** [comment]
please reopen. this is NOT fixed in the 2.1.5 release. it still doesn't contain any version numbers, neither CFBundleVersion nor  CFBundleShortVersionString.

**Comment by rkitover** [comment]
I'll take a look.

**Comment by core-code** [comment]
not fixed in 2.1.6 either

**Comment by ZachBacon** [comment]
Feel free to submit a fix

**Comment by rkitover** [comment]
I'm going to redo the mac binaries for 2.1.6 with notarization and I will take a look at this then, I forgot about it sorry.

**Comment by core-code** [comment]
awesome, thanks :)

**Comment by rkitover** [comment]
Updated the mac binaries with version numbers.

I still need to update them again later to add the stapled notarization ticket.

**Comment by rkitover** [comment]
The nightlies will also be versioned with a short sha suffix.

**Comment by core-code** [comment]
thanks! confirmed fixed

**Comment by rkitover** [comment]
I've replaced the release binaries again with notarized and stapled ones, these should pass gatekeeper.

**Comment by core-code** [comment]
thanks!
