### ISSUE TITLE
turbo mode bug

### ISSUE THREAD

**Issue by kyoxexe** [visualboyadvance-m/visualboyadvance-m#762]
### ROM details

Which games are affected by the issue (please state if GBA or GB game):

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

Include screenshots of ROM Information (File > ROM Information):

If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

**Comment by rkitover** [comment]
What problem are you having, please try the nightly from http://win.vba-m.com/nightly

**Comment by Squall-Leonhart** [comment]
Options > General > Throttle: 100%

Duplicate of #816
