### ISSUE TITLE
wierd screen glitch in pokemon emerald.

### ISSUE THREAD

**Issue by marcel89757** [visualboyadvance-m/visualboyadvance-m#770]
### Expected behavior
screen works normally.
### Actual behavior
every few steps my screen becomes all wierd and pixelated.
### Steps to reproduce the behavior
i dont know, it just happens.

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
i only played pokemon blue and emerald and i only saw this issiue on pokemon emerald.
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
pokemon blue and probably more.
Include screenshots of ROM Information (File > ROM Information):
![image](https://user-images.githubusercontent.com/73756987/97787336-bd0f7400-1bb1-11eb-8c57-dfeca416d787.png)

If you are using a BIOS file, please say which one.
i dont know what a BIOS file is but i dont think so.
### Option details

Video driver (simple, opengl):
the glich happens on both of them(i normally use opengl).
Sound driver (directsound, xaudio, openal, SDL):
SDL
### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Window 10, slovenia  

Version of code (pre-built binary version, or commit ref, or just "master"):
i dont know where to find this information

![image](https://user-images.githubusercontent.com/73756987/97787429-6c4c4b00-1bb2-11eb-9061-885d7df21d83.png)
this is the screenshot of the bug

**Comment by rkitover** [comment]
Please try the nightly from http://win.vba-m.com/nightly

**Comment by marcel89757** [comment]
> Please try the nightly from http://win.vba-m.com/nightly
i tested out this version and i played around for a bit with the glich still happening and my pokemon just died for no reason and i whited out. after i respawn the glitch is gone. my pokemons where all healed up when i last used them in the battle tent where your pokemon get healed automaticly after you win/lose . 
thanks for the help.

**Comment by piggyboy183** [comment]
I know this question was asked a year ago, but I did some testing and found that it just means that one of your Pokémon has a status effect, such as poison or burn. Every time the screen goes pixelated is when the Pokémon took damage. This is why your Pokémon eventually fainted. I hope this helps anyone else who searched the problem up.
