### ISSUE TITLE
I'm using  VBA-M 2.1.4  and my L and R keys don't do a thing

### ISSUE THREAD

**Issue by SpyrosKo** [visualboyadvance-m/visualboyadvance-m#772]
### Expected behavior
I was expecting my keyboard shortcuts for the L and R buttons to work.
### Actual behavior
When I press my keys (V and B) the keys don't work.
### Steps to reproduce the behavior
I have tried to set different keys but those don't work either.

### ROM details

###Which games are affected by the issue (please state if GBA or GB game):

GBA game, Final Fantasy VI

###Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

Include screenshots of ROM Information (File > ROM Information):

If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl):
Opengl

Sound driver (directsound, xaudio, openal, SDL):
SDL

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 10

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

**Comment by ZachBacon** [comment]
Please test if this issue persists with a nightly build https://win.vba-m.com/nightly/

**Comment by SpyrosKo** [comment]
Thanks! I downloaded
14484189 visualboyadvance-m-Win-64bit.zip
and that worked.
