### ISSUE TITLE
Music is stuck when "Pause when inactive" is enabled and focus is lost

### ISSUE THREAD

**Issue by msmigiel** [visualboyadvance-m/visualboyadvance-m#78]
### Expected behavior

The music/sound should be muted when focus is lost and "Pause when inactive" is enabled.

### Actual behavior

The music/sound is stuck at the same few notes which is very jarring.

### Steps to reproduce the behavior

1.) Load a game.
2.) Enable Emulation -> Pause when inactive
3.) Have the game window not be maximized and ensure the game is playing some music.
4.) Click on something else so that the game window is no longer in focus.
5.) Note the stuck music.

### Build details

Operating System (Windows, Mac, Linux, etc.): Windows

Interface (wx, SDL, default is wx): wx? I think

Version of code (pre-built binary version, or commit ref, or just "master"): VisualBoyAdvance-M Git

Any other relevant build information:

If this is e.g. a joystick or video issue, then the relevant hardware information:

**Comment by ZachBacon** [comment]
This was fixed in master https://github.com/visualboyadvance-m/visualboyadvance-m/issues/45
Just need to compile a new release soon. However the version, did you download that from here or did you compile your own copy?

**Comment by msmigiel** [comment]
Thanks for the update, I'm glad to see it's fixed. A while ago I posted my issue to the forum [here](http://vba-m.com/forum/thread-1542.html) but after a while I forgot about it. 

I've been looking hard for a new-ish version for Windows but couldn't find one - the latest one I found was "VisualBoyAdvance-M-WX-2.0.0-beta2.7z". Do you know when you will be releasing current builds for Windows?

**Comment by ZachBacon** [comment]
https://github.com/visualboyadvance-m/visualboyadvance-m/releases Right here on github. We've been moving infrastructure to github and away from sourceforge.
