### ISSUE TITLE
LZ77 Decompression difference from official BIOS

### ISSUE THREAD

**Issue by endrift** [visualboyadvance-m/visualboyadvance-m#789]
### Expected behavior

The LZ77 decompression routine in the HLE BIOS implementation matches the behavior of hardware.

### Actual behavior

The LZ77 decompression routine has an early termination case that does not exist on hardware, leading to (rare) cases of decompressed data getting truncated.

### Steps to reproduce the behavior

The window copy routine for compressed blocks contains an early termination case that does not exist in the hardware implementation.

See here:
https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/src/gba/bios.cpp#L713
https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/src/gba/bios.cpp#L787

While this does lead to a buffer overrun, but this same overrun happens on hardware too. An example of a visible difference is byte 0x02004003 differing during the opening cutscene of Advance Wars. Several of these compressed images have this issue, so they wind up being slightly longer than the declared size. In this instance, on hardware that byte winds up being 0x70 after it decompressed the graphics during the letter-by-letter flash at the end of the intro (but before loading the title screen); in VBA-M, this early termination leads to it being 0x00 instead.

I don't know offhand of any games _seriously_ affected by this, but it is a bug I know does affect games to some extent.

### ROM details

Which games are affected by the issue (please state if GBA or GB game): Several GBA games that use LZ77, such as Advance Wars

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):  Games that don't use LZ77, and most that do only have properly compressed data.

Include screenshots of ROM Information (File > ROM Information):

![image](https://user-images.githubusercontent.com/605502/101269485-29871100-3724-11eb-9e09-bb7ad2f501ef.png)

Only the internal HLE BIOS is affected.

### Option details

Video driver (simple, opengl): Irrelevant

Sound driver (directsound, xaudio, openal, SDL): Irrelevant

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Irrelevant

If using Linux, specify if using xorg or Wayland: Irrelevant

Version of code (pre-built binary version, or commit ref, or just "master"): master

**Comment by endrift** [comment]
Sorry for the incomplete initial report, I accidentally it shift-enter while typing it up which submitted it while I was still composing it...

**Comment by rkitover** [comment]
@endrift Advance Wars is my primary use-case for this software, so I will definitely make this a high priority, I can use the new unit test functionality I added with doctest to do this too.

**Comment by Squall-Leonhart** [comment]
This is the cause of several Shrek games failing to boot.
