### ISSUE TITLE
Remember window's size/state/position upon restart

### ISSUE THREAD

**Issue by msmigiel** [visualboyadvance-m/visualboyadvance-m#79]
### Expected behavior

It would be nice to have the application remember its size, state (whether maximized or not), and position upon being restarted. Please consider adding this, at least as an option.

### Actual behavior

The application defaults to a specific size and state and a somewhat random position.

### Steps to reproduce the behavior

1.) Load the application.
2.) Change the size/state/position from the default.
3.) Close and reopen it.
4.) Note the default settings are used.

### Build details

Operating System (Windows, Mac, Linux, etc.): Windows

Interface (wx, SDL, default is wx): wx

Version of code (pre-built binary version, or commit ref, or just "master"): 6ecab80.... (released 2/2/17)

Any other relevant build information:

If this is e.g. a joystick or video issue, then the relevant hardware information:

**Comment by ZachBacon** [comment]
You're opening a lot of issues that are related to each other. Open one with everything you find next time if it's related to issues like this.

**Comment by msmigiel** [comment]
I'm sorry. I don't understand how these issues are related and I thought it would be easier to track them separately, but if you would prefer I will open one issue going forward.

**Comment by ZachBacon** [comment]
@msmigiel It's because they are all related to configuration changes a while back which also affect various things you are reporting on. So they are all related.

**Comment by denisfa** [comment]
@rkitover This can be closed too, right?

**Comment by rkitover** [comment]
Yes. Implemented by @denisfa in master.

**Comment by rkitover** [comment]
@denisfa so this doesn't work yet, when you start the emu with a ROM it first switches to the remembered size then shrinks back to the default size, can you please take a look if and when you have a chance?

**Comment by retro-wertz** [comment]
core will  resize based on default magnification size and will not use
remembered size....

**Comment by rkitover** [comment]
Pretty sure this has nothing to do with the core, the core only calls `systemDrawScreen()` see `src/wx/sys.cpp` for the interface to the core.

**Comment by denisfa** [comment]
@rkitover I know how to fix this. I will offer a quick solution in a moment.
