### ISSUE TITLE
"Automatically Save/Load Cheats" not persisted between restart

### ISSUE THREAD

**Issue by msmigiel** [visualboyadvance-m/visualboyadvance-m#80]
### Expected behavior

This setting should be persisted between restarts.

### Actual behavior

If you enable this setting and restart the application, it is no longer enabled.

### Steps to reproduce the behavior

1.) Launch the application and enable "Automatically Save/Load Cheats".
2.) Note that it is now checked/enabled.
3.) Restart the application.
4.) Note that it is no longer checked/enabled.

### Build details

Operating System (Windows, Mac, Linux, etc.): Windows

Interface (wx, SDL, default is wx): wx

Version of code (pre-built binary version, or commit ref, or just "master"): 6ecab80... (released 2/2/17)

Any other relevant build information:

If this is e.g. a joystick or video issue, then the relevant hardware information:

**Comment by ZachBacon** [comment]
This feels more close to the issue #66

**Comment by Squall-Leonhart** [comment]
unrelated to 66, the pref is written to file  but not read back on start.
