### ISSUE TITLE
not all key assignments work when re-mapping key shortcuts, i.e. +, _, numpad+, numpad- ect...

### ISSUE THREAD

**Issue by budafuko** [visualboyadvance-m/visualboyadvance-m#802]
the title says it all. 

normally i would just use ds4windows to make the key assignments work mostly how i want them but because of a separate bug affecting connectivity while using ds4windows this is not a viable option

thank you for an amazing emulator

**Comment by rkitover** [comment]
Are you testing with the nightly?
