### ISSUE TITLE
crash with filter and interframe blending after windows update

### ISSUE THREAD

**Issue by budafuko** [visualboyadvance-m/visualboyadvance-m#805]
every game crashed after installing latest windows update along with latest intel hd driver for my secondary gpu (not sure the culpret)

EASY FIX

i was using the 6x filter and frame bending, i turned these off and restarted the rom
the rom started
i was then able to re-enable the filter and frame bending with no problem

(CHEERS)

**Comment by budafuko** [comment]
actually it does work however starting in full screen doesn't always work. sometimes i get a black screen when trying it. this is why i thought it was not working after removing the filter and re applying it

**Comment by budafuko** [comment]
i was wondering if you could help me with something afterall.. i noticed my vba.ini file is located in my roms folder. is there any way to move it to my vba folder?

**Comment by rkitover** [comment]
Normally your config file is in `%LOCALAPPDATA%\visualboyadvance-m`. You can go to `Help -> Factory Reset` to delete the current config file and restart.

**Comment by Squall-Leonhart** [comment]
strange behavior, the video device is not stored in the cfg file at all is it @rkitover
