### ISSUE TITLE
Minish Cap

### ISSUE THREAD

**Issue by ggezpz** [visualboyadvance-m/visualboyadvance-m#809]
Minish cap freezes with VBA at the first tornado in the Dark Hyrule dungeon.  See, e.g., https://gbatemp.net/threads/desperate-for-minish-cap-save-file.220019/

The game seems to run fine in 1.8.0-beta 3.  But in newer versions it seems to crash the game.

**Comment by Squall-Leonhart** [comment]
I need a save state  or battery.

**Comment by Squall-Leonhart** [comment]
Fixed by #807

**Comment by Squall-Leonhart** [comment]
I've got a reproduction, op is using an ancient svn release (1206).
