### ISSUE TITLE
Please consider adding support for Action Replay codes

### ISSUE THREAD

**Issue by msmigiel** [visualboyadvance-m/visualboyadvance-m#81]
### Expected behavior

Please consider adding support for Action Replay codes. If there is an existing way to do this, please make it more easier to find and/or document it.

### Actual behavior

When I go to List Cheats and try to add one, I only see options for GameShark and GameGenie.

### Steps to reproduce the behavior

NA

### Build details

Operating System (Windows, Mac, Linux, etc.): Windows

Interface (wx, SDL, default is wx): wx 

Version of code (pre-built binary version, or commit ref, or just "master"):  6ecab80... (released 2/2/17)

Any other relevant build information:

If this is e.g. a joystick or video issue, then the relevant hardware information:

**Comment by ZachBacon** [comment]
It's already implemented, you just input the codes as you would a gameshark or gamegenie code. Just it's called codebreaker
![untitled](https://cloud.githubusercontent.com/assets/8948676/23103105/6a64ae5c-f683-11e6-8a99-4e121d472647.png)

**Comment by msmigiel** [comment]
Thank you for the information. I'm not familiar with CodeBreaker - is that the same thing as ActionReplay? If so, would it be more intuitive to the end user to change the menu entry to something like "CodeBreaker/ActionReplay" to avoid confusion?

I did try this one earlier but it kept telling that these codes were in an invalid format. I Google'd online and found these ActionReplay codes for Pokemon Fire Red and tried entering them one at a time but was unable to due to the invalid format error. Is there another way to enter multi-line ActionReplay codes?

Ccb0b003
31cff0b6
4ebc6848
26d34f8e
1cd6b3d2
6375e67d

**Comment by Ammako** [comment]
As far as I'm aware, this is the format for GameShark Advance (XXXXXXXX, or XXXXXXXX YYYYYYYY.)
CodeBreaker uses the XXXXXXXX YYYY format.
