### ISSUE TITLE
Entire Application Closes Unexpectedly

### ISSUE THREAD

**Issue by theEternalNewb** [visualboyadvance-m/visualboyadvance-m#811]
Several times I have gone into shortcuts and removed ESC as a shortcut for quitting.  Despite this, every time my cats investigate what I'm doing and step on the escape key, I lose all progress and the entire application closes.  There is clearly a bug which keeps setting ESC back as the quit shortcut, as I have changed it to not be the shortcut multiple times.

**Comment by Squall-Leonhart** [comment]
tested on windows,  escape isn't a default binding and doesn't cause the emulator to exit.

currently resolved as WFM on my end.

**Comment by Squall-Leonhart** [comment]
Ok, i see whats up.

Download your flavour of the emulator from the nightly page here https://win.vba-m.com/nightly/, the problem you're reporting was fixed some time ago.
