### ISSUE TITLE
visualboyadvance-m fails to build against SDL-2.0.14

### ISSUE THREAD

**Issue by nvinson** [visualboyadvance-m/visualboyadvance-m#815]
Attempting to build visualboyadvance-m on a Gentoo system that also has SDL-2.0.14 installed results in a build failure because KMOD_META is not defined.  The issue can be seen in detail by going to https://bugs.gentoo.org/762208.

### Expected behavior

visualboyadvance-m build successfully.

### Actual behavior

Build fails with SDL.cpp: error: KMOD_META was not declared in this scope.

### Steps to reproduce the behavior

I did not work out the steps on how to do this without using the Gentoo package manager.
With the package manager, you set up a system with SDL-2.0.14 (or newer) installed and then try to build SDL.

### Additional details

I checked the master branch and it has the same issue as the Gentoo bug reported.  The Gentoo bug also contains a patch that can be applied to the master branch to fix the issue.  The link to the patch is https://762208.bugs.gentoo.org/attachment.cgi?id=687738

**Comment by ZachBacon** [comment]
Fix is already in master.
