### ISSUE TITLE
Persistent slowdown after days of normal speeds

### ISSUE THREAD

**Issue by pealad** [visualboyadvance-m/visualboyadvance-m#818]
### Expected behavior

100% Framerate

### Actual behavior

Framerate hovers around 65%-75% despite a lack of excessive system resource use. Turbo mode with enough tweaking can get it close to 100% framerate but this isn't consistent and leaves sounds high-pitched and choppy.

### Steps to reproduce the behavior

Unknown, vba-m worked normally for dozens of hours, since the issue has arisen restarting the emulator or performing a factory reset hasn't helped.

### ROM details

Which games are affected by the issue (please state if GBA or GB game): A variety of Pokemon roms, from main series games, to spinoffs, to romhacks.

Which games, if any, are NOT affected by the issue (please state if GBA or GB game): None that I could find.

Include screenshots of ROM Information (File > ROM Information): https://imgur.com/pIgPgRy.png

### Option details

Video driver (simple, opengl): Both simple and opengl have this issue.

Sound driver (directsound, xaudio, openal, SDL): SDL

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Ubuntu 20.04

If using Linux, specify if using xorg or Wayland: X11

Version of code (pre-built binary version, or commit ref, or just "master"): Master, at least as of a few days back

**Comment by Squall-Leonhart** [comment]
set throttle to 100%
turn down the filter scale.

**Comment by pealad** [comment]
If throttle means turbo, setting it to 100% and enabling turbo makes games run at roughly 550% speed. Contrasted to a turbo of 101%, which makes games run at 70-80% speed.

I have no filters enabled in my display settings.

**Comment by Squall-Leonhart** [comment]
check your cpu fan for dust.

if you changed no settings, and updated no drivers then it can only be a maintenance issue.

**Comment by pealad** [comment]
Would such an issue really effect only vba-m, and no other applications/games? While still having vba-m able to process much higher framerates under turbo? And without consuming a noteworthy amount of system resources?

Serious questions since I haven't encountered something like this before and that sounds like behaviour I wouldn't expect from a hardware maintenance problem.

**Comment by pealad** [comment]
Today, after no meaningful changes (no restarts, updates, hardware maintenance, etc.) it has returned to normal framerates. Strange.

**Comment by Squall-Leonhart** [comment]
it it returns, reply to reopen this bug.
