### ISSUE TITLE
Problem with start menu in game Megaman Battle Newtwork 1

### ISSUE THREAD

**Issue by kwehsadilla** [visualboyadvance-m/visualboyadvance-m#819]
### Expected behavior
Pressing start brings up the start menu, but then pressing A to select anything from it just exits the start menu.
### Steps to reproduce the behavior
Press start, try to select anything, observe how it doesn't work.

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Linux

**Comment by Squall-Leonhart** [comment]
Works fine, rebind your keys.
