### ISSUE TITLE
Cheat codes windows issues

### ISSUE THREAD

**Issue by AnthonyRyuki** [visualboyadvance-m/visualboyadvance-m#821]
### Expected behavior

When using the cheat codes related windows, I should be able to type numbers on the textboxes. 

### Actual behavior

When I try to type numbers, the size of the game window will change instead.

### Steps to reproduce the behavior

Open up any game, then open either Tools>Cheats>List cheats... or Tools>Cheats>Find cheat... then try to type any number on a textbox.

### ROM details

Which games are affected by the issue (please state if GBA or GB game): All games

### Option details

Video driver (simple, opengl): OpenGL

Sound driver (directsound, xaudio, openal, SDL): DirectSound

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Windows 10

Version of code (pre-built binary version, or commit ref, or just "master"): Pre-built binary version

**Comment by Squall-Leonhart** [comment]
Please use the template or i will close this as invalid.

**Comment by AnthonyRyuki** [comment]
Ok, sorry about that. Is it OK now?

**Comment by Squall-Leonhart** [comment]
Thanks,  I believe you're using the current 2.1.4 release which has this issue, the current nightly is not reproducing the problem.

**Comment by AnthonyRyuki** [comment]
Unfortunately, I can't open this link. I get a connection timeout error.

**Comment by Squall-Leonhart** [comment]
[visualboyadvance-m64.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/6135345/visualboyadvance-m64.zip)

[visualboyadvance-m32.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/6135346/visualboyadvance-m32.zip)

**Comment by AnthonyRyuki** [comment]
Ok, thanks a million.

**Comment by epman100** [comment]
> 
> 
> Thanks, I believe you're using the current 2.1.4 release which has this issue, the current nightly is not reproducing the problem.
> 
> https://win.vba-m.com/nightly/

apparently that site to get recent VBA-M nightlies is still unresponsive (must be a server problem) even recently as of early April 2021.  tested that site in all web browsers like Firefox and Chrome (and checking that site thru the [Isitdownrightnow.com site](https://www.isitdownrightnow.com/win.vba-m.com.html) also reports the site is DOWN for everyone)
