### ISSUE TITLE
the controls become unresponsive

### ISSUE THREAD

**Issue by OUTAmygaminmind** [visualboyadvance-m/visualboyadvance-m#822]
Controller support - Expected behavior

Controller becomes unresponsive and base controls reset - Actual behavior

Plug in a wired controller, open and close the tools and options bars and change something like the audio (i turned up the sound THIS TIME but it has happened to the point that i almost never use controller) to fix it you press the "Defaults" button under "Input" in the "Options" window - Steps to reproduce the behavior

None specific. happens on all games (i was playing a beta version of pokemon green but i have had it happen on all other games i play, wario world, pokemon red, mario world 2 gba, ect) - ROM details

Which games are affected by the issue (please state if GBA or GB game): BOTH

Which games, if any, are NOT affected by the issue (please state if GBA or GB game): None that i know of, so far every one i have tried and i have a large collection

Include screenshots of ROM Information (File > ROM Information): no need, its easy to reproduce and you can't screenshot a physical controller not registering, it shows as normal under settings too

If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl): opengl but im 99 percent sure that isn't the issue. it doesn't do that on the other emulator i use

Sound driver (directsound, xaudio, openal, SDL): directsound, again im pretty sure this isn't the issue

V2.1.4 - Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Windows

Version of code (pre-built binary version, or commit ref, or just "master"): say what now?

<!--- Hardware details:

If relevant, the joystick you are using and the drivers you are using for it: Xbox One wireless connected via charging cable. works on the other 6 emulators i use (some only 3 of those are gb/gba and nes/snes emulators)

**Comment by Squall-Leonhart** [comment]
Confirm that either of these is affected.

[visualboyadvance-m64.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/6135345/visualboyadvance-m64.zip)

[visualboyadvance-m32.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/6135346/visualboyadvance-m32.zip)
