### ISSUE TITLE
Kingdom Hearts: Chain of Memories doesn't save.

### ISSUE THREAD

**Issue by Username9980** [visualboyadvance-m/visualboyadvance-m#824]
The game says it saved successfully but VBA-M doesn't create a .sav file.

### ROM details

Which games are affected by the issue (please state if GBA or GB game): Kingdom Hearts: Chain of Memories (GBA game)

Which games, if any, are NOT affected by the issue (please state if GBA or GB game): Only this game stated above.

Include screenshots of ROM Information (File > ROM Information):

If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl): OpenGL

Sound driver (directsound, xaudio, openal, SDL): DirectSound

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Windows 10 x64

Version of code (pre-built binary version, or commit ref, or just "master"): Pre-built binary version.

**Comment by Squall-Leonhart** [comment]
is the save type set to automatic?
do you have permission to write to the folder that the emulator is using for user data and saves?
