### ISSUE TITLE
Health Bar Infinitely Going Down Pokémon Emerald

### ISSUE THREAD

**Issue by Boogie53** [visualboyadvance-m/visualboyadvance-m#826]
### Expected behavior
Health bar does down normally
### Actual behavior
Health bar is stuck in a loop of going all the way down and then all the way back up again.
### Steps to reproduce the behavior
Unknown

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
GBA Pokémon Emerald
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
Unknown
Include screenshots of ROM Information (File > ROM Information):
![image](https://user-images.githubusercontent.com/81398173/112566430-fb017480-8dac-11eb-89ec-f934ffd2b851.png)

### Option details

Video driver (simple, opengl):
Opengl
Sound driver (directsound, xaudio, openal, SDL):
SDL
### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 10

**Comment by Squall-Leonhart** [comment]
disable cheats, and load from a battery save.
