### ISSUE TITLE
Would it be possible to add GB Player emulation?

### ISSUE THREAD

**Issue by AlexN64gamer** [visualboyadvance-m/visualboyadvance-m#830]
1### on Dolphin Emulator the GB Player Startup disc gives an error cause there is no hardware emulation of the peripheral

2### GB Player code correctly emulated and being able to switch between borders and options on the main menu plus launching any .gb .gbc or .gba rom from it

3### go to Dolphin emulator config options, Gamecube tab, on SP1 theres no "Game Boy Player" option, open an iso of the GB Player startup disc and you can see this error (attached picture)
![gbpnotconnected](https://user-images.githubusercontent.com/38527600/113208344-99884c80-9269-11eb-9b46-1310e2a35bd3.PNG)

Please, help me understand better why it hasnt been possible yet to implement GB Player emulation, I really want to be able to use it on vba-m or dolphin (same way you can use Super Game Boy emulation on Bsnes with Gambatte core) with full support, if I can do anything, I offer my help, its a project I think its worth the time investment, and im sure many users will be glad to see it done, could it be possible to be in touch with Dolphin dev team so you can work together for make this happen? 

Thanks A LOT, to anybody reading this, and please stay safe in these hard times

**Comment by Squall-Leonhart** [comment]
I'm sorry, this has absolutely nothing to do with the developers of visualboy advance at any level or fork.

If Dolphin developers want to support it, they can and it'll likely be the MGBA core they use.
