### ISSUE TITLE
Sound Setting: Enable hardware acceleration doesn't save properly

### ISSUE THREAD

**Issue by TheRealDannyyy** [visualboyadvance-m/visualboyadvance-m#833]
### Expected behavior
The Sound setting to "enable hardware acceleration" for DirectSound should save between sessions.

### Actual behavior
The Sound setting to "enable hardware acceleration" for DirectSound doesn't save properly.

### Steps to reproduce the behavior
1. Navigate to: Options > Audio > Configure > Advanced
2. Switch to "DirectSound"
3. Enable "hardware acceleration"
4. Close all windows and quit VBA
5. Open VBA a do step 1 again
6. Notice setting didn't save properly

### Option details
![image](https://user-images.githubusercontent.com/15656049/113885554-3a25c180-97c0-11eb-9081-6d0dc288c208.png)

### Setup details
- Windows 10 (20H2)
- VBA-M 2.1.4
- GTX 1660 SUPER
- AMD Ryzen 7 2700x

**Comment by Squall-Leonhart** [comment]
Windows Vista, 7 8 and 10 do not support hardware accelerated Directsound without a emulation library,

none of which (except for Alchemy by Creative labs and operates on OpenAL Hardware) are worth the time and effort.
