### ISSUE TITLE
VisualBoyAdvance-M Pokemon Emerald stuck on "SAVING... DON'T TURN OFF POWER."

### ISSUE THREAD

**Issue by imperial2222** [visualboyadvance-m/visualboyadvance-m#834]
### Start -> Save

Hello, first time posting here. I recently downloaded VisualBoyAdvance-M because it has better quality than VisualBoyAdvance 1.8.0 Beta3. There, Saving in-game works fine but in VisualBoyAdvance-M, it gets stuck on "SAVING... DON'T TURN OFF POWER." while the game audio still plays. Doing File -> Save State works fine it's just the in game save that it gets stuck on. In the meantime, I'll play on the other VisualBoyAdvance till the issue is solved.

![visualboyadvancem](https://user-images.githubusercontent.com/82253335/114259294-2a9cb780-9a10-11eb-9a2e-29be96087536.JPG)

### ROM details

Which games are affected by the issue (please state if GBA or GB game):

GBA

Include screenshots of ROM Information (File > ROM Information):

![rom info](https://user-images.githubusercontent.com/82253335/114259202-aea26f80-9a0f-11eb-99a6-18fde2f26060.JPG)

If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl): OpenGL

Sound driver (directsound, xaudio, openal, SDL): SDL

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Windows

**Comment by Squall-Leonhart** [comment]
no support for downloaded games.
