### ISSUE TITLE
VBA either closing/crashing when trying to stream on discord

### ISSUE THREAD

**Issue by strydrehiryu** [visualboyadvance-m/visualboyadvance-m#843]
Currently trying to stream Pokemon Radical Red to my friends through discord, but the game is either closing or crashing once I "Go Live" on discord

Here's a play by play

Open up VBA, start running PRR

Game is running, go to discord and hit "Share Screen"

Select VBA, hit "Go Live"

Stream starts, VBA closes/crashes (dont know which)

To clarify, the game itself works fine while discord is open, even going back and forth between different applications. It's only once I start to stream it does it close/crash. Don't know what to do, completely lost here.

**Comment by Squall-Leonhart** [comment]
this doesn't occur on M 1507 or M 2.1.4+Nightly,

1507 will not display a video on either d3d or opengl
Nightly won't display it on opengl.

Refer to #84

**Comment by strydrehiryu** [comment]
this isn't the same issue. the game works fine and does not show a black screen. it flashes a screen of what is on VBA, then either closes or crashes.
