### ISSUE TITLE
VBA either closing/crashing when trying to stream on discord

### ISSUE THREAD

**Issue by strydrehiryu** [visualboyadvance-m/visualboyadvance-m#844]
**THIS IS NOT THE SAME ISSUE AS #840 THIS IS ENTIRELY DIFFERENT**
     **note is here because Squall-Leonhart had my last post closed**

Expected Behavior

I stream the game through Discord by sharing my application.

Actual Behavior

VBA closes as soon as I attempt to stream the application through discord.

**Reproducing the issue**

Open up VBA, start running ROM: Pokemon Radical Red (success)

Game is running, and open discord (game still running properly)

Click "Share Your Screen" > Applications > visualboyadvance

Stream starts (showing what is on VBA), VBA immediately closes (or crashes, still unsure which), stream stops on discord

To clarify, the game itself works fine while discord is open, even going back and forth between different applications. It's only once I start to stream it does it close/crash. Don't know what to do, completely lost here.

_edit: When I stream on StreamLabs OBS it works fine, same as streaming through StreamLabs to Twitch_

**ROM Information**
![image](https://user-images.githubusercontent.com/83686045/117098507-67578800-ad0a-11eb-849f-2b85a16b27aa.png)

Currently do not know what my driver is (still new to determining my drivers, dont know how to determine even with google searches)

**Build Details**
Operating System: Windows 10
VisualBoyAdvance emulator v. 1.8.0.603

**Comment by Squall-Leonhart** [comment]
Closed, again, because you aren't even using vba-m.

**Comment by strydrehiryu** [comment]
Just downloaded VBAM v.2.1.4, the issue repeated itself. thanks for nothing I guess. I'll just leave this site since it's apparently useless with people like you who think some people are absolutely clueless but are just trying to look for solutions in area's they struggle to understand. thought i'd give this site a shot, but you just turn everyone away

**Comment by Squall-Leonhart** [comment]
> I'll just leave this site since it's apparently useless with people like you who think some people are absolutely clueless

Lets wind this back to right as you created the issue in the issue templates.

> BEFORE REPORTING AN ISSUE PLEASE TRY THE NIGHTLY FROM:
> 
> http://win.vba-m.com/nightly

You didn't do this, and persisted in logging a bug for a legacy, 2005 release of the original branch of the emulator.

> Just downloaded VBAM v.2.1.4, the issue repeated itself. thanks for nothing I guess

![image](https://user-images.githubusercontent.com/1098176/117099443-87438600-adb4-11eb-988b-f4dd80cbdb6b.png)

We know there are issues with opengl streaming, those were identified in #840 ,
There is no reproduction of the emulator crashing in your described manner.
