### ISSUE TITLE
Xbox 360 and Xbox One controllers recognition issues

### ISSUE THREAD

**Issue by Rajzin** [visualboyadvance-m/visualboyadvance-m#845]
### Expected behavior
Xbox 360 and Xbox One controllers work whenever plugged in.

### Actual behavior
Xbox controllers are not recognized when plugging them in after launching VBA-M, and they also stop being recognized when disconnecting and reconnecting them while VBA-M is running. This behavior persists until VBA-M is relaunched (with the controller connected before launching).

### Steps to reproduce the behavior
Have the controller disconnected at any time when VBA-M is running.

### Build details
Operating System: Windows
Version of code: 2.1.4
____________________________

It seems very likely to me that the person who submitted issue #311 had the same problem, as well as two people in [this old VBA-M forum thread](https://board.vba-m.com/viewtopic.php?f=19&t=219) and someone in [this Reddit thread](https://www.reddit.com/r/emulation/comments/22xqx9/controller_on_visual_boy_advance/). Looks like this bug has been around since before VBA-M.

Someone in that Reddit thread said this behavior is "a side effect of using the windows multi-media API instead of directinput, xinput, or rawinput", in case that helps.

**Comment by Squall-Leonhart** [comment]
There is no hotplug detection implemented in WxVBAM.

**Comment by aki-cat** [comment]
Further information on this: whenever you remove a connected controller while a ROM is running, VBA crashes/hangs and must be forcibly terminated.

**Comment by Squall-Leonhart** [comment]
no it doesn't.

**Comment by aki-cat** [comment]
@Squall-Leonhart are saying i'm lying?

**Comment by Squall-Leonhart** [comment]
i'm saying

> no it doesn't.

**Comment by Squall-Leonhart** [comment]
Closing because hotplug seems to work fine now.
