### ISSUE TITLE
Stable Build Release? & Windows Nightly, Not So Nightly Any Longer

### ISSUE THREAD

**Issue by InfiniteParallel** [visualboyadvance-m/visualboyadvance-m#848]
Is there any intention to create another stable build release any time soon? The number of commits since the last major release is rather substantial at this point.

Or is the intention to do like many projects and just generate nightly builds so there is not technically an updated base "stable" version, and if one runs into a problem, they either report it here, or just try an earlier build?

Also, as mentioned in the title of this issue, the Windows Nightly built that is linked: https://win.vba-m.com/nightly/ is not so nightly any longer. Is there any intention of keeping this up to date or is is going to remain the way it is?

I sincerely apologize if this was more appropriate as a forum post, but the forum looked rather abandoned, so I thought here would be a better chance someone would see this.

**Comment by InfiniteParallel** [comment]
Ok. Never mind.

**Comment by ZachBacon** [comment]
At some point I plan on doing a release, just lately there hasn't been much time to put towards the project, right now my personal life needs to come first before the project.
