### ISSUE TITLE
I can't hear anything

### ISSUE THREAD

**Issue by OtakuDS** [visualboyadvance-m/visualboyadvance-m#858]
I can't hear any sound even if i configure the audio settings

**Comment by Squall-Leonhart** [comment]
use the template or i'm closing this.

**Comment by OtakuDS** [comment]
What template

**Comment by ZachBacon** [comment]
The template you saw when you first opened the issue. The wall of text you chose to ignore to write your own that detailed nothing.

**Comment by Squall-Leonhart** [comment]
the one you deleted after clicking new issue
