### ISSUE TITLE
Can't hear anything

### ISSUE THREAD

**Issue by OtakuDS** [visualboyadvance-m/visualboyadvance-m#860]
I can't hear anything when I'm playing any GB/GBA ROM. Can I please get some assistance

**Comment by ZachBacon** [comment]
You again failed to fill out the template that is needed, we need to know what operating system you're using, what version of the emulator etc. That's what the _template_ is there for.

**Comment by OtakuDS** [comment]
How do I check the version?

**Comment by OtakuDS** [comment]
Also, my operating system is Windows

**Comment by OtakuDS** [comment]
And the version is 2.0.1

**Comment by ZachBacon** [comment]
Your version is outdated and unsupported now. Check the releases tab in GitHub for the latest version
