### ISSUE TITLE
[Feature Request] Option to mute sound when turbo is active

### ISSUE THREAD

**Issue by bluerayxx** [visualboyadvance-m/visualboyadvance-m#865]
Would be awesome if you could toggle an option that would mute the game when you are fast forwarding. The sound gets annoying after a while and it's a cumbersome to hit two buttons to fast forward and mute since I toggle turbo on and off often. This can be worked around if we were able to set two commands to one hotkey, but currently it just overwrites the key with the new command. really awesome and smooth Emulator, just wish it had the old VBA feature to mute when in turbo.

**Comment by Overload86** [comment]
This. Alternatively find a way to speed up sound without it varying its pitch.

**Comment by harley-codes** [comment]
Upvote ^
