### ISSUE TITLE
Background Input not working, Website for Nightly is dead

### ISSUE THREAD

**Issue by MarbleQ22** [visualboyadvance-m/visualboyadvance-m#869]
Hello, so I have the latest downloadable version obtained from sourceforge, however this is the version where the background input isn't working. I read on here that a certain nightly build fixed the issue of background input not working, however the site to download, which is http://win.vba-m.com/nightly I believe, is down completely, and I can't access it. I've tried everywhere to get some semblance of info about where else I can get nightly builds, however no other site than the downed one is available. I'm very sorry if this is formatted incorrectly, it's been a long week trying to get this fixed.

**Comment by ZachBacon** [comment]
Issue is known and working on being resolved, no time frame is expected, it's done when it's done.
