### ISSUE TITLE
VBA Only Loads Save States

### ISSUE THREAD

**Issue by Langfried** [visualboyadvance-m/visualboyadvance-m#872]
When I load Pokemon Leaf Green into my VBA-M emulator, it goes straight to my most recent save state, instead of going to the title screen. This is an issue only experienced by Pokemon Leaf Green and has only popped up recently when trying to figure out how to do use VBA-M's Link function (which I also kinda need help with).

**Comment by Squall-Leonhart** [comment]
Turn off "Auto load most recent"
