### ISSUE TITLE
Game looks like 30 fps when running on 240 Hz monitor

### ISSUE THREAD

**Issue by 75th** [visualboyadvance-m/visualboyadvance-m#873]
### Expected behavior

Game looks like it's running at fully smooth 60 fps on a high refresh rate (240 Hz) display.

### Actual behavior

- Game looks like it's running at about 30 fps on a 240 Hz display.
- If I drag the Visual Boy Advance window over to my 60 Hz secondary monitor, it looks great. Drag back to the 240 Hz monitor, choppy choppy.
- Setting the 240 Hz display to 60 Hz mode in Windows settings makes the emulated game look good.
- 60 Hz games in other emulators look fine on the 240 Hz display in 240 Hz mode.
  - Breath of the Wild with 60 Hz patch in Cemu
  - Super Mario World and Super Metroid in snes9x
- The choppiness does NOT show up in Visual Boy Advance video recordings, but it DOES show up with Nvidia Overlay recordings.
  - [Choppy recording from 240 Hz monitor in 240 Hz mode](https://75thtrombone.com/links/github/240hz.mp4)
  - [Smooth recording from 240 Hz monitor in 60 Hz mode](https://75thtrombone.com/links/github/60hz.mp4)

### Option details

Video driver (simple, opengl): Both

I have toggled just about every video setting (interframe blending, skip frames, bilinear filter, all the rest), and none of them have improved the issue.

### Build details

- OS: Windows 10 Home
- VBA: September 8, 2021 nightly

### Hardware details

- Nvidia RTX 3080
- Asus Rog Strix XG27AQM monitor running at 240 Hz

**Comment by Squall-Leonhart** [comment]
Fix your expectations.

**Comment by 75th** [comment]
Uhhh okay! @Squall-Leonhart Mind telling me what I did to deserve this response so I can avoid repeating the mistake?

**Comment by ZachBacon** [comment]
> Uhhh okay! @Squall-Leonhart Mind telling me what I did to deserve this response so I can avoid repeating the mistake?

Don't mind him, that's just how he is, what he is referring to is that on actual hardware, that's how it looks.

**Comment by Squall-Leonhart** [comment]
These high refresh displays are generally not compatible with low fps content due to the way their panel scalers and interpolation works

>  For example, Leo Bodnar tests show a 3/4 frame delay at the top edge because 240Hz panels currently buffer a slow-scanning 60Hz video signal to a fast-scanning 1/240sec refresh cycle. Basically essentially tantamount of internally converting 60Hz into 240Hz. Even doing that necessarily forces a pre-buffering.
