### ISSUE TITLE
my speed is stuck on 500% and  i tried everything and it wont fix it

### ISSUE THREAD

**Issue by 12kSHFD** [visualboyadvance-m/visualboyadvance-m#875]
### ROM details

Which games are affected by the issue (please state if GBA or GB game):

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

Include screenshots of ROM Information (File > ROM Information):

If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

**Comment by ZachBacon** [comment]
Fill out the details please, need to know what version you're using, operating system etc. It's why there's a template.

**Comment by Squall-Leonhart** [comment]
duplicate #851
