### ISSUE TITLE
No version (either Windows or Mac) saves/loads the option to "save/load cheats"

### ISSUE THREAD

**Issue by tycooko** [visualboyadvance-m/visualboyadvance-m#876]
### Expected behavior
Select "Tools --> Cheats --> Automatically save/load cheats"; expect the software to register said choice and load it the next time you open VBA-M.

### Actual behavior
The option is never registered, even if it confirms so in the settings file (autoSaveCheatList=1).

### Steps to reproduce the behavior
Select "Tools --> Cheats --> Automatically save/load cheats". Close and re-open VBA-M.

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
I have tried it with six different PAL/Europe GBA ROMs, but it's not ROM-related: it's the menu.

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
I wouldn't know, though I don't think that it depends on the game.

Include screenshots of ROM Information (File > ROM Information):
I don't think that it depends on the game.

If you are using a BIOS file, please say which one.
I am not.

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): macOS Big Sur 11.5.2

<!--- Hardware details: I’m on an iMac (iMac20,2) with a 3,8 GHz 8-Core Intel Core i7, an AMD Radeon Pro 5700 XT 16 GB GPU and 128 GB 2667 MHz DDR4 RAM.

**Comment by Squall-Leonhart** [comment]
Works for me, so please don't lie about the OS's an issue is occuring in, because it misdirects finding a fix.

**Comment by tycooko** [comment]
> Duplicate of #80

"Lying" implies a decision and a goal, so if you could please avoid insulting me, since I have no idea who you are. Thanks.
So this has been known for 4 years and no one has done anything about it? Wow.
