### ISSUE TITLE
CRASH CRASH CRASH 

### ISSUE THREAD

**Issue by TsynkZZZ** [visualboyadvance-m/visualboyadvance-m#879]
2.0.1 CRASHES WAY TOO OFTEN! 

Doesn't matter which ROM I use, doesn't matter if my laptop is on charge or off charge, using Windows 10 with AMD Ryzen 5 4500u with Radeon GPU, 8 GB RAM. 

Doesn't matter which ROM, it crashes when I try to save/load states or when I am playing or even if I try to load cheats, heck it crashes upon ROM load at times. All of the crashes are random and it's highly annoying. 

VBA used to more stable than this.

**Comment by Squall-Leonhart** [comment]
didn't fill out template
didn't use nightly before opening bug

closed

**Comment by ZachBacon** [comment]
On top of that 2.0.1 is no longer the stable release.
