### ISSUE TITLE
Pokemon Emerald

### ISSUE THREAD

**Issue by Pocho74** [visualboyadvance-m/visualboyadvance-m#880]
just got pokemon emerald. it let me press enter but im stuck on a screen where it says new game or option. nothing happens when i press new game...

**Comment by ZachBacon** [comment]
So I see you failed to use the bug report template, please ensure that you fill it out in its entirety so that we can properly help you. It was created for a reason, to get as much detail as possible to better assist you.

**Comment by Squall-Leonhart** [comment]
configure your inputs appropriately

closed.
