### ISSUE TITLE
MMBN2 Chinese Translation stucks on opening menu, and a request

### ISSUE THREAD

**Issue by Yave-Yu** [visualboyadvance-m/visualboyadvance-m#889]
Version: 2.1.4-173512f6
Issue: In Mega Man Battle Network 2 (aka Rockman EXE 2) Chinese Translation, when you can control Lan then press start key, the game freezes, but it won't freeze in mGBA so I guess it's an emulation issue.
Could you look and fix it? Thanks!
Here's patch, apply it onto MMBN2 US ROM.
[MMBN2CnTran.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/7404659/MMBN2CnTran.zip)

Request: Can you make Noise channel louder? Current some music can't hear its noise drum clearly (most on MMBN series). Fun fact: an FB2K [GSF plugin](https://foobar2000.xrea.jp/up/files/up1284.7z) uses your VBA-M core but made noise channel louder, so I guess VBA-M itself could do this too.

**Comment by Steelskin** [comment]
I have a potential fix in [24b6ac5](https://github.com/visualboyadvance-m/visualboyadvance-m/commit/24b6ac5a28e6d5b5d98ec3b52ed9350db04a751d).

**Comment by Steelskin** [comment]
I tested the fix and can confirm that the graphical glitches are no longer present. I'll land the fix and close this. Thanks for the report!
