### ISSUE TITLE
OpenGL Aspect ratio broken during fullscreen (Screen is cut off)

### ISSUE THREAD

**Issue by bryc** [visualboyadvance-m/visualboyadvance-m#89]
### Expected behavior
Fullscreen should work fine with OpenGL and aspect ratio fix enabled.
### Actual behavior
Screen appears to be cut in half in fullscreen if aspect ratio fix is enabled with OpenGL.

**Example:**
![image](https://cloud.githubusercontent.com/assets/1408749/23343336/d60a3dfc-fc37-11e6-9cc7-504cca2b0b1c.png)

### Steps to reproduce the behavior
1. Download [latest release build (931fda4)](https://github.com/visualboyadvance-m/visualboyadvance-m/releases/download/waylandplus/vba-m-x86_64.zip)
2. Load any GB or GBA game (GB is more affected than GBA)
3. Set video options to OpenGL
4. Enable correct aspect ratio fix
5. Enter fullscreen

### Build details
Win7, using tagged release of 931fda4.
Also occurs on Win10 using the same build.

This issue along with issue #88 do not affect the earlier beta-3 release of f7f67ff.

**Comment by rkitover** [comment]
@bryc will try to take a look soon.

**Comment by rkitover** [comment]
Fixed in master in d1918c12.

**Comment by rkitover** [comment]
@bryc 

Fixed in this release:

https://github.com/visualboyadvance-m/visualboyadvance-m/releases/tag/throttle

Please confirm.

**Comment by bryc** [comment]
@rkitover I can confirm it's fixed :) nice work! feel free to close this

**Comment by ZachBacon** [comment]
Closed, thanks for testing
