### ISSUE TITLE
Fix resize on load

### ISSUE THREAD

**Issue by rayzchen** [visualboyadvance-m/visualboyadvance-m#890]
### Expected behavior

Open emulator to 2x (which I usually leave it on)

### Actual behavior

Black bars above and below the screen (on the sides if it's gbc)

### Steps to reproduce the behavior

Open VBA and press 2 (set to 2x)
Close VBA
Reopen

### ROM details

Which games are affected by the issue (please state if GBA or GB game):

Both GBA and GBC (idk abt GB)

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

Include screenshots of ROM Information (File > ROM Information):

![image](https://user-images.githubusercontent.com/54078384/138958221-da0ad3c2-c8df-467e-86c3-769b176ff237.png)
^^^ pokemon yellow GBC rom

If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl):

opengl

Sound driver (directsound, xaudio, openal, SDL):

SDL

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):

Windows

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

2.1.4 (from releases page)

**Comment by Squall-Leonhart** [comment]
not reproducible in nightly.
