### ISSUE TITLE
What is with the debug version of VisualBoyAdvance-M?

### ISSUE THREAD

**Issue by P0W3** [visualboyadvance-m/visualboyadvance-m#892]
What is with the debug version of VisualBoyAdvance-M? What does the debug version do specifically?

![win vba-m com_nightly_](https://user-images.githubusercontent.com/18279115/139556971-75bc14ce-28b3-414d-b641-aa68f2ae1906.png)

**Comment by ZachBacon** [comment]
Duplicate of your last issue
