### ISSUE TITLE
Audio Channel 1 (square pulse) does not record in audio record feature

### ISSUE THREAD

**Issue by Andrew900460** [visualboyadvance-m/visualboyadvance-m#896]
Audio Channel 1 (square pulse) does not record in "File > Record > Start Sound Recording..." feature
All other channels get recorded as they should, except "Channel 1"

This is occurring in the latest stable release of v2.1.4
I tested this issue in the latest "nightly builds" (v2.1.4-89028de8)
And the issue was fixed. I assume that this issue was either identified/fixed, or it may have been fixed without anyone knowing. So I figured I'd bring it to the developers' attention.I did not see any other posted issues talking about "audio channel 1".

Also, I noticed that there is now a .wav option for saving a sound recording in the nightly build. Which is very nice to have.

I only tested this on one game.

**Comment by Squall-Leonhart** [comment]
please don't open issues for fixed bugs.

**Comment by Andrew900460** [comment]
My apologies... I did do a search to make sure this wasn't already caught. But I guess I didn't use the right search terms.
Like I said, I assumed the issue might've been fixed and nobody realized it. And being made known of it would be valuable to the developers.
