### ISSUE TITLE
rtc not recognized as working by radical red

### ISSUE THREAD

**Issue by SHREADHEAD** [visualboyadvance-m/visualboyadvance-m#897]
### Expected behavior
rtc works allowing for time changing and day and night passing
### Actual behavior
not recognized as active and time permanenetly set to night
Which games are affected by the issue (please state if GBA or GB game):
gba radical red
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
idk
Operating System (Windows, Mac, Linux (state distribution), etc.):
windows

**Comment by Squall-Leonhart** [comment]
you haven't stated a game and all the ones i've got on hand work fine.
