### ISSUE TITLE
Wireless trading "semi-crash" on Mac?

### ISSUE THREAD

**Issue by deepnurple** [visualboyadvance-m/visualboyadvance-m#898]
### Expected behavior
Wireless Pokemon trading between GBA versions should work normally.

### Actual behavior
I tried trading between Pokemon FireRed and LeafGreen saves exactly as outlined [here](https://board.vba-m.com/viewtopic.php?t=862&hilit=how+to+trade+pokemon). Things went smoothly up until the final step; just as I confirmed the second person (the "connecting to trade" with my other file (the "leader") joined the room, the game crashed–kinda; the wireless icon still moves, but I couldn't do anything and had to start all over. Tried swapping leader/join roles between save files, no dice.

![Screen Shot 2021-11-16 at 4 08 14 PM](https://user-images.githubusercontent.com/94483260/142066252-47d5dd60-15af-49fe-b73e-b0b53afde99e.png)

### Steps to reproduce the behavior
follow steps in link above

### Build details
[this](https://win.vba-m.com/nightly/visualboyadvance-m-Mac-x86_64.zip) latest(?) nightly build of VBA-M (2.1.4)

Operating System: Mac OS X Big Sur 11.6

**Comment by Squall-Leonhart** [comment]
Link emulation is currently problematic and either works or it doesn't, i'll close this because we already have a hundred threads for the same issue.

**Comment by deepnurple** [comment]
> Link emulation is currently problematic and either works or it doesn't, i'll close this because we already have a hundred threads for the same issue.

Alright. I couldn't find this exact issue in search but figured something like might have shown up. thanks for the reply.
