### ISSUE TITLE
GBA colorization for GBC games

### ISSUE THREAD

**Issue by fortwoone** [visualboyadvance-m/visualboyadvance-m#899]
Hello,
I just want to ask a question : how does the GBA recolorize GBC games ? Is there any calculation or math behind the colorization process that runs when a Game Boy Color game is put into the GBA ? (or at least how did you reproduce it in the code ?)

Thanks in advance for your answer

**Comment by Squall-Leonhart** [comment]
Refer to: http://www.romhacking.net/forum/index.php?topic=23411.msg326909#msg326909

Closing.

**Comment by fortwoone** [comment]
Well I read it and it doesn't answer my question
