### ISSUE TITLE
Lost save state

### ISSUE THREAD

**Issue by DiegoNelson25** [visualboyadvance-m/visualboyadvance-m#902]
My in game save for pokemon fire red disappeared and whenever I try to load the save from VBA it gives me an error message saying "unsupported visualboyadvance save game version 0". This happened without me doing anything, it was working the night before and the last time I used it.  Using Windows 10 64bit

How can I get the save state to load if there is a way?

**Comment by ZachBacon** [comment]
First of all, use the issue template, it asks the questions we need to better assist you. If you don't then Well, it's hard to help you without proper vital information.
