### ISSUE TITLE
Save state not loading

### ISSUE THREAD

**Issue by DiegoNelson25** [visualboyadvance-m/visualboyadvance-m#903]
### Actual behavior Error message saying "Unsupported Visualboyadvance save game version 0"
![image](https://user-images.githubusercontent.com/69409755/144340259-6b4ffc95-86df-45b6-ab9a-8fc9ab62cf38.png)

### ROM details

Which games are affected by the issue (please state if GBA or GB game): Fire Red and a randomized version of Fire Red gba

Include screenshots of ROM Information (File > ROM Information): 
![image](https://user-images.githubusercontent.com/69409755/144339992-7dacc014-9d4f-45e2-9e4e-4c63ca2cf586.png)

![image](https://user-images.githubusercontent.com/69409755/144340119-60b8e163-10dd-4591-82d2-bc9f120923d0.png)

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Windows 10

**Comment by ZachBacon** [comment]
You're still missing details, what version of the emulator are you using? Is it a nightly build or release. Details that needs to be known. Don't hold anything back. It's why it's listed on the **Template**

**Comment by Squall-Leonhart** [comment]
you are trying to load an sav file instead of an sg# file.

**Comment by ShadeArtemis** [comment]
If you have fixed this or have a solution please let me know. I just got this today on my Rom hack.

**Comment by Squall-Leonhart** [comment]
closed invalid
