### ISSUE TITLE
Linux 2021-12-03 Compile Fail

### ISSUE THREAD

**Issue by OdinVex** [visualboyadvance-m/visualboyadvance-m#904]
In file included from /usr/include/GL/glx.h:333,
                 from vbam/visualboyadvance-m/src/wx/panel.cpp:2171:
/usr/include/GL/glxext.h:950:9: error: typedef ‘Status’ is initialized (use ‘decltype’ instead)
  950 | typedef Status ( *PFNGLXGETTRANSPARENTINDEXSUNPROC) (Display *dpy, Window overlay, Window underlay, unsigned long *pTransparentIndex);
      |         ^~~~~~
/usr/include/GL/glxext.h:950:19: error: ‘PFNGLXGETTRANSPARENTINDEXSUNPROC’ was not declared in this scope
  950 | typedef Status ( *PFNGLXGETTRANSPARENTINDEXSUNPROC) (Display *dpy, Window overlay, Window underlay, unsigned long *pTransparentIndex);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/wx/CMakeFiles/visualboyadvance-m.dir/build.make:230: src/wx/CMakeFiles/visualboyadvance-m.dir/panel.cpp.o] Error 1

### Steps to reproduce the behavior

`git clone https://github.com/visualboyadvance-m/visualboyadvance-m.git`
`cd visualboyadvance-m`
`./installdeps`
`mkdir build && cd build`
`cmake .. -G Ninja`
`ninja`

Xorg, vbam main (clone), Ubuntu-like (Mint).

**Comment by OdinVex** [comment]
Distro 2.1.4 isn't DPI-aware, I wanted to override the scale size but decided not to and just build first to test compilation. 2.1.4 compiled but had an issue with 1/4 of the screen was usable, the other 3/4 was wrong memory buffer being displayed. Tried main clone, it doesn't compile.

**Comment by WinterSnake** [comment]
I, too, am experiencing this failure on Linux. Attached a log of output:
OS: Arch Linux x86-64 5.18.11-arch1-1
[log.txt](https://github.com/visualboyadvance-m/visualboyadvance-m/files/9124764/log.txt)

**Comment by ZachBacon** [comment]
> I, too, am experiencing this failure on Linux. Attached a log of output:
> OS: Arch Linux x86-64 5.18.11-arch1-1
> [log.txt](https://github.com/visualboyadvance-m/visualboyadvance-m/files/9124764/log.txt)
> 

So instead of just saying same, include more details, are you using a released copy, or are you on the current git master?

**Comment by WinterSnake** [comment]
> > I, too, am experiencing this failure on Linux. Attached a log of output:
> > OS: Arch Linux x86-64 5.18.11-arch1-1
> > [log.txt](https://github.com/visualboyadvance-m/visualboyadvance-m/files/9124764/log.txt)
> 
> So instead of just saying same, include more details, are you using a released copy, or are you on the current git master?

My apologies - This log is from trying to compile from the current master.

**Comment by noabody** [comment]
It needs a patch like this:
```diff
diff --git a/src/wx/panel.cpp b/src/wx/panel.cpp
index 3a2a181b..f1a86ef1 100644
--- a/src/wx/panel.cpp
+++ b/src/wx/panel.cpp
@@ -2165,6 +2165,9 @@ void BasicDrawingPanel::DrawImage(wxWindowDC& dc, wxImage* im)
 #include <OpenGL/OpenGL.h>
 #endif
 #ifdef __WXGTK__ // should actually check for X11, but GTK implies X11
+#ifndef Status
+#define Status int
+#endif
 #include <GL/glx.h>
 #endif
 #ifdef __WXMSW__
```
See [QTBUG-9691](https://bugreports.qt.io/browse/QTBUG-9691) and related [patch](https://bugreports.qt.io/secure/attachment/14170/qt-opengl-compile.patch) for info.
