### ISSUE TITLE
vba fail

### ISSUE THREAD

**Issue by asbsadsa** [visualboyadvance-m/visualboyadvance-m#905]
### Actual behavior        it says "loaded battery with a white screen

Which games are affected by the issue (please state if GBA or GB game): pokemon fire red

**Comment by ZachBacon** [comment]
Please **Do not remove large portions of the template** it helps us, help you by understanding your system, what version your using etc.

**Comment by asbsadsa** [comment]
ok
using the latest version, and ngl since im pretty stupid i would need you to elaborate on the system, if you mean on my laptop im using windows 10, anything else you need to know?

**Comment by Squall-Leonhart** [comment]
We have a topic above for users to fix their Pokemon romhacks.

**Comment by asbsadsa** [comment]
it worked thank you
