### ISSUE TITLE
Start network link greyed out

### ISSUE THREAD

**Issue by kingfdeamons** [visualboyadvance-m/visualboyadvance-m#907]
I am playing fire red on the visualboyadvance-m I have tried the nightly version as well as version 2.1.4 both seem to have a greyed out  start network link.

 
I have tried all the link types 
I have also tried both local active and inactive
Pause when inactive is disabled  
I am currently set to 500ms 
I have no  idea what port to set GDB to and if this is the issue

screen shot of my issue
https://drive.google.com/file/d/1yhdtFZDeI1-2VsJt9vnLHmP5ZBm8It14/view?usp=sharing

**Comment by kingfdeamons** [comment]
okay new issue Save failed checking back up memory

**Comment by ZachBacon** [comment]
Linking is also not working in general. We have had time to devote to fixing it at the moment, it's Gui polishing we've been trying to do, try to get it to the point where it's on par with the old windows only release but for all platforms.

**Comment by kingfdeamons** [comment]
Ahh good to know

**Comment by ZachBacon** [comment]
It'll be done, just sorta on the back burner for now.

**Comment by kingfdeamons** [comment]
is there a version where it works i just need it for a moment?
