### ISSUE TITLE
VBA-M creates new .SAV files when linked instead of using existing files.

### ISSUE THREAD

**Issue by DragonRaider8212** [visualboyadvance-m/visualboyadvance-m#908]
### Expected behavior:
Opening a game with an existing .SAV file while two instances of VBA-M are linked together locally. (local Network via Cable)

### Actual behavior:
Opening most games while another instance of VBA-M is open causes it to create a new .SAV file instead of pulling the original .SAV.

### Steps to reproduce the behavior:
1) Open two instances of VBA-M, and link them together with the "cable" setting.
2) Open any game on either instance. They will create a new .SAV file instead of using one that already exists. If both instances load the same game, it will create two different .SAV files. Loading a save state from an original .SAV file will (I think) effectively copy the old .SAV onto the new, but certain linking actions (like linking Metroid: Zero Mission and Fusion) don't work.

### ROM details

Which games are affected: Metroid: Zero Mission, Metroid Fusion, Minish Cap, Superstar Saga. (all GBA)

Which games are not affected: Sonic Battle. (GBA)

Screenshots of ROM Information:
"Broken" games.
![rom_info1](https://user-images.githubusercontent.com/96546632/147152499-a1593bee-0522-4e9a-9fdc-548eb4e60be6.png)
"Expected" game.
![rom_info2](https://user-images.githubusercontent.com/96546632/147150528-cd8e9d2e-a4fb-4af6-8910-70df8f28e98e.png)

### Option details

Video driver: OpenGL

Sound driver: XAudio2

### Build details

Operating System: Windows 10

Version of code: 2.1.4.0

#### Additional:
I was originally attempting to link Zero Mission and Fusion together. I have just started Zero Mission but have played Fusion to completion. I've previously linked two instances of Sonic Battle just fine without this issue - both of them use the original .SAV and don't do anything unusual. I tested this with every other game I currently have installed and the same issue kept cropping up, but Sonic Battle opened up the .SAV file as normal without creating anything new.

I tried using the "Import > Battery File" function in File to try and work around it for Fusion, but I think it just wrote the new .SAV onto the old one. Thanks to me not being able to read SAVE state instead of LOAD state, I've now also effectively overwritten my completed file and am now essentially back to the first quarter of my Fusion game, lol. That's on me, but I would like to know what the purpose of the Import/Export battery file functions are.

I've done about an hour of testing to provide as much detail as possible and will try to provide more info as needed, but I am new to emulation so please be patient if I don't understand something!

**Comment by Squall-Leonhart** [comment]
Intended behavior

**Comment by DragonRaider8212** [comment]
Pardon me, but is there no way I can change this?
