### ISSUE TITLE
Shift+F1 etc not saving

### ISSUE THREAD

**Issue by Emilinrose** [visualboyadvance-m/visualboyadvance-m#909]
### Expected behavior
Shift+F1, etc, makes a save state

### Actual behavior
none

### Steps to reproduce the behavior
set to Shift+F1 to save state.

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
GBA and GBC

Include screenshots of ROM Information (File > ROM Information):

If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl):
OpenGL

Sound driver (directsound, xaudio, openal, SDL):
SDL Default

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows 10

Version of code (pre-built binary version, or commit ref, or just "master"):
VBAM 2.0.1

Additional info:
it will work with CTRL+S, and with other keybinds that don't require SHIFT.
it is working in the debug version.

**Comment by ZachBacon** [comment]
You're using an old outdated unsupported version, release 2.1.4 is out and then there's nightlies available at https://nightly.vba-m.com/
