### ISSUE TITLE
Super Game Boy lacks Super NES sound channels

### ISSUE THREAD

**Issue by FateForWindows** [visualboyadvance-m/visualboyadvance-m#91]
### Expected behavior
Certain Super Game Boy-enhanced games can use the Super NES sound channels for certain sounds. An example of this is Donkey Kong, where instead of Pauline's screams sounding like "mee-APP, mee-APP", they sound like Pauline is actually shouting "Help! Help!" and this also happens with MANY sounds on Kirby's Dream Land 2.
### Actual behavior
The sounds are silent when playing these games.
### Steps to reproduce the behavior
Play Donkey Kong in SGB mode, start a new game and wait for Donkey Kong to reach the top. Pauline will shout. Alternatively, play Kirby's Dream Land 2 in SGB mode.
### ROM details

Which games are affected by the issue (please state if GBA or GB game):
Donkey Kong, Kirby's Dream Land, other Super Game Boy-enhanced games.
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
Any game that does not take advantage of the extra SNES sound channels.
### Option details

Video driver: Direct3D

Sound driver: XAudio

### Build details

Operating System: Windows

Version of code: Pre-built

### Hardware details:

If relevant, the joystick you are using and the drivers you are using for it: None

**Comment by Squall-Leonhart** [comment]
This has always been the case, the SGB mode only enables the supergameboy frame and video palette. the audio processor for the super gameboy is not present in visualboy advance, and without Blargg implementing it, it won't ever be.

**Comment by mudlord** [comment]
SNES sound channel support means actual SNES support. IIRC Higan supports SGB because it also has the underlying SNES emulation.

**Comment by retro-wertz** [comment]
you'll have better luck playing SGB snes audio on sgb-enabled snes emulators than on any current gb/gbc emulators. youll have to practically emulate SNES.
