### ISSUE TITLE
Audio and Control Problems PLEASE HELP

### ISSUE THREAD

**Issue by Undeadzambi** [visualboyadvance-m/visualboyadvance-m#911]
### ROM details

So this is the problem
So uhhhhh i decided i wanted to play pokemon ruby so i downloaded VBA for the first time and started pokemin ruby and i realised that i had two problems 1. The input was too fast if .  I was making my name pressed the select key once and then it showed AAA even though i wanted only 1 A and tapped the key once so input too high
2. Audio problem is i couldnt hear any audio for pokemon ruby i went through the settings booted the game up a few more times but still no audio so if you know how to fix this please help

Which games are affected by the issue (please state if GBA or GB game):
Pokemon Ruby
Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

Include screenshots of ROM Information (File > ROM Information):

If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

Windows

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

**Comment by ZachBacon** [comment]
You're leaving out key details from the template. Please in the future do not leave out any details. But by the sounds of it, the turbo had been enabled, which is usually done by someone playing around with the settings. Go to the about menu and select factory reset. That should take care of the issue.

**Comment by Squall-Leonhart** [comment]
now you deleted sections of the template.

everything in your issue has a configuration fix or is addressed in the nightlies which at the present time we cannot recommend you using (pending on a solution to a visual studio issue)
