### ISSUE TITLE
FFmpeg 5.0 compatibility

### ISSUE THREAD

**Issue by alucryd** [visualboyadvance-m/visualboyadvance-m#912]
The latest release won't build against ffmpeg 5.0, here is the build log: https://build.alucryd.xyz/#/builders/82/builds/3/steps/8/logs/stdio

Haven't tried the git head yet, but I'll need a stable release for the Arch Linux repositories (or at the very least a commit you consider stable enough). Could you guys have a look? Will this require much work?

**Comment by ZachBacon** [comment]
Chances are it may take a little bit of time to get compatibility for ffmpeg 5, but we'll see about getting it added in.

**Comment by ZachBacon** [comment]
> Chances are it may take a little bit of time to get compatibility for ffmpeg 5, but we'll see about getting it added in.

But also thank you for the log, that will be extremely helpful

**Comment by jhonny-oliveira** [comment]
I applied this patch https://github.com/archlinux/svntogit-community/blob/packages/vbam/trunk/vbam-ffmpeg5.0.patch (with some minor tweaks) and everything seems to be running fine.

**Comment by ZachBacon** [comment]
I thought I already took care of that... I've had so much on my plate lately that I just forgot to have commited it.

**Comment by rkitover** [comment]
master works with 5.0, he is referring to the release.

**Comment by ZachBacon** [comment]
Ah, so I did make the changes, I was beginning to think I may of forgotten something. To be honest I should of closed the issue when it was made compatible.

**Comment by ZachBacon** [comment]
closing issue

**Comment by jhonny-oliveira** [comment]
True! The patch was related to the release.
Thank you!
