### ISSUE TITLE
When I load a game the application stops soon after it tries to load the game how do I fix that?

### ISSUE THREAD

**Issue by brolyuchiha1963** [visualboyadvance-m/visualboyadvance-m#915]
### ROM details

Which games are affected by the issue (please state if GBA or GB game):

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):

Include screenshots of ROM Information (File > ROM Information):

If you are using a BIOS file, please say which one.

### Option details

Video driver (simple, opengl):

Sound driver (directsound, xaudio, openal, SDL):

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):

If using Linux, specify if using xorg or Wayland:

Version of code (pre-built binary version, or commit ref, or just "master"):

**Comment by Squall-Leonhart** [comment]
use x64 nightly from https://nightly.vba-m.com/

**Comment by brolyuchiha1963** [comment]
the same problem is happening to me with the on you sent me
