### ISSUE TITLE
Controller (Joypad) Inputs Not Detected in Joypad Configuration Window

### ISSUE THREAD

**Issue by moritasan2040** [visualboyadvance-m/visualboyadvance-m#918]
### Expected Behavior
Controller inputs are expected to be detected in the Joypad Configuration window.

### Actual Behavior
Controller inputs are **_not_** detected in Joypad Configuration window.

### Further Details
Controller inputs  **_are_** detected during game-play.  It is only in the Joypad Configuration window that VisualBoyAdvance-M ceases to recognize controller inputs. This prevents me from correcting the reversed Confirm and Cancel, and prevents me from performing certain actions entirely, as they are not assigned to any button.

My controller is 100% detected by other emulators, Steam, and non-Steam games.

If this **_is_** indeed an SDL problem, you'll have to explain to me what that is and how I can address the issue. Googling and reading up on it, it was over my head. Please and thank you.

### Build Details

Operating System: **Microsoft Windows 10 Home** _(64-bit)_

Version: **10.0.19044 Build 19044**

### Driver Details

Device Name: **SNES Controller** _(for Nintendo Switch)_

Driver Provider: **Microsoft**

Driver Date: **6/21/2006**

Driver Version: **10.0.19041.1387**

Digital Signer: **Microsoft Windows**

**Comment by moritasan2040** [comment]
What do you _mean_ "not our bug"? It works fine in every other emulator I've got.

You're saying it's a bug in SDL? That stands for "Simple DirectMedia Layer", right? Do I even HAVE that? Is it something built into Windows 10? It seems like something I would have to install, so I get the feeling that it isn't built into Windows 10...but I don't really know. And it seems like it's a program for coding, not some-thing I need to use an emulator. Unless you're saying that the emulator was made using Simple DirectMedia Layer, and that SDL is flawed, so VBA-m is like-wise flawed...? Which would mean it's still a VBA-m flaw...

So...I don't know which you're trying to imply. I'm only guessing here, since tags, rather than sentences, are all I've got to go off of as the reply to my problem.

**Comment by Manic137** [comment]
Not sure if this works for you, but opening VBA as Administrator fixed it for me!
