### ISSUE TITLE
VBA-M crashes on loading save file

### ISSUE THREAD

**Issue by LucasKuhlemann** [visualboyadvance-m/visualboyadvance-m#919]
Whenever I press "Continue" on the main menu of Pokemon Yellow with the attached save file, VBA-M freezes.

[rom-and-save.zip](https://github.com/visualboyadvance-m/visualboyadvance-m/files/8049822/rom-and-save.zip)

Which games are affected by the issue (please state if GBA or GB game):

Pokemon Yellow (GBC)

Include screenshots of ROM Information (File > ROM Information):
![image](https://user-images.githubusercontent.com/3165129/153622052-637a0a74-367d-4c90-a301-fec3f51a773f.png)

**Comment by Squall-Leonhart** [comment]
save works fine, turn off cheats

don't upload roms, this issue will be deleted soon.
