### ISSUE TITLE
VBA file", line 5: '=' excepted ERROR - help me!!

### ISSUE THREAD

**Issue by Patrickgeemu** [visualboyadvance-m/visualboyadvance-m#920]
When I open the emulator I get this error, does anyone know how to fix this?
![error](https://user-images.githubusercontent.com/99980930/154713985-c8f0b6be-d6e4-4c3f-94bd-a9f5eb8a4d49.png)

**Comment by ZachBacon** [comment]
I like to remind people who might be coming to this issue, don't ignore the issue template. It's there for a reason.

Now to your issue, try a nightly http://nightly.vba-m.com/, let me know if one of the nightly build works or not.
