### ISSUE TITLE
[Bug]: (Slightly) Greyed-out screen on Manjaro

### ISSUE THREAD

**Issue by BrickWildcat** [visualboyadvance-m/visualboyadvance-m#939]
### Expected behavior?

Display standard/more vibrant colors.

### Actual behavior?

All GBA games appear to have a translucent grey layer over the screen. i.e:
![greyedout](https://user-images.githubusercontent.com/102120796/159385071-0d9752c9-5b56-4bb1-8d27-4e9cb36fbb04.png)
This isn't game-breaking, but it is quite annoying.

### Steps to reproduce the problem

I downloaded vba-m from Manjaro Linux's default Add/Remove Software database.
1. Open visualboy.
2. Load any GBA ROM (GBC works fine).

### Error messages?

N/A

### What game were you playing

Various; tested with Pokemon FireRed, Emerald, and a ROM Hack of Emerald - they all had the same effect.

### What settings are you using?

Video driver (simple, opengl): Apologies, I'm not sure how to configure this.
Sound driver (directsound, xaudio, openal, SDL): Same as above, but audio works fine
Scale Filter Used?: 1x

### Specifications and Build details

VBA-M: vbam-wx 2.1.4.r453.65b5affe-1
OS: (include version and OS build number using WinVer if on Windows): Manjaro Linux
If using Linux, specify if using xorg or Wayland: Wayland
CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz x 8
GPU: Mesa Intel® Xe Graphics (TGL GT2)
RAM: 7.5 GiB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
disable LCD filter
