### ISSUE TITLE
[Bug]: Turbo Mode won't turn off

### ISSUE THREAD

**Issue by schwartzpedro** [visualboyadvance-m/visualboyadvance-m#940]
### Expected behavior?

Turbo Mode turn off either trough hotkey or Option under Emulation

### Actual behavior?

Turbo mode wont turn off after either hotkey pressed or option turned off

### Steps to reproduce the problem

1.
2.
3.
4.
5.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

Pokemon Blazing Emerald

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

I dont know how to find these but im using a standard windows

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

I dont know how to find these but im using a standard windows

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
invalid  bug report
