### ISSUE TITLE
The Add A New Cheat Does Not Work [Bug]: 

### ISSUE THREAD

**Issue by PrinceMyc** [visualboyadvance-m/visualboyadvance-m#942]
### Expected behavior?

For The Add A New Cheat To Open 

### Actual behavior?

Doesn't Respond

### Steps to reproduce the problem

1. Open The VBA-m Emulator
2. Open A Game
3. Open The Cheats (Which Is In The Option Menu)  
4. Open Cheats List
5. Click Add New Cheats
6. Not Responding

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl): Opengl
Sound driver (directsound, xaudio, openal, SDL): Directsound
Scale Filter Used?: No

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version): 64-bit
OS: (include version and OS build number using WinVer if on Windows): WinVer 10 pro
If using Linux, specify if using xorg or Wayland:
CPU: Intel(R) Celeron(R) CPU N2830@ 2.16GHz
GPU: Don't Have One
RAM: 4GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Closing as Fixed, use a nightly build instead of those from the release section.
