### ISSUE TITLE
[Bug]: Multiplayer issue

### ISSUE THREAD

**Issue by secretqwerty10** [visualboyadvance-m/visualboyadvance-m#945]
### Expected behavior?

60 FPS Multiplayer Kirby Nightmare in Dream Land

### Actual behavior?

40 FPS FPS Multiplayer Kirby Nightmare in Dream Land

### Steps to reproduce the problem

1. Start and connect link
2. Load game
3. Connect in game

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title: Kirby Nightmare in Dream Land
GB, GBC or GBA: GBA
ROM CODE: A7KE
BIOS Used?: 20EF3F64
SAVE TYPE: 
Clean, Intro'd or Hacked?: Clean

### What settings are you using?

Video driver (simple, opengl): OpenGL
Sound driver (directsound, xaudio, openal, SDL): directsound
Scale Filter Used?: No

### Specifications and Build details

VBA-M: V2.1.4 64-bit
OS: Windows 10 19044.1620
CPU: AMD Ryzen 5 2600x
GPU: NVidia GeForce GTX 1070
RAM: 16 GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Linking is known broken and has never worked properly, use mgba instead.

closed duplicate.
