### ISSUE TITLE
Eulator is not recognizing joypad left joystick direction down. The other three directions work fine. Joypad is fully functioning and all its buttons work. [Bug]: 

### ISSUE THREAD

**Issue by seething-stew** [visualboyadvance-m/visualboyadvance-m#947]
### Expected behavior?

Pushing down on left joystick must be registered as joy1 axis1 +

### Actual behavior?

Pushing down on left joystick does not register in the emulator

### Steps to reproduce the problem

1.
2.
3.
4.
5.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

Problem is in the emulator itself

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: 2.1.4 32 bit version
OS: Windows 10 pro

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
please follow instructions before opening bugs, use the nightly.
