### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by TheHypeTrain** [visualboyadvance-m/visualboyadvance-m#948]
### Expected behavior?

It was supposed to compile

### Actual behavior?

It will not compile.

### Steps to reproduce the problem

1.type `$cmake .. -DCMAKE_BUILD_TYPE=Release -G Ninja`
2.
3.
4.
5.
...

### Error messages?

`-- Found SFML 2.5.1 in /usr/include
-- Found gcc-ar: /usr/bin/gcc-ar
-- Found gcc-nm: /usr/bin/gcc-nm
-- Found gcc-ranlib: /usr/bin/gcc-ranlib
CMake Error at src/wx/CMakeLists.txt:506 (message):
  Could not find gtk

-- Configuring incomplete, errors occurred!
See also "/home/tht/src/visualboyadvance-m/build/CMakeFiles/CMakeOutput.log".
See also "/home/tht/src/visualboyadvance-m/build/CMakeFiles/CMakeError.log".
`

### What settings are you using?

??

### Specifications and Build details

VBA-M: 64-bit, 2.1.4
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU: AMD Ryzen 7 2700
GPU: Radeon RX 470/480/570/570X/580/580X/590
RAM: 16 GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
Not a bug, you're missing the gtk2/3 (depending on how your wxwidgets was compiled) development headers.

**Comment by zhehangd** [comment]
The same happened to me even after installing the gtk stuff.
I saw the following in CMakeError.log

```
Determining if the __WXGTK3__ exist failed with the following output:
...
Building CXX object CMakeFiles/cmTC_e7f5b.dir/CheckSymbolExists.cxx.o
...
cc1plus: error: bad value (‘znver3’) for ‘-mtune=’ switch
cc1plus: note: valid arguments to ‘-mtune=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake tigerlake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm intel x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 generic native; did you mean ‘znver1’?
```

which was related to the following in CMakeLists.txt

```
  if(X86_64)
      set(MY_C_FLAGS ${MY_C_FLAGS} -march=core2)
      if(APPLE)
          set(MY_C_FLAGS ${MY_C_FLAGS} -mtune=rocketlake)
      else()
          set(MY_C_FLAGS ${MY_C_FLAGS} -mtune=znver3)
      endif()
  # Optimize for pentium-mmx and tune for Core2 on X86_32.
  elseif(X86_32)
      set(MY_C_FLAGS ${MY_C_FLAGS} -march=pentium-mmx -mtune=core2)
  endif()
```
After commenting out the znver3 line I sucessfully compiled the project.

I am using Kubuntu 20.04 and Intel® Core™ i7-6850K.
