### ISSUE TITLE
[Feature request]: add Super Game Boy palettes for original GB Games 

### ISSUE THREAD

**Issue by CraftFan24** [visualboyadvance-m/visualboyadvance-m#950]
### Request box

On GB Palette

### Reason box

?

### Examples

?

**Comment by Squall-Leonhart** [comment]
duplicate #933

**Comment by Squall-Leonhart** [comment]
can you stop creating new accounts and reposting things to multiple repos.

**Comment by mudlord** [comment]
They won't stop this. They did it to many other repos. They get a rise out of being pricks.
