### ISSUE TITLE
I can't get visualboyadvance-m to work when in the background. I have "pause when inactive" off and it continues to run when inactive, however I can't do any inputs in the game when it is inactive.[Bug]: 

### ISSUE THREAD

**Issue by mellky95** [visualboyadvance-m/visualboyadvance-m#953]
### Expected behavior?

Be able to control the game when the window is in the background.

### Actual behavior?

Game keeps running, but won't take any input.

### Steps to reproduce the problem

1. Open visualgameboyadvance-m
2. Open the ROM
3. Make sure "pause when inactive" is unchecked
4. Click off the window
5. Controller or keyboard doesn't make the game do anything
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
incomplete report,
invalid because background input works in nightly.
