### ISSUE TITLE
Licence File 

### ISSUE THREAD

**Issue by Pharap** [visualboyadvance-m/visualboyadvance-m#954]
### Request box

I would like to see a licence file that explains what licence the source code is actually provided under.

### Reason box

I would like to know what my rights are in regards to copying and modifying the code.

### Examples

The original VBA used a [GPL v2](https://choosealicense.com/licenses/gpl-2.0/) licence kept in a file called `COPYING`.

**Comment by Squall-Leonhart** [comment]
https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/doc/License.txt
