### ISSUE TITLE
[Feature request]: SNES/SFC (Super Nintendo / Super Famicom) support

### ISSUE THREAD

**Issue by SopTheSop27** [visualboyadvance-m/visualboyadvance-m#958]
### Request box

Is it possible to add support for SNES/SFC

SNES/SFC file extensions:

.smc
.sfc
.fig

SNES is backward compatibility with Game Boy, Game Boy Color (using Super Game Boy CARTGRIDE)

SNES resolution: 256x224 for NTSC ROMs (256x240 for PAL ROMs)

### Reason box

?

### Examples

![Super Mario World (USA) 000](https://user-images.githubusercontent.com/101358042/171996631-302b2d3d-5a44-4de5-b656-7b1bdee5edb9.png)
![Super Mario World (USA) 001](https://user-images.githubusercontent.com/101358042/171996640-1c06e2f4-5755-4469-ba96-4def7e5d8c5d.png)
![Super Mario All-Stars (U) 000](https://user-images.githubusercontent.com/101358042/171996645-c68cfc11-1cc8-487f-b8c3-356a59a2f661.png)
![Super Mario All-Stars (U) 001](https://user-images.githubusercontent.com/101358042/171996702-273eff41-ab6b-46e0-b9bc-9667dc63875b.png)
![Super Game Boy (World) (Rev 2) 000](https://user-images.githubusercontent.com/101358042/171996706-339b2064-dec6-49a1-8d7e-ec6787b593b6.png)
![Super Game Boy 2 (Japan) 000](https://user-images.githubusercontent.com/101358042/171996712-ee1c07d9-7035-4aad-bbc0-86235d7f249a.png)

**Comment by Squall-Leonhart** [comment]
No.
Closed with Prejudice.

**Comment by Squidward22** [comment]
No *planned* to add SNES support
