### ISSUE TITLE
[Bug]: cheats disable the emulator

### ISSUE THREAD

**Issue by AndresDNR** [visualboyadvance-m/visualboyadvance-m#959]
### Expected behavior?

select and/or activate a cheat

### Actual behavior?

![cheats](https://user-images.githubusercontent.com/107004016/172250188-603529bf-9804-4467-8933-0b4af4cae2ed.PNG)
when clicking on find cheats or when clicking on the cheat list and saving or adding a cheat the emulator freezes and stops working.

### Steps to reproduce the problem

1. open the emulator visualvoyadvance-m 2.1.4
2. click on tools
3. click on cheats
4. click on list cheats or find cheat
5. (in the case of list cheat when saving a cheat)

### What game were you playing

Title: All roms
GB, GBC or GBA: GBA
ROM CODE: I don't know where to look for this information
BIOS Used?: No
SAVE TYPE: the one provided by the default emulator
Clean, Intro'd or Hacked?: No

### What settings are you using?

Video driver (simple, opengl): OpenGL
Sound driver (directsound, xaudio, openal, SDL): SDL
Scale Filter Used?: HQ 4x

### Specifications and Build details

VBA-M: 2.1.4 version of 32 bits
OS: I don't know where to look for this information
CPU: Pentium(R) Dual-Core 3.00 GHz
GPU: I don't know where to look for this information
RAM: 2 GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
Do me a favour, try a nightly build https://nightly.vba-m.com/visualboyadvance-m-Win-x86_32.zip

**Comment by PNo125** [comment]
I had the same problem and this new version solved it, the post can be closed

**Comment by jgcmarins** [comment]
I had the same issue and the nightly version fixed for me
