### ISSUE TITLE
[Bug]: Doom 2 Rom experiencing issues with 3D rendering

### ISSUE THREAD

**Issue by Jack-Winters-24** [visualboyadvance-m/visualboyadvance-m#960]
### Expected behavior?

To run Doom 2

### Actual behavior?

When starting a new game, the environment creates a weird mirroring effect and does not render properly

![Doom II (USA)](https://user-images.githubusercontent.com/107106552/172570822-832b9649-8298-414a-a816-4b3b59d2806e.png)
![Doom 2 - GBA](https://user-images.githubusercontent.com/107106552/172571362-b0e40450-bafd-45df-9453-7fa862af643f.png)

some examples are shown above

### Steps to reproduce the problem

1. Load ROM
2. Press start
3. Select new game
4. Select any difficulty

### Error messages?

no error messages

### What game were you playing

Title: Doom 2
GB, GBC or GBA:
ROM CODE: 
BIOS Used?: 
![ROM info](https://user-images.githubusercontent.com/107106552/172571908-df510cc7-9ea0-483b-8586-0425f91de201.PNG)

### What settings are you using?

Video driver (simple, opengl): Simple
Sound driver (directsound, xaudio, openal, SDL): Default
Scale Filter Used?: no scale filter

### Specifications and Build details

VBA-M: VBA M 2.0.1 64bit
OS: (include version and OS build number using WinVer if on Windows): Windows 10
CPU: AMD Ryzen 7 5800H with Radeon Graphics 3.20 GHz
GPU: RTX 3080 laptop gpu
RAM: 16 GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
Version 2.0 is unsupported. Pleased update to 2.1.4 or download a nightly from nightly.vba-m.com, otherwise I'm closing this post as invalid.

**Comment by Squall-Leonhart** [comment]
Works fine in nightly
![image](https://user-images.githubusercontent.com/1098176/172580665-38dfc0b7-68a3-4ec2-8ece-e780c30c8034.png)

**Comment by Squall-Leonhart** [comment]
closed as WFM
