### ISSUE TITLE
[Bug]: Battery error + no .ini files

### ISSUE THREAD

**Issue by L337Hun73r** [visualboyadvance-m/visualboyadvance-m#961]
### Expected behavior?

Being able to use old .sav and .sgm files of Pokémon games I played with an older build without errors.
With "existent" playtime in older games and "RTC" with newer games.

### Actual behavior?

I used to play -mostly- Pokémon games with an older build of VBA-m without any error (Really sorry but I don't remember which one but my latest save state is saved in June 2021). Don't really remember which VBA-m version I used to play without errors. Sometimes later I found out there's a new version (2.1.4) and downloaded it from here just to have the latest version. 

I wanted to play Crystal "Pokemon - Crystal Version (UE) (V1.1)" with my old (From 2020) saves tonight and saw that "time not set" error in the main menu window
![Crystal 1](https://user-images.githubusercontent.com/107157157/172736781-9e0af067-bada-44cf-aebe-cf2155717954.png)

and when I pressed continue, my playtime was "???" followed by "The clock's time may be wrong" message in-game. Weirdly though, after I reset clock in-game, I could play with my manual save.
![Crystal 2](https://user-images.githubusercontent.com/107157157/172736790-3e6ec3fd-dab3-4cae-893a-2b79512ec86e.png)

But then I try to load a save state, a plain beige colored screen comes up and game receives no input...
![Crystal 3](https://user-images.githubusercontent.com/107157157/172736797-147d3217-e757-469d-837f-7efe4845f916.png)

Weirded out and I tried my luck with another game, a Fire Red hack "Radical Red v2.2b", again with my old saves. I welcomed with a "WARNING! The correct system time could not be read." error on starting the game.
![Radical Red v2 2b 1](https://user-images.githubusercontent.com/107157157/172737364-ff021917-75bb-46f1-9762-ace3cdf9df09.png)

Unlike my Crystal save, my play time was visible (Almost nine and a half days and hopefully correct? I guess??). Plus, my save states AND manual save works.. somehow?
![Radical Red v2 2b 2](https://user-images.githubusercontent.com/107157157/172737652-efa740b7-350d-4a81-acd1-15801f7e7574.png)

Because even with "Real-time clock" is enabled in the options, it was not recognized by game and/or emulator
![rtc on](https://user-images.githubusercontent.com/107157157/172737836-6bcd6944-4ce5-4352-90f2-65609b98d14c.png)

My manual save works "somehow", because when I continue with the error went on, game puts me in the pace where my save states saved last time, in front of a Poké Center
![Radical Red v2 2b 3](https://user-images.githubusercontent.com/107157157/172737992-a7df5b1f-296d-40d6-a498-fe41c21c2680.png)

But hey! This is with Automatic save type and 64k flash size
![savetype](https://user-images.githubusercontent.com/107157157/172738111-f657e90c-2907-4185-81c0-3e4e3394442c.png)

when I change settings to Automatic and 128k, emulator takes me to 231st hour of gameplay with the manual save (Probably after a League finale). While save states still at the same with the 64k version, the 232nd hour.
![Radical Red v2 2b 4](https://user-images.githubusercontent.com/107157157/172738354-bb50d5af-ffee-4b10-8bfb-f20a32db065d.png)

I wanted to dig deeper and tried other games and chose Crystal hack  "Crystal Clear v1.3b" to see if my Crystal save is corrupt or something. To not my surprise in any way, time setting was erroneous.
![crystal-clear 1](https://user-images.githubusercontent.com/107157157/172738759-97cbb062-fd0b-47af-8956-8c65d3c0bda0.png)

When I want to continue, game says save file corrupt. When I try to load a save state, well.. this comes up
![crystal-clear 2](https://user-images.githubusercontent.com/107157157/172739093-0a0f4e34-f5a1-4931-be73-00976acc50b0.png)

Clearly, there's something wrong with "Battery" of the emulator and I don't really know why but emulator keeps the save format at 64k. Even though the directory is not "read-only" or anything, there are absolutely no .ini files around in the folder!? No vba-over, no config, nothing. Just the VBA-m exe and my games+save files. Although, even I might be wrong but I don't remember having .ini files around when I played with that VBA-m version around 2021. Could it be? I could be wrong too. Right now, my configurations like volume is being saved but Gameboy Color save type is NOT.

Since I really having problems with github interface and honestly tried to search "Save" and "Battery" keywords in issues in right way, I wasn't able to find a solution among closed or open issues. Help me guys, please! I played those games and kept the save files since more than a decade now and don't really want to lose them.

### Steps to reproduce the problem

1 - Forgot which "old" version of VBA-m you were playing "normally" and absolutely without error
2 - Download latest version just because you should have the latest version
3 - Forgot about emulator and games for more than a year without even test the emulator
4 - Get bored and try to play old saves after NOT testing the new version after more than a year
5 - Get smashed in the face by multiple errors and maybe corrupted savefiles or battery "states"
6 - Have no .ini files whatsoever
7 - Ask the developers

Sorry this isn't very helpful :/

### Error messages?

There are no error messages emulator-wise. There are in-game errors though. The emulator works "normally"...

### What game were you playing

Pokémon Crystal Version (UE) Version 1.1
![image](https://user-images.githubusercontent.com/107157157/172741023-57425862-4bd8-45b8-9b74-bddc856af973.png)

Radical Red (Version 2.2b)
![image](https://user-images.githubusercontent.com/107157157/172740892-cfedf1e1-cf37-4717-b4e9-be8d60eb8d16.png)

Crystal Clear (Version 1.3b)
![image](https://user-images.githubusercontent.com/107157157/172741127-55e55b06-f5f4-4504-bd47-640345587796.png)

### What settings are you using?

Video driver: opengl

Sound driver: SDL

Scale Filter Used?: I don't know. None?
![image](https://user-images.githubusercontent.com/107157157/172741440-e3079e5d-85bb-49b3-b7af-6ea3f83a820c.png)

### Specifications and Build details

VBA-M: 
2.1.4 64-bit version for Windows

OS: 
Windows 10 21H1 (System language: Turkish if this info is helpful)

CPU:
Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz   3.20 GHz

GPU:
ATI Radeon HD6350

RAM:
8GB DDR3, 1333MHz, 2 slots (4+4)

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by ZachBacon** [comment]
So first of all, before I begin diagnosing things, do me a favour, try one of the nightlies from https://nightly.vba-m.com/ and report back. If it still happens, then we'll do a deeper dive.

**Comment by L337Hun73r** [comment]
Tried the normal 64bit Windows one. Completely same results except 128k save in the Radical Red wasn't in 231th hour, but in the 281th

**Comment by Squall-Leonhart** [comment]
Save state compatibility can not be guaranteed between versions of the emulator.

**Comment by L337Hun73r** [comment]
Thanks for trying to help. I guess I should try to find a backup of an old version and manually save from the backupped save states (Because I usually don't use manual saves with the emulator). Hopefully they'll work. Happy bug hunting.
