### ISSUE TITLE
Real Time Clock is Not Working[Bug]: 

### ISSUE THREAD

**Issue by Mehtevas94** [visualboyadvance-m/visualboyadvance-m#966]
### Expected behavior?

Options>Game Boy Advance>Real-Time Clock
Is supposed to initiate the real-time clock. Specifically for the game Radical Red.SSSSSSSsS

### Actual behavior?

I get an error saying the real-time clock is not enabled. This is regardless of if the option for RTC is checked or not.

### Steps to reproduce the problem

1. Enable RTC
2. Open Radical Red
3.
4.
5.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

Pokemon Radical Red

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Look above the search issues/new issue bar.
