### ISSUE TITLE
[Bug]: Ace Lightning crashes

### ISSUE THREAD

**Issue by michele5943** [visualboyadvance-m/visualboyadvance-m#969]
### Expected behavior?

After BBC logo, this game gives "VisualBoyAdvance-M Emulator has stopped working"

### Actual behavior?

After Choosing "Cancel" button, it appeared with "The problem seems to be caused by the following file: ntoskrnl.exe, CRITICAL_PROCESS_DIED".

### Steps to reproduce the problem

1.
2.
3.
4.
5.
...

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

<Some of this information can be provided with a screenshot of Rom Information, SAVE TYPE for GBA titles can be obtained from Options > Game Boy Advance > Config>
Title:
GB, GBC or GBA: GBA
ROM CODE: 
BIOS Used?: (Share crc hash)
SAVE TYPE: (Attach Battery or Savestate here)
Clean, Intro'd or Hacked?:(Attach Patch here)

### What settings are you using?

Video driver (simple, opengl):
Sound driver (directsound, xaudio, openal, SDL):
Scale Filter Used?:

### Specifications and Build details

VBA-M: (include commit version number and whether you are using the 32-bit or 64-bit version)
OS: (include version and OS build number using WinVer if on Windows):
If using Linux, specify if using xorg or Wayland:
CPU:
GPU:
RAM:

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
You have hardware or driver issues, the emulator cannot/does not cause Kernel exceptions.
