### ISSUE TITLE
Crash when saving sound settings and closing dialog (GB/GBC)

### ISSUE THREAD

**Issue by bryc** [visualboyadvance-m/visualboyadvance-m#97]
### Expected behavior
Changing a setting in the **Sound Settings** dialog saves .cfg and closes window.
### Actual behavior
Changing a setting in the **Sound Settings** dialog saves .cfg and emulator will **crash** when closing the window.
![image](https://cloud.githubusercontent.com/assets/1408749/23996352/74e02d44-0a23-11e7-8748-a1a2e94bb43d.png)
### Steps to reproduce the behavior
1. Open VBA-M (latest version)
2. Start any GB/GBC game (A game must be running. GBA is unaffected.)
3. Open Options > Audio > **Sound Settings**
4. Change any option or slider (Volume for example)
5. Press OK
6. Crash will occur
### Option details
opengl & directsound but it shouldn't matter
### Build details
OS: Windows 7 (also tested on Windows 10)
Version: 2e8bee1 (x64 release build)

**Comment by autofire372** [comment]
This is still a problem in 2.0.2.

**Comment by retro-wertz** [comment]
sound settings related crashing should now be fixed in latest commit...
