### ISSUE TITLE
VisualBoyAdvance-M on Android build

### ISSUE THREAD

**Issue by MCPE2** [visualboyadvance-m/visualboyadvance-m#980]
### Request box

Is it possible to do making Android build version of VisualBoyAdvance-M

Minimum API Version: API 21 (Android 5.0)

Target API Version: API 28 (Android 9.0)

File name: VisualBoyAdvance-M.apk

App name: VBA-M

### Reason box

I want Accurate Game Boy / Super Game Boy / Game Boy Color Emulator for Android with 48KHz sound, Pocket Camera, MBC6, MBC7 support

### Examples

.

**Comment by ZachBacon** [comment]
So we don't directly support android, but if you download retroarch, using the vba-m libretro core, that's as close as you'll get.
