### ISSUE TITLE
[Bug]: Any Game Rom Causes Instant Crash

### ISSUE THREAD

**Issue by emulidor** [visualboyadvance-m/visualboyadvance-m#989]
### Expected behavior?

When I attempt to launch a rom, the selected rom is supposed to launch normally.

### Actual behavior?

When I attempt to launch a rom normally by using File - Open... VBA instantly crashes with no error message. VBA itself launches normally and browses files correctly. This may be a bug or an issue with my computer. I'd love some help on this. I'm running the latest version of VBA.

### Steps to reproduce the problem

1.Launch VBA
2.Click File - Open...
3.Select the Rom to play
4.VBA crashes
5.
...

### Error messages?

N/A

### What game were you playing

Every rom crashes. Any Pokemon GBA game, Kirby's Dreamland GB rom crashes as well

### What settings are you using?

Default settings

### Specifications and Build details

64 Bit Windows 11
CPU: Intel i7 10th gen
GPU: Nvidia 3600ti

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Our discord or IRC channel is for technical support, this is not a legitimate bug.

**Comment by emulidor** [comment]
> 

Ok, thanks
