### ISSUE TITLE
Reshade crashes vba-m

### ISSUE THREAD

**Issue by Papermanzero** [visualboyadvance-m/visualboyadvance-m#99]
### Expected behavior
Using Reshade in combination with vba-m (currently 2.0) to enhance graphics (color correction).
Screenshots: https://forums.libretro.com/t/gameboy-advance-color-correction-shader/6444

### Actual behavior
Reshade 1.1.0.962 with MasterEffects cannot be applied to vba-m (the hook mode does not work)
Reshade 3.0.6 instantly crashes vba-m if the user loads a game.

### Steps to reproduce the behavior
Installing Reshade 1.1.0 or 3.0.6 and starting a game

Video driver (simple, opengl or cairo):
OpenGL and Simple

Operating System (Windows, Mac, Linux (state distribution), etc.):
Win 10

Version of code (pre-built binary version, or commit ref, or just "master"):
Latest Master (compiled)

Additional Information:
Older version of vba-m works without issues

**Comment by Squall-Leonhart** [comment]
good.

**Comment by Papermanzero** [comment]
No, not really good :-(

**Comment by Squall-Leonhart** [comment]
yes, really good.

reshade on gameboy games? thats just stupid.

**Comment by Papermanzero** [comment]
No it isn't. Because you can adjust every kind of graphic setting.
Are you going to provide a color LUT for vbam? Are you going to provide a saturation feature for vbam? Are you developing post-effects like FXAA for vbam? 
I guess not.

Giving the user the freedom of choice is always good.
Especially if it is extending the feature set.

**Comment by ZachBacon** [comment]
So. This has gone too far. I can understand the want for shaders. At this time we won't support it, we have some other pressing issues to deal with. I do want to include it on our radar though.

That said, we currently won't exactly provide support for third party shader apps, it can cause other issues that we don't need that may not partain to the app itself.

Again, we may eventually support shaders just not yet.

**Comment by Papermanzero** [comment]
You do not need to officially support it. You only need to bugfix your UI to enable reshade.
I guess bug fixing the UI should have priority.

**Comment by ZachBacon** [comment]
The issue probably lies in the fact we use wxglcanvas for OpenGL. Could be solvable by just replacing it with a better GL context, but that's sorta low on the priority for the moment. But it is on the radar.

**Comment by ZachBacon** [comment]
Also squall isn't really so much a developer on the project anymore. What he says isn't what we endorse, just ignore him

**Comment by ZachBacon** [comment]
Also going to reopen this, even if we don't support reshade, it'll help in reminding me that this will be a target to enable shaders once we get the opengl context sorted out.

**Comment by Papermanzero** [comment]
I see. I thought squall is part of the team. Then I really have to say sorry for my last statement.
I like the project and also the achievements. Your efforts are highly appreciated.

**Comment by ZachBacon** [comment]
He used to be, but he hasn't commited any code in a really long time.

**Comment by Squall-Leonhart** [comment]
FXAA doesnt belong in a 2D/2.5D console emulator.
Saturation you can control from your video driver
LUT isn't required.

All these things are desires by the reshade crowd who thinks they are making things look 'better' by crushing the color range.

VBM-Wx isn't even buildable easily anymore, so i won't touch code i can't kick off a 3 minute  build for.

**Comment by Squall-Leonhart** [comment]
was fixed on reshades end long ago.
