### ISSUE TITLE
Add default Game Boy border for Game Boy / Game Boy Color games (if it's not Super Game Boy enhanced)

### ISSUE THREAD

**Issue by EnderCraft22** [visualboyadvance-m/visualboyadvance-m#990]
### Request box

We need to show Game Boy border if Game Boy is emulating, Game Boy Color border if Game Boy Color is emulating, Game Boy Advance border if Game Boy Advance is emulating, SNES original Super Game Boy border if Super Game Boy is emulating, SNES original Super Game Boy 2 border if Super Game Boy 2 is emulating.

Resolution: 256×240 (256×224 also as crop overscan)

### Reason box

.

### Examples

.

**Comment by Squall-Leonhart** [comment]
There is no such thing as Game boy border, Color Border, Advance border.

These are all Super Gameboy features exposed on SGB enhanced games in Super Gameboy mode.
