### ISSUE TITLE
Golden Sun has the wrong colors - Build 08/18

### ISSUE THREAD

**Issue by Felipefpl** [visualboyadvance-m/visualboyadvance-m#991]
### Expected behavior?

I expect the correct colors.

### Actual behavior?

Wrong colors.

### Steps to reproduce the problem

Start the rom with vba-m, the problem is seen right away.

### Error messages?

If this is a crash bug, and you have the time and inclination, please provide a symbolic backtrace.
Instructions for doing so are [here](https://github.com/visualboyadvance-m/visualboyadvance-m/blob/master/README.md#reporting-crash-bugs).

### What game were you playing

Golden Sun (USA)

### What settings are you using?

Video driver (simple, opengl): both modes were used.

### Specifications and Build details

VBA-M: 08/18 Build, 32 bit
OS: Win7 x64
CPU: Pentium 1.8 Ghz
GPU: Intel hd 2000
RAM: 4 GB RAM

The pics below show the problem, 1st is vba-m:

![Vba-m](https://user-images.githubusercontent.com/5569804/185968156-64da5e7f-88cb-4c70-b1a2-930b8fd816d6.gif)

This one was made with classic vba 1.8.0 beta 3, the colors are fine here, also on mgba.

![Vba 1 8 0 beta 3](https://user-images.githubusercontent.com/5569804/185968318-4917df16-d47b-4796-be60-575ccac4954f.gif)

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by Squall-Leonhart** [comment]
Disable LCD Filter.

**Comment by Felipefpl** [comment]
No filters enabled.

![Sem título](https://user-images.githubusercontent.com/5569804/185996903-564cc076-dab4-423c-8cb2-32763404cba5.gif)

Also, i dont understand why this was marked as fixed since i didnt report the problem as solved.

**Comment by Squall-Leonhart** [comment]
![image](https://user-images.githubusercontent.com/1098176/185997318-fcca8898-1a2f-4846-ab2f-be79b4562218.png)

**Comment by Felipefpl** [comment]
That did the trick. Thanks for you help and explanation.
