### ISSUE TITLE
[Bug]: wxbase31ud_net.lib version mismatch when building with Visual Studio 2022

### ISSUE THREAD

**Issue by laqieer** [visualboyadvance-m/visualboyadvance-m#992]
### Expected behavior?

Build Success

### Actual behavior?

Build Error:
```
Error		'C:/Users/laqieer/source/repos/laqieer/vcpkg/installed/x64-windows/debug/lib/wxbase31ud_net.lib', needed by 'visualboyadvance-m.exe', missing and no known rule to make it	C:\Users\laqieer\Source\Repos\laqieer\visualboyadvance-m\visualboyadvance-m	C:\Users\laqieer\Source\Repos\laqieer\visualboyadvance-m\ninja	1	
```
The installed library version:
```
C:\Users\laqieer\source\repos\laqieer\vcpkg\installed\x64-windows\debug\lib\wxbase32ud_net.lib
```
Their version number doesn't match.

### Steps to reproduce the problem

1. Open the repo with Visual Studio 2022
2. It installs dependencies automatically
3. Select target x64-Debug or others
4. Build All

### Error messages?

'C:/Users/laqieer/source/repos/laqieer/vcpkg/installed/x64-windows/debug/lib/wxbase31ud_net.lib', needed by 'visualboyadvance-m.exe', missing and no known rule to make it	C:\Users\laqieer\Source\Repos\laqieer\visualboyadvance-m\visualboyadvance-m	C:\Users\laqieer\Source\Repos\laqieer\visualboyadvance-m\ninja

### What settings are you using?

NA

### Specifications and Build details

VBA-M: e0ae114f2e4b5a26409a98c0b75ac295d16a493d, 64-bit
OS: Version 21H2 (OS Build 22000.856)
CPU: Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz   2.59 GHz
RAM: 32.0 GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

**Comment by laqieer** [comment]
https://www.wxwidgets.org/news/2022/07/wxwidgets-3.2.0-final-release/

Wxwidgets 3.2.0 is released recently and then I cann't build the project. I can build it with Visual Studio 2022 before.

**Comment by ZachBacon** [comment]
I think this is more of a vcpkg issue currently as an mingw/clang/gcc build for windows hasn't been giving me any issues. My guess vcpkg is still looking for an older visual studio compiler.

**Comment by laqieer** [comment]
## Temporary Workaround

Select static target and edit the version number in generated `build.ninja` manually. However, the change to it will be overwritten after regenearation, so it may not be the correct solution to this problem, but it works as a temporary workaround to this problem.
